### ISSUE TITLE
Broken Build Infrastructure

### ISSUE THREAD

**Issue by HerbertJordan** [souffle-lang/souffle#102]
After merging the last commits of this afternoon (at 15:00 it was still working) the build system is broken on my system. When running `../configure` I get the message:
```
checking for boostlib >= 1.46... yes
checking whether the Boost::System library is available... yes
checking for exit in -lboost_system... no
checking for exit in -lboost_system... (cached) no
configure: error: Could not link against boost_system !
```
What should I do? The boost system lib is installed on my system and is also tryed to ste the LD_LIBRARY_PATH environment variable. No change.

**Comment by icesparrow** [comment]
LD_LIBRARY_PATH is actually obsolete, in any case it is for looking up dynamic libraries at execution time.

Most likely your build environment is unaware of the directories where boosl libraries are. You need to configure with:

`LDFLAGS="-L<path to boost libs>"  CPPFLAGS="-I<path to boost headers>" ./configure`

It does not seem to be a bug.

**Comment by HerbertJordan** [comment]
I purged and re-installed boost, now it is working. Sorry for bothering.
