### ISSUE TITLE
Column selection doesn't work with strings

### ISSUE THREAD

**Issue by DavideFauri** [souffle-lang/souffle#1044]
Hello,
the `columns=` argument in an input directive works as expected when the data consists of numbers, and fails for string inputs.

My edge.facts file is:

```
a	b	x
b	c	y
```

While my program is:

```
.decl edge(x:symbol, y:symbol)
.input edge(columns="1:2")

.decl path(x:symbol, y:symbol)
.output path

path(x,y) :- edge(x,y).
path(x,y) :- path(x,z), edge(z,y).
```

The output is:
```
Error loading data: Error converting number <x> in column 3 in line 1; cannot parse fact file edge.facts!
```

Misteriously, when I edit the input to `columns="1:3"`, the output is:
```
Error loading data: Values missing in line 1; cannot parse fact file edge.facts!
```

The expected behavior would be that the program chooses the first and second columns in the former example, and the first and the third in the latter.

If I remove `columns="1:2"`, and therefore have only a `.input edge` statement, the program behaves nicely and returns:
```
a	b
b	c
a	c
```

Any ideas why?

**Comment by mmcgr** [comment]
The column mapping was not being used when determining if the input was symbol or number.

A separate problem is that the columns start from 0, so `1:3` is trying to use a column that is not present.

**Comment by DavideFauri** [comment]
> A separate problem is that the columns start from 0, so `1:3` is trying to use a column that is not present.

Indeed this solved my issue, thanks!

Additionally, I might suggest to update the documentation at https://souffle-lang.github.io/docs/io/, since there I found `columns="4:7"` associated with 
>[...] and will use the **fourth and seventh** columns for input data.

**Comment by mmcgr** [comment]
I update the docs for this, as you suggested.

In a later PR I'll add a more useful error message for column count errors.
