### ISSUE TITLE
All errors fail to give a line number: "unknown source location"

### ISSUE THREAD

**Issue by rljacobson** [souffle-lang/souffle#1069]
Error messages never give me source locations. Here's a minimal example:

```prolog
.decl example(arg1, arg2)
example(a, b
```

```
$ souffle --version
Souffle: 1.5.1
Copyright (c) 2016-18 The Souffle Developers.
Copyright (c) 2013-16 Oracle and/or its affiliates.

$ souffle minimal.dl
Error: syntax error, unexpected ",", expecting : in unknown source location.
1 errors generated, evaluation aborted
```

I get the same behavior on HEAD-1ac3109. A similar issue is reported in #888, in which the source locations are only missing in specific cases.

**Comment by mmcgr** [comment]
I can't reproduce this. What OS and compiler version are you using?

**Comment by rljacobson** [comment]
I am on macos Mojave. I followed the installation instructions on the website, but I just noticed they may not be in sync with the MacOS build instructions. I am following the build-from-source instructions right now and will report back.

For reference, Mac install instructions:

```bash
$ brew install souffle-lang/souffle/souffle
```
or
```bash
brew install --HEAD souffle-lang/souffle/souffle
```
and [associated Homebrew formula is here](https://github.com/souffle-lang/homebrew-souffle/blob/master/Formula/souffle.rb).

**Comment by rljacobson** [comment]
I followed [the instructions for building on MacOS exactly](https://souffle-lang.github.io/docs/build/#mac-os-x-build). I see the same behavior. Here is the minimal example I posted above:

```
$ souffle --version
Souffle: 1.5.1-1165-g1ac31099
Copyright (c) 2016-18 The Souffle Developers.
Copyright (c) 2013-16 Oracle and/or its affiliates.
Deskbert:Lifetimes rjacobson$ souffle -D. minimal.dl
Error: syntax error, unexpected ",", expecting : in unknown source location.
1 errors generated, evaluation aborted 
```

Running `TESTSUITEFLAGS=-j8 make check` produced 4 errors, attached:
[testsuite.log](https://github.com/souffle-lang/souffle/files/3299602/testsuite.log)

**Comment by b-scholz** [comment]
It could be that the pre-processor does not issue the #line instruction causing this issue. 
We use mcpp for souffle. Have you installed a special version of mcpp or is it linked to clang-cpp?

**Comment by b-scholz** [comment]
Also, can you check whether you can invoke mcpp?

**Comment by rljacobson** [comment]
The problem is that `scanner.ll` cannot parse file paths with spaces. The relevant code is [this block](https://github.com/souffle-lang/souffle/blob/1ac310994792ebe57a34a05f00391963a02c1f68/src/scanner.ll#L198):

```c
if(sscanf(yytext,"# %d \"%s",&lineno,fname)>=2) {
  assert(strlen(fname) > 0 && "failed conversion");
  fname[strlen(fname)-1]='\0';
  yycolumn = 1; yylineno = lineno-1;
  yyfilename = SLOOKUP(fname);
} else if(sscanf(yytext,"#line %d \"%s",&lineno,fname)>=2) {
  assert(strlen(fname) > 0 && "failed conversion");
  fname[strlen(fname)-1]='\0';
  yycolumn = 1; yylineno = lineno-1;
  yyfilename = SLOOKUP(fname);
}
```

The fix is to change the pattern `"# %d \"%s"` to `"# %d \"%[^\"]"` and bump the location of the terminal `\0`, and likewise for the `else` branch:

```c
char fname[yyleng+1];
int lineno;
if(sscanf(yytext,"# %d \"%[^\"]",&lineno,fname)>=2) {
  assert(strlen(fname) > 0 && "failed conversion");
  fname[strlen(fname)]='\0';
  yycolumn = 1; yylineno = lineno-1;
  yyfilename = SLOOKUP(fname);
} else if(sscanf(yytext,"#line %d \"%[^\"]",&lineno,fname)>=2) {
  assert(strlen(fname) > 0 && "failed conversion");
  fname[strlen(fname)]='\0';
  yycolumn = 1; yylineno = lineno-1;
  yyfilename = SLOOKUP(fname);
}
```

I am running `make check` on the adjusted code right now. Recall I previously had 4 tests fail. Shall I submit a pull request if I get the same output as before?

Thanks for your help!

**Comment by rljacobson** [comment]
Strangely, `make check` now produces 8 errors instead of 4. I poked around a couple of the failed tests and wonder if they're false positives. The ones I checked all said, `sort: No such file or directory`. I have attached `testsuite.log`: [testsuite.log](https://github.com/souffle-lang/souffle/files/3302726/testsuite.log)

I went ahead and submitted a pull request: #1070.

**Comment by b-scholz** [comment]
Martin and I talked about this issue today. It could have been related to your directory names. However, I saw that you used "/Users/rjacobson/Downloads" from the log - hence that would not explain this behaviour.

Is it possible that you could send us your whole souffle directory with testsuite.dir and built executable. It is very hard to analyse what is going on with your build remotely.

We could not reproduce your issues on our side.

**Comment by rljacobson** [comment]
There are two distinct scenarios. My issue is the _second_ scenario. Since the code from `scanner.ll` posted above manifestly cannot parse a path with a space in it (see below), I suspect you are testing the first. Would you mind testing the second scenario below before we go to the trouble of sending you a 200+ MB zip file?

**Scenario 1:** `souffle` is passed a path with a space: 

```
$ ./souffle ../untitled\ folder/test.dl
Can't open input file "../untitled".
1 error in preprocessor.
```
**Scenario 2:** `souffle` is *callled* from within a directory with a space but passed a regular file name: 

```
$ cd souffle/untitled\ folder
$ ../src/souffle test.dl
Error: syntax error, unexpected identifier, expecting ) or "," in unknown source location.
.decl assign( a:var b:var )
--------------------^-------
1 errors generated, evaluation aborted
```

In any case, it is still true that the scanner is unable to parse paths with spaces, which you can see for yourself by running the following program. Note also that `mcpp` expands the path of the input file to its absolute path. 

```c++
#include <iostream>
#include <cstdio>

int main(){
    char text[200], fname[200];
    int success = 0, lineno = 0;
    char yytext[] = "#line 45 \"/Users/rjacobson/Downloads/souffle/untitled folder/test.dl\"";

    std::cout << "\nWith fix:\n";
    success = std::sscanf(yytext, "#line %d \"%[^\"]", &lineno, fname);
    std::cout << "Tokens found: " << success << '\n';
    std::cout << "The %d is: " << lineno << '\n';
    std::cout << "The %s is: " << fname << std::endl;


    std::cout << "\nOriginal:\n";
    success = std::sscanf(yytext, "#line %d \"%s", &lineno, fname);
    std::cout << "Tokens found: " << success << '\n';
    std::cout << "The %d is: " << lineno << '\n';
    std::cout << "The %s is: " << fname << std::endl;

    return 0;
}
```

**Comment by b-scholz** [comment]
Indeed - directory names with blanks would fail miserably. 

I agree that the scanning of ```#line``` directives is sub-optimal. 

It was written in a rush.  I believe that most C++ programmers would not like to see scanf() instructions in their code. 

I wonder whether we should use a small hand-written scanner for ```#line``` directives to overcome the issues as pointed out by you.  

```
if(!strncmp(yytext,"#line",5)) { 
  process arguments ...
}
```

Would you like to do this?

**Comment by rljacobson** [comment]
@b-scholz You make a good point, and I agree with you. Sure, I'd be happy to do that.

**Comment by rljacobson** [comment]
@b-scholz I've got a patch I think is workable. I've written up some test cases, but it's not clear where—of whether—they should be included in the source tree. The `test` directory appears to hold tests related to *user* input, while the `src/test` directory holds unit tests for interpreter/compiler internals. Maybe this code is too trivial to include a formal test for, as it's only likely to break if mcpp changes. Of course I'm happy to do whatever is typical for the project. Just let me know.

**Comment by b-scholz** [comment]
I propose to write a scanning function that takes the yytext string, the line number, and filename as arguments. It returns a true/false depending on whether the yytext can be parsed.

The string is invoked in the  ```scanner.ll```. For testing, it would be great to write some unit tests in ```src/tests```. For the unit tests, a new entry in ```src/Makefile.am``` is required. If you could use strings in the unit tests that fail with the current setup, that would be great.
