### ISSUE TITLE
Possible bugs in `SouffleInterface.h`

### ISSUE THREAD

**Issue by lyndonmhenry** [souffle-lang/souffle#1071]
Thanks to PR  #1068, a bug was fixed in `SouffleInterface.h` in which relations that are both input and output were being added **twice** to the vector returned by `SouffleProgram::getAllRelations()`. This led me to notice some other stuff going on in the `SouffleProgram` class which may or may not be bugs. Some things may seem pedantic, but `SouffleProgram` is rather an important class, and requires higher standards of quality than much else of the code base. 

- Why is `relationMap` an `std::map` and not a `std::unordered_map`, which is typically more efficient? The only reason I can see is that relations are required to be stored in the order of their names, though I don't know why this would be the case (maybe determinism concerns?).
- Why do `getInputRelations()`, `getOutputRelations()`, `getInternalRelations()`, and `getAllRelations()` return a copy, not a const reference? Each of these `get` methods needs to called again after each call to `addRelation()` to get an updated vector.
- Why is `Relation* rel` passed to `addRelation` and not `const Relation*` when `addRelation` does not modify `rel`?
- Why are `inputDirectory` and `outputDirectory` passed to `runAll`, `printAll`, and `loadAll` as values and not by reference? Also, why are they not marked as const parameters?
- Why is the `name` parameter to `executeSubroutine` passed as a mutable value?
- As relations can be both input and output, calling `purgeOutputRelations()` and `purgeInputRelations()` can purge the same relation twice. This sounds dangerously like a double free. 
- Why do the `purge...Relations` methods not empty their corresponding vectors in order to free memory earlier?
- Why is `getSymbolTable` not a const member function?
- Why is there no `purgeAllRelations()`?
- Why do we allow a `nullptr` to be returned from `getRelation()` when a relation cannot be found? Null pointers are generally agreed to be terrible design, and are better dealt with by an option/maybe type (e.g. `std::optional`). Note that a null pointer might actually be good here for performance reasons though, I am not sure.  
- Why are the stratum indices not passed as const parameters?
- Super pedantic mode: Why do we use `size_t` with a value of -1? Why use `Relation*` and not `auto*` in the purge methods?

**Comment by lyndonhenry** [comment]
No need for answers on those that are obvious code smells, but it would be good to know if any of my questions have well reasoned answers that I have not understood properly.

**Comment by b-scholz** [comment]
It would be great to tidy this up and strengthen the interface.

**Comment by mmcgr** [comment]
The purge methods remove facts from the relations, they don't remove the relations. This is useful if you intend to re-run a program, or part thereof, as described in #883 . It is safe to double purge a relation, since it empties rather than frees memory. purgeOutputRelations is obviously useful for re-running a program. purgeInputRelations is slightly more specialised as it is only helpful if you supply new input.

Relation* vs auto* - no reason. It just hasn't been updated yet in our attempts to improve consistency.

constness and refs - as far as I know, everything you say is reasonable, although getSymbolTable may need to be non-const if its intent is to allow changes to the symbol table.

**Comment by lyndonhenry** [comment]
Note: This is related to #1075.

**Comment by b-scholz** [comment]
Can we close this issue?
