### ISSUE TITLE
A souffle::tuple can be inserted in any souffle::Relation having the same arity

### ISSUE THREAD

**Issue by MrNbaYoh** [souffle-lang/souffle#1075]
When creating a `souffle::tuple` you must give a `souffle::Relation*` as a parameter, it is used to check the attributes and arity when adding elements to the tuple. However if you try to insert the tuple in another relation having the same arity it will work regardless of the attribute types.

**Comment by b-scholz** [comment]
Yes - indeed. We don't do a check.

**Comment by lyndonhenry** [comment]
Note: This is related to #1071
