### ISSUE TITLE
Calculating minimal hop count

### ISSUE THREAD

**Issue by simonchatts** [souffle-lang/souffle#1084]
I think this is a usage question not a bug report, sorry - is there a more appropriate place to ask?

Suppose I have a graph, and want to calculate the relation: "between `node1` and `node2`, there is a reachable path, and the minimal hop count across all possible paths is `n`". (Imperatively, this would just be a transitive closure calculation with a little extra bookkeeping.)

How can I express this? My attempts so far fail to stratify, such as the most naive example below:

```prolog
reachable_in(node1, node2, 1) :- edge(node1, node2).
reachable_in(node1, node3, n + 1) :- reachable_in(node1, node2, n), 
                                     edge(node2, node3),
                                     !(reachable_in(node1, node3, m), m <= n).
```

Thanks for Soufflé by the way, it's really impressive!

**Comment by pnappa** [comment]
Hey Simon,

We have some interesting example programs that it may be useful to study in `tests/example`. There are a few instances of shortest paths, which can be adapted for your reachability length programs. Find them in `tests/example/minpath1`, `tests/example/minpath2`, and `tests/example/minpath3`.

Cheers,
Patrick

**Comment by simonchatts** [comment]
Thanks Patrick! Yes those examples are indeed useful (`minpath3` is particularly eye-opening) and I've got something working now.

The trick in those examples of summing the distances to get a finite bound is not very constraining for my use case, so it's not quick (lots of unwanted materialization), but I have something I can try to optimize now. Thanks again!

Cheers,
Simon
