### ISSUE TITLE
magic set with failed compilation 

### ISSUE THREAD

**Issue by psubotic** [souffle-lang/souffle#1104]
I used as a source the cclyzer ruleset (https://github.com/plast-lab/cclyzer-souffle/tree/master/src)

if you compiler and have --magic-transform=callgraph_edge

the default backet nesting will exceed. 

e.g., 

./souffle-std.cpp:332448:259: fatal error: bracket nesting level exceeded maximum of 256
./souffle-std.cpp:332448:259: note: use -fbracket-depth=N to increase maximum nesting level
7704 warnings and 1 error generated.

I will mail you guys the cpp

My guess is that the transformation blows up (which can happen in theory). Perhaps there is some heuristic or improvement that can be done here?

**Comment by b-scholz** [comment]
Can you run it in the interpreter - is it blowing up there as well?

**Comment by mmcgr** [comment]
The Synthesiser handles conjunctions like this:
```cpp
            out << "((";
            visit(conj.getLHS(), out);                                                                                 
            out << ") && (";                                                                                           
            visit(conj.getRHS(), out);
            out << "))";
```
The exit condition before merging is a recursive conjunction of emptiness checks for all involved relations. The conditions themselves also add brackets. Using fewer brackets in conjunctions will help with this issue.

**Comment by psubotic** [comment]
Ok that fix allows compilation. Performance is an orthogonal issue so ill
close this
