### ISSUE TITLE
profiler

### ISSUE THREAD

**Issue by lhf777111** [souffle-lang/souffle#1106]
In the first line of the table on the left side of the first figure below, the total time is 5.4s, 15.4% of time. So, 5.4/0.154 = 35s. But the total runtime is 66.7s(the left side of the second figure below). Why are these two numbers different?

The following figures is a comparison of the results of two different versions of my program. The cost of rules is very similar, why the running time varies greatly?

![image](https://user-images.githubusercontent.com/16070223/63014429-19a94500-bec1-11e9-8e2c-745c451a1444.png)

![image](https://user-images.githubusercontent.com/16070223/63014444-2037bc80-bec1-11e9-9297-e8aec94ee738.png)

**Comment by b-scholz** [comment]
Please, can you attach the datalog and profile file so that we can investigate?

**Comment by lhf777111** [comment]
The attachment is profile.
[profile.zip](https://github.com/souffle-lang/souffle/files/3504047/profile.zip)

**Comment by b-scholz** [comment]
Can you give us the profile as well (not just the htmls)?

**Comment by lhf777111** [comment]
[profile.zip](https://github.com/souffle-lang/souffle/files/3504136/profile.zip)

**Comment by lhf777111** [comment]
The following rule has a disjunction B1 and B2.
Internally souffle have two rules representing the disjunction.
A(a, b, e, f) :-
  (B1(_, _);
   B2(_, _)),
  C(a, b, c, d),
  D(e, f, g, d),
  E(g, c).
 
You can divide above rule into two rules, if you are interested in the performance.
A(a, b, e, f) :-
  B1(_, _),
  C(a, b, c, d),
  D(e, f, g, d),
  E(g, c).
A(a, b, e, f) :-
  B2(_, _),
  C(a, b, c, d),
  D(e, f, g, d),
  E(g, c).
The profile will be correct.
