### ISSUE TITLE
Allow repeated, identical declarations of relations or use-before-declare.

### ISSUE THREAD

**Issue by HerbertJordan** [souffle-lang/souffle#111]
When structuring specifications in multiple files, there are situations in which declarations of the same relations would be allowed to be repeated several times -- just the have the declaration and definition of relations in the same file.

**Comment by HerbertJordan** [comment]
Alternatively, allow relations to be used before their declaration. There is no real argument against it, except for implementation issues that can be handled.

**Comment by b-scholz** [comment]
Could we guard it with the preprocessor, i.e., 

```
#ifndef _My_Table 
#define _My_Table
.decl MyTable(x:number,y:number)
#endif 
```

**Comment by psubotic** [comment]
or scope the relation in a file unless its exported

**Comment by HerbertJordan** [comment]
It is kinda ugly for something that can be easily covered in the parser.

The use-before-declare case is a bit tougher.

**Comment by b-scholz** [comment]
Is this really an important issue or can we put it on the back burner?

**Comment by HerbertJordan** [comment]
Would anybody be against having a use-before-declare feature?

For instance, I would like to support something like
```
.decl A( ... )
A(..) :- ..
A(..) :- .., B(..), ..

.decl B(..)
B(..) :- ...
B(..) :- ..., A(..), ..
```
such that i can distribute the A and B parts into two different files, without the need of a forward-declaration file including the declarations, but not the definitions. This C-style solution is not very nice and lead to some confusion by people working on it.

**Comment by HerbertJordan** [comment]
I checked, this is actually already working.

So I guess we can close this issue.
