### ISSUE TITLE
Dynamic set of equality relations

### ISSUE THREAD

**Issue by csabahruska** [souffle-lang/souffle#1119]
Is it possible to model a key value map in Souffle/Datalog where the key is a `symbol` and the value would be an equality relation (`eqrel`)?

i.e.
```js
.decl EqMap(name:symbol, a:symbol, b:symbol) eqrel
```

Where `a` and `b` forms an equality relation and `name` selects one relation from a set of eqrels.

EDIT:

Is the code below a sufficient and efficient solution?
```js
.type Pair = [
  name: symbol,
  v: symbol
]
.decl EQ(x:Pair, y:Pair) eqrel
```

**Comment by b-scholz** [comment]
Unfortunately, Souffle's typesystem does not support a map of eqrel relations. 

The second proposed type is an equivalence relations on pairs. Assuming that you insert pairs of pairs whose names are identical, you should get the same functionality.  However, you need to ensure that you maintain this invariant - the typesystem will not do this for you.
