### ISSUE TITLE
Floating point values are implicitly converted to integers for input fact files

### ISSUE THREAD

**Issue by lyndonhenry** [souffle-lang/souffle#1126]
The following issue was found by capstone project students @Honghyw, @NubKel, @detljh, @chadgavin.

Given a Souffle program `A.dl`

~~~
.decl A(x:number)
.input A
.output A
~~~

Where `A.facts` is 

~~~
3.141
~~~

We have that `A.csv` is computed as

~~~
3
~~~

However, adding the following line to the Datalog program

~~~
A(3.141).
~~~

Gives the error

~~~
Error: syntax error, unexpected ., expecting ) or "," in file A.dl at line 4
A(3.141).
---^------
1 errors generated, evaluation aborted
~~~

This is inconsistent behavior, and floating point values in input fact files should raise an error.

**Comment by mmcgr** [comment]
The file reading is optimised for speed. Checking for invalid input adds overhead, which is substantial when reading hundreds of gigabytes of input date, if not terabytes. If thorough checking of the input data is desired, then we may actually want a choice of input readers - default, that checks thoroughly and gives good feedback, and fast, that is fast but uninformative. It may also be reasonable to just define fact files more tightly than datalog facts.

Note that currently we use [std::stoull(string)/stoi(string)](https://en.cppreference.com/w/cpp/string/basic_string/stoul) to parse the input. 
> Discards any whitespace characters (as identified by calling isspace()) until the first non-whitespace character is found, then takes as many characters as possible to form a valid base-n (where n=base) unsigned integer number representation and converts them to an integer value.

This will 'work' for more than just floating point numbers.
