### ISSUE TITLE
How to use floats given the current type system?

### ISSUE THREAD

**Issue by josephcappadona** [souffle-lang/souffle#1127]
Hi, given that it seems float support is still a ways away, what are my options (if any) for using floats and floating point arithmetic? (Feel free to delete my comment [here](https://github.com/souffle-lang/souffle/issues/1039#issuecomment-536831407).)

@b-scholz

**Comment by b-scholz** [comment]
You can implement your own type via functors. Functors are externally defined functions

https://souffle-lang.github.io/functors

Here is a small mini-library that can be starting point for floating point numbers in Soufflé
```
#include <cstdint>
#include <cstring>
#include <string>

extern "C" {

int32_t fadd(int32_t a, int32_t b) {
    float fa = (float)a;
    float fb = (float)b;
    float result = fa + fb;
    return (int32_t) result;
}

int32_t stof(const char* s) {
    std::string fs(s);
    float result = std::stof (fs);
    return (int32_t) result;
}
}
```

With the following definitions you can write Datalog with floating point numbers:

```
.functor fadd(number, numberl):number
.functor stof(symbol):number

.decl A(x:number)
A(@fadd(stof("1.0"), stof("2.0"))) :- true.

.printsize A
```

**Comment by b-scholz** [comment]
A very basic version of float and unsigned numbers are implemented in the type system.

**Comment by josephcappadona** [comment]
Is there documentation somewhere on how to specify a float type? Or is it handled implicitly via the `number` type?

**Comment by b-scholz** [comment]
We are currently working on record I/O, unsigned/float, and the type system such that we can finish version 2.0.
The latest version has support for float/unsigned but not for user-defined functors. See issue #1274.
By the way – could you write a small news blog on souffle-lang.github.io about your souffle interface?

**Comment by josephcappadona** [comment]
> By the way – could you write a small news blog on souffle-lang.github.io about your souffle interface?

What interface are you referring to?

**Comment by b-scholz** [comment]
I see on your github that you have been working on python/souffle.

**Comment by josephcappadona** [comment]
That is something a bit different--I simply forked that--however for my work I did in fact build a Python wrapper for Souffle. If you'd like to know more I can ask my company's founders if they would be open to me doing a write-up and possibly sharing the code. If you'd like, we can continue the conversation over email, my email is on my profile.

**Comment by b-scholz** [comment]
Let's talk via email: Bernhard.Scholz@sydney.edu.au

**Comment by josephcappadona** [comment]
One follow-up question. Currently, floats are only supported in this context `Float(0) :- 0.999 <= 1.0.` but not in this context `Float(0.5) :- .....`. Are there plans to support floats in the latter context?

**Comment by b-scholz** [comment]
If I understand the question correctly - we don't have implicit casts and we still need to extend the type system for all usages of float/signed/unsigned (e.g. aggregates etc.).
