### ISSUE TITLE
-j option weirdness with the compiler

### ISSUE THREAD

**Issue by taipan-snake** [souffle-lang/souffle#1128]
Currently how the `-j` option works with the compiler is:
* If you specify `-j n` where n > 1, then the compiler will generate a parallel executable (with the `ParallelTransformer`transformer) which includes the `pfor` macro doing OpenMP stuff. Then, during runtime, you can specify any number of threads (`./compiled_souffle_program -j 123`). 
* If you specify `-j 1`, then the `pfor` macro is not generated, and also the `omp_set_num_threads` call is not generated. In this case, you can still do `./compiled_souffle_program -j 123`, but it won't do anything
* If you specify `-j auto`, then internally it converts it to `-j 0`, which makes the compiler do the same as `-j 1` (as far as I can tell). This doesn't match what it says in the help menu

It would be nice to clean this up and document it better.

There is another thing that might be nice to have with embedded souffle. Currently, if you generate a `.cpp` file with souffle (`souffle -g souffle_program -j 2`) and then try to use it embedded in something else, the souffle-generated part will always call `omp_set_num_threads(2)`, and there is no way of setting the number of threads for at runtime. It might be nice to allow the client code to call `omp_set_num_threads` to set the number of threads at runtime.

**Comment by mmcgr** [comment]
I've addressed most of your points in #1132 

The pfor macro for openmp should be generated as long as openmp is present at compiletime.
