### ISSUE TITLE
Improve Java and Python checks for SWIG features

### ISSUE THREAD

**Issue by lyndonhenry** [souffle-lang/souffle#1141]
The checks for Python and Java as SWIG dependencies in `configure.ac` introduced by PR  #1133 can be improved. 

There already appears to be at least a Python check included with the `ax_pkg_swig` Autoconf module (see [here](https://www.gnu.org/software/autoconf-archive/ax_pkg_swig.html#ax_pkg_swig)). 

There are also Java (see [here](https://www.gnu.org/software/autoconf-archive/ax_prog_java.html)) and Python (see [here](https://www.gnu.org/software/autoconf-archive/ax_pkg_swig.html#ax_pkg_swig)) Autoconf modules available that may be useful if the SWIG package does not provide all the features we need.

**Comment by b-scholz** [comment]
Is this fixed?
