### ISSUE TITLE
Vary tests based on configuration settings

### ISSUE THREAD

**Issue by mmcgr** [souffle-lang/souffle#1142]
It would be helpful if the tests varied depending on options set during the configure stage. So, for example, if provenance is disabled then the provenance tests aren't run. Currently these choices are made at testsuite compilation time using environment variables. This is sufficient for selecting particular test groups, but unhelpful for generating the broadest set of tests that should pass given the current configuration.

An alternative is to accept tests failing if their supporting features are not enabled, which is a correct result, but rarely a useful result.

This was attempted in #1133, but turned out to require further work.

**Comment by b-scholz** [comment]
With CMAKE, we changed the test environment.
