### ISSUE TITLE
Enabling provenance leads to incorrect output

### ISSUE THREAD

**Issue by mmcgr** [souffle-lang/souffle#1159]
When provenance is enabled output relations may have missing data.

I suspect this is due to a merge issue that's left behind a mix of `arity + numberOfHeights` and the older `arity + 2`.

**Comment by mmcgr** [comment]
The problem seems to arise only with interpreted souffle, provenance enabled, and concurrent jobs. This combination has been disabled until the issue is fixed.

**Comment by b-scholz** [comment]
This is related due to the fact that we don't have specialised provenance data-structures for the interpreter and hence the existence-check for provenance cannot be performed concurrently. 

For the interpreter, the provenance system must run sequentially.
