### ISSUE TITLE
Consider making a new release tag?

### ISSUE THREAD

**Issue by luc-tielen** [souffle-lang/souffle#1160]
In a [repo of mine](https://github.com/luc-tielen/souffle-haskell/issues/1) where I provide Haskell bindings to Souffle, I received the question to expose the API for configuring amount of threads for a Souffle program. 
However I noticed that the commit this was introduced (2bb86fb9c) in seems to be later than latest 1.6.2 release? Can a new release (1.7.0?) be made for this new functionality? 
Thanks in advance!

**Comment by mmcgr** [comment]
It didn't seem a major change at the time, but put like that a new release tag seems reasonable.

I want to deal with #1159 first, either by fixing or disabling interpreted provenance, but I'll make a new release soon.

**Comment by luc-tielen** [comment]
Great, I will update the souffle package in [nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/souffle/default.nix) too then once it is released since that 1 still points to 1.6.1. 😄

**Comment by luc-tielen** [comment]
Closing this, I tried out version 1.7.0 in combination with souffle-haskell. Thanks @mmcgr !
I opened a PR to nixpkgs (found here: https://github.com/NixOS/nixpkgs/pull/74704) so should be updated there soon too if all goes well 😃.
