### ISSUE TITLE
Facts from fact file handled differently from dl file

### ISSUE THREAD

**Issue by mmcgr** [souffle-lang/souffle#1174]
Input from a fact file has less rigorous checking than from a dl, e.g.,
 * 0.15
 * 0x10
 * 0b10

Reading from the dl file produces an error for the float and accepts the hex and binary input. Reading from file accepts all three, but as `0`, i.e., reads them as a decimal int until a non-int is reached.

Better behaviour would be to treat both sources the same. This may slow down file reading, so benchmarking is needed before this is changed, with the possible addition of slow error checked reading and fast restrictive reading (all input are decimal ints).

**Comment by b-scholz** [comment]
This is done - right?
