### ISSUE TITLE
Travis builds the distribution twice

### ISSUE THREAD

**Issue by scyptnex** [souffle-lang/souffle#118]
Looking at the travis logs, seems we build souffle twice.

This is about 10 minutes every pull-request we can save

**Comment by icesparrow** [comment]
I think I got rid of the issue by using a library.

For deb target though we still need to build as it needs to create a source distribution first and then build it to create binary. The default target can be overridden, but then we are not really testing the deb distribution.

**Comment by b-scholz** [comment]
We need to push the "./configure;make" into the os relevant parts of the build process. 
The best way to go forward is to build straight the packages for each OS system and do the checks in the package build process. Alternatively, we could have two modes of operation: One mode is used only for a simple check-in of new code snippets -- the other mode is used for deployment. I feel the alternative option is too much effort. Let's build the packages and do the checks when the packages are built. There is also less that can go wrong if we perform always the same steps.

**Comment by b-scholz** [comment]
We have now an improvement travis script that relies on shell scripts. There are two shell scripts in the directory .travis. One shell script installs software depending on the OS and the other one builds souffle, runs checks, and builds the packages.
