### ISSUE TITLE
CXX flag not picked up during deb build

### ISSUE THREAD

**Issue by scyptnex** [souffle-lang/souffle#119]
Seems that `make deb` on travis is not picking up the LLVM compiler, wven when that build is active (look at the logs to confirm)

We need `make deb` to actually make its internal version of souffle with clang if that is the CXX executable

**Comment by icesparrow** [comment]
Could you please elaborate on that? Is that OSX builds or Lunux builds you are talking about?

I can have a look at the issue

**Comment by b-scholz** [comment]
If you look in the log file of TRAVIS, the CXX flags is not picked up by the build process triggered by "make deb".

**Comment by b-scholz** [comment]
I suggest that we build Debian packages for G++ only. G++ seems to be the default for most Linux distributions. I talked to Nic recently - having two packages for two compilers is confusing and will cause issues especially if the packages don't differentiate their files.

In the latest attempt of reorganising the travis script, clang++ is no longer used for deployment - although it is an element of the matrix and it is checked whether clang++ can build and run the checks.
