### ISSUE TITLE
RamIndexAnalysis

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#1204]
The RamIndexAnalysis interface has collected some dust.  Especially, the class ```MinIndexSelection``` needs some overhaul. There should be some distinction between the client RamIndexAnalysis and the Synthesiser/Interpreter when using the index orders only. One solution could be that RamIndexAnalysis is a friend of RamIndexAnalysis so that the whole interface is hidden.

**Comment by b-scholz** [comment]
If totalSignature method is too slow, add a cache that keeps previously queried existence checks that have a total signature (or not).

**Comment by SamArch27** [comment]
Can we close this issue?

I think it's solved by the recent refactoring PRs: #1781 #1785 #1797

**Comment by b-scholz** [comment]
Yes, please!
