### ISSUE TITLE
souffle2bdd/souffle2lb

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#1205]
These are translators from Soufflé to Logicblox / BDDBDDB that are not very well maintained. 

I suggest to open a new repo transferring these translators there.

**Comment by mmcgr** [comment]
Logicblox has had some substantial changes. Does the translator still work or does it depend on particular versions of Logicblox?

**Comment by b-scholz** [comment]
We are interested in pa-datalog - a Logicblox 3.0 variation only. 
http://snf-705535.vm.okeanos.grnet.gr/agreement.html
Other versions of logicblox are not so important.

**Comment by mmcgr** [comment]
I'm removing the translators in #1219. Rather than maintaining them indefinitely, if they are needed in future that PR can be reverted and the translators updated.
