### ISSUE TITLE
Packaging for distributons

### ISSUE THREAD

**Issue by icesparrow** [souffle-lang/souffle#125]
I will be soon trying to push `souffle` to different Linux distributions. I suppose we can start with Debian and then address others (such as Fudora, ArchLinux, Gentoo etc). There are a couple of minor issues left.
1. We need a gpg key to sign the package. I can probably create one for myself and use it. Any objections or suggestions?
2. The source files have a souffle version hard-coded. Presently it is 0.0.0 (or 0.0.0-25-g8be1361 in some test files). So I suppose before doing anything this needs to be changed to 1.0.0. Do we want to maintain the version in the source files? This would need a change before every release/version change.
3. I suggest that each version becomes a protected branch. Then if there is a fix in a specific version then it is propagated to the master branch (if applicable) but recent developments from master do not go to previous versions normally. Any objections to such a model? 
4. I suppose we need to create a new tag.

**Comment by scyptnex** [comment]
I'll remove the hard-coded version from the header, that should keep things simple.

Seems the signing could be tricky given our current strategy of releasing via Travis CI, if you do make a keypair i would suggest encrypting the private with the same login we use to access souffle-lang account.
Though in this case, signing the debian packages for a PPA would be done manually by someone who knows that password.

**Comment by b-scholz** [comment]
Nic and I looked up the package building repositories which could sign packages automatically. 

For example, travis-ci would support bintray and other build repositories. My understanding is that bintray is free for OSS. Which of those providers would be most suitable for our project.

**Comment by b-scholz** [comment]
There is an interesting project that builds RPMs in the travis-ci environment. 

https://github.com/spacewalkproject/spacewalk

It uses the tools `koji` and `tito`. Perhaps we could replicate their effort to build RPMs in an UBUNTU/Debian environment.

**Comment by b-scholz** [comment]
I found this article:
https://blog.bintray.com/2014/12/16/hosting-debian-packages-on-bintray-rocks/

**Comment by b-scholz** [comment]
I have triggered an upload manually (not via travis-ci).

https://bintray.com/souffle-lang/deb/souffle/view

I am still need to read up how to sign automatically and how the deployment works fully automatically.

**Comment by icesparrow** [comment]
Do we want to create actual release packages that we will be sending to repositories completely automatically using Ubuntu only? Also, in the release section we will need the all files generated by the deb target including the source distribution (as generated by debuild). 

There is also an issue #128 tagged 1.0.0, are we waiting until it is fixed?

**Comment by b-scholz** [comment]
Ideally we do everything in travis-ci to minimize the build dependencies. If it cannot be done, we could use our plang1 virtual server farm to build and push the release packages. That is also an option. I am not an expert on these issues. Nic - what is your opinion?

I pushed the bug from 1.0.0 to 1.0.1. A semantic check hasn't been implemented properly. We are too permissive in the semantics. It is not a big deal. Only for the folks who are into aggregation, that might be a problem if they are not carefully writing their aggregations.

**Comment by scyptnex** [comment]
@icesparrow 

We're looking into automatic deployment. If you know, can you run me through the process of going from the repository we have to a package available for me to go `sudo apt-get install souffle`?

**Comment by icesparrow** [comment]
Sure. Is it the process that generates the package and then installs it via package manager you are looking for?

**Comment by scyptnex** [comment]
both

**Comment by icesparrow** [comment]
These are good guides, I would also suggest [this document](https://www.debian.org/doc/manuals/developers-reference/index.html), it contains much more information about the packages and how to submit them etc.

So the way the distribution should go is as follows:
We have some packaging code in configure and top-level makefile that detects the system and builds the package if the right tools are found. For debian this is currently `deb` target and for OSX it is `pkg`, I am making some adjustments at the moments to make a unified target (e.g., `package`) and better handle different distros. There are differences in Debian/Ubintu, for instance currently `deb` does not work in Debian stable because for non-native packages it requires version of the form: `VERSION-NUMBER`. 

From build perspective the sequence is as follows:
- bootstrap and configure souffle
- update the version in debian/changelog to the right one (this is not done yet)
- make deb (using debuild)
- sign it with GPG using debsign or using gpg itself. To my understanding this is not strictly required, commonly the repository metadata is signed rather then debs directly, still this is good to have the package signed I think. I do not have much experience with GPG signatures.
- install using
```
apt-get install -f *.deb
```
or 
```
dpkg -i *.deb
```
The above can be done automatically for every commit. Optionally, if we setup our own debian repository we can upload the generated file there, update and sign the metadata etc. 

Getting the package into the default debian repositories seems to be more of a manual process (parts of it can be automated but there will still be people reviewing it). Everything is done through a bug tracking system and bug reports, even the initial submission and version updates. This is approximately as follows:

- Initially we create a package, put in the first record in changelog and file a bug against `wnpp` package. We need to make sure that everything is ok. There are a lot of things mentioned in Chapters 5, 6 and 7 or the debian maintainers guide.
- Then we upload everything to their repository (including source, signatures etc)
- Then they review it and either update or reject the package.

Once the package is in the repository it is more straightforward:
- As the development goes on the changelog is updated
- once ready new bugs are filed, new packages are uploaded and reviewed.

I hope the above to some extent answers your questions, do let me know if you need more details. I am new to this whole process so I also may be wrong somewhere.
