### ISSUE TITLE
Excessive compilation times

### ISSUE THREAD

**Issue by mmcgr** [souffle-lang/souffle#1253]
With #1250, compilation times have increased (http://plang1.it.usyd.edu.au/jenkins/job/Master-Performance/plot/). The likely cause is that the removal of stratums also removed the lambda outlining that was added to reduce compilation time.

**Comment by b-scholz** [comment]
This is related to issue #1246. 
The idea is to replace the old notion of a stratum with a subroutine. 
However, for this purpose, we need to get rid of the error state in the subroutine invocation first.
