### ISSUE TITLE
AST Refactoring

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#1255]
- [x] Some of the methods of Ast-classes are implemented in cpp-files. These implementations are trivial and should be placed in the header files (c.f. AstAggregate etc.). 

- [x] We have a non-uniform interface accessing arguments/values in Ast. We can either access it as a whole vector or individual elements of the vector; we should remove individual element access methods and count methods to further compact the code. (done for AstTerm/AstFunctor/etc). The AstAtom interface is still not uniform.

- [x] Non-uniform naming of concepts and printing for AstNullConstant

- [x] Remove empty methods and place default methods into AstNode

- [x] Remove SymbolTable references in AstConstant for string / have a separate hierarchy for strings and store them directly in the AstConstant. Also, remove the dependency of a symbol table in AST, scanner, and parser. 

- [x] Move abstract classes into AstAbstract to avoid dependency mess or put every class into an own header file.  

- [x] After the first round of refactoring, I noticed that we have no true POD-style classes in AST, i.e., AST classes compute meta-information about the AST objects rather than describing what they are. As a quick fix, we can move these methods into AstUtils. In another round, we may implement them as an AstAnalysis.

 - [x] getAtom() in AstLiteral is a virtual method that has no semantic meaning for Constraints etc. That needs to be fixed (i.e. ~~creating a subclass AstAtomLiteral introducing this method~~; let's get rid of class AstAtomLiteral and have specific cases).  

- [x] The class AstClause is convoluted and needs to be entangled.  It splits Atoms, constraints etc. - perhaps this is not necessary.  Methods isComplete(), hasFixedExecutionPlan() etc needs to be placed in AstUtils. (partially done). Revisit the state of AstClause to make it a POD-style class.

 - [x] Clauses are stored in AstRelation. This causes issues in constructing and processing AstProgram and AstComponent. They need to be moved to the AstProgram/AstComponent only. An AstAnalysis should be used to access the clauses of a relation.  In AstProgram, there are parsing dependency (i.e. finishParsing()) for copying clauses to relations that need to be removed.

 - [x] AstTypeIdentifier and AstRelationIdentifier implement the same concept. We need to unify them (e.g. AstComponentQualifier etc.)
 
- [x] AstPragma has a transformer in its header file. Let's put the transformer into the AstTransforms files. 

 - [x] The classes AstExecutionOrder and AstPlan have convoluted interfaces. Tidy-up the interfaces.

 - [x] The refactoring of IO directives is necessary to streamline the class representation for AstProgram/Components. IO directives are key/value stores describing the character of an IO operation. However, we have a class hierarchy augmenting the meaning of the I/O operation (e.g. Printsize/Load/Store) in AST and RAM that violates the responsibility principle (either the key-value-store describes the IO operation or the class hierarchy). I would suggest that we have a single IO statement in AST and RAM. The parser already augments the key-value store with the right operation (printsize/input/output/etc).

- [x] AstIO class is designed for a set of relations; change it so that an AstIO is defined for a single relation.

 - [x] IO directives are stored in AstRelation, AstComponents, and AstPrograms. They need to be removed from AstRelation. 

 - [x] AstPragma has a transformer in its header file. Let's put the transformer into the AstTransforms files. 

 - [x] AstProgram has copy constructors that are misplaced  

 - [x] The debug reporting is hard-coded for AstAnalyses - check the RAM implementation for a generic reporting facility. 

- [x] equal_target utility for maps

**Comment by mmcgr** [comment]
The SymbolTable could also be removed from RAM in a similar way.

**Comment by b-scholz** [comment]
I feel there is no SymbolTable in the actual RAM representation. 
Strings have been already resolved to numbers.

**Comment by b-scholz** [comment]
After the first round of refactoring, I noticed that we have no true POD-style classes in AST, i.e., AST classes compute meta-information about the AST objects rather than describing what they are.

**Comment by b-scholz** [comment]
getAtom() in AstLiteral is a virtual method that has no semantic meaning for Constraints etc. That needs to be fixed (i.e. creating a subclass AstAtomLiteral introducing this method).

**Comment by b-scholz** [comment]
The class AstClause is convoluted and needs to be entangled.

**Comment by b-scholz** [comment]
AstTypeIdentifier and AstRelationIdentifier implement the same concept. We need to unify them (e.g. AstComponentQualifier etc.)

**Comment by b-scholz** [comment]
The classes AstExecutionOrder and AstPlan have convoluted interfaces.

**Comment by b-scholz** [comment]
The debug reporting is hard-coded for AstAnalyses - check the RAM implementation for a generic reporting facility.

**Comment by b-scholz** [comment]
AstProgram has copy constructors / parsing dependency and other functionality that is irrelevant for the description of an AstProgram.

**Comment by b-scholz** [comment]
Let's have a single IO statement only (instead of having sub-classes for load/store/etc).

**Comment by b-scholz** [comment]
AstPragma has a transformer in its header file. Let's put the transformer into the AstTransforms files.

**Comment by b-scholz** [comment]
- Refactor all AST access patterns in transformers.

**Comment by b-scholz** [comment]
- AstComponent and AstProgram have a strong similarity. Put the same functionality into a sub-class.
