### ISSUE TITLE
Complete Unsigned/Float support

### ISSUE THREAD

**Issue by darth-tytus** [souffle-lang/souffle#1274]
TODO:
- [x] Binary Constraints
- [x] Aggregators
- [x] User-defined functors
- [x] Souffle Interface
- [x] Explain Provenance
- [x] Swig
- [x] records
- [x] AstConstant should use strings
- [x] polymorphic constants
- [x] subset type support
- [x] union type support
- [ ] Provenance: binary constraint printing

**Comment by b-scholz** [comment]
There is also the need to refactor AstConstant, i.e., we should have a representation for RAM already internalized in AST. I would suggest storing all number constants as strings. 
The AstTranslator decides using the type system and the string representation of the number, which constant representation for the translation should be chosen.

**Comment by b-scholz** [comment]
Let's close the issue. Binary constraints are too hard. We will need a full RAM representation to capture all possible cases.
