### ISSUE TITLE
Improve Performance of RecordTable

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#1286]
We have uniformed the interface of RecordTable for the interpreter and the compiler. As a consequence, the compiled code may perform slower than before because we use std::vector<> instead of std::array<> for a given arity. We would require some experiments to confirm this. 

To overcome this problem, we can specialize maps for a finite set of arities in the interpreter and specialize the RecordTable for compilers so that only the occurring arities are captured with std::arrray<> maps. 

This requires some template work for RecordTable. 

Alternatively, we can replace maps with unordered maps. Templates are not so useful in the interface of RecordMap because the interface will be exposed in the UDF interface.

**Comment by b-scholz** [comment]
We may want to implement a lock-free version of RecordTables or implement a Reader-Writer mechanism so that we permit simultaneous multiple reads.

**Comment by quentin** [comment]
Hi, I have been working on redesigning the symbol and record tables to makes them concurrent and lock-free.

On some of our workloads that intensively read and write the record tables we measured that most of the thread time is spent waiting for the critical section that serializes access to the record table. Increasing the number of threads only worsen the performances.

With this change we measured a performance gain almost linear with the number of threads. And a slightly improved single thread baseline thanks to the removal of costly operations on vectors mainly.

https://github.com/quentin/souffle/commit/04a4bc9f7be9f73700d88f96e29ff30bc4f1276c

The pinnacle is the possibility to specialize the record table for some arbitrary record map arities, and fallback to a generic map for other arities:
```c++
using RecordTable = SpecializedRecordTable<0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12>;
```
You suggested to compute the set of arities in the compilers, this part is not done yet as I did not study that part of Souffle.

It probably deserves more comments, cleanup and testing, but is this something that would eventually be eligible to a merge?

**Comment by b-scholz** [comment]
That would be wonderful! 

Does this new version works for the interpreter and the compiler ?  

It would be important to have a uniform interface so that functor libraries work for the interpreter and the compiler.

**Comment by quentin** [comment]
Yes it is mostly transparent to any code that use `RecordTable` and `SymbolTable`. It passes all tests.

The API is mostly unchanged. I only removed the `size()` function of the symbol table because it's not widely used and it is not a trivial operation with the new datastructure. Moreover I didn't want to add an atomic size counter in the datastructure just for this operation. Instead there is a concurrent iterator on the datastructure. Also the `unsafeEncode/Decode` behave exactly like `encode/decode`, although it's not inevitable.

**Comment by b-scholz** [comment]
That is great. Does it pass all the test cases?

**Comment by quentin** [comment]
All test cases pass in the last version of the branch https://github.com/quentin/souffle/tree/concurrent-tables
Note that I only tested with ram domain size 64.

About tests, I am not sure the tests in `src/tests` are run when using CMake and ctest.
So I also build with `bootstrap + configure + make` and run `make check`.

**Comment by b-scholz** [comment]
Great - make a pull request! We will see quickly whether it works for 32bit as well.

It would be great if you could support both autoconf/automake and cmake at the moment. 

We are still extending the cmake infrastructure; it may still take few more weeks to remove the autoconf/automake infrastructure entirely.
