### ISSUE TITLE
cyclic aggregation

### ISSUE THREAD

**Issue by freedafeng** [souffle-lang/souffle#1295]
It seems that the aggregation functions are a bit too strict. A similar version of the following codes works fine in pyDataLog, but failed for two trials.

1st try:
.decl child(x:symbol, y:symbol)

child("b1", "a1").
child("b1", "a2").
child("b2", "a1").
child("c2", "a1").
child("c1", "b1").
child("d1", "c1").
child("d1", "c2").
child("d2", "c2").
child("d3", "c1").
child("d4", "c2").

.decl level(x:symbol, y:number)
.output level

level("a1", 0).
level("a2", 0).

level(x, z + 1) :- child(x, y), z = min u:{level(y, u)}.

Error Message:
.decl level(x:symbol, y:number)
------^-------------------------
has cyclic aggregation in file _snomed_level.dl at line 22
level(x, z + 1) :- child(x, y), z = min u:{level(y, u)}.
-------------------------------------------^-------------
1 errors generated, evaluation aborted

2nd try:

Replaced the last line of the .dl file into the following:
level(x, z + 1) :- z = min u:{level(y, u), child(x, y)}.

Error: Witness problem: argument grounded by an aggregator's inner scope is used ungrounded in outer scope in file _snomed_level.dl at line 23
level(x, z + 1) :- z = min u:{level(y, u), child(x, y)}.
------^--------------------------------------------------
Error: Unable to stratify relation(s) {level}
Relation level in file _snomed_level.dl at line 15
.decl level(x:symbol, y:number)
------^-------------------------
has cyclic aggregation in file _snomed_level.dl at line 23
level(x, z + 1) :- z = min u:{level(y, u), child(x, y)}.
------------------------------^--------------------------
2 errors generated, evaluation aborted

Could anyone take a look and see if there is a fix or workaround? Thanks a lot!

**Comment by b-scholz** [comment]
I believe you would like to have non-stratified aggregates. 
This is in principle possible; however, the semantic checker stops this at the moment for termination reasons etc.

**Comment by b-scholz** [comment]
With the current flavor of Souffle, you can compute this by building up an induction over the children of a node knowing who is the first, second, third child, etc. This coding style is more involved.

**Comment by freedafeng** [comment]
Thanks for your comments b-scholz. I am new to logic programming. The work around that I can figure out is to create a temporary relation, and then the final relation is defined to be the min of the temporary relation. This will cause a lot of memory and time waste though in the case of a complex graph. Just in case, this code is simply to find the depth of a node in a DAG. The depth is defined to be the minimal steps from the origin node which are assigned to have depth 0. 
u
The work around that I talk about is,
level(x, z + 1) :- child(x, y), level(y, z).

.decl min_level(x:symbol, y:number)
min_level(x, y) :- y = min z:{level(x, z)}.

**Comment by b-scholz** [comment]
Grounded variables in Datalog have very specific semantics (and yes it is related to free variables). 
The idea here is that a grounded variable can assume a value from at least one relation in the body of a clause. Free variables (variables that cannot assume values from relations in the body of a clause) are trouble-same and not permitted. I hope that helps. 

Could you solve your problem above?

**Comment by freedafeng** [comment]
Thanks! I've got a workaround working.
