### ISSUE TITLE
asking for help on using souffle's c++ interface or swig

### ISSUE THREAD

**Issue by freedafeng** [souffle-lang/souffle#1303]
Hi, not sure if this is the right place to ask for help. So, please let me know if I need to post this request somewhere else. 

I am thinking to use souffle's c++ interface or swig so that I can use souffle's functionality in one of my python projects (through cython or swig). However, my use case might be a little more complicated than the examples that I read in the documentations for souffle's c++ interface or swig. Here is how my project should look like,

1. read the initial facts, probably about 1M relations.
2. for loop:
    i): read more facts, probably ~10 new relations each time. 
    ii): define a new relation.
    ii): run the program to solve this relation.

A more concrete example would be like the following - please ignore the syntax errors. 

.decl edge(x:number, y:number)
.input edge
// the input has the relations such as,  edge(1, 2), edge(1, 3).
.decl path(x:number, y:number)
path(x, y) :- edge(x, y).
path(x, y) :- path(x, z), edge(z, y).

// now we enter the for loop.
// for(;;)
// read the new data somewhere else, then we add some new facts, such as,
edge(2, 4).
// define new relation
.decl path2(x:number)
path2(x) :- path(2, x)
// now we need to read the result for the path2(x), and then send the result out.
// for loop ends here.

I have read all the souffle's documents about C++ interface and swig. but I am still not sure if this can be done. Can someone please let me know? If it can be done, is there an example that does similar things? an example would be super helpful. I am kinda new to logic program, and not very familiar with C++ either. but I am fine with programming in general, especially in C and python. 

Thanks a lot!

**Comment by b-scholz** [comment]
Yes - definitely that is the right place to ask. 

Please, can you have a look at the C++ interface? There, you will see that there is a notion of an instance. 

Is it possible that you express these numerous relations via separate instances if they do exactly the same calculation?

```
SouffleProgram* prog1 = ProgramFactory::newInstance("path");
SouffleProgram* prog2 = ProgramFactory::newInstance("path");
SouffleProgram* prog3 = ProgramFactory::newInstance("path");
```

You would need to keep track of them and push/pull data from these various instances.

**Comment by freedafeng** [comment]
Thanks Bernhard for the quick response! 

I have actually read the documents on C++ interface multiple times. I believe I did not make question clear enough in my previous message.

Can I define a new relation using the C++ interface, instead of using the datalog program?
    For example, I want to do the same as ".decl reachable (n: symbol, m: symbol)" as in a .dl script, but using the C++ interface instead. 
    Imagine this is a server program. It reads the initial fact db into its memory when it starts. Then it starts to wait for the requests from the client programs. One of the client programs in the system sends a request to the server, saying, "now I have this new fact. You should add this new fact to the system. and I also need to know what result I can get for my new query (a relation that did not exist on server side before)?" 

  In order to respond to this request correctly, the server needs to define a relation, add couple of new facts, and calculate the result. 

Using that "edge, path" example, the initial fact data is, edge(1, 2), edge(1, 3). The client sends to the server a new fact - edge(2, 4). notice there "4" is a new term. then the client asks what nodes I can get to through paths from node 2. The client does not care nodes that paths can lead to from any other node. So here we define a new relation, path2(x): path(2, x). Next time another client might send us some other facts with a different question. 

Thanks.
Thanks a lot!

**Comment by psubotic** [comment]
Does it have to be a new named relation or just new tuples in pre-existing
relation?

**Comment by freedafeng** [comment]
It doesn't need to be a new named relation. as in the example of calculating path(2, x), the path is a pre-existing relation. but we don't want to calculate path(x, y) for all x and y, because that's a huge set. we only need to get all the paths from the node "2". 

Thanks!

**Comment by freedafeng** [comment]
Maybe there is a work-around using a permanent relation for temporary usage, like a scratch space. Following the above "edge", "path" example, 

// The temporary space.
.decl interesting_node(n: number)

// The result we look for.
.decl interesting_path(n: number)
interesting_path(n) :- interesting_node(m), path(m, n). 

Then when using C++ interface, we can do  "interseting_node.insert(2)", and then calculate "interesting_path". After collecting the result, we can purge the "interesting_node" relation....
