### ISSUE TITLE
Records as ADTs

### ISSUE THREAD

**Issue by psubotic** [souffle-lang/souffle#1327]
I would like to use records as poor mans ADT e.g., 

.type A = [a: symbol, n: number]
.type B = [a: symbol, n: number, c: symbol]

.type AorB = A | B

.decl P(AorB)
P([x, 5]) :- R(x).
P([x, 4, y]) :- G(x), H(y).

K(a) :- P([a, b]), b < 10 a = "Single".
M(a, c) :- P([a, b, c]), b < 10, a = "Double".

**Comment by b-scholz** [comment]
This is related to issue #380.

**Comment by ohamel-softwaresecure** [comment]
There is a proposed implementation of ADTs & sum-types in #1310. That PR is currently awaiting some feedback/review regarding alternative designs for unions of structurally heterogeneous types. Please leave some feedback over there if it satisfies your use case or if you've an alternative proposal.
