### ISSUE TITLE
relation name same as reserved c++ keyword

### ISSUE THREAD

**Issue by psubotic** [souffle-lang/souffle#133]
Hi I'm wondering if this can happen:  a relation name is say default and the C++ generates an ident default which is not a valid C++ ident. I think its not good practice to put the burden of the user to avoid C++ keywords when programming in Datalog. Souffle should augment a prefix to relation names in the generated C++. 

Also we should document better what idents are and not allowed in the Souffle datalog.

**Comment by psubotic** [comment]
updated wiki

**Comment by b-scholz** [comment]
Relation names are translated to C++ identifiers with Anton's recent fix, i.e., issue #55. Also I believe that each relation name in the generated C++ receives the prefix "rel_"

Anton you looked at this recently. Anton - can you comment?

**Comment by psubotic** [comment]
oh - this must be recent. On my fork it isn't the case. So even R-1 and R/1 are valid?

**Comment by b-scholz** [comment]
No - R-1 would be interpreted as (R)-(1) and the same for (R)/(1) because - and / are arithmetic operations. We could extend the lexer to cope with this. However, it would get messy very quickly. Basically, for arithmetic operations we would need to have always a space in between operands. This is not a nice solution.

**Comment by psubotic** [comment]
ok just checking - this all needs to be documented in the wiki. Perhaps Anton can document what a literal can and cant be?

**Comment by zyzek** [comment]
Any relation name translated to a C++ identifier is prefixed with "rel_" or "wrapper_", I believe. So C++ identifiers should work fine on this basis. Otherwise, the C++ identifier rules are followed, except that '?' is also permitted.

**Comment by b-scholz** [comment]
I double checked and relation names such as "default" work without issues.

I close this issue.
