### ISSUE TITLE
Request help: possibility to remove facts dynamically and calculate single relation

### ISSUE THREAD

**Issue by freedafeng** [souffle-lang/souffle#1332]
This is some scenario I need to handle in my application.

1. I need to remove some facts in a big EDB fact data set at run time from time to time. For relations with only small set of facts, I can call purge and then rebuild. but for large relations, it's not practical to purge every time.
2. I have many output relations, but I don't need to run all of them every time I call souffle. I only need to run one or two relations to serve each request. 

Is there an easy way to make these two functions work? or workarounds? please let me know. Thanks!

**Comment by b-scholz** [comment]
Datalog has no notion of deletion. However, you can copy. 
For example, you can make a copy of relation A without elements specified in notA:
```
   B(x) :- A(x), !notA(x).
```
where B contains A without tuples in notA(). 

Alternatively, you can use the programmatic C++ interface to filter out tuples in C++ using the iterator and an if-statement.
