### ISSUE TITLE
Type Cast (as <typename>) 

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#1338]
With the new refactoring phase and extensions of signed/float, type-casts may not work as expected. This needs to be revisited.

**Comment by nevillegrech** [comment]
Casting is a necessity I think, without which it's very hard to write anything substantial. Here's what I'm doing to cast things, I defined these two functors:

```
  inline int32_t hex_to_number(const char *x) {
    return (int32_t) uint256_t(x).template convert_to<int>();
  }

  inline int32_t cast_to_number(int32_t x) {
    return x;
  }
```

Now I can write code like this:

```
.type Variable <: symbol
.type StackIndex <: symbol
.type VariableOrStackIndex = Variable | StackIndex

.decl A(a: VariableOrStackIndex)

.decl B(a: Variable)

B(@cast_to_symbol(a)) :- A(a).
```

**Comment by b-scholz** [comment]
Indeed - we need this urgently.
