### ISSUE TITLE
Document the way to Import/reuse .dl file

### ISSUE THREAD

**Issue by izgzhen** [souffle-lang/souffle#1340]
I am using Souffle and I wonder if it supports "importing" one .dl file inside another one so I can share code between different ".dl" files?

I've read the help message on "-L" and "-I", but they seem not related to the problem I had.

Thanks in advance!

**Comment by izgzhen** [comment]
Update:

It seems that the following directive works

```
#include "path/to/x.dl"
```

I would change the issue to a documentation one. Feel free to close it as well.

**Comment by psubotic** [comment]
you might want to use #pragma once if you have a large projects to avoid
multiple includes -- same rules apply as in C++ as a C-preprocessor is
used.

**Comment by b-scholz** [comment]
We need to document how mcpp works in conjunction with soufflé. Basically, mcpp is a c-preprocessor that processor that is used to expand the source code internally. You can use macros and includes in your Soufflé programs.

**Comment by mmcgr** [comment]
Our current documentation exists, but is extremely limited:
https://souffle-lang.github.io/tutorial#remarks-on-input-and-c-preprocessor
