### ISSUE TITLE
Cannot create a new directory for output files

### ISSUE THREAD

**Issue by shrutihiray** [souffle-lang/souffle#1341]
`.output A(IO=file, filename="newDir/A.csv", delimiter=",")`

Output file **A.csv** is not created unless **newDir** is already present in the file system. 
A new directory is not automatically created if it does not exist.

**Comment by b-scholz** [comment]
Does it need to be in the souffle system? None of the C-compilers, for example, produce output directories for created objects. It is better to create the directories outside of souffle via a script etc.

**Comment by mmcgr** [comment]
Closing this as there has been no new feedback.

The current behaviour is intended, but if there is a clear overall benefit could be changed. Discussion first would be needed as there are also drawbacks.
