### ISSUE TITLE
Souffle chat room

### ISSUE THREAD

**Issue by psubotic** [souffle-lang/souffle#136]
Hi this isn’t so related to souffle code but it would be kind of nice to have a chat room for souffle - say someone has a quick question that doesn’t warrant a ticket - someone can answer it?

**Comment by b-scholz** [comment]
In another project we use slack. This seems to be more modern than IRC. 

http://www.slack.com

**Comment by psubotic** [comment]
thats pretty hip! lets use it!

**Comment by b-scholz** [comment]
Ok - I set a channel up. 
Please let me know whether somebody would like to join the channel.

**Comment by icesparrow** [comment]
I have just joined too! Slack is pretty great for this sort of thing
