### ISSUE TITLE
Error loading data: Required table and view does not exist for relation edge

### ISSUE THREAD

**Issue by Ayrx** [souffle-lang/souffle#1363]
I have the following Souffle program:

```
.decl edge(x:symbol, y:symbol)
.input edge(IO=sqlite, dbname="data.sqlite")

.decl path(n:symbol, m:symbol)
.output path

path(x, y) :- edge(x, y).
```

I get the following error when running the program:

```
➜  repro souffle --version
Souffle: 1.7.1-1169-gb03eb9ef(32bit Domains)
Copyright (c) 2016-19 The Souffle Developers.
Copyright (c) 2013-16 Oracle and/or its affiliates.
➜  repro souffle -F. -D. repro.dl
Error loading data: Required table and view does not exist for relation edge
```

`data.sqlite` has a table named `edge`, file can be found at [data.sqlite.zip](https://github.com/souffle-lang/souffle/files/4332820/data.sqlite.zip)

From what I see at https://souffle-lang.github.io/io#input, it seems like this should work. I'm not sure if it's a bug in my program or a bug in Souffle.

**Comment by b-scholz** [comment]
Can you try an older release version and check whether you observe the same behavior?

**Comment by Ayrx** [comment]
Tried two other versions, all installed via the `apt` repository:

* 1.7.0-34-gea33d41b-1
* 1.6.2-454-g8c7d7750-1

Same behaviour observed.

**Comment by Ayrx** [comment]
So I traced the issue to the following piece of code:,

```cpp
void checkTableExists() {
    sqlite3_stmt* tableStatement;
    std::stringstream selectSQL;
    selectSQL << "SELECT count(*) FROM sqlite_master WHERE type IN ('table', 'view') AND ";
    selectSQL << " name IN ('" << relationName << "', '_" << relationName << "');";
    const char* tail = nullptr;

    if (sqlite3_prepare_v2(db, selectSQL.str().c_str(), -1, &tableStatement, &tail) != SQLITE_OK) {
        throwError("SQLite error in sqlite3_prepare_v2: ");
    }

    if (sqlite3_step(tableStatement) == SQLITE_ROW) {
        int count = sqlite3_column_int(tableStatement, 0);
        if (count == 2) {
            sqlite3_finalize(tableStatement);
            return;
        }
    }
    sqlite3_finalize(tableStatement);
    throw std::invalid_argument("Required table and view does not exist for relation " + relationName);
}
```
https://github.com/souffle-lang/souffle/blob/master/src/ReadStreamSQLite.h#L132

Given the relation edge, it is expecting a table `_edge` and a view `edge`. I can workaround the problem by generating my sqlite database with those constraints in mind.

However, is this intended behaviour? Seems odd that I would need to create a view that basically returns the entire table.

**Comment by b-scholz** [comment]
Well - this is sort of intended behavior since you would like to load data from a database. In case, the tables don't exist, it is sort of unusual semantics to create them because you would have to tuples in them.  

I need to discuss with @mmcgr whether this is something we would like to change in the near future.

**Comment by Ayrx** [comment]
Right, but in this case the database needs to have a table named `_edge` __and__ a view named `edge` even though they both return the same set of data. It seems like the presence of a single table or view named `_edge` would be sufficient?

In any case, if this is the expected behaviour the documentation should be updated to state this? I would be happy to open a PR to update the docs.

**Comment by b-scholz** [comment]
Let me talk to @mmcgr so that we can decide either to document or to fix it. 

Thanks for pointing out this issue.

**Comment by b-scholz** [comment]
I had a quick conversation with @mmcgr today. We decided that this is a documentation issue. 
I.e., when you load from a relation in SQLITE3, we assume it must exist. 

May I ask you for a favor - can you extend the Souffle's documentation saying that for input-directives reading from SQLITE3 tables, the tables must exist. Many thanks in advance.

**Comment by Ayrx** [comment]
@b-scholz PR opened.

**Comment by mmcgr** [comment]
To add a bit of explanation - the view is helpful when there are symbols. Symbols are stored in `__SymbolTable` and an index to the table is stored in `_RelationName` rather than storing the symbol directly.

So the tables used are '__SymbolTable` and `_RelationName`. `RelationName` is a view which joins these together.

I'm fairly sure the reader will work just fine with a table if `checkTableExists` is modified.
