### ISSUE TITLE
--fact-dir option does not work for IO=sqlite

### ISSUE THREAD

**Issue by Ayrx** [souffle-lang/souffle#1370]
The `--fact-dir` option does not work with `IO=sqlite`. This makes specifying the directory of the database file at runtime impossible.

Following `repro.dl` script:

```
.decl edge(x:symbol, y:symbol)
.input edge(IO=sqlite, dbname="input.sqlite")

.decl path(n:symbol, m:symbol)
.output path

path(x, y) :- edge(x, y).
```

Ran with:

```
➜  repro ls .. | grep input.sqlite 
input.sqlite
➜  repro souffle -F.. -D. repro.dl 
Error loading data: Required table and view does not exist for relation edge
```

It would be very helpful if `--fact-dir` applies to `IO=sqlite` if a relative path is provided.

**Comment by b-scholz** [comment]
This is a similar issue. The idea of a fact-directory is in case we have several comma-separated files. In the case of a database, the fact-directory becomes superfluous. 

Please can you amend the documentation? Many thanks in advance.

**Comment by Ayrx** [comment]
I think the documentation is pretty clear on this point.

This is a feature request for the `--fact-dir` option to be extended to the database (or a different option added) as it would offer a nice flexibility especially for the compiled executable as hard coding the path is not ideal if you are writing code that should run in environments outside of your direct control.

**Comment by mmcgr** [comment]
sqlite hasn't had much use for a long time so there also hasn't been much work on it. 
Would specifying the path in the datalog meet your needs?
```
.input edge(IO=sqlite, dbname="/path/to/input.sqlite")
```
That can be made more flexible using a macro, something like
```
souffle -M PATH="/path/to/input.sqlite" edge.dl
```
with 
```
.input edge(IO=sqlite, dbname=DBPATH)
```

I think specifying paths for sqlite in the same manner as for csv input is reasonable. If sqlite support is proving useful, adding a siilar path support could be looked at.

**Comment by Ayrx** [comment]
Ah! I wasn't aware that sqlite wasn't used as much as the CSV inputs.

A macro is one way to work around the issue but I think a CLI option to specify the path would be very helpful for compiled executables.

E.g. if I am writing a static analysis CLI tool that takes a sqlite database as an argument, a natural way to structure the tool would be to compile all souffle scripts into executables at install time. When the tool is run, create a temporary folder, copy the database there and run the executable with a command line option specifying the location of the temporary folder.

I _could_ generate a permanent folder at install time and use a macro to specify that folder when compiling the executables but that would not allow me to run multiple analysis scripts in parallel for instance.

**Comment by Ayrx** [comment]
I believe #1372 has addressed this? Thank you so much @mmcgr :)
