### ISSUE TITLE
souffleprof.jar manpage

### ISSUE THREAD

**Issue by icesparrow** [souffle-lang/souffle#138]
Could someone familiar with `souffleprof.jar` please write a brief manpage for it? It is not strictly required for distribution but `lintian` keeps throwing warnings about that, that would be good if we could minimise the warnings.

**Comment by b-scholz** [comment]
I will do it. It is the profiler tool of souffle.

**Comment by icesparrow** [comment]
Thanks Bernhard, that would be great
