### ISSUE TITLE
Efficiently selecting n elements from another relation.

### ISSUE THREAD

**Issue by dschoepe** [souffle-lang/souffle#1390]
Given a relation `R(arg1, arg2, .., argn)`, I want to create a relation `S(arg1, arg2, .., argn)` that contains a subset of R of at most `n` elements (doesn't matter which ones). The only solution I could find is to pick some injective function mapping tuples in R to some number, and then using count. Here's an example using an `R` with two arguments: 

```
.decl R(x: symbol, y: symbol)
.input R

.decl Limit(n: number)
Limit(5).

.decl S(x: symbol, y: symbol)

.decl RwithOrd(x: symbol, y: symbol, o: number)
RwithOrd(x, y, o) :-
    R(x, y), o = ord(cat(x, y)).

S(x, y) :-
    RwithOrd(x, y, o1),
    Limit(n),
    count : { RwithOrd(x2, y2, o2), o2 < o1 } < n.
```

However, this takes minutes if R contains around 10,000 tuples and results in an intermediate relation for count with 50 million tuples. Profiling indicates that the problem is the last line with `count`. 

Intuitively, there should be a way to compute this with the running time only depending on `n`, regardless of how many elements R has. Is there a way to implement `S` more efficiently?

**Comment by b-scholz** [comment]
Perhaps you would like to use the auto-increment functor. Unfortunately, you don't know the starting point of the autoincrement and hence you need to do some post-processing to filter this out:

```
#define N 10

.decl A(x:number, y:number) 
.input A

// only know that it is contiguous – don’t know the starting number of $
// especially if used in more than one rule
.decl B(x:number, y:number, ctr:number)
B(x,y,$) :- A(x,y). 

.decl C(x:number, y:number, ctr:number, i:number) 
C(x,y,m,1) :- m = min p: { B(x,y,p)}, B(x,y, m). 
C(x,y,o+1,i+1) :- C(_,_,o,i), B(x,y,o+1) < N. 
.output C
```

**Comment by b-scholz** [comment]
Can you do me a favor and write up an example in tests/example and make a pull-request (so that others can benefit from the solution as well)? Many thanks.

**Comment by dschoepe** [comment]
I think that solves my issues, thanks. I'll write it up as an example as well. A side note is that the documentation for `$` in https://souffle-lang.github.io/arithmetic should probably mention that `$` can be assumed to be contiguous. I had assumed it was just random and unique and that anything else would be an implementation detail that may change in the future.

**Comment by b-scholz** [comment]
Could you please update the documentation? Many thanks.
