### ISSUE TITLE
[souffle 1.7.1-1290-g978c8c4c] testsuite: 180 342 842 failed

### ISSUE THREAD

**Issue by lubosures** [souffle-lang/souffle#1393]
Opening an issue directly instead of e-mailing to an https address ...
```
## ------------- ##
## Test results. ##
## ------------- ##

ERROR: All 995 tests were run,
3 failed unexpectedly.
## -------------------------- ##
## testsuite.log was created. ##
## -------------------------- ##

Please send `tests/testsuite.log' and all information you think might help:

   To: <https://github.com/souffle-lang/souffle/issues>
   Subject: [souffle 1.7.1-1290-g978c8c4c] testsuite: 180 342 842 failed
```
```
$ src/souffle --version
Souffle: 1.7.1-1290-g978c8c4c(32bit Domains)
```
```
$ uname -a
Darwin tarpon18 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
```
```
$ $CC --version
gcc-9 (Homebrew GCC 9.3.0) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
```

[testsuite.log.gz](https://github.com/souffle-lang/souffle/files/4386526/testsuite.log.gz)

Previous version passes all tests
```
$ src/souffle --version
Souffle: 1.7.1-1286-g462a3a87(32bit Domains)
```

**Comment by b-scholz** [comment]
Can you make sure that there is no state from a previous build?
```
make distclean
sh bootstrap
./configure
make check 
```

**Comment by b-scholz** [comment]
It looks like that you have issues with OpenMP. 

Have you installed gcc on your OS X system via brew or do you use the default compiler?

**Comment by mmcgr** [comment]
The log says compiled with `gcc-9 (Homebrew GCC 9.3.0) 9.3.0`
An openmp issue can be checked by using `./configure --disable-openmp`
```sh
make distclean
./bootstrap
./configure --disable-openmp
TESTSUITEFLAGS=-j12 SOUFFLE_CONFS='-j1,-c -j1' make check -j12
```

The log for test 842, `tests/evaluation/subsumption`, shows an odd issue with mcpp not recognising utf8. There is nothing in that test that treats mcpp differently to other tests, and mcpp does recognise utf8 (as it says in the error output in the log). (OpenMP is not used at this stage.)

The other two tests have no csv output, and both exit early with an error code.

If you rerun the tests, do the same tests fail each time? Note that you can rerun only the failed tests by using `tests/testsuite --recheck`

**Comment by b-scholz** [comment]
If I can remember correctly, gcc must be installed via brew with additional flags. Has this be done?

**Comment by lubosures** [comment]
No, I was not aware of any special additional flags, so did just
```
brew install gcc
```

I apologize if this is something obvious which I did not catch :-(

I ran few more builds/tests with gcc and openmp disabled
```
export PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig/
export CXX=g++-9
export CC=gcc-9
export PATH="/usr/local/opt/bison/bin:$PATH"
make distclean
./bootstrap 
./configure --disable-openmp
TESTSUITEFLAGS=-j12 SOUFFLE_CONFS='-j1,-c -j1' make check -j12
```
and the test results for multiple builds are inconsistent:
```
Subject: [souffle 1.7.1-1290-g978c8c4c] testsuite: 174 205 425 failed
Subject: [souffle 1.7.1-1290-g978c8c4c] testsuite: 182 failed
Subject: [souffle 1.7.1-1290-g978c8c4c] testsuite: 227 353 failed

Subject: [souffle 1.7.1-1303-g45a8fdc1] testsuite: 183 failed
Subject: [souffle 1.7.1-1303-g45a8fdc1] testsuite: 317 364 failed
Subject: [souffle 1.7.1-1303-g45a8fdc1] testsuite: 364 502 588 594 failed
```

Using the OS X default compiler creates a binary which passed all the tests consistently, so I shall probably stick to that.

**Comment by b-scholz** [comment]
May I ask - have you run this command to install souffle:

```
 brew install souffle-lang/souffle/souffle
```

or for the latest updates  the development head

```
brew install --HEAD souffle-lang/souffle/souffle
```

**Comment by b-scholz** [comment]
I think the recommended way to install gcc/OpenMP is the following:
```
brew install gcc --without-multilib
```

**Comment by lubosures** [comment]
> brew install gcc --without-multilib

does not work for me:
```
$brew remove gcc
Uninstalling /usr/local/Cellar/gcc/9.3.0... (1,461 files, 287.6MB)

$ brew install gcc --without-multilib 1>/dev/null
Usage: brew install [options] formula
...
Error: invalid option: --without-multilib

$ brew install  gcc
==> Downloading https://homebrew.bintray.com/bottles/gcc-9.3.0.catalina.bottle.tar.gz
Already downloaded: /Users/lubos/Library/Caches/Homebrew/downloads/eecd8468998d1ebdc5d1d4bee0fc0d3241054e78a757343d185b739912ce875c--gcc-9.3.0.catalina.bottle.tar.gz
==> Pouring gcc-9.3.0.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/gcc/9.3.0: 1,461 files, 287.6MB
```

**Comment by lubosures** [comment]
> May I ask - have you run this command to install souffle:
> 
> ```
>  brew install souffle-lang/souffle/souffle
> ```
> 
> or for the latest updates the development head
> 
> ```
> brew install --HEAD souffle-lang/souffle/souffle
> ```

I need to run souffle compiler on multiple platforms: OS X, Ubuntu 16 & 18, Redhat 8.  Sice I did not find prebuilt image fro RHEL8, I decided to clone from git and build it myself. At the same time I used the brew-installed version on OS X. This setup was working well until recently when the self-built images started printing  deprecation warnings:
```
Warning: Deprecated type declaration used in file diag.dl at line 7
.number_type Distance
^-------------------
```
I tried to replace `.number-type Distance` by `.type  Distance=number` but that started giving errors
```
Error: Non-numeric argument for functor in file diag.dl at line 77
ada(a, c, d+1) :- dep(a, b), ada(b, c, d), d < count : { svc(_) }.
------------------------^----------------------------------------------------------------------------------
Error: Unable to deduce type for variable d in file diag.dl at line 77
```
So I changed the type definition to `.type Distance <: number`, which fixed the linux versions, but the brew version 1.7.1 started complaining:
```
Error: syntax error, unexpected <, expecting end of file in file diag.dl at line 5
.type Distance <: number
---------------^---------
1 errors generated, evaluation aborted
```
So my next step was to build souffle on OS X as well, and to stay as close as possible I decided to use the gcc compiler instead of  the xcode version. 

Souffle installed via brew will not compile the `<:` type definition:
```
$ brew install souffle-lang/souffle/souffle
Updating Homebrew...
==> Installing souffle from souffle-lang/souffle
==> Installing dependencies for souffle-lang/souffle/souffle: automake
==> Installing souffle-lang/souffle/souffle dependency: automake
==> Downloading https://homebrew.bintray.com/bottles/automake-1.16.2.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/fe/fe26d4df57481b6a7ca0a6915c37c53648c27ffb41926b3570c45f80fdd8888e?__gda__=exp=1585556373~hmac=5cec9be6445d019421a78ac384ed2026caba30f31753497141b1625c5855ac08&respo
######################################################################## 100.0%
==> Pouring automake-1.16.2.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/automake/1.16.2: 131 files, 3.4MB
==> Installing souffle-lang/souffle/souffle
==> Downloading https://dl.bintray.com/souffle-lang/osx/souffle-1.7.1.tar.gz
Already downloaded: /Users/lubos/Library/Caches/Homebrew/downloads/518b59054d79ea942c8f4dc465c35585fea302cbe8a82c1522f538134a4972bf--souffle-1.7.1.tar.gz
==> ./configure --prefix=/usr/local/Cellar/souffle/1.7.1
==> make install
🍺  /usr/local/Cellar/souffle/1.7.1: 81 files, 9.5MB, built in 2 minutes 58 seconds
$ which souffle
/usr/local/bin/souffle

$ ls -l /usr/local/bin/souffle
lrwxr-xr-x  1 lubos  admin  35 Mar 30 10:11 /usr/local/bin/souffle -> ../Cellar/souffle/1.7.1/bin/souffle

$ souffle diag.dl
Error: syntax error, unexpected <, expecting end of file in file diag.dl at line 2
.type Distance <: number
---------------^---------
1 errors generated, evaluation aborted
```

**Comment by mmcgr** [comment]
I don't have an RHEL8 install to test with, but the [centos/fedora repos ](https://souffle-lang.github.io/install#centos7)will probably also work for RHEL8.

```
yum install https://dl.bintray.com/souffle-lang/rpm-unstable/centos/7/x86_64/souffle-repo-centos-1.0.2-1.x86_64.rpm
yum install souffle
```

There are also the stable repos with which you will avoid the deprecation warnings (until 2.0 is released), although you will also not have any new features/bug fixes made since the previous release. As you've noticed, there have been some syntax changes - new syntax fails in the old version, old syntax is deprecated in the new version. #1375 would help you, if implemented.

**Comment by b-scholz** [comment]
Note there was a change in the syntax for our type system for accommodating different primitive types. We have now number, unsigned, float, and symbol.
I have rewritten some of the type-system documentation. 
https://souffle-lang.github.io/types

I will try to install soufflé via the normal brew commands to see whether I can reproduce your problem.

**Comment by b-scholz** [comment]
I tried to install it via brew and it worked without issues. Is this still an issue?

**Comment by lubosures** [comment]
> I tried to install it via brew and it worked without issues. Is this still an issue for you?

It's not, after you explained I should not use gcc-9 compiler on OS X.  I have no problems building with gcc-8 on linux boxes and clang 11 on OS X. Build `Souffle: 1.7.1-1303-g45a8fdc1` on OS X works for me as well, thanks for your support. 

One last question: what's the exact difference between 
```
.type Distance <: number
```
and
```
.type Distance = number
```
?

**Comment by b-scholz** [comment]
I have recently improved the write-up about types:
https://souffle-lang.github.io/types

Basically <: defines a sub-type and = defines an equivalence type. 
The user-defined type Distance is equivalent to primitive type number. 
You can use either Distance or Number / it is the same. 
Subtypes are different: when a number is expected you can use Distance but not the opposite. 
I hope that makes sense.
