### ISSUE TITLE
Refactor AstTranslator.cpp

### ISSUE THREAD

**Issue by psubotic** [souffle-lang/souffle#140]
The code is pretty difficult to navigate with very very large monolithic functions. I was wondering if there is an agreement/consensus on if its worth while to use a visitor-like pattern to generating RAM? 

Disclaimer: I'm not one of those code perfectionists who reason about subjective code attributes e.g., "code beauty" or a code fascists that follows some rigid rules  -- I have just simply found working with RamTranslator.cpp unnecessarily painful.

**Comment by b-scholz** [comment]
That would be great to tidy up the code. Using the visitor pattern for the translation would be great.

**Comment by b-scholz** [comment]
This is related to issue #541.
