### ISSUE TITLE
Invalid Debian/Ubuntu package state?

### ISSUE THREAD

**Issue by woodruffw** [souffle-lang/souffle#1403]
Hi all,

I'm trying to install souffle using the instructions [here](https://souffle-lang.github.io/install#debianubuntu-systems), but am running into a size and (presumably) checksum mismatch when I `apt-get install souffle`:

```
E: Failed to fetch https://dl.bintray.com/souffle-lang/deb-unstable/dists/bionic/main/binary-amd64/Packages.gz  File has unexpected size (46067 != 45971). Mirror sync in progress? [IP: 52.26.64.218 443]
   Hashes of expected file:
    - Filesize:45971 [weak]
    - SHA256:ce0889c7f8d1f88474afc2f5e462aadf00bd56c0ee2862dccde2f937843fa934
    - SHA1:650b77fca1cf58bb4c4e950bff57337c9c3b9a30 [weak]
    - MD5Sum:1cccc4cfcb87e4b5dd66e7e25460973f [weak]
   Release file created at: Tue, 07 Apr 2020 00:17:57 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

I'm running within an Ubuntu Bionic (18.04) container.

**Comment by mmcgr** [comment]
I just tried and it seems to install fine now. The issue is/was probably temporary.

Does it work for you now?

**Comment by woodruffw** [comment]
> Does it work for you now?

Nope, same error, unfortunately. Did you try with Bionic, or with another distro?

Fetching the `Packages.gz` for Bionic directly I get the incorrect size (46067 bytes).

**Comment by mmcgr** [comment]
I tried with bionic.

I checked, and Releases lists Packages.gz as having size 45971, but it is actually 46067. The checksum for Packages.gz is also different. The unzipped version of Packages inside that *is* the correct size, and has the correct checksum.

I don't know why the file size is different, or why apt-get on different installs of bionic behaves differently. I expect this will work itself out in an equally mysterious manner soon, perhaps with the next commit of souffle. In the meantime, you can try installing the package directly from https://dl.bintray.com/souffle-lang/deb-unstable/pool/main/s/souffle/souffle_1.7.1-1337-g93645011-1_amd64.deb or use the stable repository at deb https://dl.bintray.com/souffle-lang/deb

**Comment by mmcgr** [comment]
I pushed a new commit. The Releases description of Packages.gz now matches the actual size.

Does it work for you now?

**Comment by woodruffw** [comment]
Yep, it appears to be working now. Thanks for looking into it, and pushing a fix!

**Comment by woodruffw** [comment]
@mmcgr it looks like this has manifested again:

```
E: Failed to fetch https://dl.bintray.com/souffle-lang/deb-unstable/dists/bionic
/main/binary-amd64/Packages.gz  File has unexpected size (47814 != 47721). Mirror sync in progress? [IP: 54.190.59.110 443]
   Hashes of expected file:
    - Filesize:47721 [weak]
    - SHA256:937328487d150e1bce99289c24878e1bbb0219c3dcfb12c4255ced550497a2e0
    - SHA1:8a99ab5a9a35a67c6b6ed433c2bc0b8901638190 [weak]
    - MD5Sum:89709abd30005704b9d9d9d83aa32347 [weak]
   Release file created at: Fri, 08 May 2020 14:08:37 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Educated guess: this happened almost exactly one month after my initial report, so it might be a broken cronjob or other scheduled release system.

**Comment by woodruffw** [comment]
As a tangent: I tried switching from `deb-unstable` to `deb` and ran into a separate error:

```
W: GPG error: https://dl.bintray.com/souffle-lang/deb bionic Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A0107419B8C4C745
E: The repository 'https://dl.bintray.com/souffle-lang/deb bionic Release' is not signed.
```

**Comment by mmcgr** [comment]
It looks like the two repos were set up with different keys - our own key or bintray's key. They both worked in the past, and should keep on working, but apparently that hasn't happened. I've changed the repositories so that they both use the same key as deb-unstable, since that's used more often. The (re)signing should be long completed and available, but if you still have issues then the instructions in the [documentation](https://souffle-lang.github.io/install) may help.
```
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys A0107419B8C4C745
sudo apt-get update
```

As always, 'it works for me'. I'll try on a fresh image to see if I can duplicate the error, or success.

**Comment by woodruffw** [comment]
Thanks for the update! I can confirm that `deb-unstable` is once again working (with Bionic).

I was having trouble fetching that `A010` key earlier (every keyserver I queried said that it didn't have it), but I'll give it a stab again.

**Comment by mmcgr** [comment]
I have the same problem now, and also can't check the key from the keyserver. The key has been changed in the repo, but it seems the signing is not regenerated until a new push is made.

You can use `sudo apt-get update --allow-unauthenticated` for now, at the cost of disabling authentication.

**Comment by b-scholz** [comment]
Is this topic resolved - can we close this one?

**Comment by woodruffw** [comment]
I believe so, at least on my end. I'll reopen (again) if it reappears.

**Comment by mmcgr** [comment]
The automatic re-signing didn't happen, but I just triggered an update by adding a package which regenerated the release files and signatures.

The deb repository is now signed the same way as deb-unstable, and the key can be verified, as per the docs.
