### ISSUE TITLE
Proposal: String formatting library

### ISSUE THREAD

**Issue by ohamel-softwaresecure** [souffle-lang/souffle#1408]
Right now we're exclusively using `ostringstream` as our type-safe string formatting facility. I personally find it unpleasant to use as it requires several statements, or long expressions, for something you'd expect to be rather trivial.

There are several high quality libraries out there which do convenient type-safe string formatting. If we're interested in keeping the dependency set small, I propose using https://github.com/c42f/tinyformat and embedding it much as we did json11 (they're roughly the same size).

As a bonus, we can now settle on a standard `fatal` helper function instead of (ab)using various `assert(false && "msg"); exit(1) / abort()` in various partial functions: 
```
template <typename... Args>
[[noreturn]] void fatal(const char* fmt, const Args&... args) {
    format(std::cerr, fmt, args...); // alias for whatever type-safe formatting library we settle on
    assert(false && "fatal error; see std err");
    abort();
}
```

**Comment by b-scholz** [comment]
We had such a request in the past #304. Unfortunately, we did not make progress on it and I closed it. I would fully encourage this.

**Comment by mmcgr** [comment]
Added in #1413
