### ISSUE TITLE
Support Input / Output of Records

### ISSUE THREAD

**Issue by HerbertJordan** [souffle-lang/souffle#142]
We should extend the IO format to support records.

For instance, a relation 

```
.type pair = [ x : number , y : number ]
.decl A( a : number , b : pair )
```

should have the IO format

```
5   [  7  2  ]
```

instead of the current

```
5  8
```

where 8 is just some key referencing the pair [ 7 2 ]. It would make debugging much easier.

**Comment by psubotic** [comment]
yes I agree that would be awesome

**Comment by b-scholz** [comment]
The only problem with printing records that the can be recursively defined, e.g., 
```
.type list = [x:number y:list]
.decl A(x:list)
```
To overcome this I would suggest to print the records only to the first recursive level and add to each record also the reference number.
```
1:[4711 2]
2:[888 3]
3:[123 nil]
```

**Comment by HerbertJordan** [comment]
We could also print it as
```
[ 4711 [ 888 [ 123 nil ]  ] 
```
since we can not have cyclic recursive values. This would not break the general line-format.

**Comment by b-scholz** [comment]
In theory we could produce cycles?

**Comment by gkastrinis** [comment]
I'm thinking that what Herbert is describing is reasonable.

**Comment by HerbertJordan** [comment]
@b-scholz in our current implementation (and language design) it is impossible to form cyclic recursive values.

There is only one way to create a record, by constructing it from a list of values. For this, those values have to be given, hence can not contain the newly created record as a sub-element. Thus, cylces can not be created.

**Comment by b-scholz** [comment]
Ok - let's do it.  I agree that at the moment this is  not possible.  

The other problem might be that if data structures are large and deeply recursive, there will be a lot of data printed and there might be a lot of replication in the output. 

In future, we could permit self-referring constructions  such as 
```
x = [ 10 x] 
```
This could be useful for some applications requiring arbitrary graphs. I am thinking now about the graph database folks. 
 
Furthermore, the compiler/interpreter will require quite a bit of work doing this printing.

**Comment by b-scholz** [comment]
Perhaps we can connect this enhancement with issue #56

Perhaps we use an input/output directives which permits a more flexible specification how to read and write relations for records.

**Comment by HerbertJordan** [comment]
It is much better to process one task after another -- and in between maintain stable, green builds. Combining features causes problems, delays and broken builds. 

Updating the load/store to support a different format is completely independent of #56  which is a language modification that can be conducted independently.
