### ISSUE TITLE
RFC: refactoring - built-in functor overload table

### ISSUE THREAD

**Issue by ohamel-softwaresecure** [souffle-lang/souffle#1424]
Right now we have around sixty different built in functor overloads, more if you could arity overloads. Odds are we'll be adding more.

Each entry requires populating half a dozen or so bits of information across several helper functions (aka giant switches) and make the parser aware of them. In practice this is an awkward game of whack-a-mole.

Proposal: We replace this with a table of built-ins. e.g.
```
BuiltInFunctor BUILTINS[] = {
  { "name", ret-type, { param types list } }, // example
  { "substr", T::String, { T::String, T::Signed } }, // arity overloads
  { "substr", T::String, { T::String, T::Signed, T::Signed } },
  { "min", T::String, variadic(T::String) }, // variadics are supported through constructor overloads
  { "min", T::Signed, variadic(T::Signed) },
  ...,
}
```

Everything else then derives from this table. A bonus is that we can now use macros generate trivial bulk overloads.

What remains is how to map these signatures to implementation keys. An obvious option would be to continue as-is and add an opcode field (or prepare a map from opcode -> signature).

**Comment by b-scholz** [comment]
This would be nice!
