### ISSUE TITLE
Improve CSV Parser

### ISSUE THREAD

**Issue by bragaigor** [souffle-lang/souffle#1427]
Currently I've been experiencing different behaviour in souffle program if I declare the facts associated with inside a `dl` file as opposed to a CSV file. With that in mind, it would be nice to improve souffle CSV parser, so that it behaves the same way as if we were declaring facts inside `dl` files. To illustrate the issue, I have this simple souffle program example:
```
.decl Parent(n: symbol, m: symbol)
Parent("f","rr[rr").
Parent("d,d", "rr[rr").
```

And this one:
```
.decl Parent(n: symbol, m: symbol)
Parent("f","rr,rr").
Parent("d,d", "rr,rr").
```

Where in the first there's a square bracket in the middle of the string and in the second example there's a comma. These two examples run fine if we declare the facts just like above inside the `.dl` file. However, if we want to simulate these behaviour by passing the facts through a CSV file it's not quite possible. So instead, if we had the following in a CSV file:
```
"f","rr[rr"
"g", "rr[rr"
```

or
```
"f","rr,rr"
"g", "rr,rr"
```

The first would complain about unbalanced square brackets and the second would split into 3 arities instead of just 2.
I have also tried to simulate records in a CSV file without success:
```
.type Pair = [a:number, b:number]
.decl A(p: Pair)
A([1,2]).
A([3,4]).
```
Where I tried the following without success:
```
[1,2]
[3,4]
```
and

```
"[1,2]"
"[3,4]"
```

I would imagine a CSV file that simulates the behaviour of declaring facts inside a `.dl` file. For instance, for the first example above I would imagine:
```
"f","rr[rr"
"g", "rr[rr"
```
or
```
"f","rr,rr"
"g", "rr,rr"
```
Since the facts are all symbols (represent them between quotes). For the second example:
```
[1,2]
[3,4]
```

Where records are represented between square brackets. And lastly I wanted to open discussion to see how we can represent more complex expressions like the following:
```
.type IntList = [next: IntList, x: number]
.decl L(l: IntList)
L([nil,10]). // :1:
L([r1,x+10]) :- L(r1), r1=[r2,x], x < 40. // :2:
```
For `:1:` I would image to look like `[nil,10]` just like the example above to parse records.
As for `:2:` I'm not really sure, would everything be an element/token? This one might be overkill, but I think we could start with the simple examples and maybe in the future allow CSV files to support complex expressions like this?

**Comment by darth-tytus** [comment]
The tests that perform reading of records are
```
 semantic.at:147    load_record_delimiter
 semantic.at:148    load_record_large
 semantic.at:149    load_record_large2
 semantic.at:150    load_record_invalid_parenthesis
 semantic.at:151    load_simple_record
 semantic.at:152    load_simple_record2
 semantic.at:153    load_symbol_in_record
```
I think the records examples should work.
We don't represent symbols with quotes in fact-files. Changing this could be difficult as it could break some existing code. Also, symbols are outputted without quotes, therefore `store` and `load` compose nicely.

I think the CSV parser could be enhanced by adding escaping. Maybe in the form of `\[`, `\\`, and some option for escaping delimiter? There could also be an option to produce output in the escaped form so that we could have the composable `store` and `load`.

**Comment by bragaigor** [comment]
In that case we would need to escape characters such as square brackets, back slashes, and commas, as well as modify `WriteStream` accordingly, just like you mentioned, correct? Also is it possible to run individual tests, like the ones mentioned above without the need to run all of them with `make check`?

**Comment by darth-tytus** [comment]
For running tests, you can look at [wiki](https://github.com/souffle-lang/souffle/wiki/Testing,-Continuous-Integration,-and-Deployment) and there are also Martin's and Bernhard's comments under [this pull request](https://github.com/souffle-lang/souffle/pull/1377) which give a very nice overview.

There is a complication related to delimiters. The user can choose the delimiter (arbitrary long, I think) by using the IO directive. For example: 
```
.output Relation(delimiter=" | ")
```
I'm not sure what would be the correct approach to this.

**Comment by bragaigor** [comment]
I wonder if we could be more strict on the user defined delimiters. For instance, we could still allow user defined delimiters but as long as they're a single character, not a digit, excluding special chars such as brackets, parenthesis, etc. And if they happen to fall into one of those cases then the parser throws an error? That way the parser can become more structured, potentially more efficient, and it would allow to encode richer arities in the future. What you think?

**Comment by ohamel-softwaresecure** [comment]
What we really need is a way to define column literals that can't become ambiguous with user-defined column separators. The simplest (IMO) way of doing this would be to add explicit support for quoted column literals:
1) `"` cannot be part of a delimiter
2)  `"` must appear in balanced pairs. (e.g. dangling `"` would be parsed as an incomplete column literal)
3) Leading/tailing whitespace between separators and column literals are skipped over.
4) The (escaped) characters within the quotes define the column's value. 
5) Within a quoted column literal the usual escape sequences would be allowed (using `\`). e.g. `"\""` is the column value `"`".
6) For backwards compat/sanity: Non-quoted column literals are parsed as the shortest sequence possible before matching a delimiter. Leading/tailing whitespace is stripped and the result is the column value.
7) The Souffle value is parsed from the column value. No special top-level handling in the CSV parser handling structured value encoding. (BREAKING CHANGE)
