### ISSUE TITLE
Fail to build on Ubuntu Bionic

### ISSUE THREAD

**Issue by moqingyan** [souffle-lang/souffle#1428]
Hey,

I am building souffle from source, and I ran into a problem during the make phase. 

make[2]: Entering directory '/home/jianih/research/object_reference/prosynth/souffle/src'
bison -Wall -Werror -Wno-error=deprecated -Wno-error=other -v -d -o parser.cc ./parser.yy
*** %n in writable segment detected ***

I am on version tags/1.7.1.
Any help is appreciated.
Environment:
The bison version I am using is bison (GNU Bison) 3.0.4

The Os I am using is:
Ubuntu 18.04.3 LTS, bionic

**Comment by mmcgr** [comment]
That's not a problem I've seen before. Our standard tests run on Ubuntu 18.04 with bison 3.0.4, and have done so for a long time.

To be sure the error is occurring within bison, you can change to the src directory and run `bison -Wall -Werror -Wno-error=deprecated -Wno-error=other -v -d -o parser.cc ./parser.yy` yourself.

You could also try updating Ubuntu (18.04.04 is the latest point release for bionic) in case there was a change in bison.

**Comment by moqingyan** [comment]
I have run the command in src folder, and the error still occurs. 
```
 bison -Wall -Werror -Wno-error=deprecated -Wno-error=other -v -d -o parser.cc ./parser.yy
*** %n in writable segment detected ***
```

This is really weird, but thank you for your help.

**Comment by moqingyan** [comment]
I have asked the admin to install the bison package for me on ubuntu and fix the error. I am not exactly sure what was broken in the bison 3.0.4. Here is the link I wget the package from: https://ftp.gnu.org/gnu/bison/bison-3.0.4.tar.gz. Just in case anyone met this error again.
