### ISSUE TITLE
Semantics of FP operations is not documented

### ISSUE THREAD

**Issue by mbudiu-vmw** [souffle-lang/souffle#1439]
Are operations on FP values done using FP, or are the numbers converted to integers?

**Comment by ohamel-softwaresecure** [comment]
It depends. For almost everything it behaves like a boring old FP, but if you're clever you can find some corner cases where it behaves as though they were bit-integers. e.g. tuple-equality uses bit equality, which means you can get two tuples which only differ in that one has a -0 element and the other +0. If you were to examine the tuple components for equality, however, it would use floating point equality (-0 = +0).

The corner cases are crazy but they're small and easily overlooked.

**Comment by b-scholz** [comment]
We haven't implemented epsilon environments for equivalence checks. That is up to the programmer, i.e., 
```
.decl a,b(x: float)
a(-0).
a(0).
.printsize a // a = { (-0), (+0) }
b(1) :- a(x), a(y), abs(x-y) > 1E-10. 
.printsize b // b = {}
```
