### ISSUE TITLE
Full integeration of boolean values

### ISSUE THREAD

**Issue by HerbertJordan** [souffle-lang/souffle#145]
Today is stumbled over the problem that I am not able to store the boolean result of a comparison between two numbers directly into a relation. For instance, i can not write

```
A( x , y , x < y ) :- B(x), C(x).
```

Since x < y is a constraint, and those a literal and not an attribute, I have to write something like

```
A( x , y , true ) :- B(x), C(x), x < y.
A( x , y , false ) :- B(x), C(x), !(x < y).
```

Which is (a) a bit combersome, especially if i need to have a more complex boolean expression, and (b) much less efficient then if we would synthesize the code for the first version. 

My suggestion is, that now where we are already supporting boolean connectors, we (a) upgrade bool to a full primitive type an (b) make constraints boolean attribute (or actually expression) and (c) allow any boolean expression to be used as a literal in the clauses.

**Comment by b-scholz** [comment]
I agree - that would be interesting as a feature. However, how would that work if we use boolean variables in the body as a constraints.  For example, 
```
C(x,y) :- A(x,y,z), z. 
```
would that work in your proposal?

**Comment by HerbertJordan** [comment]
Ideally, yes. It would be intuitive for the user to be like that.

**Comment by scyptnex** [comment]
C(x,y) :- A(x,y,z), z. 
is the same as:
C(x,y) :- A(x,y,true)
?

**Comment by b-scholz** [comment]
Yes but we could do more complex things like 
```
C(x,y) :- A(x,y,z), z land x < y
```

**Comment by HerbertJordan** [comment]
Should I start working on this?
