### ISSUE TITLE
Incorrect result ?

### ISSUE THREAD

**Issue by rhendrix42** [souffle-lang/souffle#1453]
Hi,
Consider the following datalog file:

```
.decl MZV(U:number, V:number)
.input MZV

.decl HqV(U:number)
HqV(a) :- MZV(a,b), MZV(c,d).

.decl gQk(U:number)
gQk(jW) :- MZV(jW,jW).

.decl QOq(U:number, V:number)
QOq(aS,GF) :- MZV(GF,GF), gQk(M), HqV(aS), MZV(aS,M).

.decl RwL(U:number)
RwL(qr) :- QOq(u,qr), gQk(u), gQk(u).

.decl out(U:number, V:number)
out(jB,ym) :- gQk(h), RwL(ym), MZV(h,jB).


 // ------ ouput ----- 
.output out
```
Running the above file with souffle gives me the following result:
[original_output.csv](https://github.com/souffle-lang/souffle/files/4629786/original_output.csv.zip)

The result has 240 entries. 
If I now drop `MZV(c,d)` from the rule `HqV(a) :- MZV(a,b), MZV(c,d).`, the result changes.
The new datalog file looks like:
```

.decl MZV(U:number, V:number)
.input MZV

.decl HqV(U:number)
HqV(a) :- MZV(a,b).

.decl gQk(U:number)
gQk(jW) :- MZV(jW,jW).

.decl QOq(U:number, V:number)
QOq(aS,GF) :- MZV(GF,GF), gQk(M), HqV(aS), MZV(aS,M).

.decl RwL(U:number)
RwL(qr) :- QOq(u,qr), gQk(u), gQk(u).

.decl out(U:number, V:number)
out(jB,ym) :- gQk(h), RwL(ym), MZV(h,jB).


 // ------ ouput ----- 
.output out
```
Now i get:
[new_output.csv](https://github.com/souffle-lang/souffle/files/4629793/new_output.csv.zip)
with 306 entries.
But why did the output change? shouldn't it remain the same ? since the variables `c` and `d` in `MZV(c,d)` are unconstrained. 

MZV FACTS FILE: [MZV.facts](https://github.com/souffle-lang/souffle/files/4629802/MZV.facts.zip)

I am running this on 64-bit ubuntu16.04
The revision i am using is : 4b6b17fe322eb1ed12aa1f945df6da4c9925002d

**Comment by mmcgr** [comment]
```
.decl A,B,C(x:number)
.decl D,E(x:number,y:number)

A(x) :- D(x,_).
B(x) :- D(x,y).
C(x) :- D(x,x).

E(x,x) :- A(x).
E(x,x) :- B(x).
E(x,x) :- C(x).

.input D
.output E
```
If you run with `souffle --show transformed-datalog` you will see that the rules for B and C are rated as equivalent, while A and B are not. This does seem like a bug.

**Comment by b-scholz** [comment]
The component is the MinimiseProgramTransformer. By removing this from the pipeline, it should work.

**Comment by mmcgr** [comment]
You can do this from the command line with
```
souffle <dlfile> --disable-transformers=MinimiseProgramTransformer
```

**Comment by rhendrix42** [comment]
Awesome! That fixed it. Thanks guys!

**Comment by azreika** [comment]
No worries - thanks for raising the issue!
