### ISSUE TITLE
Can't install souffle on Ubuntu 20

### ISSUE THREAD

**Issue by lukwue** [souffle-lang/souffle#1462]
Hello,

I have tried to follow [these](https://souffle-lang.github.io/install) instructions to install `souffle`. However, unfortunatelly souffle requires `libffi6`. It seems like it was replaced with `libffi7 `in `ubuntu 20.04` (see [here](https://packages.ubuntu.com/search?keywords=libffi6)).
Is there a way to install it in `ubuntu 20.04`, too? Building doesn't work for me either, maybe also because of libffi6.

Thank you :)

**Comment by mmcgr** [comment]
If you are using the repository, then replace 'bionic' with 'focal' in those instructions and it should work.

Building is a separate issue. For that either libffi6 or libffi7 will do.

**Comment by b-scholz** [comment]
Is this issue resolved?

**Comment by scull06** [comment]
Hello, I got the error problem even using 'focal' on ubuntu 20.10

`The following packages have unmet dependencies:
 souffle : Depends: libffi7 (>= 3.3~20180313) but it is not installable
E: Unable to correct problems, you have held broken packages.`

**Comment by mmcgr** [comment]
'focal' is Ubuntu 20.04. For Ubuntu 20.10 you should use 'groovy'. The libffi dependency has changed slightly with each new Ubuntu release.

**Comment by b-scholz** [comment]
Unfortunately, bintray stopped its service. We could not set up an alternative service yet but will attempt so in near future. 

In the meantime, I would suggest to build Soufflé from scratch or you can download the Debian package from the release and install it manually. 

https://github.com/souffle-lang/souffle/releases

**Comment by JGameCreation** [comment]
Thanks for the update! You only release Debian packages for Ubuntu 18.04 though, right?

**Comment by adjoint-modality** [comment]
This issue has reappeared for ubuntu 24.04 LTS, which has `libffi8` but not `libffi7`.

**Comment by behnazh-w** [comment]
We are currently unable to use Souffle on GitHub runners with `ubuntu-latest` after the recent upgrade to Ubuntu 24.04. This issue arises because `libffi7` is no longer available, as noted in the [GitHub Actions Runner image updates for Ubuntu 24.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md). For more details, see [this GitHub issue](https://github.com/oracle/macaron/issues/962).

**Comment by behnazh-w** [comment]
> I generated packages for ubuntu 22 and 24.
> If you confirm that it solves your issue, I will make a proper official release of souffle.

Thanks @quentin.  I can confirm that this version of Souffle resolves the issue.

**Comment by benmss** [comment]
Will the new release that fixes this issue be distributed as before? i.e. made available on Ubuntu via `apt`.
