### ISSUE TITLE
Incorrect result with magic-transform ?

### ISSUE THREAD

**Issue by rhendrix42** [souffle-lang/souffle#1463]
Hi, 
Consider the following datalog file:

```
.decl IBf(U:unsigned)
.input IBf

.decl dfm(U:unsigned)
dfm(a) :- IBf(a).

.decl onG(U:unsigned, V:unsigned)
onG(a,b) :- IBf(a), dfm(b), IBf(a).

.decl YVz(U:unsigned)
YVz(a) :- onG(a,a), onG(b,a).

.output YVz
```
Running with souffle gives me:
[YVz.csv](https://github.com/souffle-lang/souffle/files/4677851/YVz.csv.zip)
having 51 entries. 

But if I run the same file with `--magic-transform=*` option, I get an empty result.
Shouldn't the result stay the same?

**IBf FACT FILE:** [IBf.facts](https://github.com/souffle-lang/souffle/files/4677861/IBf.facts.zip)

I am running this on 64-bit ubuntu16.04
The revision i am using is :  20d76ce2124d40e6636c3cc5a956116cf984d16a

**Comment by b-scholz** [comment]
The transformation failed to produce semantically equivalent code. The transformed program is as follows using the latest version of souffle. 
```
.decl +m0_YVz+_f() 
.decl YVz+_f(U:unsigned) 
.decl +m0_onG+_fb(V:unsigned) 
.decl onG+_ff(U:unsigned, V:unsigned) 
.decl +m0_IBf+_f() 
.decl onG+_fb(U:unsigned, V:unsigned) 
.decl +m0_IBf+_b(U:unsigned) 
.decl IBf+_f(U:unsigned) 
.decl IBf+_b(U:unsigned) 
.decl YVz(U:unsigned) 
+m0_YVz+_f().

+m0_YVz+_f() :- 
   +m0_YVz+_f().

+m0_onG+_fb(a) :- 
   +m0_YVz+_f(),
   onG+_ff(a,a).

YVz+_f(a) :- 
   +m0_YVz+_f(),
   onG+_ff(a,a),
   onG+_fb(_,a).

+m0_IBf+_f() :- 
   +m0_YVz+_f().

+m0_IBf+_f() :- 
   +m0_YVz+_f(),
   IBf+_f(a).

onG+_ff(a,b) :- 
   +m0_YVz+_f(),
   IBf+_f(a),
   IBf+_f(b).

+m0_IBf+_b(b) :- 
   +m0_onG+_fb(b).

+m0_IBf+_f() :- 
   +m0_onG+_fb(b),
   IBf+_b(b).

onG+_fb(a,b) :- 
   +m0_onG+_fb(b),
   IBf+_b(b),
   IBf+_f(a).

+m0_IBf+_f() :- 
   +m0_IBf+_f().

IBf+_f(a) :- 
   +m0_IBf+_f(),
   IBf+_f(a).

+m0_IBf+_b(a) :- 
   +m0_IBf+_b(a).

IBf+_b(a) :- 
   +m0_IBf+_b(a),
   IBf+_b(a).

YVz(arg0) :- 
   YVz+_f(arg0).
.input IBf+_f(IO="file",filename="IBf.facts")

.output YVz

```

**Comment by azreika** [comment]
Magic set is currently being rewritten in a more maintainable way with a cleaner algorithm and transformation output, and will address this issue.

**Comment by rhendrix42** [comment]
Sounds good ! :)

**Comment by azreika** [comment]
For completion's sake, this is an issue with how input relations are adorned and sourced. The Datalog code produced should also use IBf.facts as input source for `IBf+_b`, as well as `IBf+_f`.

The new magic set transformation in development will bypass input relation adornment (and handles input and output relations mroe smoothly), and so this will not be an issue.

**Comment by mmcgr** [comment]
Closing this in favour of #1491
