### ISSUE TITLE
Type System: Negation

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#1464]
The following code should pass
```
.type Variable <: symbol
.type StackIndex <: symbol
.type VariableOrStackIndex = Variable | StackIndex

.decl A(a: VariableOrStackIndex)

.decl B(a: Variable)

.decl C(a: VariableOrStackIndex)


C(a) :- !B(a), A(a).
```

This problem was reported by @nevillegrech. 

The type of variable `a` in the rule should be of type `{Variable}`. 
The debug report produces following constraint system:
```
(return to top)
-- Analysis logs --
Clause: C(a) :- 
   !B(a),
   A(a).
Problem:
{
	var(a) <: __symbolConstant,
	var(a) <: __symbolConstant,
	var(a) <: VariableOrStackIndex
}
Solution:
{var(a)->{VariableOrStackIndex}}

-- Result --
C(a∈{VariableOrStackIndex}) :- 
   !B(a∈{VariableOrStackIndex}),
   A(a∈{VariableOrStackIndex}).
```

**Comment by b-scholz** [comment]
We need to reconsider the type-system for constraints and expressions.

**Comment by b-scholz** [comment]
An additional is caused by functors. We need to decide how to resolve this in the future. The example was given by @nevillegrech. 
```
.type Variable <: symbol
.type StackIndex <: symbol
.type VariableOrStackIndex = Variable | StackIndex

.decl A(a: VariableOrStackIndex)

.decl B(a: Variable)

B(cat(a, "")) :- A(a).
```
The problem here is that `cat(a,"")` is guessing the type at the moment. Perhaps we want to rethink the type system by saying that `cat(a,"")` returns symbol and it is up to the user to redefine the type, i.e., `(as symbol)cat(a,"")`.

**Comment by nevillegrech** [comment]
In the original example, I think a should still be variableOrStackIndex. I think that a join to a negated relation should be contravarient.

**Comment by b-scholz** [comment]
I reflected more on negations in our type-system. 

At the moment, we have a conservative approach:
we have sources and sinks in the type system. Sources denote types that stem from grounded variables in the body of a rule. A sink is a projection / expression / constraint. If a variable has several sources, we intersect the types of the sources to get the type of the variable.

Normally, we assume that the type of a variable needs to be of the same type or a subtype of a sink location. This is to ensure that no values outside of the domain may flow into the sink. I.e., the values of the sink are protected statically by the type-system. 

@nevillegrech's proposal breaks that semantic because we would permit any type for a sink showing up in a negation. In general, the question is whether this is preferable. 

Let's assume the example 
```
.decl A(x:float) 
.decl B,C(y:number) 

C(x) :- B(x), !A(x). 
```

This example is extreme but hopefully highlights the problem. Sets A and B do not share any values.

Semantically, we could replace the rule with the following rule:
```
C(x) :- B(x), true. 
```
because we know via the type system that there is no intersection between `float` and `number` elements, and we can forego the containment check for element `x` in set A. 

Hence, my question: do we want to be either permissible or strict for negations. A strict semantic is that any value found in set B can potentially exist in set A. 

A compromise could be that if the intersection of types `A` and `B` is non-empty, the negation is valid, i.e., sets A and B have the same primitive/base types.

**Comment by olligobber** [comment]
The only issue I can think of where negation would be a problem is when two types being unioned overlap. For example
```
.type AUCities <: symbol
.type CACities <: symbol
.type Cities = AUCities | CACities

.decl Home(x : AUCities)
Home("Sydney").

.decl AustralianCities(x : AUCities)
AustralianCities("Sydney").
AustralianCities("Melbourne").

.decl CanadianCities(x : CACities)
CanadianCities("Sydney").
CanadianCities("Toronto").

.decl Cities(x : Cities)
Cities(x) :- AustralianCities(x).
Cities(x) :- CanadianCities(x).

.decl TravelDestinations(x : Cities)
TravelDestinations(x) :- !Home(x), Cities(x).
```
We would end up with only Melbourne and Toronto being travel destinations, because Sydney CA, despite not being Sydney AU, would be filtered by `!Home(x)`. I'm not sure if this should be expected behavior, it seems a bit iffy to me.

**Comment by olligobber** [comment]
If we take the original program which failed type checking:
```
.type S <: symbol
.type T <: symbol
.type U = S | T

.decl A(a: U)
.decl B(a: S)
.decl C(a: U)

C(a) :- !B(a), A(a).
```
there is an equivalent program which passes type checking:
```
C(a) :- A(a), B(b), a != b.
```
This makes me thing both should pass.
