### ISSUE TITLE
"-nan" not returned with "ResolveAliasesTransformer" 

### ISSUE THREAD

**Issue by rhendrix42** [souffle-lang/souffle#1467]
Hi,
Consider the following datalog file:
```
.decl WWc(U:float, V:float)
.input WWc

.decl eZB(U:float)
eZB(nGa^M) :- WWc(v,nGa), WWc(M,M), M > 25.301, v <= nGa, 4.698 > v.

.decl Wdf(U:float)
Wdf(MSE/MSE) :- eZB(MSE), eZB(MSE), MSE = MSE.

.decl ABI(U:float)
ABI(Bzi) :- Wdf(Bzi).

.output ABI
```

It's easy to see that the result should be just `1`. 
But when i run souffle, i get:

```
-nan
1
```

I suspect that the problem is coming from **ResolveAliasesTransformer**, because when I run souffle with `--disable-transformers=ResolveAliasesTransformer`, I get the correct result.

**WWc Facts file:** [WWc.facts](https://github.com/souffle-lang/souffle/files/4696358/WWc.facts.zip)

I am using a 64-bit machine running ubuntu16.04
The revision i am using is : a9ac3cbf2aad1b3bf8dfd335192e7a9328ec4b4d

**Comment by mmcgr** [comment]
The transformation only affects one line in the datalog
```diff
< Wdf(MSE/MSE) :- eZB(MSE), MSE = MSE.
---
> Wdf((MSE/MSE)) :-   eZB(MSE).
```

When MSE is `-nan`, in one it is simply inserted, in the other `-nan` is compared to `-nan` which returns false, so it is not inserted.

I think the ResolveAliasesTransformer should not be assuming that floats are equal to themselves.

**Comment by rhendrix42** [comment]
I see. But `-nan` in the original result is definitely  a problem, right ?

**Comment by mmcgr** [comment]
The -nan occurs because you have a negative base and a floating point exponent (25.523).
`2^25.523 => 3.935 x 10^7`
`-2^25.523 => -2.95197 × 10^7 -2.60251 × 10^7 i => -nan`

**Comment by rhendrix42** [comment]
Oh I see! yes you are right. 
`-nan` in the original is alright.

**Comment by b-scholz** [comment]
Can we close this issue?

**Comment by rhendrix42** [comment]
yes we can

**Comment by rhendrix42** [comment]
Acutally @b-scholz  thinking about it more, this does seem like a bug. Here is a simplified example.

```
.decl fac(U:float, V:float)
.decl A(U:float)
.decl B(U:float)
.decl out(U:float)


fac(2.1, -1.5).
fac(1.1, 1.1).


A(n^m) :- fac(v,n), fac(m,m).

B(m/m) :- A(m), m = m.

out(b) :- B(b).

.output out


```

As @mmcgr  mentioned, in the second clause ResolveAliasesTransformer gets rid of `m = m`
and hence `-nan` is returned in the original result. So for floating points, `ResolveAliasesTransformer` should not consider that a float is equal to itself. what do you think ?

**Comment by rhendrix42** [comment]
Acutally @b-scholz  thinking about it more, this does seem like a bug. Here is a simplified example.

```
.decl fac(U:float, V:float)
.decl A(U:float)
.decl B(U:float)
.decl out(U:float)


fac(2.1, -1.5).
fac(1.1, 1.1).


A(n^m) :- fac(v,n), fac(m,m).

B(m/m) :- A(m), m = m.

out(b) :- B(b).

.output out


```

As @mmcgr  mentioned, in the second clause ResolveAliasesTransformer gets rid of `m = m`
and hence `-nan` is returned in the original result. So for floating points, `ResolveAliasesTransformer` should not consider that a float is equal to itself. what do you think ?
