### ISSUE TITLE
Profiler produces invalid JSON

### ISSUE THREAD

**Issue by langston-barrett** [souffle-lang/souffle#1468]
After sorting out #1458, I was able to get a valid profiling log. However, the JSON output is invalid. Specifically, the following key is not a valid JSON string, apparently due to some escaping woes:
```
"class_type_name(?type,substr(?type,8,(strlen(?type)-8))) :- \n   struct_type(?type),\n   !template_type(?type),\n   \".*%\\"class\\..*\" match ?type."
```
Here's the whole log: [prof.json.zip](https://github.com/souffle-lang/souffle/files/4697732/prof.json.zip)

Again, my apologies that I can't share the source code. Let me know what other information might be helpful. The Souffle version is 1.7.1.

**Comment by langston-barrett** [comment]
The following `sed` command fixed the JSON:
```bas
sed -i 's|\\\\"|\\\\\\"|g' prof.json
```

**Comment by b-scholz** [comment]
We will look into this - I see the bug on my side.

If you want to fix this on your side quickly, the culprit is the `stringify` function in `utility/StringUtil.h`. In the current version, it is implemented as follows:
```
/**
 * Stringify a string using escapes for newline, tab, double-quotes and semicolons
 */
inline std::string stringify(const std::string& input) {
    std::string str(input);

    // replace semicolons returns by escape sequence
    size_t start_pos = 0;
    while ((start_pos = str.find(';', start_pos)) != std::string::npos) {
        str.replace(start_pos, 1, "\\;");
        start_pos += 2;
    }
    // replace double-quotes returns by escape sequence
    start_pos = 0;
    while ((start_pos = str.find('"', start_pos)) != std::string::npos) {
        str.replace(start_pos, 1, "\\\"");
        start_pos += 2;
    }
    // replace newline returns by escape sequence
    start_pos = 0;
    while ((start_pos = str.find('\n', start_pos)) != std::string::npos) {
        str.replace(start_pos, 1, "\\n");
        start_pos += 2;
    }
    // replace tab returns by escape sequence
    start_pos = 0;
    while ((start_pos = str.find('\t', start_pos)) != std::string::npos) {
        str.replace(start_pos, 1, "\\t");
        start_pos += 2;
    }
    return str;
}
```

**Comment by mmcgr** [comment]
I've added a fix that works for me. The strings get escaped/unescaped/parsed/reformatted in a few places, so I'm not completely confident it's a fix for you. Longer term this needs refactoring to be more coherent and more testable.
