### ISSUE TITLE
add directive to rule or relation definition to drive magic set

### ISSUE THREAD

**Issue by psubotic** [souffle-lang/souffle#1475]
Often when developing large dl code bases you find several good candidates for magic set optimizations. Remembering all these candidates and adding them to .pragma or command line is laborious and it would be nice to add a magic set directive to the rule or relation definition (similar to "inline").  Abdul assigning to you as I understand you will work in magic set re-implementation. You might want to take this feedback in mind.

**Comment by azreika** [comment]
Agreed - I plan on adding this in. Thanks for the feedback!

**Comment by psubotic** [comment]
nice!

**Comment by mmcgr** [comment]
Closing this in favour of #1491
