### ISSUE TITLE
Remove redundant self-copy rules.

### ISSUE THREAD

**Issue by azreika** [souffle-lang/souffle#1487]
In many cases, transformations (or users) might introduce rules of the form:

```
A(X) :- A(X).
```

Which end up in RAM as a recursive rule:

```
BEGIN_DEBUG "A(X) :- \n   A(X).\n"
QUERY
    IF (NOT (@delta_A = ∅))
         FOR t0 IN @delta_A
             IF (NOT (t0.0) ∈ A)
                 PROJECT (t0.0) INTO @new_A
END_DEBUG
```
Since in the first loop, `@delta_A` will be the full relation `A`, this is a needless iteration through the entire relation.

Such rules might also block other transformations from occurring. In particular, in the following snippet:

```
A(0).
A(X) :- A(X).
```
`A` is treated as a recursive relation, when really it is a static relation with exactly one element, `0`.

`RemoveRelationCopiesTransformer` can often introduce this inefficiency after optimising out intermediate relations. E.g.:

```
.decl A, B, C(X:number)
B(0).
A(X) :- B(X).
C(X) :- A(X), X != 3.
.output C()
```
produces the code:

```
.decl B(X:number) 
.decl C(X:number) 
B(0).

B(X) :- 
   B(X).

C(X) :- 
   B(X),
   X != 3.
.output C
```

The `MinimiseProgramTransformer` should be extended to cater for this case.

**Comment by b-scholz** [comment]
It might be good to extend the `RemoveRelationCopiesTransformer` for this case.
What do you reckon?

**Comment by b-scholz** [comment]
Oh maybe -not so a good idea. However, some of the search patterns can be replicated for this transformer.

**Comment by b-scholz** [comment]
Basically we need to traverse all clauses and check for 
```
 for (auto cl : program.getClauses()) { 
            std::vector<AstAtom*> bodyAtoms = getBodyLiterals<AstAtom>(*cl);
            if (!isFact(*cl) && cl->getBodyLiterals().size() == 1u && bodyAtoms.size() == 1u) {
                AstAtom* atom = bodyAtoms[0];
                if (equal_targets(cl->getHead()->getArguments(), atom->getArguments())) {
                    // found rule to remove 
``

**Comment by azreika** [comment]
We can extend it to cover the more general case, where an atom equivalent to the head appears in the body of a rule. For example,

```
a(X) :- b(X), a(X).
```

These rules are redundant, because they are satisfied only if they have already been satisfied.

**Comment by b-scholz** [comment]
Actually, I discovered some transformations produce clauses like this:
```
A(x) :- B(x), B(x), ...., B(x). 
```
It would be great to reduce replicas as well.

**Comment by azreika** [comment]
An example goal is to minimise:

```
.decl a,b,c(X:number)

a(0).
b(1).

c(X) :- b(X).

a(X) :- b(X), c(X).
a(X) :- a(X).

q(X) :- a(X).


.decl q(X:number)
.output q()
```

to

```
.decl a(X:number) 
.decl b(X:number) 
.decl q(X:number) 
a(0).

b(1).

a(X) :- 
   b(X).

q(X) :- 
   a(X).
.output q
```


Currently, the result is
```
.decl a(X:number) 
.decl b(X:number) 
.decl q(X:number) 
a(0).

b(1).

b(X) :- 
   b(X).

a(X) :- 
   b(X),
   b(X).

a(X) :- 
   a(X).

q(X) :- 
   a(X).
.output q
```

**Comment by azreika** [comment]
These cases were all covered by PR #1495.
