### ISSUE TITLE
Record I/O using JSON?

### ISSUE THREAD

**Issue by nevillegrech** [souffle-lang/souffle#1489]
Record I/O is potentially tricky. Rather than re-invent the wheel with a new input or output format, how about JSON?

I asked Bernhard about this and this was his response:

```
Ideally, we would have a format key for I/O statements. For example, we would have the following syntax:

.type list = [x:number, y:list]

  

.decl A(a:number, b:list)

 

A(1,[1,[2,[3,nil]]]).

A(0,nil).

 

.output A(format=json)

 

Producing a json file as follows:

 

[{“a”:1, “b”:{“x”: 1, “y”: {“x”: 2, “y”: {“x”: 3, “y”: { } } } } },

{“a”:0, “b”: { } ]

 

This requires to develop a new Stream I/O for the JSON format that complies to the interfaces in ReadStream.h and WriteStream.h

 ```

**Comment by b-scholz** [comment]
This is also related to #1427. 

I would either have a sole CSV text format with brackets as already implemented or as pure JSON format.

**Comment by b-scholz** [comment]
@nevillegrech - we have now the first version of the new IO by @GaloisNeko. Please can you double-check and see whether you want changes.
