### ISSUE TITLE
Clean up the examples test folder

### ISSUE THREAD

**Issue by azreika** [souffle-lang/souffle#1501]
Some tests in the `examples` test folder no longer work with the current version of Souffle. These tests should be modified to reflect current syntax/semantics.

For example, `examples/tic-tac-toe` fails with:
```
Requested arity not yet supported. Feel free to add it.
```
and `examples/strategies` fails because the component default output filenames use dashes instead of the current dot-naming system (e.g. `C-link.csv` instead of `C.link.csv`).

The other tests should also be looked into for similar problems.

**Comment by b-scholz** [comment]
We need to extend the interpreter with more relations arities.

**Comment by mmcgr** [comment]
Are you up to date with master? The available interpreter arities was just significantly upped.

**Comment by azreika** [comment]
Yep, just checked - this is on the master branch.

**Comment by mmcgr** [comment]
Ah, it was the BTree provenance arities that were upped. `tic-tac-toe` fails with a request for a BTree index with an arity of 20.

We can just add all the arities up to 32, the downside is compilation time, and maybe memory.

**Comment by azreika** [comment]
Resolved by PR #1505.
