### ISSUE TITLE
Component parameter name clash.

### ISSUE THREAD

**Issue by zyzek** [souffle-lang/souffle#151]
Name expansion occurring after component instantiation means that the `num_param` relation takes the local symbol type `Param`, though what it manipulates should be the numeric version from the outer scope.

```
.number_type Param

.comp WithParam<K> {
    .symbol_type Param

    .decl Param(p:Param)
    Param("Sym").

    .decl num_param(n:K) output
    num_param(3).
    num_param(2).
    num_param(X+Y) :- num_param(X), num_param(Y), X+Y < 6.
}

.init wParam = WithParam<Param>
```

**Comment by b-scholz** [comment]
If we provide a scope the semantics of the component instantiation will change. 

To me it is not clear (look at other examples), whether the proposed behaviour is the correct answer to the problem.

To overcome this issue, it might be better to have a scoping directive that uses the namespace of the outer scope.
