### ISSUE TITLE
Retrieve internal parameter name for record by internal API

### ISSUE THREAD

**Issue by GaloisNeko** [souffle-lang/souffle#1510]
Is it possible to get the parameter name of corresponding record by the parameter index through some APIs? For example I have:
```
.type list = [x:number, y:list]
.decl A(a:number, b:list)
A(1,[1,[2,[3,nil]]]).
A(0,nil).
```

Then I could use an API like `getRecordParameterName(parameterBOfRecordA, 0)` which return me `x`.

**Comment by b-scholz** [comment]
We don't have this information in the API at the moment. The information is generated in AstTransator for the I/O system in the form of JSON objects (see translateDirectives). We would need to pass it through the C++ interface. 

Would you like to attempt this? We can give you some guidance?

**Comment by GaloisNeko** [comment]
Yeah this function looks quite essential, I will add it to my TODO list.
