### ISSUE TITLE
--output-dir stopped working

### ISSUE THREAD

**Issue by rhendrix42** [souffle-lang/souffle#1525]
Hi guys, 
In the latest commit, "--output-dir" flag stopped working. The results are not exported to the specified output directory anymore ?
I am using Ubuntu 16.04

**Comment by mmcgr** [comment]
Looks like copy-paste went wrong. #1526 should fix this issue

**Comment by azreika** [comment]
Can we add simple tests for this, fact dirs, and the debug report, just to make sure things go in the right place?
