### ISSUE TITLE
Floating point rounding errors

### ISSUE THREAD

**Issue by luc-tielen** [souffle-lang/souffle#1539]
Hi, I've been working on adding float support to souffle-haskell. 
I created a property based test to generate floating point values and saw that the value being read from souffle is different than the value written. This error happens with both interpreted and compiled mode.

I made a minimal example for testing:

```prolog
.decl fact(x: float)
.decl other(x: float)
.input fact
.output other

other(x) :- fact(x).
```

```bash
$ cat fact.facts
-9.9999994e8
```

```bash
$ cat other.csv
-1e+09
```

I ran souffle using this command (for interpreted mode): `souffle float_conversion.dl`.

Seeing as no floating point calculations happen here, could this be related to how floats are written to CSV files? Maybe a rounding error happens there?

**EDIT**: Error only seems to occur if you create a program using `souffle -g`, embedded mode seems to work (probably because it is directly read from/written to a float.

**Comment by mmcgr** [comment]
The CSV output uses standard stream operations, so I tried this in a simpler C++ program using std::out
```
#include <iostream>
#include <iomanip>

int main() {
	float a = -9.9999994e8;
	std::cout << a << std::endl;
	std::cout << std::setprecision(5) << a << std::endl;
	std::cout << std::setprecision(6) << a << std::endl; // the default
	std::cout << std::setprecision(7) << a << std::endl;
	std::cout << std::setprecision(8) << a << std::endl;}
```
with output of
```
-1e+09
-1e+09
-1e+09
-9.999999e+08
-9.9999994e+08
```

A precision of 8 obviously works better for your case, but given the error inherent in floating point numbers, I'm not sure what the best approach to take is in general.

I'm not seeing the downside of using a much higher precision setting. It's not necessarily any more correct, but it's more likely to reflect the original input which is at least convenient.

**Comment by luc-tielen** [comment]
Yes, floating point calculations have rounding errors, but I wouldn't expect them as a user to have a rounding error between the final result and writing to the CSV file. 
If I generate a C++ file and compile with embedded souffle, I get the full precision (since the value is read directly from RAM) which might be confusing when developing your algorithm.

Thanks for pointing me to `setprecision`, I think the following always preserves max precision (found this [here](https://en.cppreference.com/w/cpp/io/manip/setprecision)):
```cpp
std::setprecision(std::numeric_limits<long double>::digits10 + 1) // replace "long double" with "float" / "double"? 
```

**Comment by mmcgr** [comment]
I've been working on this, and adding `std::setprecision(std::numeric_limits<RamFloat>::max_digits10)`to WriteStreamCSV.h fixes the output for your particular example. However, many floating point tests now fail as they're sensitive to precision. For example, an input of `0.3` is no longer output as `0.3`, either as a double or as a float, when the precision is higher than the default. In all these cases there is no manipulation of the number, it's just that the value can't be represented exactly.

The tests can all be tweaked to match the new output, but it would be nice if they weren't quite so sensitive to precision so I'm trying to adjust them to use more reliable values. Users will continue to be surprised by this issue, regardless of precision setting, but the results will at least be less surprising if the values start as representable floats.

**Comment by luc-tielen** [comment]
Thanks for putting in the effort! Floats can be very finicky but at least this change will bring the CSV output in sync with reading directly from RAM 😃.

**Comment by luc-tielen** [comment]
Closing this since the issue is fixed, thanks @mmcgr!
