### ISSUE TITLE
Separate .type and .decl namespace

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#157]
We use a lot of finite types, essentially sets of strings.  It would be cool if in Souffle I could do

```
.type foo
.decl foo(x: foo)
foo("foo-1").
foo("foo-2").
...

.decl P(x: foo)
P(x) :-
  foo(x), 
  Q(x).
```

The `foo(x)` acts like a typing predicate, since you don't have finite types as such.  It's a little redundant-looking, but to my taste seems nicer than having `is_foo(x)` or something similar.

**Comment by b-scholz** [comment]
Souffle has compile-time types only. Your type ```foo``` is a compile-time type. At compile-time we do not know the actual values of the attributes that have the type ```foo```. To avoid confusion, we really would like to keep the name spaces of relations and types separate. 

To overcome the issue raised by you, we could manually introduce a domain set ```is_A```. For your example, we could write:
```
.type A
.decl foo(x: A)
foo("foo-1").
foo("foo-1"). 
...

.decl is_A(x:A)

is_A(x) :- foo(x). 
.decl P(x: A)

P(x) :- 
   is_A(x), 
   Q(x). 
```
Every time we populate new information into a relation with an attribute of type A, we also update our ```is_A``` set. This can be done nicely with multi-head rules. 

Now the question is whether we should support this automatically. With my interns at Oracle Labs we ported DOOP to Souffle and experienced semantic problems because the domains influence the semantic of the programs and vice versa. I need to think about it but I believe I could construct an example with negation/string manipulation where if we had the feature, we could not stratify the program (i.e. we cannot find a valid execution order). I.e., these are not-standard Datalog programs that create new values for ```A``` while executing.

**Comment by seanmcl** [comment]
I see, so you don't really know all the elements of the type until you read the .rules files.  Hmm..  For me it's purely an aesthetic/readability issue.  It seems to limit the usefulness of ".type" to write and then need to write a type predicate for foo in every rule where it appears.  The title of this issue should instead have been "feature request for enum types" :)  From a naive point of view, it seems adding real types by inserting type predicates like you suggest automatically would capture the intent as long as there were no rules for generating new elements of type foo.  Perhaps that's one possibility.

**Comment by b-scholz** [comment]
This is a little bit contrived but here is an example:

```
.decl R(x:A)

R(1).
R(x+1) :- R(x), !is_A(x), x < 100. 
```

This example would be translated to 

```
.decl R(x:A)
.decl is_A(x:A)

R(1).
is_A(1). 
is_A(x), R(x+1) :- R(x), !is_A(x), x < 100. 
```
for which we cannot find a strata.

**Comment by b-scholz** [comment]
I forgot to answer your question: The ```.type ``` declaration  is a  type declaration like in any other strongly typed language. We  really don't know the concrete set of elements of a type unless we run the program with all possible inputs. 

With the separation of type as a concept and as a concrete domain, we are able to assist the programmer, i.e., wrong variable bindings in bodies of clauses are detected quickly. For large logic specifications this is really important.

**Comment by seanmcl** [comment]
Hi Bernhard.  What does it mean when there are two atoms to the left of `:-`?  Is that shorthand for 

```
is_A(x) :- R(x), !is_A(x), x < 100.
R(x+1) :- R(x), !is_A(x), x < 100.
```
?

I think I was just unclear about what I meant by "enum".  The literal `!is_A(x)` doesn't make sense when thinking of `A` as an enum, since it wouldn't type check according to how I naively imagine enums would work; in Haskell for example, you can't write 

```
data T = A | B | C
isT :: ??? -> Bool
```

There's nothing to write for `???` except T, in which case the function is `const True`.  

Enums seem to me a useful extension; it makes for shorter logic programs with less clutter.  
I meant to argue that your type system can handle enums if you limit the rules to only allow atoms for their creation.  At runtime you'd have all the possible values of the enum before the program started, and could proceed accordingly.

**Comment by b-scholz** [comment]
Yes. The multiple-head notation is just a short form. It saves time to write the same body again. 

I see. Basically, you are arguing for sets that are not extendible during runtime. In Datalog slang this would be the EDB (extensional database). However, every modern Datalog language extends the "pure semantics" of Datalog and new elements can be created on-the-fly that are not in the EDB. This would violate the fixed set assumption and we would need a stronger type system to avoid this.

Note that current standard practice is that the extractor of an application produces such domain sets. The extractor is the program that translates the input program (or any other input instance)  to relational form. If such domain sets are required, the domain sets are produced by the extractor and later read by Souffle (and hopefully not changed). 

Currently, I don't have a good handle on the problem, i.e., ensuring that the language feature is complete.  I feel that that even if we omit negation applied to domain sets, we still can use negation via other relations. It becomes a quite restrictive feature. I believe the only good way out would be a type extension, ie., having a keyword immutable that guarantees that no new values can be created for a type (except the values read from a spreadsheet and from facts in the program input).

**Comment by seanmcl** [comment]
Precisely.  My thinking on this is too muddy to be useful.  I observe that in our use case, we have many sets of strings before we run the program that will never change, and that would naturally become enums in C, Haskell, etc.  E.g. instance ids, subnet ids, ip protocol ids, etc.  To write the rules that operate on those types, it is aesthetically suboptimal to systematically write, e.g. is_subnet_id(Subnet), is_protocol(Protocol), ... for all input arguments, and then write the clauses that matter.  We're generating Souffle code, so it's no big deal for us, but I imagine if I were writing Souffle rules directly that writing the is_XXX clauses would become tiresome in this case.  Just an idea :)
