### ISSUE TITLE
Support for metalogic

### ISSUE THREAD

**Issue by XVilka** [souffle-lang/souffle#1576]
> In recent work by Gottlob et al., the usefulness and adequacy of Datalog, and precisely augmented with rules with existential heads to implement ontological reasoning has been shown. Also, it has been shown how to express forms of reasoning that go beyond the expressive capabilities of Description Logics. In [our recent work](https://scholar.google.com/scholar?q=Costantini%2C%20S.%2C%20Formisano%2C%20A.%3A%20Augmenting%20knowledge%20representation%20and%20reasoning%20languages%20with%20customizable%20metalogic%20features.%20In%3A%20Proceedings%20of%20CILC%202019.%20CEUR%20Workshop%20Proceedings%2C%20vol.%202396%2C%20pp.%2014%E2%80%9329.%20CEUR-WS.org%20%282019%29) we present a methodology for introducing customizable metalogic features in logic-based knowledge representation and reasoning languages. We made the specific case of Answer Set Programming (ASP), where such features may be part of software engineering toolkits for this programming paradigm. In this paper we show how such metalogic features can further enrich with minor changes to its operational semantics (provided in terms of “chase”) and no additional complexity burden.

See full paper at https://link.springer.com/chapter/10.1007/978-3-030-35166-3_3

**Comment by b-scholz** [comment]
Thanks for the link - very nice work.
