### ISSUE TITLE
Improve warnings

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#158]
In the program

```
.type Node
.decl IsNode(n: Node)
.decl Reachable(n:Node, m:Node) output
Reachable(x, x) :-
  IsNode(x),
  IsNode(_y).
```

I get the following warnings

```
Warning: No rules/facts defined for relation IsNode in file reachable.dl at line 2
.decl IsNode(n: Node)
^---------------------
Warning: Variable _y only occurs once in file reachable.dl at line 6
  IsNode(_y).
---------^----
```

I don't think _y should give a warning here, in the style of Prolog.  I would like to allow singleton variables when I know they're singletons.  (I love the warning otherwise.)  I would also like to be able to turn off the "No rules/facts" warning when I know there are no rules or facts but I don't care.

**Comment by seanmcl** [comment]
Singletons don't make much sense here, since I keep forgetting that there are no finite types.  Closing.

**Comment by b-scholz** [comment]
We have similar semantics only for underscore. I.e.,

```
.decl B(x:number)
B(1). 

.decl A(x:number) output
A(1) :- B(_).
``` 
would compile without warning. However, 

```
.decl B(x:number)
B(1). 

.decl A(x:number) output
A(1) :- B(_x).
```
would compile with warning because ```_x``` is seen as an normal identifier. Perhaps we make it compliant to Prolog such that ```_x``` is an unnamed variable as well.
