### ISSUE TITLE
Nontermination with recursive records

### ISSUE THREAD

**Issue by langston-barrett** [souffle-lang/souffle#1596]
Souffle doesn't seem to terminate on this example, it just spins while consuming 100% of the CPUs I give it.
```
.type List = [
    head: number,
    tail: List
]

.decl list_item(item: number)
list_item(0).

.decl list(l: List)
list(nil).
list([head, tail]) :-
  list_item(head),
  list(tail).

.output list
```
```
souffle --version
Souffle: 2.0.1(32bit Domains)
Copyright (c) 2016-19 The Souffle Developers.
Copyright (c) 2013-16 Oracle and/or its affiliates.
```
I'd love to give #1581 a shot, is there a 2.1 or 3.0 in the works? :smile:

**Comment by mmcgr** [comment]
Wouldn't non-termination be expected in your example? Slightly simplified:
```
list(nil).
list([0, tail]) :- list(tail).
```
Every entry in `list` after the first is a link to the previously added entry and there is no stopping condition, so it recurses endlessly.

**Comment by b-scholz** [comment]
Another alternative would be 
```
.type List = [
    head: number,
    tail: List
]

.decl first(item: number)
first(0).

.decl next(item: number, next:number)
next(0,1).
next(1,2).


.decl list(l: List)
list([n,nil]) :- first(n).

list([n2, [n1,l]]) :-
  list([n1,l]), next(n1, n2).

.output list
```

The problem is (as Martin pointed out) that you build with your program an endless set of lists with the following 
structure:
```
[0, nil] 
[0,[0,nil]]
[0,[0,[0,nil]]]
...
```

**Comment by langston-barrett** [comment]
@b-scholz @mmcgr Thanks for clarifying! I was in a classical Datalog mindset, so I was incorrectly assuming every program I could write would be guaranteed to terminate, but it makes sense that recursive records break you out of that paradigm. I'll be more careful!
