### ISSUE TITLE
Create a Docker image

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#160]
It would be very nice if you provided a Docker image on Dockerhub.  The Dockerfile helps a lot to figure out how to build software, and if you just want to run it, Docker is a nice way to do it.  I'm having a lot of trouble building on a clean Ubuntu 16.04 image.

Bonus if we can figure out exactly which boost libraries are used so the Docker image doesn't need libboost-all-dev!

**Comment by b-scholz** [comment]
I have never worked with Docker before. I heard a lot of good things about it. This is a very nice idea. 

Please can you let us know your trouble. Unfortunately, the boost library dependency is not so great but we needed a stand-alone c-preprocessor for Souffle. Boost provides a self-contained c-preprocessor called wave. For wave, we have currently following boost-library dependencies: 
- System 
- Filesystem
- Thread
- Data&Time

On a debian system you can install these libraries as follows:
```
sudo apt-get install libboost-system-dev libboost-filesystem-dev libboost-thread-dev libboost-date-time-dev
```

**Comment by seanmcl** [comment]
Great, thanks.  I'll send a MR with a minimal-ish Dockerfile.
