### ISSUE TITLE
Is that possible to traverse a list in soufflé?

### ISSUE THREAD

**Issue by yangzhewen** [souffle-lang/souffle#1609]
Hi there, if we have a list which is a recursive record, how to program in soufflé to traverse every element in it?
A list such as:
.type List = [
    head : number,
    tail : List
]
Thanks a lot !

**Comment by SamArch27** [comment]
In the Souffle wiki at the bottom of the records tutorial, there is an example which shows how to "flatten" a recursive record. This is probably the simplest way to extract the values from a recursive record.

https://souffle-lang.github.io/records

**Comment by b-scholz** [comment]
What would you like to implement?

**Comment by b-scholz** [comment]
Can you explain how you want to use the traversal? What is your end-goal?

**Comment by yangzhewen** [comment]
I just need to get all the data from the list one by one till the end of the list, in other language, it's just a 'for' loop, and I am wondering how to write a 'for' loop in souffle. Thanks!

**Comment by b-scholz** [comment]
I would be interested whether you need this traversal in a relation etc - I am interested in how you use the traversal. I hope that makes sense.

**Comment by yangzhewen** [comment]
In fact I am trying to translate something in other language into souffle. And the loop is in a function but according to the tutorial, I don't know how to write functions which take vars in and out put vars. So I have to put those function inside a relation as a constrain.

**Comment by b-scholz** [comment]
Yes - you need to dump this information into a relation.

**Comment by yangzhewen** [comment]
Yes, so if I have a list and I want to traverse it for the right data I want and put those data into a relation, is that possible in souffle?

**Comment by b-scholz** [comment]
Here is an example:
```
.type List = [ head:number, tail: List]
.decl A(l:List)
A([1,[2,[3,nil]]]).

.decl B(l:List, sl:List, n:number)
B(l, sl, n) :- A(l), l = [n, sl].
B(l, sl, n) :- B(l, [n, sl], _).

.decl C(l:List, n:number)
C(l, n) :- B(l, _, n).

.output C
```
Relation `C` maps a list to a set of elements. To construct relation `C`, we use an auxiliary relation `B` that tracks the sublists.

**Comment by yangzhewen** [comment]
Thanks a lot !

**Comment by azreika** [comment]
Here's an example that doubles every element in the list.

The process here is: Get the input -> Grab the sublists -> Transform each sublist -> Filter for the 'main' sublist

```
.type List = [ head:number, tail:List ]

// Input list we care about
.decl original(list:List)
original([0, [1, [2, [3, [4, [5, [6, nil]]]]]]]).

// Intermediate relation to store all the sublists
.decl to_transform(list:List)
to_transform(x) :- original(x).
to_transform(rest) :- to_transform([_, rest]).

// Intermediate relation that maps each sublist to its result
.decl transformed(orig:List, result:List)
transformed(nil, nil).
transformed([first, rest], [2*first, transformedRest]) :-
    to_transform([first, rest]),
    transformed(rest, transformedRest).

// Final relation that grabs the result we actually care about
.decl result(result:List)
.output result()
result(out) :-
    transformed(orig, out),
    original(orig).
```
