### ISSUE TITLE
Profiler crash + issues

### ISSUE THREAD

**Issue by psubotic** [souffle-lang/souffle#162]
1. when I load my log and type "rel" I get an array index out of bounds exception at ProgramRun.java:501
2. When loading my log file there is output "unknown command"
3. Total run-time is 16 ...seconds should be added to it and this should be a decimal not an integer value

**Comment by b-scholz** [comment]
Can we have the profile to see where it fails?

**Comment by psubotic** [comment]
Ill try and replicate it with another profile and attach it

**Comment by psubotic** [comment]
is this fixed by the oracle pull?

**Comment by b-scholz** [comment]
yes - i believe so - can you check.
