### ISSUE TITLE
Customize return type for functors

### ISSUE THREAD

**Issue by GaloisNeko** [souffle-lang/souffle#1629]
Let's say we want to create a subtype for symbol:
```
.type expr <: symbol
.functor some_func():expr
```

This will have errors:
```
Error: [number | symbol | float | unsigned] identifier expected in file XXX.dl at line 2
.functor some_func(expr, symbol):symbol
----------------^--------------------
1 errors generated, evaluation aborted
```

Could we extend the parser to identify all the defined type? Since expr is just an alias for symbol (or any other primitive data type).

I think this bug prevents us from customizing records type in stateful functor as well.

**Comment by b-scholz** [comment]
That would be a great feature to have; also there is a new type of functor that exports the symbol table and record table. 

We call this functor a stateful functor that would need arbitrary argument/result types including record types.

**Comment by b-scholz** [comment]
I have done a basic fix so that record tables can be accessed. You will need casts to convert records/adts to numbers for arguments and a cast to convert a result back to a record/adt.
