### ISSUE TITLE
Better IF optimization application 

### ISSUE THREAD

**Issue by psubotic** [souffle-lang/souffle#163]
The following datalog program 

A(q, p, r) :- A(r, _, _), A(q,_, _), A(p, q, _), A(p,_,q), A(_, p, r), A(p, q, r).

is translated to:

```
INSERT 
  SCAN A AS t0 
     SCAN A AS t1 
       SEARCH A AS t2 ON INDEX t2.v2=t1.v1 WHERE (t1.v1,t2.v1,t0.v1) ∉ A
      SEARCH A AS t3 ON INDEX t3.v1=t2.v1 and t3.v3=t1.v1 
         SEARCH A AS t4 ON INDEX t4.v2=t2.v1 and t4.v3=t0.v1 
         IF ∃ t5 ∈ _temp1_A WITH t5.c0=t2.v1 and t5.c1=t1.v1 and t5.c2=t0.v1 
            PROJECT (t1.v1, t2.v1, t0.v1) INTO _temp2_A
```

An if optimization is only applied at the last scan - can be applied on the above two scans

**Comment by b-scholz** [comment]
The schedule is not optimal for the query above. It would be better to reorder, e.g., 
```
A(q, p, r) :- A(p, q, r), A(p, q, _), A(p,,q), A(_, p, r), A(r, , _), A(q,, ).
```
Nevertheless the problem still remains that the SEARCH operations should be IF operations.

**Comment by mmcgr** [comment]
This issue needs to be addressed in class RamTransforms.cpp:ConvertExistenceChecksTransformer
