### ISSUE TITLE
[Question] The duplicity of Records and ADT

### ISSUE THREAD

**Issue by GaloisNeko** [souffle-lang/souffle#1632]
I think ADT is supported recently after I checked the documentation from [souffle website repo](https://github.com/souffle-lang/souffle-lang.github.io/commit/0a49b54ef138a9a901d2b3371855f5a4d23afde6). It's an extremely powerful feature.

But I think ADT accomplish the basic features of [Record](https://souffle-lang.github.io/records) in souffle with a more consistent grammar and more powerful semantic. Will it eventually replace Record type or are there certain advantages of Record.

**Comment by b-scholz** [comment]
ADTs are an extension of records. If there is only a single branch, there is no need for an ADT and just a record is needed. This relates mainly to performance. For example, for a single linked list:
```
.type List = [x:List, n:number[ 
```
there is no need to introduce an ADT.
