### ISSUE TITLE
The home page is not available

### ISSUE THREAD

**Issue by ouerum** [souffle-lang/souffle#1642]
Hello, I want to learn how to use the souffle toolkits in my research, but the home page (http://souffle-lang.github.io/) is not available which returns ("ERR_EMPTY_RESPONSE") in the chrome browser. Could you check the home page is available and repair it? Thanks a lot for your help!

**Comment by b-scholz** [comment]
That is strange it is accessible to me - can you try 

https://souffle-lang.github.io

instead of 

http://souffle-lang.github.io

**Comment by ouerum** [comment]
Ok, it's work, thanks.
