### ISSUE TITLE
Debug Report code output missing

### ISSUE THREAD

**Issue by azreika** [souffle-lang/souffle#1654]
When I run souffle now (on the `master` branch) with the debug report option on, the debug report code sections are empty (even though the "changed" marker still seems to work).

```
.decl A(X:number)
A(0).
A(X+1) :- A(X), X < 100.
.output A()
```

**Comment by mmcgr** [comment]
Looks like this was introduced in #1638 . fgetc in execStdOut returns a char as an int, and it needs to be cast to char.
