### ISSUE TITLE
Souffle community?

### ISSUE THREAD

**Issue by luc-tielen** [souffle-lang/souffle#1658]
Hi,

I was wondering if there's such a thing as an online community for Souffle? Something along the lines of Slack, Gitter, Discord, ...?

If not, I think this would be beneficial to have:
- People interested in/using Souffle can more easily connect with each other
- "Short" questions can be answered without having to file a github issue (knowledge sharing!). Questions can be language related (e.g. how to do X, what is the best way to implement Y, ...), or maybe things like setting up development environment, ...

**Comment by b-scholz** [comment]
We started a slack space few years ago. We should revive it. This is a good idea. 
It is souffle-lang.slack.com. Can you try to join it?

**Comment by langston-barrett** [comment]
@b-scholz I tried to sign up but got:

> Don’t have an @sydney.edu.au email address?
> Contact the workspace administrator at Souffle for an invitation.

**Comment by luc-tielen** [comment]
I can confirm the same issue as @langston-barrett (I tried logging in with my personal email):
![image](https://user-images.githubusercontent.com/3411018/93931413-0b159a00-fd1f-11ea-897e-5b426acd2467.png)

**Comment by b-scholz** [comment]
I am technically not so familiar with slack. Is there a way to make this channel a public channel?
I.e., everybody with a google account / github account can join this slack channel. 

At the moment it is by invitation only; this will not scale.

**Comment by b-scholz** [comment]
When you continue with your google account - what does it say?

**Comment by luc-tielen** [comment]
@b-scholz if I try that, then I get the error message above (because my email doesn't end in `sydney.edu.au`.
I'm also not familiar with setting up a slack channel.. but maybe one of these links help:
- https://slack.com/intl/en-be/help/articles/115004856503-Manage-how-people-join-your-workspace
- https://slack.com/intl/en-be/help/articles/115004854783-Manage-workspace-invitation-permissions-and-requests

**Comment by b-scholz** [comment]
We need something like this:
https://medium.com/aspirethemes/create-your-own-public-slack-chat-community-with-slackin-1825c1d3efb2

Can you check whether we could hoist this on souffle-lang.github.io?

**Comment by luc-tielen** [comment]
Github pages only supports static content and if I understand correctly, this approach requires a nodejs server to be deployed somewhere (which then provides a URL to join the slack workspace).

Maybe this alternative approach works better: https://intoli.com/blog/make-a-public-slack-community/. You can add a github page afterwards with the form that lets users invite themselves. 

Also: once we have slack up and running again, I would mention it in a few places (README, docs, ...) so people can easily find it.

**Comment by b-scholz** [comment]
That might work quite well for us. 

Luc - can you set this up for us? I can invite you and make you an administrator for souffle-lang.slack.com.

**Comment by luc-tielen** [comment]
Ok, I will give it a try 🙂 .

**Comment by luc-tielen** [comment]
So I spent some time the last few days trying to get Slack setup initially.. but Slack nowadays only allows invite links that expire every 30 days for free plans, which is very annoying as an administrator since you have to keep maintaining/updating the invite link.

I discussed this issue with @b-scholz and we decided to give Zulip a try as an alternative.
I have set up the basics for the server, so you can give it a look: https://souffle.zulipchat.com/.
Because Souffle is open source, I also managed to request sponsorship so we get the paid plan for free. 
This gives us nice things like infinite history for messages 😁.

I propose we give Zulip a try over the next few weeks and see how it goes. 🙂
I will make a PR that adds some links to the Zulip chat in the README, docs pages, ... so people will know how to find it.

**Comment by b-scholz** [comment]
Let's all join ZULIP!

**Comment by b-scholz** [comment]
Thanks for the effort!

**Comment by langston-barrett** [comment]
Huh, I just tried to sign up and got:

> You need an invitation to join this organization.

**Comment by luc-tielen** [comment]
@langston-barrett can you try again? I changed permission settings.

**Comment by langston-barrett** [comment]
I'm in! Thanks @luc-tielen.
