### ISSUE TITLE
printsize should print to stderr

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#166]
I love the new printsize feature!  It's wonderful to get these statistics.  

I think it would be better if they were written to stderr by default, so that programs that use souffle can still control stdout without needing to filter out diagnostics like this.

**Comment by b-scholz** [comment]
Sorry for the long delay. I was on holidays and we very busy with a conference. 

The rule of thumb is that error messages go to stderr; if it is a canonical output we use stdout. 
If you would like to use standard output you could pipe the standard output to standard error. 

For example, create a file ```mytest.dl```:
```
.decl A(x:number) printsize
A(1).
```
and produce an executable as follows 
```
souffle -o mytest mytest.dl 
```

With the command
```
./mytest >&2
```
