### ISSUE TITLE
Add more documentation regarding testing

### ISSUE THREAD

**Issue by luc-tielen** [souffle-lang/souffle#1669]
https://souffle-lang.github.io/build#testing-souffl%C3%A9 is a short section which only tells the command to run the whole testsuite.

Is it possible to run only part of the test suite for quicker dev iterations? Maybe it is also possible to add a section on writing tests for a new part of the code (how is it normally done?) since I noticed Souffle seems to use custom code for tests iso existing test frameworks?

**Comment by b-scholz** [comment]
We have some information on our wiki page:
https://github.com/souffle-lang/souffle/wiki/Testing,-Continuous-Integration,-and-Deployment

It might be good to migrate some of this information.

**Comment by b-scholz** [comment]
and this page:
https://github.com/souffle-lang/souffle/wiki/build

**Comment by luc-tielen** [comment]
That first link is exactly what I needed, thank you 😃.
