### ISSUE TITLE
Document JSON I/O

### ISSUE THREAD

**Issue by langston-barrett** [souffle-lang/souffle#1675]
The release notes for release 2.0.1 mention JSON I/O, but it's not in the documentation: https://souffle-lang.github.io/io

**Comment by monperrus** [comment]
JSON is cool! Is it possible to generate JSON instead of CSV? Thanks!

**Comment by langston-barrett** [comment]
@monperrus See this test for an example of JSON output: https://github.com/souffle-lang/souffle/blob/07c6db0b229f465bebd007c9095fea0c8d291bcb/tests/semantic/jsonfile/jsonfile.dl#L18

**Comment by b-scholz** [comment]
I moved this issue to the documentation repo.

https://github.com/souffle-lang/souffle-lang.github.io
