### ISSUE TITLE
Redundant nullaries are generated

### ISSUE THREAD

**Issue by mmcgr** [souffle-lang/souffle#1680]
A program like this:
```prolog
.decl A()
.decl B(x:number)

A() :- B(x), x = 1.
```
is turned into
```prolog
.decl A() 
.decl B(x:number) 
.decl +disconnected0() 

+disconnected0() :- B(x), x = 1.
A() :- +disconnected0().
```

**Comment by b-scholz** [comment]
I was thinking about this. Perhaps Abdul can comment on this in more detail. 
In isolation, this transformation does not make much sense. However, if we had 
something like this:
```
.decl A,B()
.decl C(x:number)
B() :- C(x), x = 1.
A() :- C(x), x = 1.
```
we will have an opportunity to coalesce the computation, i.e.,
```
```

**Comment by azreika** [comment]
> I was thinking about this. Perhaps @azreika can comment on this in more detail.
> In isolation, this transformation does not make much sense. However, if we had
> something like this:
> 
> ```
> .decl A,B()
> .decl C(x:number)
> A() :- C(x), x = 1.
> B() :- C(x), x = 1.
> ```
> 
> we will have an opportunity to coalesce the computation, i.e.,
> 
> ```
> .decl A,B() 
> .decl C(x:number) 
> .decl +disconnected0() 
> 
> +disconnected0() :- C(x), x = 1.
> A() :- +disconnected0().
> B() :- +disconnected0().
> ```

Yep - we actually already have this, thanks to the combination of `PartitionBodyLiterals` and `MinimiseProgramTransformer`!

This program:

```
.decl A,B()
.decl C(x:float)
.output A,B
C(1).
A() :- C(x), x = 1.
B() :- C(x), x = 1.
```

Will be converted to this program:

```
.decl A,B() 
.decl C(x:float) 
.decl +disconnected0() 
.output A,B

C(1).
+disconnected0() :- C(x), x = 1.
A() :- +disconnected0().
B() :- +disconnected0().
```

**Comment by b-scholz** [comment]
I believe we can close this issue.

**Comment by azreika** [comment]
Since these are nullaries, there is no gain from inlining them other than removing a simple layer of indirection. Moreover, there is a potential introduction of further optimisation opportunities for the clause minimiser. Perhaps in the future this could be part of some automated inlining transformation if another use-case prompts it. At the moment, though, I think we should keep it as is.

**Comment by mmcgr** [comment]
`PartitionBodyLiteralsTransformer` is actually what introduces the redundant relations. It's intended to move literals into new clauses if they are independent of remaining literals, but does so even where there are *no* remaining literals, thus adding in the extra relations for no gain.
