### ISSUE TITLE
User-defined functors do not work on Mac OS X

### ISSUE THREAD

**Issue by HaoxianChen** [souffle-lang/souffle#1688]
Dear souffle authors,

I was following the instructions here https://souffle-lang.github.io/functors.

When I run soufflé on my Mac, it complains:  
`cannot find user-defined operator `path_join`
Assertion failed: (false && "fatal error; see std err"), function fatal, file ./utility/MiscUtil.h, line 122.
Abort trap: 6`

However, I run the same program on an Ubuntu system and it works just fine.

**Comment by mmcgr** [comment]
Paths to libraries, and restrictions on libraries, behave differently on the two systems. The version of OSX used can also affect this behaviour. It may help to use the `-L<path>` with souffle to add the correct path. Running `export DYLD_LIBRARY_PATH=<path>` before the binary is run may also help.

**Comment by b-scholz** [comment]
Is this resolved?
