### ISSUE TITLE
Souffle can't parse *.facts

### ISSUE THREAD

**Issue by haotianmichael** [souffle-lang/souffle#1691]
Hi, I'm a newer to souffle.  When I used souffle running the  example.dl provided by [Toturial](https://souffle-lang.github.io/simple)  it errored that `Error loading data: Error converting <1   2> in column 1 in line 1; cannot parse fact file edge.facts!`.  I don't know how to fix it, Please help me out, Thanks!  
My Machine is MacOS Catalina 10.15.7.

**Comment by mmcgr** [comment]
The problem is probably that `edge.facts` is in an incorrect format. The standard delimiter is a tab character, so the first line is `1<tab>2<new line>`.

**Comment by haotianmichael** [comment]
My `edge.facts`'s format is `1<tab>2<enter>3<tab>4<enter>`, which didn't work either:(

**Comment by haotianmichael** [comment]
> My `edge.facts`'s format is `1<tab>2<enter>3<tab>4<enter>`, which doesn't work either:(

It seems My vim changed the default tab. Now it works.
Thanks a lot!
