### ISSUE TITLE
Limitsize not working in some cases

### ISSUE THREAD

**Issue by azreika** [souffle-lang/souffle#1694]
In the testsuite, we have the following testcase (`semantic/limitsize`):

```
.decl A(x:number)
A(1).
A(x+1) :- A(x), x< 1000.
.printsize A
.limitsize A(n=47)
```

This works fine, with `A` outputting only 47 tuples.

But, if the program is altered to the semantically equivalent program:

```
.decl B(x:number)
B(1).
B(x+1) :- B(x), x< 1000.

.decl A(x:number)
A(x) :- B(x), x != 0.
.printsize A
.limitsize A(n=47)
```

`A` now outputs 1000 tuples, instead of 47.

Is this supposed to only work in certain cases? Or is it a bug?

**Comment by b-scholz** [comment]
It only works for recursive relations. For non-recursive rules, we would require a check-in each loop iteration.

**Comment by azreika** [comment]
No problem. Note that some transformations (e.g. MST) might transform a recursive relation into a non-recursive relation, so `limitsize` may not work as expected in conjunction. I'll close the issue.
