### ISSUE TITLE
Result class unified and easily converted to input data

### ISSUE THREAD

**Issue by psubotic** [souffle-lang/souffle#170]
We need to unify the Result given by the compiler interface (souffle Interface) and the interpreter. Also The data input for the interpreter and compiler should be easily converted to from the result. This will enable chaining several compiler/interpreter instances. You may want this if for example you would like to compile some code and then chain the output relations as input relations in another interpreter compiler instance.

**Comment by b-scholz** [comment]
Martin implemented a new I/O interface.
