### ISSUE TITLE
Refactor/Modularise AST-to-RAM translator

### ISSUE THREAD

**Issue by azreika** [souffle-lang/souffle#1705]
The translator is currently a huge mess that's been left aside in favour of improving the AST and RAM representations. Now that the AST and RAM structure has been mostly fixed up, the translator should be cleaned up and modularised into a more maintainable and clear form.

Work has already begun, with PRs #1665 and #1676 moving out the clause translator, value index, and location classes into separate independent files. Similar work should be done for value, constraint, and relation translation. The current goal is to break up the functionality/role of the translator into smaller, more manageable pieces.

**Comment by b-scholz** [comment]
This is related to issue #1247. I will close the old issue.

**Comment by azreika** [comment]
PR #1711 will be prioritised before this.
