### ISSUE TITLE
Removal of Provenance elements in AST

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#1709]
Provenance has an AST transformer and AST elements including SubroutineArgument and ProvenanceNegation. These classes should be removed, and the semantics of the provenance translation should be placed into the translator.

**Comment by azreika** [comment]
Translator refactoring, issue #1705, should be done with this in mind, as the current translator codebase makes this painful.

**Comment by azreika** [comment]
Resolved by PR #1822.
