### ISSUE TITLE
Invalid JSON produced by the profiler

### ISSUE THREAD

**Issue by langston-barrett** [souffle-lang/souffle#1713]
Here's a JSON file that the profiler produced: [prof.json.zip](https://github.com/souffle-lang/souffle/files/5418345/prof.json.zip). `jq` says it's invalid JSON:
```
cat prof.json | jq
parse error: Invalid escape at line 81229, column 93
```
`souffle-profile` doesn't seem to like it, either:
```
souffle-profile prof.json 
exception whilst reading profile DB: Parse error: invalid escape character '.' (46)
souffle-profile: ./include/souffle/utility/MiscUtil.h:195: void souffle::fatal(const char*, const Args& ...) [with Args = {const char*}]: Assertion `false && "fatal error; see std err"' failed.
Aborted (core dumped)
```
```
souffle --version
Souffle: 2.0.2(32bit Domains)
Copyright (c) 2016-19 The Souffle Developers.
Copyright (c) 2013-16 Oracle and/or its affiliates.
```
I can try to produce a MWE if necessary, just thought I'd post early in case the error is obvious from inspection.

**Comment by mmcgr** [comment]
I think the initial rule contains an escaped `.`. That makes sense in the original string as a regex, but our simplistic escaping fails to produce valid json.

**Comment by langston-barrett** [comment]
Thanks for taking a look @mmcgr!
