### ISSUE TITLE
inlining produces segmentation fault

### ISSUE THREAD

**Issue by rhendrix42** [souffle-lang/souffle#1731]
Hi guys,
Consider the following program: 

```
.decl A(x:symbol)
.decl B(x:symbol)
.decl Nullary()
.decl C(x:symbol)
.decl kIkE(A:symbol, B:symbol, C:symbol) inline
.decl out(A:symbol) btree


B(substr(x,2,2))  :- A(x).
C(substr("12",22,12))  :- Nullary().
kIkE(t,K,o) :- A(o), A(t), A(K).
out(y) :- B(y).

.output out

A("abc123").
A("bc123a").
A("c123ab").
A("123abc").
A("23abc1").
A("3abc12").
Nullary().

```
I get segmentation fault if I run this with souffle. However, if I remove `inline` the problem goes away.

I am running this on 64-bit ubuntu16.04
The revision I am using is: fbb4c4b967bf58cccb7aca58e3d200a799218d98

**Comment by azreika** [comment]
Looks like the relevant analyses are not being invalidated after inlining to take into account that the relation `kIkE` has already been deleted thanks to inlining. `InlineRelationsTransformer` is not returning the correct `changed` result.
