### ISSUE TITLE
Infinite loop on some invalidly typed programs

### ISSUE THREAD

**Issue by azreika** [souffle-lang/souffle#1739]
With the new type analysis framework, the following program hangs indefinitely:

```
.decl A(X:number)
A(to_number(to_number(2))).

.output A()
```

In the current souffle system, this is invalidly typed, as there is no `int -> int` overload for the `to_number` functor (will be done when issue #1722 is resolved). As a result, during the type-analysis fixpoint, the inner `to_number` is set to have an `int` type, but then cleared when polymorphic overloads are considered. Since this can never be resolved, we get an endless loop. Either the type-analysis fixpoint should have a fixed termination depth, or such situations should be identified.

**Comment by TomasPuverle** [comment]
@azreika You mentioned this issue is not resolved yet.  Do you have other examples of when this still happens?

**Comment by azreika** [comment]
PR #1802 fixed a symptom of the real issue. 

By introducing identity functors, a valid overload for the `to_number` functor (`number`->`number`) now exists, which is chosen and the type analysis continues as expected.

The real issue is when a valid overload where the argument types and return type of the functor match up *doesn't* exist, in which case the type analysis cyclically tries updating argument and return types to fit an overload. Future functor or type additions can easily lead to the same problem appearing again.

**Comment by b-scholz** [comment]
This is a resolved issue.
