### ISSUE TITLE
Assertion `hasValidTypeInfo(inf) && "functor type not set"' failed

### ISSUE THREAD

**Issue by rhendrix42** [souffle-lang/souffle#1744]
Hi guys, 
Consider the following program: 

```
.decl WsuW(A:float, B:float)
.decl FGAf(A:float, B:float)
.decl qlca(A:float)
.decl XcMa(A:float)
.decl nhoA(A:float)

.input WsuW
.input FGAf

qlca(max(V,V)) :- WsuW(qgV,V).
XcMa(h) :- WsuW(h,xEf).
qlca(FPY) :- FGAf(D,D), WsuW(FPY,BOb),  D =  min a + 7.585 : { XcMa(a)}.
nhoA(H) :- XcMa(H), qlca(H).
.output nhoA
```

Running Souffle on this program gets me:

```
souffle: ast/analysis/Type.cpp:278: souffle::FunctorOp souffle::ast::analysis::TypeAnalysis::getPolymorphicOperator(const souffle::ast::IntrinsicFunctor*) const: Assertion `hasValidTypeInfo(inf) && "functor type not set"' failed.
Aborted
```

It seems like the expression `+ 7.585` in the aggregate is causing the assertion failure. According to my understanding, this should be allowed right?

Fact Files: [facts.zip](https://github.com/souffle-lang/souffle/files/5567697/facts.zip)

Souffle Version: 6315b36d5757fb96f53c8db108ac530ca15c1061

**Comment by b-scholz** [comment]
Yes - indeed - this should be permitted. We will look into this.

**Comment by b-scholz** [comment]
The type information is not set in the aggregate expression `a + 7.585`.

**Comment by TomasPuverle** [comment]
Question:  After SimplifyAggregateTargetExpressionTransformer, the code becomes

![image](https://user-images.githubusercontent.com/8096452/102393015-ae77f300-3f8c-11eb-9055-038bf49906c7.png)

A few more passes run and then ResolveAliasesTransformer, which effectively undoes the transformation.

![image](https://user-images.githubusercontent.com/8096452/102393117-cea7b200-3f8c-11eb-8890-f850eacfa87a.png)

Is this the expected behaviour?

**Comment by TomasPuverle** [comment]
I would just like to add to my comment from above that this does, in fact, result in sub-optimal C++ code.  For example:

```
.decl A(x: float)
.decl B(x: float)

B(2).
B(3).

A(x) :- x = min y + 3.2: B(y).

.output A
```

results in the following C++ code with ```--dl-program```:

```
for(const auto& env0 : *rel_1_B) {
if( (ramBitCast<RamFloat>((ramBitCast<RamFloat>(env0[0]) + ramBitCast<RamFloat>(RamFloat(3.2000000000000002)))) == ramBitCast<RamFloat>((ramBitCast<RamFloat>(env0[0]) + ramBitCast<RamFloat>(RamFloat(3.2000000000000002)))))) {
shouldRunNested = true;
res0 = std::min(res0, ramBitCast<RamFloat>((ramBitCast<RamFloat>(env0[0]) + ramBitCast<RamFloat>(RamFloat(3.2000000000000002)))));
}
```

**Comment by TomasPuverle** [comment]
The transformer above may still be a performance issue but likely a red herring for this bug.  When the transformer is disabled, the following (shorter) test still fails:

```
.decl WsuW(A:float, B:float)
.decl FGAf(A:float, B:float)
.decl qlca(A:float)
.decl XcMa(A:float)

.input WsuW
.input FGAf

qlca(FPY) :- FGAf(D,D), WsuW(FPY,BOb),  D =  min a + 7.585 : { XcMa(a)}.

.output qlca
```

Likely cause here in MaterializeSingletonAggregation.cpp:

```
        aggHead->addArgument(souffle::clone(variable));
        aggRel->addAttribute(mk<Attribute>(variableName, "number"));
        aggClause->setHead(souffle::clone(aggHead));
```

**Comment by b-scholz** [comment]
We would prefer if the aggregate-argument were an expression; this is only an artefact of our type system and the translator/transformations for aggregates. We did not have time to fully tidy up aggregates.  
Our main focus is the refactoring of the translator. We hope this will be finished by the end of the week.
