### ISSUE TITLE
Producing enumerations of a term

### ISSUE THREAD

**Issue by hessammehr** [souffle-lang/souffle#1747]
I've been trying to get souffle to enumerate observations of a certain term, e.g.:

```prolog
.decl node(x: symbol)
node("A").
node("B").
node("C").

.decl elem(x: symbol, i: number)
.output elem
```

The desired output would be something like the following:
```
// constraint: each index used only once; each node used only once
elem("A", 0).
elem("B", 1).
elem("C", 2).
```
Or any permutation thereof, ideally without having to essentially sort the nodes. I have tried approaching this a few different ways but keep running into cyclic negation/aggregation errors. Any suggestions (or indication of whether or not this is possible using souffle) would be appreciated.

**Comment by hessammehr** [comment]
FWIW when node comparison is allowed the following does the trick

```prolog
.decl node(x: number)
node(2).
node(6).
node(11).

.decl elem(x: number, i: number)
.output elem

elem(x, i) :- node(x), i = count: {node(y), x > y}.
```

**Comment by azreika** [comment]
Does the `$` operator work for you? It's a global counter variable that increments each time you use it, allowing you to assign unique IDs.

In your program:
```
.decl node(x: symbol)
node("A").
node("B").
node("C").

.decl elem(x: symbol, i: number)
elem(x, $) :- node(x).
.output elem
```

would output:

```
---------------
elem
x	i
===============
A	0
B	1
C	2
===============
```

Let me know if I've misunderstood the requirement!

**Comment by azreika** [comment]
Feel free to reopen the issue if you have more questions!

**Comment by hessammehr** [comment]
@azreika Thanks very much for the tip. I haven't had a chance to try it yet but will report back if it doesn't do the trick. Perhaps it would be a good idea to document this feature (maybe I missed it?) if it's stable/public.

Many thanks for accommodating my noob question!

**Comment by azreika** [comment]
Definitely not a noob question, this is one of those surprisingly useful constructs that takes some getting used to haha. The counter argument (`$`) is actually technically an arithmetic operator (with no arguments), so it's documented in the arithmetic section at the end here: https://souffle-lang.github.io/arithmetic.
