### ISSUE TITLE
Result changes with magic transform enabled with "$"

### ISSUE THREAD

**Issue by rhendrix42** [souffle-lang/souffle#1764]
Hi guys, 
Consider the following program:

```
.decl R(X:number) 
.decl E(X:number) 

E(0).
E(1).

R($)  :- E($).

.output R
```
The result changes when I select magic set transformation. 
```
$ ./souffle -w rules.dl
$ cat R.csv
0
1

$ ./souffle -w --magic-transform=* rules.dl
$ cat R.csv
1
```

Souffle version: 1fc01140670143ed6b64bbc050e07b7bc18afaf4

**Comment by langston-barrett** [comment]
I wonder if this is expected behavior:

> $ is used to generate unique random values to populate a table.

https://souffle-lang.github.io/arithmetic

**Comment by b-scholz** [comment]
This is expected behaviour. $ is quite non-deterministic. 
Since you change the order/number of functor invocation of $ the result will be different.

**Comment by azreika** [comment]
Yep, expected behaviour that comes up from argument normalisation during magic-set. I've tried to minimise this happening in magic-set, but because it's a complex transformation with certain preconditions, cases like this will pop up.

**Comment by rhendrix42** [comment]
I see. Got it! Thanks for clarifying guys! :)
