### ISSUE TITLE
Support for alternate number literal formats

### ISSUE THREAD

**Issue by copumpkin** [souffle-lang/souffle#178]
Hexadecimal literals would be nice using the standard `0x01abcdef` convention.

Possibly more esoteric but still very appealing now that souffle has bitwise operators is the IPv4 dotted quad notation to represent a 32-bit number.

**Comment by psubotic** [comment]
hex is supported. See the test directory souffle/tests/semantic/hex/

I will look into implementing IPv4 dotted notation.

**Comment by copumpkin** [comment]
Oh, I thought I'd tried hex and it had failed, but I probably did something wrong. Sorry for the noise!

**Comment by psubotic** [comment]
Also boolean should work 0b0101010101 etc. No problem -- feel free to ask or suggest anything!

**Comment by psubotic** [comment]
implemented in #180

**Comment by seanmcl** [comment]
Sorry, I'm a bit behind, but what happened to hex literals?  I don't find the tests mentioned above anymore, nor do I find '0x' in any of the test files.

**Comment by psubotic** [comment]
they are in the semantic section

https://github.com/souffle-lang/souffle/blob/master/tests/semantic/binhex/binhex.dl
