### ISSUE TITLE
"lnot" is not documented

### ISSUE THREAD

**Issue by langston-barrett** [souffle-lang/souffle#1793]
It appears in tests:

https://github.com/souffle-lang/souffle/blob/e06b19ddd38dbfca98f980cd504e5290d6ae6fbd/tests/semantic/logical/logical.dl#L15

But not on the page where `lor` and `land` are described: https://souffle-lang.github.io/arithmetic

**Comment by b-scholz** [comment]
Thanks for this - also JSON I/O is still undocumented.
Would you like to do this?

**Comment by langston-barrett** [comment]
>  Would you like to do this?

Yes, I'll put it on my TODO list though it may take me a bit to get around to it!

**Comment by b-scholz** [comment]
I have added missing bitwise and logical operations to the documentation. 
Some examples would be still good.
