### ISSUE TITLE
wrong result ?

### ISSUE THREAD

**Issue by rhendrix42** [souffle-lang/souffle#1798]
Hi guys, 
Consider the following program: 

```
.decl WWW(A:number)
.decl mAqE(A:number)
.decl p(A:number)
.decl y(A:number)
.decl out(A:number)


WWW(18).
WWW(15).
WWW(25).
WWW(16).
mAqE(29).
mAqE(39).


p(g) :- mAqE(x), WWW(g), x < g.
y(d) :- mAqE(a), p(d), !WWW(_).
out(c) :- y(a), WWW(b), WWW(c).  
.output out

```

`out`'s result should just be all the entries in `WWW`, right? But running it with souffle gives me an empty result. Or am I misunderstanding something?

```
$ ./souffle -w rules.dl 
$ cat out.csv 


```

I also get an empty result with the following program:

```
.decl WWW(A:number)
.decl mAqE(A:number)
.decl y(A:number)
.decl out(A:number)


WWW(18).
WWW(15).
WWW(25).
WWW(16).
mAqE(29).
mAqE(39).

out(c) :- y(a), WWW(b), WWW(c).  
.output out

```

souffle version: 0b1b282943419263dd8eb331bfe05bc48db38efb

**Comment by psubotic** [comment]
, is an intersection. So since p will be empty from the first rule, this
propagates to all your other IDBs. See an empty relation is false and in
any conjunctive formula with a false the entire formula will evaluate to
false.

**Comment by rhendrix42** [comment]
But whats confusing me is that in the rule: 
`out(c) :- y(a), WWW(b), WWW(c). `

There is no join between the subgoal `y(a)` and `WWW(c)`. And the head contains the variable `c`.

If the clause was:
`out(c) :- y(c), WWW(b), WWW(c). `

Then an empty result would make sense. no?
I apologize in advance if there is a fundamental mistake in my understanding.

**Comment by psubotic** [comment]
Hi

logically you have  the equivalent of

out(c) :- FALSE, WWW(b), WWW(c).

and operationally at the nested loop level, it looks something like this
(assuming this literal ordering)

for all t1 in EMPTY
  for all t2 in WWW
    for all t3 in WWW
      if (t3 not in out)
        insert into out

but you can see regardless of the literal ordering (how you order the
foralls) it will never end up inserting into the relation.

I hope this helps a bit. I think a good explanation of the semantics can be
found in http://webdam.inria.fr/Alice/pdfs/Chapter-12.pdf

**Comment by rhendrix42** [comment]
I see. Thanks so much for pointing out the document. This seems very helpful. 

So to summarize.  I get an empty result because `y` is an empty relation. 
Because coming to your point of `,` being an intersection. 
If I change the clause to:
`out(c) :- mAqE(a), WWW(b), WWW(c).`

Now I do get all the entries in `WWW` even though the intersection between `WWW` and `mAqE` is empty.

**Comment by psubotic** [comment]
Perhaps if you read the formula as follows it might help: "if there is
a mAqE "a" *and* a WWW "b" *and* a WWW "c", then there is a c in out.

To understand it deeper, I suggest you look at the rule as a first order
formula (as described in the section model theoretical semantics in the
book) and convince yourself by finding a model (there will be a single
minimal model).

Perhaps this text below is a good start:

"The Herbrand base B of a Datalog program P is the set of all ground atoms.
A ground atom is a predicate symbol that occurs in P with its arguments
drawn from the Herbrand universe. Note that the Herbrand base respects the
arity of the predicates. The Herbrand base is also finite. An
interpretation I of a Datalog program P is a subset of the Herbrand base B.
A ground atom R is true w.r.t. an interpretation I if R ∈ I. A conjunction
of atoms R1,...,Rn is true w.r.t. an interpretation, if each atom is true
in the interpretation. A ground rule is true if either the body conjunction
is false or the head is true. A ground rule is a rule where all atoms are
ground. A model M of a Datalog program P is an interpretation, i.e. a
subset of the Herbrand base B, that makes each ground instance of each rule
in P true. A ground instance of a rule is obtained by replacing every
variable in a rule with a term from the Herbrand universe. A model M is
minimal if there is no other model M1 such that M1 ⊂ M."

Hope this helps and apologies if I still haven't explained this well enough.

**Comment by rhendrix42** [comment]
That makes it perfectly clear! Thanks so much Paul! :)
