### ISSUE TITLE
Aggregate witness question/documentation issue?

### ISSUE THREAD

**Issue by TomasPuverle** [souffle-lang/souffle#1801]
In the docs, here: [Aggregates](https://souffle-lang.github.io/aggregates) it states that aggregates can't produce witness variable instantiations.  The specific example in that section,

```
.decl family(name:symbol, age:number)
.decl youngest(name:symbol, age:number)

family("Alissa", 10).
family("Maria", 46).
family("Mark", 50).

youngest(p, n) :- n = min x : family(p, x).
```
says "This will raise a Witness Problem Error"; however, in the current master of Souffle this succeeds and runs, producing "Allysa, 10", which is correct.

Is the documentation incorrect, or is there a bug in the compiler?  Also note that if I add ```family("John", 10)```, the result will contain both witnesses, so it seems that the aggregate works and the documentation is incorrect.  Before I start reading the code, what is the expected behavior?

**Comment by b-scholz** [comment]
We have not updated the documentation. Rachel has written a transformer that permits witnesses in Aggregates.
We need to update the documentation of Souffle.
