### ISSUE TITLE
compiler doesn't run the type checker

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#181]
I generated some .facts files and misconfigured the data in such a way that the type checker should have complained.  Namely, I had strings where numbers should have been.  Souffle happily ran and gave me an answer I didn't expect.   I sent an example to @psubotic who verified the claim.

**Comment by psubotic** [comment]
ill look into this

**Comment by b-scholz** [comment]
loadCSV() in CompiledRamRelation.cpp and load() in RamRelation.cpp use the C function atoi() to convert numbers. We need to replace atoi() by stoi() and catch an exception if the conversion fails.
