### ISSUE TITLE
Number of tests in "Ubuntu LTS - 64bit domains"?

### ISSUE THREAD

**Issue by TomasPuverle** [souffle-lang/souffle#1821]
A quick question about PR pre-merge testing:  "Ubuntu Dev" and others run close to 800 tests but today I noticed that "Ubuntu LTS - 64bit domains" only runs 443:

```
443: recursive   -c -j8                            souffle-profile -c "help" [0;32mok[m

## ------------- ##
## Test results. ##
## ------------- ##

[0;32mAll 443 tests were successful.[m
```

Is this a deliberate choice or a configuration error?

Thanks,

Tom

**Comment by b-scholz** [comment]
We run the `Ubuntu LTS - 64 bit domains` test with the following flags:
```
TESTSUITEFLAGS=-j4 SOUFFLE_CATEGORY=Syntactic,Evaluation,Interface,Provenance,Profile make check -j4 
```

Perhaps @mmcgr can comment on this but in the past we had to ensure that all tests ran reasonably well on Travis-Ci and had to reduce the configuration space (interpreter / compiler / parallel etc) for each run. 

However, Travis-Ci withdrew/restricted the support for Soufflé recently, and we had to abandon Travis-Ci (NB: I liked the idea of democratising testing, i.e.,  developers could run their own continuous testing on their local Soufflé repos). 

Now we run all continuous-integration tests on local servers at The University of Sydney. We may need a larger server for running all tests / configurations.

Note that github offers Actions and cloud support. We did not have time to look into this but the ultimate question is whether running the tests is for free / workable for Soufflé.
