### ISSUE TITLE
GIT repository too big

### ISSUE THREAD

**Issue by mingodad** [souffle-lang/souffle#1827]
It's strange that cloning the git repository needs so much data (network/disk).

There isn't files been versioned that shouldn't ?

**Comment by b-scholz** [comment]
I feel the main culprit for the large git repo could be the doxygen documentation that is stored in there. Perhaps @mmcgr  can comment on this.

**Comment by TomasPuverle** [comment]
You can also avoid some of that by using shallow clones and limit the number of branches cloned.  See e.g. here: https://www.perforce.com/blog/vcs/git-beyond-basics-using-shallow-clones
