### ISSUE TITLE
Cmake?

### ISSUE THREAD

**Issue by TomasPuverle** [souffle-lang/souffle#1829]
What are your thoughts about migrating to cmake?  I feel doing things in automake is about as pleasant as exploring my nostrils with a hot poker.  I am not a huge fan of cmake but IMHO it's better and, for better or worse, it's a de-facto standard for building C++ these days.  In addition, it would support IDEs/editor integration better etc.

**Comment by b-scholz** [comment]
We had several discussions about this in the past. We feel it would be better for an MS environment. 
However, we did not have the time/ could not justify the effort to migrate to CMAKE. 
Note that automake was chosen for historical reasons, which are not relevant anymore. 

So the bottom line is - yes it would be well perceived by the team in Sydney but we will focus on more pressing issues from our perspective such as refactoring of the code base (nearly done) and language extensions in near future.
