### ISSUE TITLE
better error message for unground variable

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#183]
Assertion failed: (index.isDefined(*var) && "variable not grounded"), function translateValue, file RamTranslator.cpp, line 280.

It would be awesome to know which variable is unground, or which line of the datalog file it is.

**Comment by b-scholz** [comment]
Indeed - the semantic check should have captured it.
Could you send us the rule that causes the issue?

**Comment by psubotic** [comment]
I believe this is fixed in the main souffle -- its happening in the tiros
branch. Ill fix this next week

**Comment by b-scholz** [comment]
Is this problem still showing up?

**Comment by psubotic** [comment]
its only on the Tiros branch cause i disabled warnings. you can close this
issue.
