### ISSUE TITLE
Error with newest version of autoconf (2.70)

### ISSUE THREAD

**Issue by eschulte** [souffle-lang/souffle#1833]
Hi,

With the latest version of autoconf (2.70) I'm getting the following error building soufflé's git repository:
```
configure.ac:35: error: AC_CONFIG_MACRO_DIR can only be used once
```
This error goes away using autoconf 2.69.  See more discussion in the comments on the Arch aur package here: https://aur.archlinux.org/packages/souffle-git/

Thanks,
Eric

**Comment by LittleLightLittleFire** [comment]
I made PR #1835

**Comment by b-scholz** [comment]
Thanks for raising this issue. This should be fixed now.
