### ISSUE TITLE
At most one

### ISSUE THREAD

**Issue by dtornow** [souffle-lang/souffle#1834]
Hello,

I'm just starting out using souffle and I have some beginner questions as to how to model constraints. 

For example, if I have two predicates, male and female, how would I express X is either male or female?

```
male("dominik").
female("dominik"). <-- "[In Monty Python Voice] Souffle says no!"
```

Or, if I have a relationship, married, how would I express that each element of the domain must map to at most one element of the range.

```
married("dominik", "jessica").
married("dominik", "sara"). <-- "[In Monty Python Voice] Souffle says no!"
```

Is there a canonical way to express these constraints in souffle/datalog or is it generally understood that these constraints have to be adhered to in the fact base but are not enforced?

Thanks for your help

**Comment by XiaowenHu96** [comment]
Hi, afaik, I don't think there is a way to raise an error about constraint - you can only add rules to check your constraint and output it in the result.

For the first one, use an auxiliary relation.
```
.decl voliate_either_male_or_female()
voilate_either_male_or_female() :- male(x), female(x).
```

For the second one, you can use the latest `choice-domain` keyword. This is new, so if you need any example, please check test cases in `souffle/tests/evaluation/choice_*`, meanwhile I will try to update the document asap. 
But basically, `choice-domain` makes sure the given key is unique in the relation (silently rejiect redundant key, so still not exactly what you want):

```
.decl married(x:symbol, y:symbol) choice-domain x
```

**Comment by azreika** [comment]
> Is there a canonical way to express these constraints in souffle/datalog or is it generally understood that these constraints have to be adhered to in the fact base but are not enforced?

While this is not yet possible, I think having 'assertions' like this is a great idea.

Maybe something of the form:

**Comment by azreika** [comment]
> Is there a canonical way to express these constraints in souffle/datalog or is it generally understood that these constraints have to be adhered to in the fact base but are not enforced?

Following on from the previous answer, while this is not yet possible, I think having 'assertions' like this is a great idea.

Maybe something of this form can be allowed in future:

```
.decl violates_at_most_one_gender()
violates_at_most_one_gender() :- male(x), female(x).

.decl violates_at_most_one_partner()
violates_at_most_one_partner() :- married(x,y), married(x,z), y != z.

assert-empty violates_at_most_one_gender.
assert-empty violates_at_most_one_partner.
```

or maybe even as a relation tag (`.decl violates_at_most_one_partner() assert-empty`).

At the moment, I print out assertions like this (i.e. output the `violates_*` helper relations) and manually check that they're empty. A built-in error-raiser would be pretty cool.

**Comment by dtornow** [comment]
@XiaowenHu96 @azreika Great idea, elegant and clever! I will go the "auxiliary relations route". Of course, an "assert-empty" would be the cherry on the cake :-)

Thank you very much for your help!
