### ISSUE TITLE
Match rule

### ISSUE THREAD

**Issue by dtornow** [souffle-lang/souffle#1843]
Hello,

I have a beginners question that I cannot find an answer for: I want a "Match" predicate so that Match(X, Y) is true if X = Y or if Y = *

I tried the following

```
.decl Match(a : symbol, b : symbol)

Match(a, a).
Match(a, "*").
```

But that does not work with the following error

```
Error: Argument in fact is not constant in file test.dl at line 3
Match(a, a).
------^------
Error: Argument in fact is not constant in file test.dl at line 3
Match(a, a).
---------^---
Error: Argument in fact is not constant in file test.dl at line 4
Match(a, "*").
------^--------
Warning: Variable a only occurs once in file test.dl at line 4
Match(a, "*").
------^--------
```

Any suggestions would be appreciated. Thanks a lot

**Comment by psubotic** [comment]
If I understood what you want to do correctly: you can't do this by using
fact syntax. It needs to be done in a rule. E.g.,

.decl Match(x: symbol, y: symbol)
.input Match

.decl Matches()
.output Matches

Matches() :- Match(a, a).
Matches() :- Match(_, "*").

I hope that helps.

**Comment by dtornow** [comment]
Hello, thanks for your reply!

I am looking to use souffle in the context of networking analysis: I would like to match a message with a forwarding table. For example:

```
forwarding("127.0.0.1", "*", "127.0.0.1", "90", "P1").
forwarding("*", "*", "10.0.0.1", "*", S1).

message("127.0.0.1", "1234", "10.0.0.1", "80").
```

So I would like to match the message with the forwarding table, a "*" in the forwarding table matches any value in the message.

I will try to apply your solution.

Thanks again

**Comment by psubotic** [comment]
Nice. Yes, soufflé doesn’t have assertions as far as I know so you need
something like a Nullary to simulate one.
