### ISSUE TITLE
Refactoring size_t to std::size_t

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#1844]
We have an inconsistent use of type `size_t` and `std::size_t`. 
Let's change everything to std::size_t.

**Comment by TomasPuverle** [comment]
I've been doing some of this gradually.  Another note is that I frequently see parameters being passed as

`const size_t`

I think that should also be cleaned up to just `std::size_t`.

**Comment by b-scholz** [comment]
I agree - the major refactoring of the AST translator is done. 
Now we can change the code base without causing too much trouble.
