### ISSUE TITLE
ord intrinsic functor missing overload of ADTs

### ISSUE THREAD

**Issue by TomasPuverle** [souffle-lang/souffle#1846]
As per my issue #1845, I think it would be good to have some uniformity in converting values to their RAM representations.  However, the ADT overload is missing:

src/FunctorOps.cpp:216
```
        OP_1(ORD, Signed, Signed),
        OP_1(ORD, Unsigned, Signed),
        OP_1(ORD, Float, Signed),
        OP_1(ORD, Symbol, Signed),
        OP_1(ORD, Record, Signed),
```

We need to add

```
        OP_1(ORD, ADT, Signed),
```

and a unit test.

**Comment by b-scholz** [comment]
Yes, indeed!
