### ISSUE TITLE
--disable-transformers=ResolveAliasesTransformer changes result

### ISSUE THREAD

**Issue by rhendrix42** [souffle-lang/souffle#1848]
Hi guys !
Consider the following program: 

```
.type Word <: symbol

.decl words (i:number, w:Word) brie
.decl bigram (w:Word, w1:Word) 
.decl LYSF(a:Word, b:Word) inline brie
.decl ORKU(a:Word, b:Word) btree

.input words

bigram(w, w1)  :- words(i,w), words(i+1,w1).
LYSF(u,s) :- bigram (s,s), bigram (u,pcn), bigram (u,u).
ORKU(c,t) :- LYSF(t,c), bigram (t,t).  

.output ORKU
```
([words.facts](https://github.com/souffle-lang/souffle/files/5889558/words.zip))

I get an empty result
```
$ ./souffle -w rules.dl 
$ cat ORKU.csv 
$ 
```

If in the last rule, I replace both occurrings of variable `c` with variable `t`:

```
.type Word <: symbol

.decl words (i:number, w:Word) brie
.decl bigram (w:Word, w1:Word) 
.decl LYSF(a:Word, b:Word) inline brie
.decl ORKU(a:Word, b:Word) btree

.input words

bigram(w, w1)  :- words(i,w), words(i+1,w1).
LYSF(u,s) :- bigram (s,s), bigram (u,pcn), bigram (u,u).  
ORKU(t,t) :- LYSF(t,t), bigram (t,t). 

.output ORKU
```
I again get an get empty result for the new file:
```
$ ./souffle -w new_rules.dl 
$ cat ORKU.csv 
$ 
```

However, running this new file with `--disable-transformers=ResolveAliasesTransformer` changes the result:

```
$ ./souffle -w new_rules.dl --disable-transformers=ResolveAliasesTransformer
$ cat ORKU.csv 
There   There
are     are
four    four
red     red
birds   birds
and     and
five    five
green   green
in      in
the     the
tree    tree
```

My understanding is that disabling a transformer should not change the result, right?
Running the original file with `--disable-transformers=ResolveAliasesTransformer` gives me an assertion failure.

Souffle Version: 4bf6d1ceba23693d3e4a2e8bda3b86fec86f93a2

**Comment by TomasPuverle** [comment]
Hi Richard,

"My understanding is that disabling a transformer should not change the result, right?"

I think that's not strictly true, even though I agree with that statement in principle.  For example, the SemanticChecker is a transformer, and I doubt that disabling the SemanticChecker would lead to good things :laughing:  Another example would be the aggregate clause transformers - they handle the processing of aggregate clauses and I don't think any program using them would function without those steps.

In either case, there are perhaps three separate issues here:
1) What is the error and why are you seeing it; and if it's an actual bug let's fix it
2) What are you trying to accomplish by disabling that specific transformer
3) Should "transformers" be separated into ones which are "required" (at least for a given program/set of features) and "optional" (e.g. optimizations).  I think that's a good idea from a design perspective but the question is what the benefits of such a large redesign might be.

For what it's worth, I have run/observed similar things and certainly support at least the "idea" of point 3) but without understanding your use-case more fully, I can't make a judgement either way.

Perhaps as a bit of a tangent, restructuring/reorganizing the transformer pipeline could also lead to some nice things:

1) Always run the SemanticChecker first (not optional).  At the moment, it runs later and that has caused me some issues with not being able to assume certain invariants hold in certain "passes".
2) Allow "transformers" to be written in souffle itself running on top of a bare-bones, minimal implementation.  I think that would be great both for correctness and ease of implementation of new transformers.  Then enabling/disabling transformers might seem even "more natural".

Thanks,

Tom

**Comment by TomasPuverle** [comment]
I'd also like to add another example to show that "disabling passes" is a non-trivial problem.  Here's an example of a bug in LLVM which occurs depending on whether certain passes are enabled or not.  I think my point is that it would be nice if each pass was a pure function `f(valid) -> valid` but in practice that seems hard to accomplish: [Pointers Are Complicated II](https://www.ralfj.de/blog/2020/12/14/provenance.html).  Specifically, see the section titled "How 3 (seemingly) correct optimizations can be incorrect when used together".

**Comment by b-scholz** [comment]
The transformed Datalog program looks like this (with the transformer):
```
.type Word <: symbol
.decl words(i:number, w:Word) brie
.decl bigram(w:Word, w1:Word) 
.decl ORKU(a:Word, b:Word) btree
bigram(w,w1) :- 
   words(i,w),
   words( _tmp_0,w1),
    _tmp_0 = (i+1).

ORKU(c,t) :- 
   bigram(c,t),
   bigram(c,c),
   bigram(t,t),
   bigram(t,_).
```

And that (without the ResolveAliasesTransformer):
```
.type Word <: symbol
.decl words(i:number, w:Word) brie
.decl bigram(w:Word, w1:Word) 
.decl ORKU(a:Word, b:Word) btree
bigram(w,w1) :- 
   words(i,w),
   words((i+1),w1).

ORKU(c,t) :- 
   bigram(c,t),
   bigram(<inlined_s_0>,<inlined_s_0>),
   bigram(<inlined_u_0>,<inlined_u_0>),
   bigram(<inlined_u_0>,_),
   <inlined_u_0> = t,
   <inlined_s_0> = c.
```

**Comment by b-scholz** [comment]
The following program is smaller and produces similar issues:
```
.type Word <: symbol
  
.decl words (i:number, w:Word)
.decl bigram (w:Word, w1:Word)

.input words

bigram(w, w1)  :- words(i,w), words(i+1,w1).

.output bigram
```
The output with and without the transformer differs.

**Comment by b-scholz** [comment]
The RAM reveals the issue
```
  QUERY
    IF (NOT (words = ∅))
     FOR t0 IN words
      FOR t1 IN words
       PROJECT (t0.1, t1.1) INTO bigram
```
without the transformer and
```
   QUERY
    IF (NOT (words = ∅))
     FOR t0 IN words
      FOR t1 IN words ON INDEX t1.0 = (t0.0+number(1))
       PROJECT (t0.1, t1.1) INTO bigram
```
with the transformer.

**Comment by b-scholz** [comment]
For some reason, the equivalence constraint `_tmp_0 = (i+1).` is thrown away in the translation.

**Comment by b-scholz** [comment]
Ok - resolve aliases is required to bring the Datalog program into a certain normal form for the translator. 
We cannot disable this transformer. 

Instead of a silent failure, it might be better to throw an assertion in the translator (i.e. functors as arguments in predicates etc).

**Comment by b-scholz** [comment]
Well spotted! Great work!

**Comment by TomasPuverle** [comment]
@b-scholz 

Regarding my comment above, how would you feel about running the SemanticChecker first in the transformer pipeline?  Or rather, I assume there is a reason why it doesn't at the moment, so what are some of the reasons why it doesn't?  

By "missing invariant", I would consider, e.g. the fact that the TypeChecker and TypeConstraints can't assume that a functor declaration exists, or that a TypeAttribute's qualified name points to a valid type.

Another observation, one possible way to address the issue encountered above would be to have an explicit dependency chain for the transformers, so if a specific pass is required, it would be automatically added/injected; or, at least, the compiler could issue an error if a required pass was disabled deliberately.

**Comment by b-scholz** [comment]
Hmm - I can think of following options:
 
 - We extend the ast2ram translator so that all possible AST programs (that pass the current semantic checker), can be translated.  

 - We integrate a semantic checker in the ast2ram translator; if the AST program has not the desired properties, the ast2ram translator will reject the program and will report an error. 

 - Alternatively, we can build a normalform checker as a separate pass. 

I feel that the latter solution decouples the actual check from the translator and somebody may disable the check from the pipeline  and errors as the reported one may occur again. 

I feel that integrating the check in the ast2ram translator might be the best short-term solution and extending ast2ram so that it can deal with programs that are not in normal form, is a long-term solution.

**Comment by b-scholz** [comment]
I would suggest not permitting to disable resolveAliasesTranformer. That is the easiest way forward and no further action is required. With that the user cannot destroy the compilation.
