### ISSUE TITLE
swig testsuite doesn't run even with --enable-swig

### ISSUE THREAD

**Issue by TomasPuverle** [souffle-lang/souffle#1853]
It also seems that if I force it, some of the tests are actually failing.

**Comment by b-scholz** [comment]
We need to double-check. Can you describe which tests are failing? 
We will try to replicate this.

**Comment by TomasPuverle** [comment]
Hi @b-scholz,

What I'm observing is the following:  Even when I configure with --enable-swig and try to run tests, the SWIG tests don't get run.  If I manually add them, some tests actually fail.

I encountered this because I'm trying to make swig tests work under cmake.  It's been a reeeally long rabbit hole today.  
My latest commit on the cmake branch now includes the swig tests when SWIG_PYTHON/SWIG_JAVA/SWIG (i.e. both are enabled) - with the exception of the "dump_output" and "family" tests which use "dumpOutputs" in the test.

I spent most of the evening/tonight debugging my build, thinking there is something wrong.  However, I think what's happening is that since the tests have not been running as part of the suite, it looks like the generated code is actually wrong.  Specifically, calling `dumpOutputs` from those two tests actually fails with an assertion "map::at" while looking for "auxArity".  It seems the map/schema is not complete or out of date (could this be because of @azreika's changes?).

I'm disabling those two tests in the cmake build for now and won't bother fixing for now unless I hear otherwise.

Thanks,

Tom

**Comment by b-scholz** [comment]
I would suggest dropping the SWIG tests for the initial CMAKE port and add the functionality later if it is too hard at the moment. It seems that more things are broken and our test suite did not pick it up.

**Comment by TomasPuverle** [comment]
I've made the required changes to make swig run under cmake and 4 out of 6 tests now pass under both python and java.  I will leave the other two tests commented out for now.  The test setup code seems to be working and they are only failing because of souffle.  Should be easy to enable and fix at some point.

**Comment by b-scholz** [comment]
Great - thanks for spotting this!

**Comment by b-scholz** [comment]
I checked today what is going wrong. The problem is that the headers are misplaced, i.e., the swig prefix is missing in the SouffleInterface.h header file. This bug was introduced when we refactored the directory structure of souffle (and the problem that we did not set the -x flag in the souffle-compile script).

**Comment by TomasPuverle** [comment]
Thanks for the fix!
