### ISSUE TITLE
PSA: jfrog is sunsetting Bintray

### ISSUE THREAD

**Issue by TomasPuverle** [souffle-lang/souffle#1855]
I believe souffle hosts binaries/packages on bintray, as per [https://souffle-lang.github.io/download.html](https://souffle-lang.github.io/download.html)

Source: [https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)

**Comment by b-scholz** [comment]
The deadline is  May 1st, 2021. That is no good!

We lost quite a bit of infrastructure recently: travis-ci and bintray.

**Comment by b-scholz** [comment]
I removed the installation instruction. As soon as GitActions and CMAKE are fully functional, we will implement scripts for PackageIO and upload the latest build there.

**Comment by langston-barrett** [comment]
It's past May 1st now, and my CI builds are failing :cry: 
```
#9 5.162 Reading package lists...
#9 5.770 E: Failed to fetch https://dl.bintray.com/souffle-lang/deb/dists/focal/InRelease  403  Forbidden [IP: 52.12.180.214 443]
#9 5.770 E: The repository 'https://dl.bintray.com/souffle-lang/deb focal InRelease' is not signed.
```
Any ideas when there might be another host for pre-built packages?

**Comment by b-scholz** [comment]
I talked to packagecloud - they would host us. If you have spare capacity and build the upload scripts for Git Action that would be amazing. 

For us the priority is:

(1) Switch to CMAKE (which will take more time than expected; my team here @ USYD are new to CMAKE)

(2) Go back to the functionality as before (uploading packages, doxygen, etc)

Bintray & Travis CI were quite a blow to our infrastructure.

**Comment by b-scholz** [comment]
Build scripts and cmke are done.
