### ISSUE TITLE
A few beginner questions

### ISSUE THREAD

**Issue by logicReasoner** [souffle-lang/souffle#1862]
Hi,
I've just started experimenting with Soufflé and have been wondering how to express some relations in rules.

1) How do I specify a default value for a relation, e.g. if I have
```
.type bool <: unsigned

.decl testRel2(n: symbol)
testRel2("foo").
testRel2("bar").
testRel2("baz").

testRel("bar", 0).

.decl testRel(n: symbol, m: unsigned)
testRel(x, 1) :- testRel2(x), !testRel(x, 0).

.output testRel()
```
That is, I need to state that: for every X for which `testRel2(x)` is true, and there EXISTS NO previous fact in the DB stating that `testRel(x, 0)`, then it follows that testRel(x, 1). In other words the default value is 1, unless the value 0 has already been stated as a fact for that same X.
The above rule generates an error `has cyclic negation in file test.dl at line 15
testRel(x, 1) :- testRel2(x), !testRel(x, 0).` despite the constants supplied as the second argument being different (`0` and `1`).
The expected result should be:
```
testRel
n       m
===============
foo     1
bar     0
baz     1
```

2) How do I express the fact that there exists at least one X (in other words `for some X`) for which `testRel2(x)` is true (which means that X is one or more of "foo", "bar" or "baz" from the code above) AND also `testRel3(x)` is true. In pseudo code: `exists(X) such that testRel2(x) && testRel3(x)`.

PS I know how to express that for every X where for which `testRel2(x)` is true, then it follows that `testRel3(x)` is true, but my question is regarding the existential quantifier (there exists an X) and NOT the universal one (for every X).

I've got some additional questions ready that I will try to articulate more clearly later.

Thanks in advance and keep up the good work on Souffle

**Comment by b-scholz** [comment]
For the first problem, could you stratify it. You could rewrite the first one as follows:
```
.type bool <: unsigned

.decl testRel2(n: symbol)
testRel2("foo").
testRel2("bar").
testRel2("baz").


.decl testRel(n: symbol, m: unsigned)
testRel("bar", 0).

.decl testRelS(n: symbol, m: unsigned)
testRelS(x,1):- testRel2(x), !testRel(x,0).   

.output testRelS()
```

**Comment by logicReasoner** [comment]
@b-scholz  Thanks!
Introducing an auxiliary relation seems to be the way to handle more complex scenarios.
Do you have any tips on how to express: if `testRel4(x, y)` is true for some x and y, then `testRel5(x, y)` MUST be false for those x and y. OTOH, if `testRel4(x, y)` is false, then we can NOT make any conclusions. I tried to use the logical equivalency P→¬Q  <==> ¬P∨¬Q but couldn't get it to work in Souffle.
What I mean is something like the code below (which is invalid syntax):
```
.decl testRel4(x: symbol, y: symbol)

.decl testRel5(x: symbol, y: symbol)
!testRel5(x, y):- testRel4(x, y).
```

**Comment by b-scholz** [comment]
Note that Datalog is a bottom-up solver. Relation testRel5(x,y) is more a constraint rather than a relation. Saying, that everything is permitted in testRel5 except if it tuples are testRel4 -- this relation is a very large set assuming the universe is finite. 
If you have questions about Datalog semantics, please read the Foundation of Database book by Abiteboul.  

Said this, you could just provide rules for testRel5 and introduce a new relation that filters the tuples of testRel4.

**Comment by logicReasoner** [comment]
Yes, you are right that the above example is more of a constraint that needs to be satisfied rather than a simple Datalog rule.
I was kinda testing the limits of Soufflé, because the documentation says that `Soufflé goes beyond the standard semantics of Datalog (i.e., finite domains, stratified negations, and totally ordered domains), and becomes Turing equivalent.` 
And if it's really Turing-complete, then any general purpose program should be possible to be expressed in it.

**Comment by b-scholz** [comment]
I just want to remark that Soufflé requires Horn clauses.

**Comment by b-scholz** [comment]
We achieve Turing equivalence via introducing new values, eg,
‘’’
A(x+1) :- A(x), x < 100.
A(0).
‘’’

**Comment by logicReasoner** [comment]
@b-scholz how can the same approach be used with symbolic variables, i.e. using non-integer types?

**Comment by b-scholz** [comment]
Can you be more specific? Note that logic solvers like Datalog/Prolog are not SMT solver, but you can use them to implement one.

**Comment by logicReasoner** [comment]
It'd be interesting to see something like the Z3 solver implemented on top of Datalog. Is there prior art of that?

**Comment by b-scholz** [comment]
We have some simple rewriting examples using equivalence relations. 
Have you read the egg paper (POPL'21)? It might be interesting to implement this in Souffle.
