### ISSUE TITLE
Ask for help for big datalog

### ISSUE THREAD

**Issue by qunqunqun** [souffle-lang/souffle#1866]
Souffle is build for speed and has achieved great achievement in datalog engines (most successful engine).
However, souffle often uses java-points-to analysis as example. 
So I am searching for other widely used datalog program with hundreds of rules (maybe graph?). 
I wonder if you can tell me some other benchmark for me , thank you !

**Comment by psubotic** [comment]
Maybe these might be interesting?
https://github.com/frankmcsherry/dynamic-datalog/tree/master/problems

**Comment by qunqunqun** [comment]
Thank you for answering! I have read it, the number of rules in galen/query.dl is 6 and the numbers of rules in crdt/query.dl is 14.
The doop/query.dl 's type is also Points-to analysis. 
I wonder if there is larger and different type application dl in real except Points-to analysis.
Thank you again for your patience.

**Comment by psubotic** [comment]
Bernhard can prob point u to others but I’m aware of:

https://github.com/eth-sri/securify

https://github.com/grammatech/ddisasm

I think they have large rulesets.

**Comment by b-scholz** [comment]
Gigahorse (ICSE'19) is another code base and other smart-contract analysis frameworks you see in the wild.

**Comment by b-scholz** [comment]
https://github.com/nevillegrech/gigahorse-toolchain

**Comment by b-scholz** [comment]
I would search github repos as well for souffle codes. I saw a few related to IDEs etc.

**Comment by qunqunqun** [comment]
Thank you for your answers! That helps me a lot. I will take a good look at these repos.

**Comment by b-scholz** [comment]
If you find more repos with souffle-code, could you post them here?

**Comment by qunqunqun** [comment]
@b-scholz  Okay, I think make a summary about souffle is important and necessary.  
If I find other repos, I would post them in this issue.

**Comment by efferifick** [comment]
There's also the following repository (which is developed by the same team in University of Athens which developed Doop). https://github.com/plast-lab/cclyzer-souffle

I don't think it is finished, but perhaps later this year.

**Comment by decalek** [comment]
Might be we should spawn a community sourcegraph instance somewhere, indexing the collection of souffle based projects ... ?

And why not, one nice day, the datalog collection to be searchable in something datalog-ish, instead of current sourcegrah structural search :-)

**Comment by b-scholz** [comment]
Let's have just a page on souffle-lang.github.io. That might be the easiest.

**Comment by luc-tielen** [comment]
I am doing many small experiments (livecoding on twitch) to implement parts of a compiler using Souffle (combined with Haskell).
So far I did dataflow analysis and some static analyses like unbound variables, name shadowing, ...
Code is at https://github.com/luc-tielen/playground (check out the various branches, not all are souffle related though).

**Comment by b-scholz** [comment]
I have added a page.

http://souffle-lang.github.io/applications
