### ISSUE TITLE
Generated code in a static library

### ISSUE THREAD

**Issue by efferifick** [souffle-lang/souffle#1868]
Hello,

I've been recently playing with Souffle, going over the documentation and understanding its use cases. Just last week, I have jumped from the simple examples into integrating Souffle into a large code base. While I was able to modify the build system for this large code base to use the C++ synthesized by Souffle, I found the following (minor) integration issue:

Souffle registers generated classes at run-time with the `ProgramFactory`. In order to achieve this, there is a global variable created for each Souffle Program (e.g., for a class named `example` the global variable will be a type `factory_Sf_example __factory_Sf_example_instance`. This works well if the generated file is linked directly into the application (e.g., `g++  main.c example.o  -std=c++17`. But I believe that if the generated file is placed in an archive (a static library, for example: `ar rc libexample example.o`) and then this library is linked into the application (e.g, `g++  main.c libexample.a  -std=c++17`) then the global variable will not be exported into the application. This means that the class is never registers with the `ProgramFactory` and all calls to `newInstance("example")` will return `NULL`.

I've managed to work around this issue by modifying the generated file and instead of creating a global variable I create a global pointer to a variable. Then I add a function called `init_souffle` which is visible from the global scope and call that function before calling `newInstance("example")`.

This is not the most elegant solution, but I'd be happy to discuss other alternatives and help contribute something to address this issue. If you would like, I can try to modify the generated code to include `#ifdef` statements to include this different initialization mode. But I would like to hear your opinions about this first.

There is also another alternative, which is to modify the build system of the application to avoid placing the generated file into a static library, but I think generating the static library is the right way to go in this case.

Let me know what you think, happy to contribute!

**Comment by b-scholz** [comment]
We designed the interface a long time ago. It would be great to improve it. I believe there are various options. One option would be to give up the registration at all.

**Comment by MarkusBauer** [comment]
I experienced a similar problem when I packed two Souffle programs into a single static library. As a workaround, I used this snippet of code (in the file that later uses the programs), that does not require manual modification of compiled files in the build process:
```C++
extern "C" {
extern char __factory_Sf_<program1>_instance;
extern char __factory_Sf_<program2>_instance;
}
void use_souffle_programs() {
  __factory_Sf_<program1>_instance = 0;
  __factory_Sf_<program2>_instance = 0;
}
```
The defined function `use_souffle_programs` should never be used, it just enforces that the symbols `__factory_Sf_..._instance` from all programs will be linked.

**Comment by efferifick** [comment]
@MarkusBauer this is awesome and exactly what I needed. Thank you! This solves all my problems. I'll leave it up to @b-scholz to decide whether he wants to close this issue or leave it open. I'd still be happy to contribute changes in the interface, but would likely need some further direction. 

Thanks everyone!

**Comment by b-scholz** [comment]
Perhaps we close it if there is a simple solution for this problem.

**Comment by b-scholz** [comment]
Thanks for the solution!
