### ISSUE TITLE
Negation of constraints

### ISSUE THREAD

**Issue by psubotic** [souffle-lang/souffle#187]
Looking at the AST and Grammar it seems to me that soufflé doesn't support negation of constraints. i.e., P(x) :- R(x), !(x < 5). It probably should.

**Comment by b-scholz** [comment]
That is correct. Soufflé would need symbolic transformations. At the moment, the Soufflé programmer requires an intrinsic knowledge how to write fast Soufflé specifications. It would be great if Soufflé  rewrites the specifications on its own. This issues is also related to magic set evaluation.

**Comment by b-scholz** [comment]
This is working with changes made for permitting disjunction and multiple-heads by Herbert a while ago. The following program works:

```
.decl A(x:number)
.output A

A(1).
A(x+1) :- A(x), !(x > 10).
```
