### ISSUE TITLE
What is the better way to populate universal facts in Soufflé?

### ISSUE THREAD

**Issue by pierre-ludmann-depinfonancy** [souffle-lang/souffle#1874]
Hi,

I have a need for a pure Datalog dialect accepting facts with free variables. E.g. the fact statement `R(x,x,y,y).` means that for all x and y in the (finite) domain D of the program, (x,x,y,y) is in R. Universal facts for `R` may co-exist with `R`-producing rule, e.g. `R(x,y,x,z) :- P(x,y,z).`

Now, I understand Soufflé disallows such free variables at the moment (is this a potential future feature?). To overcome this restriction, I envision to populate the relation `R` with each grounded version of the universal fact on [0, N] (e.g. with N=1000), an over-approximation of the domain D (D subset of [0,N]).

Now, I see 2 ways to do so:
1. Extensively: by the enumeration of all these tuples in a `R.facts` file (and `.input R` in the source)
2. Intensively: `R(0,0,0,0). R(x+1,x+1,y,y) :- R(x,x,y,y), x<1000. R(x,x,y+1,y+1) :- R(x,x,y,y), y<1000.`

Let's say I compile the sources:
- is that part of the relation `R` is pre-computed in the intensive populating solution?
- is one solution faster than the other?
- is one better with Magic set?

Thank you for bearing with me.

**Comment by pierre-ludmann-depinfonancy** [comment]
I experimented and would love some comments and insights:

#### Intensive solution
```
#define N 10000
.decl R(x:number, y:number, z:number, t:number)
R(0,0,0,0).
R(x+1,x+1,y,y) :- R(x,x,y,y), x<N.
R(x,x,y+1,y+1) :- R(x,x,y,y), y<N.
.decl S(x:number, y:number)
.output S
S(x,y) :- R(x,y,z,z).
```

#### Extensive solution
```
.decl R(x:number, y:number, z:number, t:number)
.input R
.decl S(x:number, y:number)
.output S
S(x,y) :- R(x,y,z,z).
```

| Solution | Time (s) | Memory (MB) |
|-----------|--------|----------|
| Intensive | 210 | 242 |
| Extensive | 76 | 237|

These results seems to indicate that the part of `R` due to the universal fact `R(x,x,y,y).` is not pre-computed in the intensive solution. Thus, the extensive solution appears better.

Domain solution
----------------
The domain solution naturally arises with multiple universal facts. And retrospectively is more natural. The idea is to only populate a predicate `Dom` representing the over-approximation of the domain, extensively or intensively. Then any universal fact `P(x1, ... ,xn).` can be translated to the Soufflé-compatible rule `P(x1, ... ,xn) :- Dom(x1), ..., Dom(xn)`. E.g. `R(x,x,y,y).` becomes `R(x,x,y,y) :- Dom(x), Dom(y).`.

#### Intensive domain solution
```
#define N 10000
.decl Dom(x:number)
Dom(0).
Dom(x+1) :- Dom(x), x<N.
.decl R(x:number, y:number, z:number, t:number)
R(x,x,y,y) :- Dom(x), Dom(y).
.decl S(x:number, y:number)
.output S
S(x,y) :- R(x,y,z,z).
```

#### Extensive solution
```
.decl Dom(x:number)
.input Dom
.decl R(x:number, y:number, z:number, t:number)
R(x,x,y,y) :- Dom(x), Dom(y).
.decl S(x:number, y:number)
.output S
S(x,y) :- R(x,y,z,z).
```

| Solution | Time (s) | Memory (MB) |
|-----------|--------|----------|
| Intensive domain, N=10k | 12 | 239 |
| Extensive domain, N=10k | 11 | 239|
| Intensive domain, N=20k | 51 | 465 |
| Extensive domain, N=20k | 52 | 380 |

Unable to set a difference for N=10 000, I tried with N=20 000. And the results unsettle me: I was expecting a difference similar to the previous non-domain experiment; but it is definitely not the case. Why such a difference?

**Comment by b-scholz** [comment]
You are right that free variables are not permitted in Souffle. This is not a Souffle restriction -- this is, in general, a Datalog restriction.

However, you could define an inline relation that has free variables in its rules. 
When the relation is inlined, the hope is that free variables become grounded by substitution. 
Alternatively, you could enumerate the domain as shown by you, but this is expensive. 

Another way to solve your problem is to use SMT solvers / symbolic solvers like Z3 (NB: Datalog is not an SMT solver).

**Comment by pierre-ludmann-depinfonancy** [comment]
Thanks for answering.

> However, you could define an inline relation that has free variables in its rules.
> When the relation is inlined, the hope is that free variables become grounded by substitution.

Unfortunately, the precedence graphs of my programs are often strongly connected; so inlining is out of order.


> Alternatively, you could enumerate the domain as shown by you, but this is expensive.

Could you explain why the execution time is so different between my so-called "domain" and non-domain solutions?


> Another way to solve your problem is to use SMT solvers / symbolic solvers like Z3 (NB: Datalog is not an SMT solver).

Wouldn't it be even more expensive? Theory-wise, SMT subsumes Datalog, right?

**Comment by b-scholz** [comment]
The "intensive domain solution" execution time is slower because you use a semi-naive evaluation procedure to generate values. Loading the data directly from a file seems to be faster. 
An alternative way to generate number ranges are generative functors. For example, 

```
.decl A(x:number)
A(x) :- x = range(1,5,1). 
.output A
```
generates numbers from 1 to 4 (similar to Python). 

It really depends on the overall application. I am happy to discuss this in more detail if you can give me more context. 
You can send me an email (Bernhard.Scholz@sydney.edu.au) if you don't want to discuss this in public.
