### ISSUE TITLE
Would it be possible souffle do not output a relation?

### ISSUE THREAD

**Issue by jjyAmongCookie** [souffle-lang/souffle#1877]
I recently write a LONG relation with multiple reasoning rules in a .dl file, and compile it using souffle, 

but I didn't get an output of that relation.

Notice: I'm sure that I write `.output relation` in my .dl file.

Would it be possible that souffle do not output a relation with long definition ?

**Comment by b-scholz** [comment]
Can you give us an example of where this is happening? 

It could be that your rules don't produce any results and hence the output is empty.
