### ISSUE TITLE
SEGFAULT in `InlineRelationsTransformer`

### ISSUE THREAD

**Issue by markusscherer** [souffle-lang/souffle#1878]
Hi!

While trying to compile a huge (generated) Datalog program, I consistently encountered a `SEGFAULT` in the version of souffle installed via my distribution (`2.0.1`) as well as a reasonably current development version (`4aea4a3`).

I was able to distill a minimal example, which still causes a `SEGFAULT` in `4aea4a3` but not in the version installed via my distribution.

```souffle
.decl A(A1: symbol)
.decl AG()
.decl SU(A1: number)
.decl B() inline
.decl BG() inline
.decl C() inline
.decl CG() inline

BG().
CG().

B() :- BG().
C() :- CG().

AG() :- B().
AG() :- C().

A("54") :-
  AG(),
  SU(_).
```

The `SEGFAULT` appears in `souffle::ast::Node::operator==(souffle::ast::Node const&) const` when an invalid address is dereferenced in `typeid(*&other)`.

The relevant stack trace looks like this:

```
souffle::ast::Node::operator==(souffle::ast::Node const&) const ()
souffle::ast::Program::removeClause(souffle::ast::Clause const*) ()
souffle::ast::transform::InlineRelationsTransformer::transform(souffle::ast::TranslationUnit&)
```

I instrumented the code to output the memory address of `Clause` objects in the destructor and found that the destructed and addresses and the addresses of the clauses that are removed in this snippet don't match.

```
        for (const Clause* clause : clausesToDelete) {
            program.removeClause(clause);
            changed = true;
        }
```

This is likely due to `souffle::ast::Node::operator==(souffle::ast::Node const&) const` being too "indulgent" when checking for equality (i.e. only check for the `typeid` not for content or referential equality). If an ostensibly (but not really) equal `Clause` is encountered before the correct one in `Program::removeClause`, it is destructed. If the destructed `Clause` is accessed in a later iteration of the loop, the `SEGFAULT` occurs. I assume that the bug appears only if the order of objects in `clausesToDelete` and `Program::clauses` differ, which can of course always happen, since one is a `std::set` and the other is a `std::vector`, so making `clausesToDelete` a `std::vector` would maybe also work.

If the provided example does not trigger the `SEGFAULT`, I can also provide the original (much bigger) original example, which was more consistent in triggering it.

**Comment by b-scholz** [comment]
There is an issue with smart pointers. We need to double-check the memory ownership.

**Comment by b-scholz** [comment]
With the latest inline fix, this bug went away (i.e. inline rules are no longer process).

**Comment by b-scholz** [comment]
This is related to issue #1956.

**Comment by b-scholz** [comment]
Please find below the fix for the problem. The problem was caused by a double-delete of duplicated clauses that were introduced by inlining. The `removeClause()` method deletes based on structural equivalence rather than object pointers (i.e. identity). 
The problem can be solved by cloning / instead of storing pointers in the set `clausesToDelete`.

```
diff --git a/src/ast/transform/InlineRelations.cpp b/src/ast/transform/InlineRelations.cpp
index c1aa5323c..4b0969841 100644
--- a/src/ast/transform/InlineRelations.cpp
+++ b/src/ast/transform/InlineRelations.cpp
@@ -1046,7 +1046,7 @@ bool InlineRelationsTransformer::transform(TranslationUnit& translationUnit) {
     // terminate.
     bool clausesChanged = true;
     while (clausesChanged) {
-        std::set<Clause*> clausesToDelete;
+        VecOwn<Clause> clausesToDelete;
         clausesChanged = false;
 
         // Go through each relation in the program and check if we need to inline any of its clauses
@@ -1065,7 +1065,7 @@ bool InlineRelationsTransformer::transform(TranslationUnit& translationUnit) {
                     std::vector<Clause*> newClauses = getInlinedClause(program, *clause);
 
                     // Replace the clause with these equivalent versions
-                    clausesToDelete.insert(clause);
+                    clausesToDelete.push_back(clone(clause));
                     for (Clause* replacementClause : newClauses) {
                         program.addClause(Own<Clause>(replacementClause));
                     }
@@ -1078,8 +1078,8 @@ bool InlineRelationsTransformer::transform(TranslationUnit& translationUnit) {
         }
 
         // Delete all clauses that were replaced
-        for (const Clause* clause : clausesToDelete) {
-            program.removeClause(clause);
+        for (const auto &clause : clausesToDelete) {
+            program.removeClause(clause.get());
             changed = true;
         }
     }
```

We would need to find a small example that replicates the issue.
