### ISSUE TITLE
Strange behavior of as() functor

### ISSUE THREAD

**Issue by gfour** [souffle-lang/souffle#1890]
I am seeing some strange behavior when casting values with subtyping and `as()`. Assume the following:
```
.type A <: symbol
.type B1 <: A
.type B2 <: A

.decl isB1(b1: B1)
.output isB1
.decl isB2(b2: B2)
.output isB2

isB1("test").
isB2("hello").

.decl isBothB1AndB2(x: A)
.output isBothB1AndB2

isBothB1AndB2(x) :-
    isB1(x),
    isB2(as(x, B2)).
```
This is accepted by Souffle and produces the following output, where relation "isBothB1AndB2" looks wrong:
```
$ souffle file.dl
$ cat isB1.csv
test
$ cat isB2.csv
hello
$ cat isBothB1AndB2.csv
test
```

Is the code triggering some sort of undefined behavior? I understand that the code is somewhat ill-defined (since B1 and B2 are supposed to be disjoint sets).

**Comment by b-scholz** [comment]
This is a bug. Type-casts `as(...)` are not translated properly in the new ast-to-ram translator. 
Thanks for raising this issue. We need to rewrite the program from
```
--isB1--
isB1("test").

--isB2--
isB2("hello").

--isBothB1AndB2--
isBothB1AndB2(x) :- 
   isB1(x),
   isB2(as(x, B2)).
```
to 
```
--isB1--
isB1("test").

--isB2--
isB2("hello").

--isBothB1AndB2--
isBothB1AndB2(x) :- 
   isB1(x),
   isB2(x).
```
in the ResolveAliasTransformer.

**Comment by b-scholz** [comment]
Do you want to give it a go? I could guide you.

**Comment by gfour** [comment]
Sure, do I have to edit src/ast/transform/ResolveAliases.cpp?

**Comment by b-scholz** [comment]
Hmm ... I think the easiest is to write a simple AST transformer that eliminates as(...) expressions, i.e., as(x,type) => x . 

That would be the easiest actually. It needs to be invoked before ResolveAliases in the transformation pipeline (see `main.cpp`). 

Please test recursive type-casts as(as(as(x,T1),T2),T3).

**Comment by b-scholz** [comment]
I take it back - it is better to implement this in ResolveAliases. 
ResolveAliases should transform this rule:
```
isBothB1AndB2(x) :-
    isB1(x),
    isB2(as(x, B2)).
```
to
```
isBothB1AndB2(x) :-
    isB1(x),
    isB2(temp0), 
    temp0=x.
``
which is currently not happening.

**Comment by gfour** [comment]
In ResolveAliasesTransformer::removeComplexTermsInAtoms()?

**Comment by b-scholz** [comment]
Have a look - it was just a single line.
