### ISSUE TITLE
Lazy eval in generated C++ code

### ISSUE THREAD

**Issue by psubotic** [souffle-lang/souffle#190]
Int he interface a user has the option of having part of their program pre compiled. In this case several optimizations cannot be done by souffle and this results in having to evaluate all rules even if they are not needed. We should allow the generated C++ code to be able to take in set of relations that need to be computed (obtained for example by a dependency graphs so that when the C++ is executed only required rules are computed..

**Comment by b-scholz** [comment]
Is this still an issue? Could you expand more on this issue?
