### ISSUE TITLE
RFC: Add `#pragma gcc optimize("O3")` and similar to generated code

### ISSUE THREAD

**Issue by efferifick** [souffle-lang/souffle#1901]
Not sure if this will be a welcomed addition, but I suppose that asking won't hurt. I've been playing with Souffle for the last month or so and I have integrated Souffle into the build system of a large project. I was having some performance problems and then I noticed that running the souffle profiler was actually running the program faster than my compiled version. I am not sure if this is the case, but I suspect that internally when souffle takes an input `.dl` file it will compile it using `-O3`. Maybe it would be a good idea to add pragmas to compile the generated cpp file using `-O3` and similar?

As an alternative, maybe I can document which flags are used and somehow highlight it to the user? (It could just be on the website) but an message on `-h` would also be nice.

**Comment by b-scholz** [comment]
That is correct. We use a compile script called souffle-compile in the `souffle/src`. At the moment, we use autoconf/automake that produces the script from `souffle-compile.in` and sets the CXX_FLAGS accordingly.

You can add pragmas easily by modifying the `souffle/src/synthesiser/Synthesiser.cpp` so that pragmas are issued in the source code.

It is odd that the profiled version ran faster. Are you sure about it? (Or did you mean the interpreter with the profile options on?).

**Comment by efferifick** [comment]
Hi, thanks for answering my question. I see now that `CXX_FLAGS` are set at configuration time. Perhaps my suggestion doesn't really make much sense in hindsight.

Also, yes I did run the interpreter with the profile options on. I was surprised that this was faster than my generated C++ code compiled without `-march=native`. It took me some time to realize this difference and the performance improvement is really noticeable (depending on the input given).

I think, if you consider it worthwhile, that outputting which `CXX_FLAGS` are used in `souffle-compile.in` inside the usage string of souffle will be good contribution for improving user experience. Let me know and I can contribute it in the coming week or two. Otherwise, thanks for helping me understand what was happening!

**Comment by b-scholz** [comment]
Normally it is expected that the compilation takes a lot of time and the runtime less than the interpreter. If you have a smaller dataset to process, most likely, the interpreter will be faster. 

We do not want to expose souffle-compile to end-users. That should be hidden for normal operation and only exposed for specific reasons. You can control the flags from outside using the configure script.
