### ISSUE TITLE
efficient sub-tree size

### ISSUE THREAD

**Issue by csabahruska** [souffle-lang/souffle#1904]
Hello,

I've seen that with the new `choice-domain` feature it is possible to calculate the spanning tree efficiently.
But I do not know how to calculate the tree size efficiently (**EDIT:** including the sub-trees) with a single bottom-up traversal.
Is it possible at all?
Could you give me some advice please?

Here is my simple example:
```prolog
/*
  see the graph layout visually:
    https://bit.ly/32rjHaO
*/

.decl graph_edge(x : symbol, y : symbol)
.decl tree_edge(x : symbol, y : symbol)

graph_edge("aa", "b").

graph_edge("a", "b").
graph_edge("b", "c").
graph_edge("c", "d").

graph_edge("d", "y").
graph_edge("d", "z").

graph_edge("a", "m").
graph_edge("m", "n").
graph_edge("n", "o").

graph_edge("z", "y").
graph_edge("o", "z").

graph_edge("z", "o").
graph_edge("o", "n").

graph_edge("n", "w").

/////////

// spanning tree

.decl st(level : number, u:symbol, v:symbol) choice-domain v
.decl startNode(x:symbol)

startNode("aa").
startNode("a").

st(0, "root", x) :- startNode(x).
st(level + 1, v, u) :- st(level, _, v), graph_edge(v, u).

.output st

tree_edge(x, y) :-
  st(_, x, y).

/////////

// (ineffiecient) utility relation

.decl flows(x : symbol, y : symbol)
.output flows

flows(n, m) :- tree_edge(n, m).
flows(n, m) :- flows(n, x), tree_edge(x, m).

// calculate tree size

.decl tree_size(r : symbol, size : number)
.output tree_size

tree_size(r, 1 + descendant_count) :-
  (tree_edge(r, _) ; tree_edge(_, r)), // HINT: nodes
  descendant_count = count : {flows(r, _)}.
```

**Comment by csabahruska** [comment]
Maybe these Datalog extensions are needed for efficient graph queries:
- SociaLite: Datalog Extensions for Efficient Social Network Analysis
  https://mobisocial.stanford.edu/papers/icde13.pdf

- SociaLite: An Efficient Graph Query Language Based on Datalog
  https://mobisocial.stanford.edu/papers/tkde2015.pdf

**Comment by lyxell** [comment]
Modelling the flows relation with `eqrel` should give a linear representation instead of a quadratic one, see:
https://github.com/souffle-lang/souffle-lang.github.io/blob/master/pages/docs/relations.md#equivalence-relations

Maybe this would solve your problem?

**Comment by csabahruska** [comment]
The `flows` relation is not commutative, so `eqrel` could not be used for it.

**Comment by lyxell** [comment]
@csabahruska Right, maybe you can define a new relation that actually is the transitive closure of the edge relation and let this relation use `eqrel`. Then use this to find all nodes that are reachable from a certain node and count them?

**Comment by csabahruska** [comment]
Yes, `flows(a,b) ⇔ flows(b,a)` does not hold.

**Comment by lyxell** [comment]
How about using a relation that is not binary then, say:

```
.decl marked(x : symbol)
marked(m) :- marked(n), tree_edge(n, m).
```
Now, marking a node, say node `a`:
```
marked("a").
```
and then counting the size of the `marked`-relation should give the size of the subtree, while the `marked` relation would be linear.

**Comment by csabahruska** [comment]
Ok, with the `marked ` relation, it is possible to count the nodes for the whole tree.
But it would not work to calculate the sub-tree size of the tree graph, which would be important in my actual use case.

**Comment by lyxell** [comment]
Do you mean that you want to calculate the sizes of all subtrees?

**Comment by csabahruska** [comment]
yes

**Comment by lyxell** [comment]
Right, there might be up to N subtrees and each subtree might contain up to N nodes so it will be hard to store this relation without consuming N² memory.

One solution might be to never store the relation, and calculate the size directly and recursively, starting at the nodes:

```
leaf(x) :-
  ! tree_edge(x, _).

tree_size(x, 1) :- leaf(x).
tree_size(x, n) :- n = sum m : tree_size(y, m), tree_edge(x,y).
```

**Comment by csabahruska** [comment]
This is a good idea, but does not work unfortunately:
```proglog
.decl leaf(n : symbol)

leaf(x) :-
  tree_edge(_, x),
  ! tree_edge(x, _).

tree_size(x, 1) :- leaf(x).
tree_size(x, n) :- n = sum m : tree_size(y, m), tree_edge(x,y).
```

error:
```
Error: Unable to stratify relation(s) {tree_size}
Relation tree_size in file spanning-tree-size-slow.dl at line 60
.decl tree_size(r : symbol, size : number)
------^------------------------------------
has cyclic aggregation in file spanning-tree-size-slow.dl at line 74
tree_size(x, n) :- n = sum m : tree_size(y, m), tree_edge(x,y).
-------------------------------^--------------------------------
1 errors generated, evaluation aborted
```

**Comment by lyxell** [comment]
Yeah, that's unfortunate, I didn't know of that limitation. The obvious workaround is something like:
```
.decl leaf(n : symbol)

leaf(x) :-
  tree_edge(_, x),
  ! tree_edge(x, _).

tree_size(x, 1) :- leaf(x).
tree_size(x, n) :- tree_size(y, n), tree_edge(x,y).

summed_tree_size(x, n) :- n = sum m : tree_size(y, m).
```
But then the `tree_size` relation is quadratic again. Maybe someone else has an idea on how to solve this, I would have to think about it a bit more.

**Comment by lyxell** [comment]
Issue #1295 seems related. It also contains a proposed solution if you are able to order the child nodes. I.e. change the `tree_edge` relation to also include which index the child has with respect to its parent. This would allow you to sum the sizes of the child trees of a node in order.

**Comment by csabahruska** [comment]
Thanks, this was a good hint.
So the lesson is that native recursive aggregation is not supported, but it can be simulated with `choice-domains`.

Here is my solution:

```prolog
// calculate tree size (fast)

//  utility relations to simulate recursive aggregation

// child ordering
.decl next(parent : symbol, a : symbol, b : symbol) choice-domain (parent, a), (parent, b)

next(parent, "nil", "head") :-
  st(_, parent, _).

next(parent, p, n) :-
  st(_, parent, n),
  next(parent, _, p).

.decl last(parent : symbol, a : symbol)

last(parent, n) :-
  st(_, parent, n),
  ! next(parent, n, _).

.output next, last

//  recursive aggregation using a specific visit order (like a for loop)

.decl tree_size_fast(n : symbol, size : number)

.decl size_accumulator(n : symbol, v : number) // loop variable
.output size_accumulator, tree_size_fast

size_accumulator(n, 1 + s) :-
  next(_, "head", n),
  tree_size_fast(n, s).

size_accumulator(n, prev_size + s) :-
  size_accumulator(prev, prev_size),
  next(_, prev, n),
  tree_size_fast(n, s).

tree_size_fast(parent, s) :-
  size_accumulator(n, s),
  last(parent, n).

// base case: leaf size = 1
tree_size_fast(n, 1) :-
  tree_edge(_, n),
  ! tree_edge(n, _).
```
