### ISSUE TITLE
Question: Clause ordering changes when rule is inside a component

### ISSUE THREAD

**Issue by langston-barrett** [souffle-lang/souffle#1906]
This may be a bug, or possibly a question. I've recently refactored a large program (which unfortunately, I can't share in its entirety) to make extensive use of components. After this refactoring, I noticed some performance issues. I'm positive that the output hasn't changed in any way, so I investigated if the "componentization" had interacted poorly with some of Souffle's optimizations. Here's an example of what I found.

```
$ souffle --version
Souffle: 2.0.2-987-gbcb2a08e5(32bit Domains)
Copyright (c) 2016-19 The Souffle Developers.
Copyright (c) 2013-16 Oracle and/or its affiliates.
```

#### Before

```
rec_memcpy(?toCtx, ?to, ?fromCtx, ?from) :-
   memcpy(?toCtx, ?toOuter, ?fromCtx, ?fromOuter),
   ptr_compatible_allocation(?toOuter),
   alloc_subregion_at_path(?toOuter, ?path, ?to),
   allocation_type(?to, ?destType),
   alloc_subregion_at_path(?fromOuter, ?path, ?from),
   allocation_type(?from, ?srcType),
   type_compatible(?srcType, ?destType).
```

#### After

Note: The clauses haven't changed in order, just some of them are "namespaced" by a component.
```
  rec_memcpy(?toCtx, ?to, ?fromCtx, ?from) :-
    _memcpy(?toCtx, ?toOuter, ?fromCtx, ?fromOuter),
    ptr_compatible_allocation(?toOuter),
    alloc_subregion_at_path(?toOuter, ?path, ?to),
    allocation_type(?to, ?destType),
    alloc_subregion_at_path(?fromOuter, ?path, ?from),
    allocation_type(?from, ?srcType),
    type_compatible(?srcType, ?destType).
```

### Transformed Program

I produced this using `--show=transformed-datalog`.

#### Before

```
rec_memcpy(?toCtx,?to,?fromCtx,?from) :- 
   memcpy(?toCtx,?toOuter,?fromCtx,?fromOuter),
   ptr_compatible_allocation(?toOuter),
   alloc_subregion_at_path(?toOuter,?path,?to),
   allocation_type(?to,?destType),
   alloc_subregion_at_path(?fromOuter,?path,?from),
   allocation_type(?from,?srcType),
   type_compatible(?srcType,?destType).
```

#### After

Note that the clauses are ordered differently:
```
subset_memcpy.rec_memcpy(?toCtx,?to,?fromCtx,?from) :- 
   subset_memcpy._memcpy(?toCtx,?toOuter,?fromCtx,?fromOuter),
   ptr_compatible_allocation(?toOuter),
   type_compatible(?srcType,?destType),
   subset_dynamic_subobjects.alloc_subregion_at_path(?toOuter,?path,?to),
   subset_allocation_type.allocation_type(?to,?destType),
   subset_dynamic_subobjects.alloc_subregion_at_path(?fromOuter,?path,?from),
   subset_allocation_type.allocation_type(?from,?srcType).
```

So it seems that the clause order is different for an "internal" reason, i.e. one not related to the order I wrote them. What's going on here? Are there some optimizations that aren't being applied to rules that appear inside components?

**Comment by b-scholz** [comment]
That is an interesting observation. We have a simple heuristic at the moment for scheduling. You can always overwrite it with `.plan`. What makes me wonder is why the heuristic decides differently for the relation inside the component. 

We would need to investigate further. Can you have a look into the `src/ast/transformer/ReoderLiterals.h/cpp`.

**Comment by langston-barrett** [comment]
> You can always overwrite it with `.plan`. 

Understood. Unfortunately, this won't be easy for our codebase, since most of it now uses components and the workflow here would presumably be to step through every rule in the program and compare it to the "old" version, and write a query plan if they differ.

> We would need to investigate further. Can you have a look into the src/ast/transformer/ReoderLiterals.h/cpp.

Sure - what should I be looking for? I don't have any significant experience with the Souffle codebase so I'm not sure if I'm the best person to investigate this.

**Comment by b-scholz** [comment]
I think I understand why. The problem is that our heuristic for literal reordering is weak. For this example, it will give a certain degree of freedom. To resolve the freedom, it uses the naming of the relations. 

This is of course only a hypothesis. You can try this by using different instantiation names and see whether it starts reordering the literals again. 

I feel you need to fix the reordering for your application. You know which ordering is right - Souffle's current reordering is very weak. 

Can you try a different SIPS (ie. Reordering strategy)?

We have following strategies:
 - strict
 - all-bound
 - naive
 - max-bound
 - max-ratio
 - least-free
 - least-free-vars
 - profile-use
 - delta
 - input
 - delta-input
 - all-bound

The default is "all-bound". Can you run Souffle with `--show=transformed-datalog -PSIPS:strict` and check again.

**Comment by langston-barrett** [comment]
Running with `-PSIPS:naive` produced the following ordering, which is different from both of the above.
```
subset_memcpy.rec_memcpy(?toCtx,?to,?fromCtx,?from) :- 
   subset_memcpy._memcpy(?toCtx,?toOuter,?fromCtx,?fromOuter),
   ptr_compatible_allocation(?toOuter),
   subset_dynamic_subobjects.alloc_subregion_at_path(?toOuter,?path,?to),
   subset_allocation_type.allocation_type(?to,?destType),
   type_compatible(?srcType,?destType),
   subset_dynamic_subobjects.alloc_subregion_at_path(?fromOuter,?path,?from),
   subset_allocation_type.allocation_type(?from,?srcType).
```
Both `all-bound` and `strict` produce the sub-optimal query plan posted above in "After".

Are the SIPS strategies documented? They're clearly having a large impact on the performance of our project, so it'd be good for us to explore them but I'm not sure where to start.

**Comment by b-scholz** [comment]
Note these SIPS strategies are for the whole program. The work on averaging arguments but only a handful of rules kill your performance. I would suggest that you write `.plan` statements for these rules. I can help with the plan statements if you need some instructions. 

Basically, you will need a profile output to understand how many versions there are and which version of the rule needs tweaking. 
If you need help, please post the profile info for a representative run.

**Comment by langston-barrett** [comment]
> The work on averaging arguments but only a handful of rules kill your performance. I would suggest that you write .plan statements for these rules. I can help with the plan statements if you need some instructions.

Okay, I'll have a go at trying out `.plan` statements for the rules that have jumped to the top of the profiles since starting to use components, and I'll reach out if I have difficulties. Thanks for the offer!
