### ISSUE TITLE
Magic set transformation

### ISSUE THREAD

**Issue by psubotic** [souffle-lang/souffle#191]
this is badly needed

**Comment by scyptnex** [comment]
(leaving this here incase someone gets around to it)

**Background**
http://dx.doi.org/10.1007/978-3-642-04238-6_9

There are issues with implementing magic sets for _general_ datalog problems, i think we should instead go with subsumptive tabling (this is what Logicblox does)
http://dx.doi.org/10.1145/1989323.1989393

**Comment by psubotic** [comment]
yes I have seen this paper - looks like a good way to go.

**Comment by psubotic** [comment]
would you be interested in working on this Nic?

**Comment by scyptnex** [comment]
Unfortunately i dont really have much time.

on a related issue, how does souffle handle negation?
```
X(a,b) :- Y(a,b), !Z(a,b)

P(a,b) :- Q(a,b), !P(a,b)
```
how would souffle handle the X and P relations?

**Comment by psubotic** [comment]
it can handle stratified negation
http://www3.cs.stonybrook.edu/~warren/xsbbook/node59.html. So your second
rule would not be an acceptable program.

**Comment by scyptnex** [comment]
ah.
subsumptive tabling requires non-inflationary (eager) negation.

i.e. if the relation is absent *at the time of evaluation* then it is considered absent, but if it becomes present later that does not change the tuples that arose because it *was* considered absent

**Comment by psubotic** [comment]
@b-scholz This is a massive priority if you have any resources at usyd. The results of magic set + souffle on some industry code I have tried it on is staggering. I will have time to implement it in Dec if its not done by anyone until then.

**Comment by b-scholz** [comment]
I plan to do some work on magic-set transformation in the summer-break.

**Comment by psubotic** [comment]
great i can help out too -- i will have time then

**Comment by tiros-team** [comment]
FWIW, this is the best type-theoretic exposition I know of: https://hal.inria.fr/inria-00535948/document

**Comment by b-scholz** [comment]
Abdul is working on magic set. Help is welcome to check his progress.

**Comment by psubotic** [comment]
Im happy to assist in reviewing etc.
