### ISSUE TITLE
User-defined functors with floats

### ISSUE THREAD

**Issue by mclements** [souffle-lang/souffle#1918]
The [manual](https://souffle-lang.github.io/functors#functor-declaration) currently states that only symbols and numbers are available for user-defined functors, whereas a [test](https://github.com/souffle-lang/souffle/blob/master/tests/interface/functors/functors.dl) for functors includes an example with `.functor rnd(float):number`.

Is there any possibility to include functors that return floats, please? The problem domain I had in mind was statistical analysis (e.g. Poisson-based confidence intervals using the r-matlib library). I had tried:
```
#include <Rmath.h>
#define MATHLIB_STANDALONE
extern "C" {
  double myexp(double x) { return ::exp(x); }
}
```
and `.functor myexp(float):float`, but then using `@myexp(1.0)` returned `4.6071824188000174e+18` with 64-bit floats.

Doing this in Datalog itself would be awkward:
```
.decl xs(x:float)
.decl Is(x:float)
.decl factorial(x:float,y:float)
.decl exp(x:float,y:float)
xs(1.0).
Is(x) :- x = range(1.0, 15.0, 1.0). 
factorial(1.0,1.0).
factorial(x,y*x) :- Is(x), factorial(x-1.0,y).
exp(x,y) :-
    xs(x),
    y = 1.0 + sum fi: {xs(x), factorial(i,fact), Is(i), fi=x^i/fact}.
```
Sincerely, Mark.

**Comment by b-scholz** [comment]
If you want to use "double" you need to configure souffle in 64 bit mode: `./configure  --enable-64bit-domain`

Wit the functor declaration
```
.functor myexp(float):float
```
it should work. Let me know how it goes. Happy to help!

**Comment by mclements** [comment]
Thank you for the timely reply - appreciated.

I had already used `/configure --enable-64bit-domain`. Using the [example code](https://souffle-lang.github.io/functors), I have now simplified the C code:

```
  double h(double x) {
    return x + 1.0;
  }
```

The functors `.functor f(number):number` and `.functor g():symbol` work as expected, however `.functor h(float) : float` does not (returning 4.6223820675423928e+18 for @h(10.0)). Note that I am using Ubuntu 20.04 LTS.

Is there any chance you could write and run a test for this case, please? 

Sincerely, Mark.

**Comment by b-scholz** [comment]
There must be something wrong with the bit-casts. 
Can you further reduce your example. E.g., 
```
A(1.0).
B(@h(x)) :- A(x).
```
and see whether it still prevails. 

It could be related to bit-casts (we use internally) and we did not consider the 64bit case well.

**Comment by b-scholz** [comment]
Your PR reveals the bug. This needs to be fixed.

**Comment by b-scholz** [comment]
Can you check whether it fails for interpreter and compiler (-c)?

**Comment by mclements** [comment]
Nice catch! This fails with the interpreter and works with the compiler.
