### ISSUE TITLE
New libraries: souffle-math and souffle-datetime

### ISSUE THREAD

**Issue by mclements** [souffle-lang/souffle#1934]
I have written two fairly short libraries for the C math library [souffle-math](https://github.com/mclements/souffle-math) and C dates/times [souffle-datetime](https://github.com/mclements/souffle-datetime).

Note that the C math library is assumed to use `double`s. The datetime library uses C `time_t` as unix timestamps with various conversions. The latter can use either `int32_t` or `int64_t` for the timestamps.

Two questions: first, would either of these libraries be useful for the main distribution? Second, could the Wiki or web-site include a page for contributed packages?

Sincerely, Mark.

**Comment by b-scholz** [comment]
I would suggest setting up a new repo in the souffle-lang domain. 
Let me know whether this works for you.

**Comment by mclements** [comment]
Currently, I don't believe that I can create a new repo on that domain. Can you add me to the domain?

**Comment by b-scholz** [comment]
I created the new repo and gave you admin rights. Let me know whether it works.

**Comment by b-scholz** [comment]
The new library repo is `souffle-lang/souffle-lib`.

Can we close this issue?

**Comment by mclements** [comment]
Thank you - this is a good idea. 

For configuration of the library, is there a simple way to determine whether souffle is enabled for 64-bit `number`s and `float`s?

**Comment by XiaowenHu96** [comment]
Currently no. But once we integrate with Cmake (which will happen soon) the information will be available.
And I don't think we have an option relates to `float`.

**Comment by b-scholz** [comment]
That is a good point. I have never thought about this. 

I would generate two libraries (one for 32bit and one for 64bit) with adequate naming. 
Something like soufflem32 and soufflem64 etc.

**Comment by mclements** [comment]
I could use:

```
// test-cfg.dl
.decl Test(x:number)
Test(64) :- 2^32>0.
Test(32) :- 2^32<=0.
.output Test
```

and a bash script:

```
#!/bin/bash
souffle -D- ./test-cfg.dl | grep -E "(32|64)"
```

Will this work on all of the architectures?

**Comment by b-scholz** [comment]
Yes - that is a great idea to find out whether a souffle installation is 32bit or 64bit. 
However, you have an easier option. If you call souffle with `-v` you should get the same information. 
I.e., 
```
Souffle: 1.7.1-4113-g4ff0bbcb2(32bit Domains)
Copyright (c) 2016-19 The Souffle Developers.
Copyright (c) 2013-16 Oracle and/or its affiliates.
```

**Comment by XiaowenHu96** [comment]
> Yes - that is a great idea to find out whether a souffle installation is 32bit or 64bit.
> However, you have an easier option. If you call souffle with `-v` you should get the same information.
> I.e.,
> 
> ```
> Souffle: 1.7.1-4113-g4ff0bbcb2(32bit Domains)
> Copyright (c) 2016-19 The Souffle Developers.
> Copyright (c) 2013-16 Oracle and/or its affiliates.
> ```

I think this is only available if built with cmake.

**Comment by b-scholz** [comment]
It should also work with a standard build.
```
   std::cout << "Souffle: " << PACKAGE_VERSION;
            std::cout << "(" << RAM_DOMAIN_SIZE << "bit Domains)";
            std::cout << std::endl;
            std::cout << "Copyright (c) 2016-19 The Souffle Developers." << std::endl;
            std::cout << "Copyright (c) 2013-16 Oracle and/or its affiliates." << std::end;
```

**Comment by mclements** [comment]
I have now pushed an initial commit for the souffle-lib library. In the `configure.ac` file, I used `if test $(souffle --version | grep -c "64bit Domains") = "1"; then` to test for a 64-bit domain -- this may need to be updated.

We could now close this issue.
