### ISSUE TITLE
Installation: error: forbidden id

### ISSUE THREAD

**Issue by Ytvivian21** [souffle-lang/souffle#1941]
I'm unable to install souffle on my Ubuntu 20.04.2 LTS
`E: Failed to fetch https://dl.bintray.com/souffle-lang/deb-unstable/dists/focal/InRelease  403  Forbidden [IP: 52.43.14.61 443]
`
`E: The repository 'https://dl.bintray.com/souffle-lang/deb-unstable focal InRelease' is not signed.`

**Comment by Ytvivian21** [comment]
I just used the command in the Document:
`echo "deb https://dl.bintray.com/souffle-lang/deb-unstable bionic main" | sudo tee -a /etc/apt/sources.list`
`sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61`
`sudo apt-get update`

**Comment by b-scholz** [comment]
Unfortunately, bintray stopped its service. At the moment, we try to switch to CMAKE followed by packageIO. 
We hope we have a similar service working soon. 

In the meantime, please build souffle from scratch using the source ball (sh bootstrap;./configure;make -jauto install).
