### ISSUE TITLE
String escaping in Souffle treats the escape sequences literally

### ISSUE THREAD

**Issue by lyxell** [souffle-lang/souffle#1947]
I am trying to construct a Soufflé string containing a quotation mark, that is, the character `"` (Unicode U+0022).

However, string escaping in Soufflé seems to work differently from, say C or C++, since the string `"\""` results in a *two* character sequence containing `\` (U+005C) and `"` (U+0022).

The same thing holds true for the string `"\n"` which does not produce a line feed (U+000A) but rather a sequence of two characters, `\` (U+005C) and `n` (U+006D).

Is this a known bug and is there a known workaround?

**Comment by b-scholz** [comment]
We should fix this. No - we did not have this feature. Would you like to implement it?

**Comment by lyxell** [comment]
> We don't have this feature. Would you like to implement it?

Sure! I'll look into it.

**Comment by b-scholz** [comment]
I missed this (I am on leave). I think long-term it would be good to implement the same functionality as given by the C/C++ standard. That would be the easiest in terms of documentation and terms of acceptance in the community. 

A way to improve the compatibility for legacy code is to switch on old-style string parsing with the flag ```--legacy``` if necessary.
