### ISSUE TITLE
`generateRandomVector` called with the default seed in `record_table_test` always return the same vector

### ISSUE THREAD

**Issue by quentin** [souffle-lang/souffle#1958]
Hello,
Unless I misunderstand the test performed in `record_table_test.cpp`, I think `generateRandomVector` should be given a different `seed` value for each call otherwise the test is just inserting the same tuple `NUMBER_OF_TESTS` times:

https://github.com/souffle-lang/souffle/blob/dce5a30bf996bd394a2f23b205e05c172fe28e96/src/tests/record_table_test.cpp#L97-L99

https://github.com/souffle-lang/souffle/blob/7174f14ef50debc742ff874c76f67382ca3bdd5e/src/tests/test.h#L39-L42

Or should the test be updated to look more like the previous one:
https://github.com/souffle-lang/souffle/blob/dce5a30bf996bd394a2f23b205e05c172fe28e96/src/tests/record_table_test.cpp#L57-L73

**Comment by b-scholz** [comment]
Indeed, this test should be improved. Also, the arity should vary (not just their values). Currently, the arity is set to 10.
