### ISSUE TITLE
Using "eqrel" on non-binary relations

### ISSUE THREAD

**Issue by langston-barrett** [souffle-lang/souffle#1963]
I have a relation like so:
```
  .type AllocWithContext = [?aCtx: Context, ?alloc: Allocation]
  .decl unify(?a: AllocWithContext, ?b: AllocWithContext) eqrel
```
There are a few places in my program where I need to join with this relation. I discovered it was very slow to do so directly, presumably because Souffle can't construct indices into the fields of the records here. So I made a relation that "unpacks" the record:
```
  .decl unify_unrecord(?ctx1: Context, ?alloc1: Allocation, ?ctx2: Context, ?alloc2: Allocation)
  unify_unrecord(?ctx1, ?alloc1, ?ctx2, ?alloc2) :- unify([?ctx1, ?alloc1], [?ctx2, ?alloc2]).
```
*Using* this relation in other places was much faster, because its uses had half of their variables bound and Souffle will use an index. But *constructing* it turns out to be very slow, because `unify` is very large. Here's a sample profile:
```
> rel R313 
  ----- Rules of a Relation -----
   TOT_T  NREC_T   REC_T  TUPLES      ID NAME

     70s   .000s     56s   30.6M    R313 unification.unify_unrecord
 ---------------------------------------------------------
     56s   .000s     56s   30.6M  C313.1 unification.unify_unrecord

Src locator: /x/llvm/PointerAnalysis/datalog/points-to/unification.dl [340:9-340:23]

 C313.1  unification.unify_unrecord(?ctx1,?alloc1,?ctx2,?alloc2) :-     unification.unify([?ctx1,?alloc1],[?ctx2,?alloc2]).
```
(By the way, I'm also not sure why the rule lists `56s`, but the relation overall lists `70s`, even though this is the only rule in the relation.)

There's no reason for me to pack this data into records in the first place, except that `eqrel` requires it. So I'm wondering if it's at all technically feasible that `eqrel` could *not* require it, and instead I could provide a "grouping" of the variables or something like that:
```
.decl eq(x: number, y: number, x2: number, y2: number) eqrel ((x, y), (x2, y2))
```

**Comment by b-scholz** [comment]
That is a very interesting observation. For `eqrel`, you require an encoding, and records indeed might not be the fastest. 

Could you find some semantic encoding for (x,y) (like horner scheme, i.e., first few bits are x and second few bits are y)?

**Comment by langston-barrett** [comment]
> Could you find some semantic encoding for (x,y) (like horner scheme, i.e., first few bits are x and second few bits are y)?

In a way, the records provide such an encoding via the pointer into the record table. I've ended up doing this:
```
  .decl pack(?aCtx: Context, ?alloc: Allocation, ?awc: AllocWithContext)
```
and then using it like so where I need to join with `unify`: 
```
    pack(?aCtx, ?alloc, ?packed),
    unify(?packed, ?packedNew),
    pack(?newCtx, ?newAlloc, ?packedNew),
```
This way, the join with unify can happen on an index. However, it's still not optimal: I have to construct `pack`, and every time I want to join with `unify` I have these two extra joins/loops.

**Comment by b-scholz** [comment]
By enabling 64bit in souffle, you could encode x,y as 32bit numbers in a single 64bit number. 

With such an encoding, you won't have a lookup. For the encoding, a few bit-wise operations (and / shift) are necessary for retrieving the two numbers and packing the numbers. Have you tried this?

**Comment by langston-barrett** [comment]
> Have you tried this?

I haven't tried this, in my actual program the components of the record are subtypes of `symbol`. I could maybe try this with `to_number`/`to_string`!

**Comment by langston-barrett** [comment]
I'm probably playing with fire here, but I've attempted to use `as` to invert `ord`. Here's what I've got so far, where the types like `Allocation`, `Context`, etc. come from my real program:
```
.type Allocation <: symbol
.type Instruction <: symbol
.type ContextItem = Instruction | symbol
.type Context = [
  head : ContextItem,
  tail : Context
]
.decl allocation(alloc: Allocation)
.decl context(ctx: Context)
.decl test(ctx1: Context, alloc1: Allocation, ctx2: Context, alloc2: Allocation)

.decl umask(un: unsigned)
umask(0x00000000FFFFFFFF).

.decl mask(n: number)
mask(as(n, number)) :- umask(n).

// PACK: (Context, Allocation) -> Word64
#define PACK(aCtx, alloc, packed) \
  packed = (ord(aCtx) bshl 32) bor ord(alloc)

// UNPACK: Word64 -> (Context, Allocation)
#define UNPACK(aCtx, alloc, packed) \
  mask(m), \
  aCtx = as((packed bshr 32) band m, Context), \
  alloc = as(packed band m, Allocation)

allocation("alloc").
allocation("alloc2").
context(nil).
context(["foo", nil]).

test(ctx1, alloc1, ctx2, alloc2) :-
  allocation(alloc1),
  context(ctx1),
  PACK(ctx1, alloc1, x),
  UNPACK(ctx2, alloc2, x).

.output test(IO=stdout)
```
The output looks good:
```
test
===============
nil	alloc	nil	alloc
nil	alloc2	nil	alloc2
[foo, nil]	alloc	[foo, nil]	alloc
[foo, nil]	alloc2	[foo, nil]	alloc2
===============
```
But when I integrate it into my full analysis I see segfaults. So I must be misusing it somewhere...

**Comment by b-scholz** [comment]
I think there is somewhere an integer overflow/underflow. Can you test it with pairs of numbers first (rather than ord-numbers)? 
Make sure that the numbers are sufficiently large.

**Comment by thinkmoore** [comment]
I notice this also calls `ord`/`as` on a record, could that be a potential issue?

**Comment by langston-barrett** [comment]
> I think there is somewhere an integer overflow/underflow. Can you test it with pairs of numbers first (rather than ord-numbers)?

Certainly if you use `0xFFFFFFFFFFFFFFFF` in place of both `ord(alloc)` and `ord(aCtx)`, then `UNPACK` will give you back `0x00000000FFFFFFFF` for both. So the scheme only works assuming that `ord` gives back integers in the [0, 2^32-1] range. But I figured that would always be true, that Souffle would assign `ord` to each record/string/whatever in order and that my program doesn't have 32 bits worth of entities.

> I notice this also calls ord/as on a record, could that be a potential issue?

Seems like it works on simple examples:
```
.type Context = [
  head : symbol,
  tail : Context
]
.decl context(ctx: Context)
context(nil).
context(["foo", nil]).
context(["bar", nil]).
context(["baz", ["foo", nil]]).

.decl test(ctx1: Context, n: number, ctx2: Context)
test(ctx1, n, as(n, Context)) :-
  context(ctx1),
  n = ord(ctx1).

.output test(IO=stdout)
```
```
---------------
test
===============
nil	0	nil
[foo, nil]	1	[foo, nil]
[bar, nil]	2	[bar, nil]
[baz, [foo, nil]]	3	[baz, [foo, nil]]
===============
```
```
$ souffle --version
Souffle: 2.0.2-1428-g2d46eb83(64bit Domains)
```

**Comment by langston-barrett** [comment]
Arg, apologies - looks like the script I was using to test my full program was using a non-64-bit-enabled Souffle. For 64-bit-enabled Souffle, this packing/unpacking scheme seems to be working well! Thanks for the suggestion @b-scholz!

It's worth noting that this scheme is fairly limited - It'll only work for packing *pairs* of things into an `eqrel`, not, e.g., 3-tuples. But it works for me, so I'll close the ticket for now.
