### ISSUE TITLE
Souffle failed to build from -git package from aur

### ISSUE THREAD

**Issue by hXtreme** [souffle-lang/souffle#1964]
**[souffle 2.0.2-1428-g2d46eb836] testsuite: 9 10 11 12 37 38 59 60 67 68 95 96 105 106 107 108 111 112 113 114 115 116 119 120 121 122 127 128 129 130 131 132 133 134 135 136 139 140 145 146 159 160 163 164 169 170 171 172 173 174 175 176 177 178 181 182 205 206 207 208 209 210 211 212 223 224 225 226 227 228 229 230 233 234 237 238 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290 295 296 297 298 299 300 305 306 307 308 309 310 311 312 313 314 315 316 317 318 321 322 323 324 325 326 331 332 335 336 337 338 359 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379 380 381 382 383 384 385 386 387 388 391 392 397 398 407 408 409 410 415 416 417 418 419 420 439 440 449 450 451 452 453 454 469 470 473 474 477 478 479 480 481 482 483 484 485 486 487 488 489 490 491 492 493 494 495 496 499 500 501 502 503 504 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525 526 527 528 529 530 531 532 535 536 537 538 539 540 541 542 543 544 545 546 547 548 553 554 555 556 557 558 559 560 561 562 565 566 567 568 573 574 575 576 583 584 585 586 591 592 593 594 595 596 597 598 599 600 603 604 605 606 607 608 609 610 611 612 613 614 615 616 617 618 621 622 623 624 631 632 633 634 637 638 639 640 641 642 643 644 645 646 647 648 649 650 651 652 653 654 655 656 657 658 661 662 663 664 665 666 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683 684 685 686 687 688 689 690 691 692 697 698 699 700 701 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 719 720 721 722 723 724 727 728 729 730 731 732 733 734 735 736 737 738 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773 774 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791 792 793 794 795 796 797 798 799 800 801 802 805 806 807 808 809 810 811 812 failed**

When building the -git package from AUR I got this error, which asked me to open an issue here.

testsuite.log: http://sprunge.us/9HKpKA
testsuite.dir: https://drive.google.com/file/d/1qi75tf9Rn3KhXFQBrb7alKLMIy4CqYmh/view?usp=drivesdk

Let me know if you need any further information.

**Comment by b-scholz** [comment]
Your installation core dumps for each test file. Can you tell us more about your system and installation environment?

**Comment by hXtreme** [comment]
I think that the core dumps may be in the testsuite.dir that was attached above (otherwise I don't know where to look for that)

Machine Info:
```
                   -`                    hpar@tsukihi
                  .o+`                   ------------
                 `ooo/                   OS: Arch Linux x86_64
                `+oooo:                  Host: H310M S2 2.0
               `+oooooo:                 Kernel: 5.12.14-arch1-1
               -+oooooo+:                Uptime: 2 hours, 19 mins
             `/:-:++oooo+:               Packages: 1585 (pacman)
            `/++++/+++++++:              Shell: zsh 5.8
           `/++++++++++++++:             Resolution: 1680x1050
          `/+++ooooooooooooo/`           WM: dwm
         ./ooosssso++osssssso+`          Theme: Adwaita [GTK2/3]
        .oossssso-````/ossssss+`         Icons: Adwaita [GTK2/3]
       -osssssso.      :ssssssso.        Terminal: st
      :osssssss/        osssso+++.       Terminal Font: Hack Nerd Font Mono
     /ossssssss/        +ssssooo/-       CPU: Intel i5-9400F (6) @ 4.100GHz
   `/ossssso+/:-        -:/+osssso+-     GPU: NVIDIA GeForce GTX 1070
  `+sso+:-`                 `.-/+oso:    Memory: 10341MiB / 15950MiB
 `++:.                           `-/+/
 .`                                 `/


```

Package Info:
```
Repository      : aur
Name            : souffle-git
Keywords        : None
Version         : r3910.7ce84469-2
Description     : Soufflé is a translator of declarative Datalog programs into the C++ language
URL             : https://github.com/souffle-lang/souffle
AUR URL         : https://aur.archlinux.org/packages/souffle-git
Groups          : None
Licenses        : UPL
Provides        : souffle-git
Depends On      : sqlite  python  zlib
Make Deps       : git  autoconf  automake  bison  doxygen  flex  sqlite
                  libtool  jdk8-openjdk  pkg-config  python  zlib
Check Deps      : None
Optional Deps   : None
Conflicts With  : souffle-git
Maintainer      : lllf
Votes           : 2
Popularity      : 0.000000
First Submitted : Wed 31 May 2017 10:49:44 AM EDT
Last Modified   : Wed 17 Apr 2019 08:20:56 PM EDT
Out-of-date     : No
```

Versions of listed dependency:
```
Name            : python
Version         : 3.9.5-3

Name            : sqlite
Version         : 3.36.0-1

Name            : zlib
Version         : 1:1.2.11-4
```

**Comment by b-scholz** [comment]
Perhaps you start from scratch building souffle and configure souffle in debug mode. 
```
make distclean
sh bootstrap
./configure --enable-debug
TESTSUITEFLAGS=-j8 make -j8 check 
```

Run a small example with the `gdb`/`lldb` and let us know where it is crashing.

**Comment by b-scholz** [comment]
It looks to me that you have a configuration / Linux environment problem (most likely it is not a Souffle issue).

**Comment by b-scholz** [comment]
Could you fix this? Can we close the issue?

**Comment by hXtreme** [comment]
Please do.

Thanks,
Harsh
