### ISSUE TITLE
Headers support for output files

### ISSUE THREAD

**Issue by akritid** [souffle-lang/souffle#1969]
It would be very convenient if the IO system supported an option for headers in output files.

**Comment by b-scholz** [comment]
There is an option in the output directive. For example, you can write
```
.decl A(mynum:number, mysym:symbol)
A(1,"x")
.output(headers=true)
```
which will create a header. 

This is also documented here:
https://souffle-lang.github.io/io
but not very well. 

Would you like to improve the documentation related to headers ?

**Comment by akritid** [comment]
Great! I should try to make a pass since I'm playing with it.

**Comment by b-scholz** [comment]
I have reorganised the documentation. The new page is
https://souffle-lang.github.io/directives

**Comment by b-scholz** [comment]
I moved this issue to the documentation repo.

https://github.com/souffle-lang/souffle-lang.github.io
