### ISSUE TITLE
Strange profiling data: Time for relation greater than sum of time for rules

### ISSUE THREAD

**Issue by langston-barrett** [souffle-lang/souffle#1972]
I posted on Zulip about this since I wasn't sure if it was a bug or I'm misinterpreting this, but I didn't hear back, so apologies for the spam if this is not a bug! When profiling my program, I've gotten into a strange situation where all of the rules for a given relation seem to contribute negligible runtime, but the relation itself is the most expensive relation in my program. In particular, the sum of the time taken by the rules does not equal (and isn't even close to) the time taken by the relation. Any ideas why this might be the case? For what it's worth, the relation in question is backed by an eqrel.

Here's some example data:
```
> rel R308
  ----- Rules of a Relation -----
   TOT_T  NREC_T   REC_T  TUPLES      ID NAME

     57s   .000s   .761s   6.27M    R308 unification.unify
 ---------------------------------------------------------
   .333s   .000s   .333s   6.17M  C308.4 unification.unify
   .104s   .000s   .104s     567  C308.2 unification.unify
   .045s   .000s   .045s   68.6K  C308.3 unification.unify
   .042s   .000s   .042s   1.93K C308.10 unification.unify
   .028s   .000s   .028s      42  C308.5 unification.unify
   .019s   .000s   .019s     320  C308.1 unification.unify
   .017s   .000s   .017s   25.9K C308.11 unification.unify
   .009s   .000s   .009s      16  C308.9 unification.unify
   .004s   .000s   .004s     581  C308.8 unification.unify
   .001s   .000s   .001s      33  C308.7 unification.unify
   .001s   .000s   .001s       0  C308.6 unification.unify
   .000s   .000s   .000s     429  N308.1 unification.unify
   .000s   .000s   .000s     299  N308.2 unification.unify
```
The `TOT_T` column indicates that this relation took 57s to compute, but the sum of the times for each rule looks to be <1s. I would expect that the sum of the `TOT_T` for each rule would be equal to the `TOT_T` for the relation.

**Comment by XiaowenHu96** [comment]
Hi, sorry for the late reply. Are you using interpreter or synthesizer for the execution?  And do they give the same result?

**Comment by langston-barrett** [comment]
> Are you using interpreter or synthesizer for the execution? And do they give the same result?

Thanks for the response! I've been using the synthesizer. I'll try it with the interpreter and see what happens.

**Comment by langston-barrett** [comment]
Here are results from the interpreter on a smaller input. It looks like the issue remains:
```
> rel R326 
  ----- Rules of a Relation -----
   TOT_T  NREC_T   REC_T  TUPLES      ID NAME

   .598s   .000s   .420s   31.5K    R326 unification.unify
 ---------------------------------------------------------
   .238s   .000s   .238s   19.2K C326.11 unification.unify
   .055s   .000s   .055s   6.16K C326.10 unification.unify
   .017s   .000s   .017s      44  C326.9 unification.unify
   .010s   .000s   .010s     217  C326.7 unification.unify
   .009s   .000s   .009s     742  C326.5 unification.unify
   .008s   .000s   .008s     428  C326.8 unification.unify
   .005s   .000s   .005s   3.42K  C326.6 unification.unify
   .004s   .000s   .004s     731  C326.3 unification.unify
   .003s   .000s   .003s      14  C326.4 unification.unify
   .000s   .000s   .000s       0  C326.1 unification.unify
   .000s   .000s   .000s       0  C326.2 unification.unify
   .000s   .000s   .000s     368  N326.2 unification.unify
   .000s   .000s   .000s     166  N326.1 unification.unify

Src locator: /x/llvm/PointerAnalysis/datalog/points-to/unification.dl [251:9-251:14]
```
I'll try to make a small program that uses `eqrel` and see if that is related/has the same issue.

**Comment by langston-barrett** [comment]
Yeah, it looks like this small sample program demonstrates the issue:
```
.decl test(x: number, y: number) eqrel
test(0, 0).
test(x + 1, x + 1) :- test(x, _), x < 10000.
.output test
```
```
> rel R1 
  ----- Rules of a Relation -----
   TOT_T  NREC_T   REC_T  TUPLES      ID NAME

     25s   .000s   .247s   10.0K      R1 test
 ---------------------------------------------------------
   .049s   .000s   .049s   10.0K    C1.1 test
   .000s   .000s   .000s       1    N1.1 test
```
Though interestingly, it *also* seems to happen when I remove the `eqrel`, it's just less pronounced:
```
> rel R1 
  ----- Rules of a Relation -----
   TOT_T  NREC_T   REC_T  TUPLES      ID NAME

   .155s   .000s   .125s   10.0K      R1 test
 ---------------------------------------------------------
   .024s   .000s   .024s   10.0K    C1.1 test
   .000s   .000s   .000s       1    N1.1 test
```

**Comment by XiaowenHu96** [comment]
For the `eqrel` version, if you look at the profiling info on relation-level:
```
Slowest relations to fully evaluate
 ----- Relation Table -----
   TOT_T  NREC_T   REC_T  COPY_T  LOAD_T  SAVE_T  TUPLES   READS   TUP/s    ID NAME

     22s   .000s   .224s     22s   .000s   .006s   10.0K       0     440    R1 test

```
You can see 22s is spent in COPY_T. This is the time spent merging newly found facts at the end of each fixpoint iteration. 
Looking at the RAM representation of the example you provided, it is this code at the end of LOOP. 
```
.....
   QUERY
    FOR t0 IN @new_test
     INSERT (t0.0, t0.1) INTO test
   END QUERY
   SWAP (@delta_test, @new_test)
   CLEAR @new_test
END_LOOP
```

**Comment by langston-barrett** [comment]
@XiaowenHu96 Thanks for that explanation! So it sounds like I should expect that
```
TOT_T = COPY_T + LOAD_T + SAVE_T + NREC_T + REC_T
      = COPY_T + LOAD_T + SAVE_T + \sum_{rules} (NREC_T + REC_T)
```
where `\sum_{rules}` is the sum over each rule that contributes to the relation. Does that sound right?

Looking at more realistic data from my actual program:
```
> rel
 ----- Relation Table -----
   TOT_T  NREC_T   REC_T  COPY_T  LOAD_T  SAVE_T  TUPLES   READS   TUP/s    ID NAME

   .558s   .000s   .396s   .160s   .000s   .000s   31.5K    398K   56.6K  R326 unification.unify

> rel R326 
  ----- Rules of a Relation -----
   TOT_T  NREC_T   REC_T  TUPLES      ID NAME

   .558s   .000s   .396s   31.5K    R326 unification.unify
 ---------------------------------------------------------
   .229s   .000s   .229s   19.2K C326.11 unification.unify
   .050s   .000s   .050s   6.16K C326.10 unification.unify
   .015s   .000s   .015s      44  C326.9 unification.unify
   .009s   .000s   .009s     217  C326.7 unification.unify
   .008s   .000s   .008s     742  C326.5 unification.unify
   .007s   .000s   .007s     428  C326.8 unification.unify
   .004s   .000s   .004s   3.42K  C326.6 unification.unify
   .004s   .000s   .004s     731  C326.3 unification.unify
   .003s   .000s   .003s      14  C326.4 unification.unify
   .000s   .000s   .000s       0  C326.1 unification.unify
   .000s   .000s   .000s       0  C326.2 unification.unify
   .000s   .000s   .000s     368  N326.2 unification.unify
   .000s   .000s   .000s     166  N326.1 unification.unify
```
So we should have:
```
  TOT_T = COPY_T + LOAD_T + SAVE_T + \sum_{rules} (NREC_T + REC_T)
        = 0.160 + \sum_{rules} REC_T     [Cancelling out zero terms]
        = 0.160 + 0.229 + 0.050 + 0.015 + 0.009 + 0.008 + 0.007 + 0.004 + 0.004 + 0.003
        = 0.489
```
But that's not right! We can see above that `TOT_T = .558s`. In particular, it looks like the sum reported for `REC_T` (`.396`) isn't actually the sum of the times for `REC_T` for each of the rules (`0.229 + 0.050 + 0.015 + 0.009 + 0.008 + 0.007 + 0.004 + 0.004 + 0.003 = 0.329`).

There must be some problem in (1) the equations I wrote above (i.e., my understanding of how to read the profiler output), (2) my arithmetic, or (3) the profiling data. I'm not sure which it is, so I'd very much appreciate any help you can offer!

**Comment by langston-barrett** [comment]
@XiaowenHu96 Any thoughts on this? It's a bit of a blocker for me, I'm trying to optimize this program but can't make sense of the profiling data.

**Comment by XiaowenHu96** [comment]
I'm pretty sure that REC_T of a relation and its rules are measured separately, that is REC_T of a relation is not simply \sum_{rules}{REC_T}. (resp. NREC_T)
But the exact detail of the implementation is out of my territory. I'll try my best.

Again, for the eqrel example, let's look at the generated C++ code, in particular, the part that corresponding to the big fixpoint iteration (A `for(;;)` while loop in C++). 
```C++
for (;;) {
  {
    Logger logger(
        R"_(@t-recursive-relation;test;/home/xihu5895/souffle/1972/prog.dl [1:7-1:11];)_",
        iter, [&]() { return rel_3_new_test->size(); });
    signalHandler->setMsg(R"_(test((x+1),(x+1)) :- 
   test(x,_),
   x < 10000.
in file /home/xihu5895/souffle/1972/prog.dl [3:1-3:45])_");
    {
      Logger logger(
          R"_(@t-recursive-rule;test;0;/home/xihu5895/souffle/1972/prog.dl [3:1-3:45];test((x+1),(x+1)) :- \n   test(x,_),\n   x < 10000.;)_",
          iter, [&]() { return rel_3_new_test->size(); });
      if (!(rel_2_delta_test->empty())) {
        [&]() {
          CREATE_OP_CONTEXT(rel_3_new_test_op_ctxt,
                            rel_3_new_test->createContext());
          CREATE_OP_CONTEXT(rel_1_test_op_ctxt, rel_1_test->createContext());
          CREATE_OP_CONTEXT(rel_2_delta_test_op_ctxt,
                            rel_2_delta_test->createContext());
          for (const auto &env0 : *rel_2_delta_test) {
            if ((ramBitCast<RamSigned>(env0[0]) <
                 ramBitCast<RamSigned>(RamSigned(10000))) &&
                !(rel_1_test->contains(
                    Tuple<RamDomain, 2>{
                        {ramBitCast((ramBitCast<RamSigned>(env0[0]) +
                                     ramBitCast<RamSigned>(RamSigned(1)))),
                         ramBitCast((ramBitCast<RamSigned>(env0[0]) +
                                     ramBitCast<RamSigned>(RamSigned(1))))}},
                    READ_OP_CONTEXT(rel_1_test_op_ctxt)))) {
              Tuple<RamDomain, 2> tuple{
                  {ramBitCast((ramBitCast<RamSigned>(env0[0]) +
                               ramBitCast<RamSigned>(RamSigned(1)))),
                   ramBitCast((ramBitCast<RamSigned>(env0[0]) +
                               ramBitCast<RamSigned>(RamSigned(1))))}};
              rel_3_new_test->insert(tuple,
                                     READ_OP_CONTEXT(rel_3_new_test_op_ctxt));
            }
          }
        }();
      }
    }
  }
  if (rel_3_new_test->empty())
    break;
  {
    Logger logger(
        R"_(@c-recursive-relation;test;/home/xihu5895/souffle/1972/prog.dl [1:7-1:11];)_",
        iter, [&]() { return rel_3_new_test->size(); });
    rel_3_new_test->extend(*rel_1_test);
    [&]() {
      CREATE_OP_CONTEXT(rel_3_new_test_op_ctxt,
                        rel_3_new_test->createContext());
      CREATE_OP_CONTEXT(rel_1_test_op_ctxt, rel_1_test->createContext());
      for (const auto &env0 : *rel_3_new_test) {
        Tuple<RamDomain, 2> tuple{{ramBitCast(env0[0]), ramBitCast(env0[1])}};
        rel_1_test->insert(tuple, READ_OP_CONTEXT(rel_1_test_op_ctxt));
      }
    }();
    std::swap(rel_2_delta_test, rel_3_new_test);
    rel_3_new_test->purge();
  }
  iter++;
}

```
The code is quite a mess, but we only focus on the control flow and the log objects.
There are three logs happening here.
1. Once the iteration starts, a log that records the REC_T relation time starts (denoted by the `@t-recursive-relation` prefix), let's call it `@t-recusive-relation log`. 
2. Then immediately, another log that records the REC_T *rule* time starts, let's call it `@t-recursive-rule log`. 
3. After that, the souffle computes the tuples at that fixpoint iteration. 
4. Once the computation is finished and before checking the exit condition, `@t-recursive-rule log` is stopped. 
5. We check the exit condition, if we haven't reached the fixpoint, we start copying the newly generated result. But before the actual work, we start another log `@c-recursive-relation` to measure the time spend in COPY_T.
6. After the copy is done,  `@c-recursive-relation log` is stopped.
7. Before the next iteration starts, `@t-recusive-relation log` is stopped.

Therefore, the `@t-recusive-relation log` is at least `@c-recursive-relation log` + `@t-recursive-rule log` + **the overhead of creating / stopping those logs**.

Again, I'm not at all familiar with the codebase related to the profiler, I'm just backward analyzing the output from the generated C++ code. You can tell each log's rule by looking at its prefix, e.g `@t-recursive-relation`. `include/souffle/profile/EventProcessor.h`  tells me
what each prefix means.

**Comment by b-scholz** [comment]
Can you try running this branch 

https://github.com/b-scholz/souffle/tree/profiler

of soufflé and add the following pragma to your code while profiling:

.pragma “no-rule-profiling”
 
It will disable the query profiling which distorts the profiling data of relations most likely (and other issues such as clearing relations etc.). It may reveal a better performance measurement of the whole program.

**Comment by langston-barrett** [comment]
Something has changed; I've not seen this confusing behavior in a while.

**Comment by langston-barrett** [comment]
In an ironic twist, I just started seeing this issue again today. Will try cherry-picking that commit onto HEAD and looking at the profiles.

**Comment by langston-barrett** [comment]
The thing that's going on here is just that `COPY_T` is dominating the runtime because MERGE-EXTEND is slow. See for example #2231
