### ISSUE TITLE
`std::sort` called with a comparator that is not a strict weak ordering 

### ISSUE THREAD

**Issue by quentin** [souffle-lang/souffle#1978]
Hi,  
While running Souffle built with a debug version of `std::` an assertion was raised detecting that this comparator does not guarantee strict weak ordering:

https://github.com/souffle-lang/souffle/blob/cda3de9b34aab07da19ed9ee21a5c88609db22b7/src/ram/transform/MakeIndex.cpp#L259-L262

The last statement of the comparator at line 259 uses `<=` but should use `<` to respect strict weak ordering requirements of `std::sort` comparator.

**Comment by b-scholz** [comment]
Yes, indeed. Well spotted! 

Would you like to fix this and make a PR. It should not take too long.
