### ISSUE TITLE
Represent complements in multi-head rules.

### ISSUE THREAD

**Issue by markww** [souffle-lang/souffle#1979]
Currently, Souffle has a syntax for multi-head rules like follows:

```
A(x), B(x) :- C(x).
```

Which is syntactic sugar for:

```
A(x) :- C(x).
B(x) :- C(x).
```

It would be really nice to have a concise syntax for a rule that says "if C(x), put x in A; if not, put x in B". Here's some candidate syntax that might work:

```
A(x), !B(x) :- C(x).
```

Which would be syntactic sugar for:

```
A(x) :- C(x).
B(x) :- !(C(x)).
```

The above is nice for writing tests in Datalog, a circumstance in which you want to bin things into a "passes" or "fails" bucket dependening upon how a rule evaluates, but really don't want to have any `x` just not show up in the output.

**Comment by b-scholz** [comment]
The second rule is not grounded, i.e., 
```
B(x) :- !C(x). 
```
has a negation `!C(x)` in the body whose variable x cannot draw a value from a positive predicate.

**Comment by markww** [comment]
That's a good point. I also found another way to do what I was doing with preprocessor macros that works quite well; I imagine others might as well. You can close this as unnecessary if you'd like.

**Comment by b-scholz** [comment]
Great - thanks!
