### ISSUE TITLE
Document what `SOUFFLE_FAST_RELEASE` and `SOUFFLE_FAST_DEBUG` does

### ISSUE THREAD

**Issue by lyxell** [souffle-lang/souffle#1992]
There's two options in the `CMakeLists.txt` file called `SOUFFLE_FAST_RELEASE` and `SOUFFLE_FAST_DEBUG`.
Right now their CMake descriptions are `Enable/Disable 'fast release' mode` and `Enable/Disable ON 'fast debug' mode` respectively.

Maybe it would be possible to update the descriptions of these options to make their function obvious when reading their descriptions through a CMake user interface?

**Comment by b-scholz** [comment]
We describe the new build here:

https://souffle-lang.github.io/build

These specific flags are related to how the project is built:

SOUFFLE_FAST_RELEASE: changes the compiler flag from -O2 to -O3
SOUFFLE_FAST_DEBUG: changes the compiler flag from -g to "-O0 -g3" 

Would you like to reflect this in the documentation? That would be appreciated.

**Comment by lyxell** [comment]
> SOUFFLE_FAST_DEBUG: changes the compiler flag from -g to "-O0 -g3"

Specifying no optimization implies `-O0`, both for `clang` and `gcc`: https://gcc.gnu.org/onlinedocs/gnat_ugn/Optimization-Levels.html

So the only difference this option makes is adding `-g3`. This makes the name `SOUFFLE_FAST_DEBUG` a bit misleading I think.

> SOUFFLE_FAST_RELEASE: changes the compiler flag from -O2 to -O3

`-O3` is already the default for `clang` and `gcc`: https://github.com/Kitware/CMake/blob/6efdd7e81480bf48fa2daeb292a12c77e23d3a17/Modules/Compiler/GNU.cmake#L58

What was the original intention of adding these options?

**Comment by b-scholz** [comment]
These options were introduced by Tom when he started the initial CMake port. 
I haven't had reflected on the necessity of these options yet. 

Thinking about it - we might be better off without these options - instead of documenting them.

**Comment by b-scholz** [comment]
The fewer options we have, the better it will be in terms of configuration management.
