### ISSUE TITLE
Use of interpreter through C++ interface

### ISSUE THREAD

**Issue by lyxell** [souffle-lang/souffle#2030]
Currently, only Soufflé programs created by the synthesizer are available through the C++ interface. It would be useful if the C++ interface also could be used with the interpreter. Would this be technically possible without changing too much of the implementation of the interpreter?

In my current use case I have to fork Soufflé to change the header file of the interpreter to make the datastructures public, but it is still a pain to extract the relation data after the interpreter has ran.

**Comment by b-scholz** [comment]
I don't fully understand the use case, however, this is already done. The interpreter uses the C++ interface to expose its relations to the provenance interface. The provenance system does not know whether the data was either produced by the interpreter or the compiler. 

Have a look in `main.cpp`. There you will find the line:
```
interpreter::ProgInterface interface(*interpreter);
``` 
which wraps up the interpreter in a C++ interface.

I have seen that DDISASM uses the interpreter now for development purposes:
https://github.com/GrammaTech/ddisasm

I hope that helps.

**Comment by lyxell** [comment]
> I don't fully understand the use case

Yeah, I should have explained this better. In the past, I've mostly felt a need for this for development purposes. When prototyping a complex application where a lot of Datalog is mixed with C++ it is a pain to have to recompile everything and wait (sometime minutes depending on the Datalog program size) everytime one makes a small change to the Datalog code.

Another use case would be if you want to allow the users of your C++ application to write custom queries that is executed on your data, but you don't want your application to have a C++ compiler as a runtime dependency.

I'll take a look at how the provenance system and DDISASM handles this. Thanks Bernhard!

**Comment by b-scholz** [comment]
By the way - the provenance system has a simple query processor as well. Perhaps that helps as well.
