### ISSUE TITLE
Error: Unable to deduce type for variable

### ISSUE THREAD

**Issue by lyj18688610256** [souffle-lang/souffle#2056]
![image](https://user-images.githubusercontent.com/60656299/132125762-c56c21c2-0aa6-4b99-b696-264be380c007.png)
![image](https://user-images.githubusercontent.com/60656299/132125782-2929f6c1-e741-4552-8a7f-83ca67cb8117.png)
![image](https://user-images.githubusercontent.com/60656299/132125801-f9c3ade1-9590-46e1-8b3b-5d401a54ef49.png)
what's the problem may be?

**Comment by b-scholz** [comment]
Can you provide the datalog file so that we can investigate?

**Comment by b-scholz** [comment]
Also can you let me know which version of Souffle you are using?

**Comment by lyj18688610256** [comment]
this is a datalog file that doop generate,I use souffle 2.0.2,this is the newest souffle version that doop supports
[gen_5991972833572585107.txt](https://github.com/souffle-lang/souffle/files/7120016/gen_5991972833572585107.txt)

**Comment by lyj18688610256** [comment]
![image](https://user-images.githubusercontent.com/60656299/132311104-b76fb926-fb93-451d-90fd-7ea1f0b1c092.png)

**Comment by lyj18688610256** [comment]
![image](https://user-images.githubusercontent.com/60656299/132312018-96a17b84-ffeb-4032-86a8-bcda59c9b45c.png)
[gen_3499621935191682446.txt](https://github.com/souffle-lang/souffle/files/7120104/gen_3499621935191682446.txt)
[analysis.txt](https://github.com/souffle-lang/souffle/files/7120110/analysis.txt)

Hi,the analysis.txt is the source code file,but because I use doop frame,So though I write a few lines of words,but there are many nested code in doop,then doop generate complete datalog rules in gen_3499621935191682446.txt,the image shows the error it occurs.
Because the doop now only support souffle 2.0.2 and 1.5.1.Now I use souffle 2.0.2

**Comment by lyj18688610256** [comment]
In the analysis.txt,my target is to get variable length of Context and HeapContext,because it depends on the program flow,I can't specify fixed length
In the doop frame work,for example,it defines like this:
 .type Context  = [ value1:Value, value2:Value ]
 .type HContext = [ value:Value ]
 but it can't match my demands,so I changed it 
  .type Context = [head:Context, tail:Value]
  .type HContext = [ head:HContext, tail:Value ]
  then it occurs above errors
  
 Below is the doop frame orginally defines
![image](https://user-images.githubusercontent.com/60656299/132314329-d22b73ca-3e30-42d0-a642-e866b6562797.png)

below is what I defines
![image](https://user-images.githubusercontent.com/60656299/132314443-5101dc11-1ce1-4c3c-8003-df4fa295f623.png)

**Comment by lyj18688610256** [comment]
I hope I have explictly show my problem,or I have to provide other material?

**Comment by b-scholz** [comment]
Can you switch on the flag `--legacy` or run DOOP with an older version of souffle.

**Comment by lyj18688610256** [comment]
I have tested souffle 1.5.1,but It occurs the same error,--legacy option seems not work

**Comment by lyj18688610256** [comment]
the errors seems I can't deduce the type,but I specify its element is Value,it's explictly

 .type Context = [head:Context, tail:Value]
 .type HContext = [ head:HContext, tail:Value ]

**Comment by lyj18688610256** [comment]
I want to ask another problem related to this problem
if I have a recrusive record like this :  List( [[[[[[nil,2],3],4],5],6],7])
how I can get a record List2( [[[[[nil,3],4],5],6],7]  ) convient?Certainly List is a unknow list,you don't know how many elements in the List

**Comment by b-scholz** [comment]
Can you use the latest release? It seems to work.

**Comment by b-scholz** [comment]
2.1 or the HEAD of souffle.

**Comment by lyj18688610256** [comment]
Ok,thank you,I'm testing

**Comment by b-scholz** [comment]
No - it is not working.

**Comment by lyj18688610256** [comment]
I have tested the souffle2.1,but it seems there are some bugs not compatible with souffle2.1

**Comment by b-scholz** [comment]
I would not say it is a bug. I checked the line more closely - there is an ungrounded variable ?calleeCtx.

**Comment by lyj18688610256** [comment]
Maybe I can abstract this problem(souffle with doop) to a pure souffle problem,then we devote to deal with souffle,let me have a think

**Comment by lyj18688610256** [comment]
you say it is ungrounded variable,it means it is not initialized?

**Comment by lyj18688610256** [comment]
![image](https://user-images.githubusercontent.com/60656299/132346370-28f72a7a-477a-40aa-b8ad-608999412cbd.png)
it is indeed that there is a logic error,ie,
In fact here I want to acquire the last (n-1) elements of hctx(if hctx has n elements) ,and then combines with value,so here is not 
?calleeCtx = [?hctx,?value],

it should be ?calleeCtx = [?hctx_sub(the last (n-1) elements of hctx),?value],
how I can achieve it?
it is just described in the below issue
https://github.com/souffle-lang/souffle/issues/2056#issuecomment-914187951

**Comment by b-scholz** [comment]
Variables need to show up in a positive predicate in the body of a rule. The only exception is for records that can be initialized transitively via the record constructor.

**Comment by lyj18688610256** [comment]
Not yet,I need to write some logic to get the last n-1 elements of a list and combine them to form a new list

**Comment by b-scholz** [comment]
You have some type issue with your rules. You have some ill-formed recursive list context:
```
Clause: mainAnalysis.configuration.ContextResponse(?callerCtx,?hctx,?invo,?value,?tomethod,[?hctx,?value]) :-
   mainAnalysis.configuration.ContextRequest(?callerCtx,?hctx,?invo,?value,?tomethod,_).
Problem:
{
    var(?callerCtx) &lt: mainAnalysis.configuration.Context,
    var(?hctx) &lt: mainAnalysis.configuration.HContext,
    var(?invo) &lt: __symbolConstant,
    var(?value) &lt: __symbolConstant,
    var(?tomethod) &lt: __symbolConstant,
    var([?hctx,?value]) &lt: mainAnalysis.configuration.Context,
    var(?hctx) &lt: var([?hctx,?value])::0,
    var(?value) &lt: var([?hctx,?value])::1,
    var(?callerCtx) &lt: mainAnalysis.configuration.Context,
    var(?hctx) &lt: mainAnalysis.configuration.HContext,
    var(?invo) &lt: MethodInvocation,
    var(?value) &lt: Value,
    var(?tomethod) &lt: Method,
    var(_) &lt: number
}
Solution:
{var(?callerCtx)->{mainAnalysis.configuration.Context},var(?hctx)->{},var(?invo)->{MethodInvocation},var(?value)->{Value},var(?tomethod)->{Method},var([?hctx,?value])->{mainAnalysis.configuration.Context},var(_)->{number}}
```

**Comment by lyj18688610256** [comment]
Sorry,I just can't get the solution meaning,can you help me to explain it?

**Comment by b-scholz** [comment]
You have a type clash because in your relation declaration:
```
decl mainAnalysis.configuration.ContextResponse(?callerCtx:mainAnalysis.configuration.Context, ?hctx:mainAnalysis.configuration.HContext, ?invo:MethodInvocation, ?value:Value, ?method:Method, ?calleeCtx:mainAnalysis.configuration.Context)
```

The first and last contexts do not match. You use them synonymously.

**Comment by lyj18688610256** [comment]
you means that htcx and calleeCtx are not the same type?

**Comment by b-scholz** [comment]
You have following type/relation declarations: 
```
.type Value = symbol
.type mainAnalysis.configuration.Context = [head:mainAnalysis.configuration.Context, tail:Value]

.decl mainAnalysis.configuration.ContextResponse(?callerCtx:mainAnalysis.configuration.Context, ?hctx:mainAnalysis.configuration.HContext, ?invo:MethodInvocation, ?value:Value, ?method:Method, ?calleeCtx:mainAnalysis.configuration.Context)

.decl mainAnalysis.configuration.ContextRequest(?ctx:mainAnalysis.configuration.Context, ?hctx:mainAnalysis.configuration.HContext, ?invo:MethodInvocation, ?value:Value, ?method:Method, ?createCGE:number)

mainAnalysis.configuration.ContextResponse(?callerCtx,?hctx,?invo,?value,?tomethod,[?hctx,?value]) :-
   mainAnalysis.configuration.ContextRequest(?callerCtx,?hctx,?invo,?value,?tomethod,_).
```

You are mixing the heap context with the normal context. 

Can you see it?

**Comment by b-scholz** [comment]
Please ask the list questions in a separate issue. Other people might be interested in this topic outside the scope of DOOP.

**Comment by lyj18688610256** [comment]
> You have the following type/relation declarations:
> 
> ```
> .type Value = symbol
> .type mainAnalysis.configuration.Context = [head:mainAnalysis.configuration.Context, tail:Value]
> .type mainAnalysis.configuration.HContext = [head:mainAnalysis.configuration.HContext, tail:Value]
> 
> .decl mainAnalysis.configuration.ContextResponse(?callerCtx:mainAnalysis.configuration.Context, ?hctx:mainAnalysis.configuration.HContext, ?invo:MethodInvocation, ?value:Value, ?method:Method, ?calleeCtx:mainAnalysis.configuration.Context)
> 
> .decl mainAnalysis.configuration.ContextRequest(?ctx:mainAnalysis.configuration.Context, ?hctx:mainAnalysis.configuration.HContext, ?invo:MethodInvocation, ?value:Value, ?method:Method, ?createCGE:number)
> 
> mainAnalysis.configuration.ContextResponse(?callerCtx,?hctx,?invo,?value,?tomethod,[?hctx,?value]) :-
>    mainAnalysis.configuration.ContextRequest(?callerCtx,?hctx,?invo,?value,?tomethod,_).
> ```
> 
> You are mixing the heap context with the normal context in this rule.
> 
> Can you see it? I.e. the `hctx` in the predicate `mainAnalysis.configuration.ContextRequest` is of type `hctx:mainAnalysis.configuration.HContext`
> whereas the `hctx` in the head is of type
> `mainAnalysis.configuration.Context`

Yes,this is the main cause,but how to express what I want?
htcx (calleeCtx,callerCtx)has variable length,I have to define like this because only recrusive record in souffle can store variable length vars just like ArrayList in Java code
  .type Context = [head:Context, tail:Value]
  .type HContext = [ head:HContext, tail:Value ]
  If I define like this,it will occur the type mismatch
  Or if there are other ways to deal with this problem?
  I need to hctx and ctx has variable length and the same time they can transfer to each other

**Comment by b-scholz** [comment]
You need to say 
```
.type Context = HContext
```
otherwise you have type clash. Souffle has no structural equivalence for types like most other languages.

**Comment by lyj18688610256** [comment]
Ok,thank you very much for your patient answer

**Comment by b-scholz** [comment]
Ok - I thought we enabled equivalence types for Lists and ADTs but we did not. 

Again, this is not a Souffle issue; this is how you express types for your program. You use two different type names for the same type concept. It is wrong. 

No - you should replace all HContext with Context manually in the system. 

Basically, you want that both are the same so that you can mix them.

**Comment by lyj18688610256** [comment]
> Ok - I thought we enabled equivalence types for Lists and ADTs but we did not.
> 
> Again, this is not a Souffle issue; this is how you express types for your program. You use two different type names for the same type concept. It is wrong.
> 
> No - you should replace all HContext with Context manually in the system.
> 
> Basically, you want that both are the same so that you can mix them.

yes,if I only write my logic without using doop,that's OK,I can mix them
but in fact in doop,they provide developers self definition type such as Context and HContext extends original abstract definition,the orginal definition of Context and HContext  have been write in Bottom-level logic,I can't change it
developers can define HContext and Context like this:
  2-object-sensitive+heap
    .type Context  = [ value1:Value, value2:Value ]
    .type HContext = [ value:Value ]
 3-object-sensitive+3-heap
   .type Context  = [ value1:Value, value2:Value, value3:Value ]
   .type HContext = [ value1:Value, value2:Value, value3:Value ]
that's ok,because in program the Context and HContext has a fixed length,I can randomly split and combine them and will not meet the type problem,but If I define like this:
![image](https://user-images.githubusercontent.com/60656299/132438443-a74a66e3-b23d-471f-8aef-eece84f65565.png)
or like this:
.type Context = [head:Context, tail:Value]
  .type HContext = [ head:HContext, tail:Value ]
As we discussed before,problem occurs,that's the problem I need to solve

**Comment by b-scholz** [comment]
Again, this is not a Souffle issue - this is a Doop issue; perhaps you talk to Yannis directly. One way is to copy the structures if you don't want to change the type directly.

**Comment by lyj18688610256** [comment]
> Again, this is not a Souffle issue - this is a Doop issue; perhaps you talk to Yannis directly. One way is to copy the structures if you don't want to change the type directly.

I solve the problem
https://github.com/souffle-lang/souffle/issues/2061#issuecomment-914958237
