### ISSUE TITLE
List split and combine

### ISSUE THREAD

**Issue by lyj18688610256** [souffle-lang/souffle#2060]
For example,if I have a recrusive record like this : mList( [[[[[[nil,2],3],4],5],6],7])
how I can get a record mList2( [[[[[nil,3],4],5],6],7] ) conviently?
I want to remove the first element,the remain elements consist a new list.
Certainly mList here is a unknow list,you don't know how many elements in the List

**Comment by b-scholz** [comment]
Let's assume you have an upper bound  on the number of list elements and the upper bound is three. As simple FIFO queue can be simulated as follows, 
```
.type List = [l:List, n:number]
.decl A(x:number, l:List )
A(1, [nil, 1]).
A(2, [[nil, 1],2]).
A(3, [[[nil, 1],2],3]).
A(i+1, [[[nil, x2], x3], i+1]) :- A(i, [[[nil, _x1], x2], x3]), i < 10.
.output A
```

and produces following result:

```
---------------
A
x	l
===============
1	[nil, 1]
2	[[nil, 1], 2]
3	[[[nil, 1], 2], 3]
4	[[[nil, 2], 3], 4]
5	[[[nil, 3], 4], 5]
6	[[[nil, 4], 5], 6]
7	[[[nil, 5], 6], 7]
8	[[[nil, 6], 7], 8]
9	[[[nil, 7], 8], 9]
10	[[[nil, 8], 9], 10]
===============
```

**Comment by lyj18688610256** [comment]
what the program can give you is only a list of a variable: list_var1  ([[[[[[nil,2],3],4],5],6],7])(or list_var2,list_var3 ......)
what the program wish to get is a new list of a varibale new_list_var1( [[[[[nil,3],4],5],6],7] ) 
(new_list_var2,new_list_var3......)

so for different variables,they have different numbers of elements,I need to acquire the new_list_var for every varible,that's what I need

**Comment by b-scholz** [comment]
You can achieve this by flattening and reconstructing the lists. We have some examples in the test-benchmark.

**Comment by b-scholz** [comment]
May I ask for what you need it in DOOP (is this research or a study assignment)?

**Comment by lyj18688610256** [comment]
> You can achieve this by flattening and reconstructing the lists. We have some examples in the test-benchmark.

Ok,thanks a lot

**Comment by lyj18688610256** [comment]
> May I ask for what you need it in DOOP (is this research or a study assignment)?

I want to publish a paper using  doop tool,this problem is one part of my algorithm

**Comment by b-scholz** [comment]
No worries - perhaps you get familiar with logic programming first. My suggestion is to flatten and reverse lists etc. You have various options. Try to solve this problem in isolation. Also,  you can extend the previous solution, up to a certain bound by having for each length a pattern.

**Comment by lyj18688610256** [comment]
> You can achieve this by flattening and reconstructing the lists. We have some examples in the test-benchmark.

Can you specify the concrete path for me?I can't find it

**Comment by b-scholz** [comment]
Have a look in the tests/example and tests/evaluation directories. Also, please work through Souffle's tutorial. Good luck!

**Comment by lyj18688610256** [comment]
> Have a look in the tests/example and tests/evaluation directories. Also, please work through Souffle's tutorial. Good luck!

OK,thanks a lot!
