### ISSUE TITLE
Unexpected behaviour for external functors

### ISSUE THREAD

**Issue by andreabedini** [souffle-lang/souffle#2077]
I have the following code 

```
.decl In(x: float, y: float)
In(791834.8, 7519631.55).

.functor test(x:float, y:float):symbol stateful
.decl OutTest(x:symbol)
.output OutTest

OutTest(@test(x, y)) :- In(x, y).

.functor idFloat(x:float):float
.decl OutIdFloat(x:float)
.output OutIdFloat

OutIdFloat(@idFloat(x)) :- In(x, _).

.functor idFloatStateful(x:float):float stateful
.decl OutIdFloatStateful(x:float)
.output OutIdFloatStateful

OutIdFloatStateful(@idFloat(x)) :- In(x, _).
```

and

```cpp
#include <sstream>
#include <souffle/RamTypes.h>
#include <souffle/SouffleInterface.h>

extern "C" {

souffle::RamFloat idFloat(souffle::RamFloat x) { return x; }

souffle::RamFloat idFloatStateful(souffle::SymbolTable *symbolTable,
                                  souffle::RecordTable *recordTable,
                                  souffle::RamFloat x) {
  return x;
}

souffle::RamDomain test(souffle::SymbolTable *symbolTable,
                        souffle::RecordTable *recordTable, souffle::RamFloat x,
                        souffle::RamFloat y) {
  assert(symbolTable && "NULL symbol table");
  assert(recordTable && "NULL record table");

  std::ostringstream buf;

  buf << x << "_" << y;

  std::cout << "x = " << x << " y = " << y << " returning " << buf.str()
            << std::endl;

  return symbolTable->encode(buf.str());
}
}
```

results in

```
~/code/souffle/install_debug/bin/souffle test.dl -D-
x = 0 y = 2.95683e+11 returning 0_2.95683e+11
---------------
OutTest
x
===============
0_2.95683e+11
===============
---------------
OutIdFloat
x
===============
791834.812
===============
---------------
OutIdFloatStateful
x
===============
791834.812
===============
```

The string returned by test functor seems to be consistent with the symbol in the OutTest relation but the x and y values passed to it are garbage (they change at every run). 

The functors idFloat and idFloatStateful are identities and seem to work as expected.

I have compiled the functor with

```
g++ -I/home/andrea/code/souffle/install_debug/include -g -std=c++17 -shared -o libfunctors.so -fPIC -fopenmp functors.cpp
```

**Comment by quentin** [comment]
Hi, 
Can you try to use `RamDomain` for the `x` and `y` parameters of the **stateful** functors c++ implementation, and then convert to float using `ramBitCast`:
```cpp
RamFloat x_float = ramBitCast<RamFloat>(x)
```
If you generate the c++ program for your datalog exemple you will observe that the parameters are typed with `RamDomain`:
```cpp

#include "souffle/CompiledSouffle.h"

extern "C" {
souffle::RamFloat idFloat(souffle::RamFloat);
souffle::RamDomain test(souffle::SymbolTable *, souffle::RecordTable *,souffle::RamDomain,souffle::RamDomain);
}
```

I don't know if that's the expected behavior or not. It would be natural to expect `RamFloat` since you declared the functor with `float` parameters.

**Comment by andreabedini** [comment]
Thanks @quentin. Looking at the generated C++ code is a good trick! Using `souffle::RamDomain` in the signature and `ramBitCast` to obtain a float does indeed solve my problem. To be fair, using `ramBitCast` had already been suggested by @b-scholz [here](https://github.com/souffle-lang/souffle/discussions/2062#discussioncomment-1315207), so perhaps this is the intended behaviour and just needs better visibility in the documentation.

**Comment by b-scholz** [comment]
Great that you found the issue!
