### ISSUE TITLE
Inaccurate bison version dependency

### ISSUE THREAD

**Issue by aeflores** [souffle-lang/souffle#2089]
The CMake file specifies that the version of bison required is "3.0.4" but that is not true (since Souffle 2.1). Bison 3.0.4  (which is the one that comes with ubuntu 18) fails. I've had more success with  bison "3.5.1" (the one in Ubuntu 20). The minimum required version is probably is probably somewhere in between.

**Comment by XiaowenHu96** [comment]
I just tried this on an Ubuntu20 image. I compiled bison 3.0.4 from the source and things seem fine to me. What exact issue you are encountering with 3.0.4?

But you are right, the dependency list is outdated and does need an update, e.g. Souffle can't be built with g++-7.

**Comment by aeflores** [comment]
Interesting, I was getting the following error with Souffle 2.1:
```
[  3%] [BISON][parser] Building parser with bison 3.0.4
/souffle/src/parser/parser.yy:20.9-24: error: %define variable 'api.parser.class' is not used
 %define api.parser.class {parser}
         ^^^^^^^^^^^^^^^^
src/CMakeFiles/libsouffle.dir/build.make:61: recipe for target 'src/parser/parser.cc' failed
```
But it looks like the current master `9a8d9c864bb3f4a61f13e6c23688baad0d8dedf3` works, so I guess it was solved at some point. Thanks for looking into it.
