### ISSUE TITLE
error when installing: fatal error: 'ast/BranchDeclaration.h' file not found

### ISSUE THREAD

**Issue by wdduncan** [souffle-lang/souffle#2103]
I am trying to install souffle on OSX 11.6.  

I am following the build directions listed [here](https://souffle-lang.github.io/build).  
However, I am getting the following error when run `cmake --build build -j8 `:
```
In file included from ~/repos/souffle/src/parser/ParserDriver.cpp:32:
./parser/parser.yy:68:14: fatal error: 'ast/BranchDeclaration.h' file not found
    #include "ast/BranchDeclaration.h"
```

I also attempted install using homebrew as described [here](https://souffle-lang.github.io/install). When running `brew install --HEAD souffle-lang/souffle/souffle`, I receive the error
```
==> cmake --build build --target install
Last 15 lines from ~/Library/Logs/Homebrew/souffle/03.cmake:
/tmp/souffle-20211015-55340-1cu7kzf/src/include/souffle/utility/json11.h:290:14: error: expected unqualified-id
    if (std::isfinite(value)) {
             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/math.h:155:5: note: expanded from macro 'isfinite'
    ( sizeof(x) == sizeof(float)  ? __inline_isfinitef((float)(x))       \
    ^
15 errors generated.
make[2]: *** [src/CMakeFiles/libsouffle.dir/ast/analysis/ProfileUse.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/libsouffle.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 45%] Linking CXX executable test_brie
[ 45%] Linking CXX executable souffleprof
[ 45%] Built target test_brie
[ 45%] Built target souffleprof
make: *** [all] Error 2
```
Even after following the instructions to update the command line tools.

**Comment by XiaowenHu96** [comment]
Currently, CI tests were run only on 10.5 so things could be fragile on 11+.
I updated my old Macbook to 11.6 and was able to compile Souffle from the source fine, I had a linking error with Sqlite3 on my Macbook, I disabled it and Souffle was built, didn't bother to fix it as it should be irrelevant to your issue. Most likely yours is just another configuration issue.

Could you post the log files? `build/CMakeCache.txt` and Under `build/CMakeFiles`,  there should be a `CMakeError.log` and a `CMakeOutput.log`. Maybe we can figure out what's going on.

**Comment by wdduncan** [comment]
Hi @XiaowenHu96 Thanks for getting back to me. I've attached the files you requested
[CMakeCache.txt](https://github.com/souffle-lang/souffle/files/7357638/CMakeCache.txt)
[CMakeError.log.txt](https://github.com/souffle-lang/souffle/files/7357639/CMakeError.log.txt)
[CMakeOutput.log.txt](https://github.com/souffle-lang/souffle/files/7357640/CMakeOutput.log.txt)
.

**Comment by wdduncan** [comment]
Hi @XiaowenHu96 I did as you suggested and the build failed. I am attaching the errors in the file `souffle-build-errors.txt`. I am also attaching the `CMakeCache.txt` and `CMakeOutput.log`. No `CMakeError.log` was produced.

One problem I did detect, was that my system was using `/usr/bin/gcc` instead of `/usr/local/bin/gcc-11`. So, I ran:
```
CXX=/usr/local/bin/gcc-11 cmake -S . -B build
```
Here is the version info for `gcc-11` if that helps ...
```
/usr/local/bin/gcc-11 --version
->
gcc-11 (Homebrew GCC 11.2.0) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
``
[CMakeCache.txt](https://github.com/souffle-lang/souffle/files/7360052/CMakeCache.txt)
[CMakeOutput.log.txt](https://github.com/souffle-lang/souffle/files/7360053/CMakeOutput.log.txt)
[souffle-build-errors.txt](https://github.com/souffle-lang/souffle/files/7360054/souffle-build-errors.txt)
`

**Comment by wdduncan** [comment]
Hi again @XiaowenHu96   
Sorry, I misread your instructions. I should have used `g++` not `gcc`. ugh ....

I reran using `CXX=/usr/local/bin/g++-11 cmake -S . -B build`, followed by `cmake --build build`. This generated the error:
```
[ 55%] Building CXX object src/CMakeFiles/libsouffle.dir/parser/ParserDriver.cpp.o
In file included from ~/repos/wdduncan/forks/souffle/src/parser/ParserDriver.cpp:32:
./parser/parser.yy:68:14: fatal error: ast/BranchDeclaration.h: No such file or directory
compilation terminated.
make[2]: *** [src/CMakeFiles/libsouffle.dir/parser/ParserDriver.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/libsouffle.dir/all] Error 2
make: *** [all] Error 2
```
I am attaching the `CMakeCache.txt` and `CMakeOutput.log`.  
No `CMakeError`.log was produced.
[CMakeCache.txt](https://github.com/souffle-lang/souffle/files/7360097/CMakeCache.txt)
[CMakeOutput.log.txt](https://github.com/souffle-lang/souffle/files/7360098/CMakeOutput.log.txt)

**Comment by XiaowenHu96** [comment]
Ah, I just realized this... Which version of Souffle are you building? We don't have `ast/BranchDeclaration.h` in the master branch, it was renamed to something else I believe.

**Comment by XiaowenHu96** [comment]
@wdduncan
The branch seems fine, I think you just need a clean source: `parser.yy` does not include `ast/BranchDeclaration.h` at all. It might be some cache issue.

**Comment by wdduncan** [comment]
`ast/BranchDeclaration.h` is not in my `parser.yy`. Here are dependencies listed:
```
    #include "AggregateOp.h"
    #include "FunctorOps.h"
    #include "ast/Aggregator.h"
    #include "ast/Argument.h"
    #include "ast/Atom.h"
    #include "ast/Attribute.h"
    #include "ast/BinaryConstraint.h"
    #include "ast/BooleanConstraint.h"
    #include "ast/BranchInit.h"
    #include "ast/Clause.h"
    #include "ast/Component.h"
    #include "ast/ComponentInit.h"
    #include "ast/ComponentType.h"
    #include "ast/Constraint.h"
    #include "ast/Counter.h"
    #include "ast/ExecutionOrder.h"
    #include "ast/ExecutionPlan.h"
    #include "ast/FunctionalConstraint.h"
    #include "ast/FunctorDeclaration.h"
    #include "ast/Directive.h"
    #include "ast/IntrinsicFunctor.h"
    #include "ast/Literal.h"
    #include "ast/NilConstant.h"
    #include "ast/NumericConstant.h"
    #include "ast/Pragma.h"
    #include "ast/QualifiedName.h"
    #include "ast/RecordInit.h"
    #include "ast/RecordType.h"
    #include "ast/Relation.h"
    #include "ast/StringConstant.h"
    #include "ast/SubsetType.h"
    #include "ast/AliasType.h"
    #include "ast/AlgebraicDataType.h"
    #include "ast/BranchType.h"
    #include "ast/Type.h"
    #include "ast/TypeCast.h"
    #include "ast/UnionType.h"
    #include "ast/UnnamedVariable.h"
    #include "ast/UserDefinedFunctor.h"
    #include "ast/Variable.h"
    #include "parser/Helper.h"
    #include "parser/ParserUtils.h"
    #include "souffle/RamTypes.h"
    #include "souffle/BinaryConstraintOps.h"
    #include "souffle/utility/ContainerUtil.h"
    #include "souffle/utility/StringUtil.h"

    #include <ostream>
    #include <string>
    #include <vector>
```
