### ISSUE TITLE
CSV Headers Written With Wrong Delimeter

### ISSUE THREAD

**Issue by cwarden** [souffle-lang/souffle#2108]
When `.output` directive is used with `stdout` or `file`, and `headers` is set along with `rfc4180` or `delimiter`, a tab delimiter is used for the header instead of the correct delimiter.

**Comment by b-scholz** [comment]
Setting the delimiter to tabs for stdout is done on purpose so that humans can read the output better.

**Comment by cwarden** [comment]
Sorry, I had misspelled `delimiter` when testing this.  The `delimiter` attribute does apply to both the headers and facts, both with `stdout` and `file` `IO`.

It's just the `rfc4180` attribute that results in the incorrect headers.  With both `IO=stdout` and `IO=file`, the headers are tab separated, but the facts are comma separated.
