### ISSUE TITLE
playground website can't be accessed

### ISSUE THREAD

**Issue by sdifv** [souffle-lang/souffle#2110]
playground website in souffle homepage [try in out](http://plang1.it.usyd.edu.au:8000/) can't be accessed, has the services been stopped? Hope to use again!

**Comment by b-scholz** [comment]
The plang1 server is down, and I need to restart it. This may take some time.

**Comment by sdifv** [comment]
Got it, thank you!

**Comment by safinaskar** [comment]
@b-scholz , http://plang1.cs.usyd.edu.au:8000/ is down, again
