### ISSUE TITLE
question: specify input name at runtime

### ISSUE THREAD

**Issue by wdduncan** [souffle-lang/souffle#2111]
Sorry if I am missing this in the docs, but can you specify the inputs to a relation at runtime?

For example (from you help docs), this specifies that `edge` relation reads the facts from `edge.facts`.
```
.decl edge(x:number, y:number)
.input edge
```
I assume that if I want to apply the `edge` relation to a different data source (e.g., `foo.facts`), I have to rename `foo.facts` to `edge.facts`. Right? Or can specify my program to use the `foo.facts` data source?

**Comment by jckling** [comment]
> I assume that if I want to apply the `edge` relation to a different data source (e.g., `foo.facts`), I have to rename `foo.facts` to `edge.facts`.

@wdduncan If you don't want to change logic file, yes. I think one solution is organize facts into different directories and run with option `-F, --fact-dir`

Or you can specify input file:

```
.decl edge(x:number, y:number)
.input edge(IO="file", filename="path/to/foo.facts", delimiter=",")
```
