### ISSUE TITLE
How to break the cycle in a recrusive record?

### ISSUE THREAD

**Issue by lyj18688610256** [souffle-lang/souffle#2126]
Below is my datalog rules in VFlow.dl
----------------------------------------

.decl SourceValue(a:number, b:number)
.output SourceValue

.decl SmallVFlow(a:number, b:number)
.output SmallVFlow

.type List = [
        tail : List,
        head : number
    ]
    
.decl B(x : List)
.output B

SourceValue(1,2).
SmallVFlow(2,4).
SmallVFlow(4,6).
SmallVFlow(6,8).
SmallVFlow(8,4).
SmallVFlow(8,10).

B([[nil,a],b]) :-
   SourceValue(a,b).

B(r3) :-
   B(r1), r1=[r2, b], SmallVFlow(b, c), r3=[r1, c].

----------------------------------------
when I run :    
    souffle -F. -D- VFlow.dl
 The souffle can't stop and the memory useage is increasing until it reaches nearly 100%
 
I think the reason is that it occurs a cycle in the B relation(because of SmallVFlow(8, 4))

![VFlow](https://user-images.githubusercontent.com/60656299/141804673-acba433c-ac0b-4c10-ba24-6dc32d506750.png)

How to solve the problem?

**Comment by b-scholz** [comment]
In your example, you create an endless set of lists. You can double-check this adding a `.limitsize B(n=10)` directive. The output becomes:
```
B(r1), r1=[r2, b], SmallVFlow(b, c), r3=[r1, c].
-----------^-------------------------------------
---------------
SourceValue
a	b
===============
1	2
===============
---------------
SmallVFlow
a	b
===============
2	4
4	6
6	8
8	4
8	10
===============
---------------
B
x
===============
[[nil, 1], 2]
[[[nil, 1], 2], 4]
[[[[nil, 1], 2], 4], 6]
[[[[[nil, 1], 2], 4], 6], 8]
[[[[[[nil, 1], 2], 4], 6], 8], 4]
[[[[[[nil, 1], 2], 4], 6], 8], 10]
[[[[[[[nil, 1], 2], 4], 6], 8], 4], 6]
[[[[[[[[nil, 1], 2], 4], 6], 8], 4], 6], 8]
[[[[[[[[[nil, 1], 2], 4], 6], 8], 4], 6], 8], 4]
[[[[[[[[[nil, 1], 2], 4], 6], 8], 4], 6], 8], 10]
===============
```

Note that the lists/ADT cannot be cyclic - they can be at mosts DAGs and there is no single list in set B, i.e. it contains a set of lists. 

I hope that helps.

**Comment by lyj18688610256** [comment]
Thank you!
![image](https://user-images.githubusercontent.com/60656299/141871544-674649a8-1615-424a-b847-672fe9924337.png)
But What I want is to elimate the results above in red color
My major problem is that once I start from 1 ---> 2 ---> 4 ---->6 ---->8,It means that I have passed through (1,2,4,6,8),when I decide the next node from 8,I have two choices(4,10),but because my past path have gone through 4, so I can't go back to 4 again,this is my needed rule.

**Comment by b-scholz** [comment]
There are various ways to achieve this. But just to be sure - you have given a graph and you want all non-cyclic paths -- is this correct?

**Comment by lyj18688610256** [comment]
> There are various ways to achieve this. But just to be sure - you have given a graph and you want all non-cyclic paths -- is this correct?

Yes

**Comment by b-scholz** [comment]
Let's assume you would like to have all non-cyclic paths in a graph. Let's rewrite the problem so that it is better for a  general audience:
```
.type Node <: symbol
.type Path = [
rest : Path,
node : Node
]
.decl E(x:Node, y:Node)
E("s","1").
E("1","2").
E("2","2").
E("2","3").
.decl S(p:Path, l:number)
S([nil,"s"],1).
.decl P(p:Path)
P([nil, "s"]).
P([[p,u],v]), S([[p,u],v],l+1)  :-
   P([p,u]),
   E(u,v),
   S([p,u],l).
.output P,S
.limitsize P(n=10)
```

**Comment by b-scholz** [comment]
The next step is to delete all paths between "s" and "u" if the are longer than the shortest possible one. We achieve this by adding a subsumption clause, i.e., 
```
.type Node <: symbol
.type Path = [
rest : Path,
node : Node
]
.decl E(x:Node, y:Node)
E("s","1").
E("1","2").
E("2","2").
E("2","3").
.decl S(p:Path, l:number)
S([nil,"s"],1).
.decl P(p:Path) btree_delete
P([nil, "s"]).
P([[p,u],v]), S([[p,u],v],l+1)  :-
   P([p,u]),
   E(u,v),
   S([p,u],l).
.output P,S
P([p1,u]) <= P([p2, u]) :- 
   S(p1, l1),
   S(p2, l2),
   l2 <= l1.
``` 
and obtain:
```
---------------
S
p	l
===============
[nil, s]	1
[[nil, s], 1]	2
[[[nil, s], 1], 2]	3
[[[[nil, s], 1], 2], 2]	4
[[[[nil, s], 1], 2], 3]	4
===============
---------------
P
p
===============
[nil, s]
[[nil, s], 1]
[[[nil, s], 1], 2]
[[[[nil, s], 1], 2], 3]
===============
```

**Comment by lyj18688610256** [comment]
Okay,thanks a lot,I need to have a double-check

**Comment by lyj18688610256** [comment]
![image](https://user-images.githubusercontent.com/60656299/141884241-a92f7795-7ab5-4724-8692-28589d2b4bc4.png)
Is this a advanced grammer? my souffle version is 2.0.2

**Comment by b-scholz** [comment]
You need to install the latest version on GitHub.

**Comment by lyj18688610256** [comment]
> You need to install the latest version on GitHub.

OKay

**Comment by b-scholz** [comment]
This generates you the set of shortest path / not the set of all acyclic path - by the way. For this you need another formulation - perhaps you try this on your own.

**Comment by lyj18688610256** [comment]
> This generates you the set of shortest path / not the set of all acyclic path - by the way. For this you need another formulation - perhaps you try this on your own.

OKay,thank you very much

**Comment by lyj18688610256** [comment]
> In your example, you create an endless set of lists. You can double-check this adding a `.limitsize B(n=10)` directive. The output becomes:
> 
> ```
> B(r1), r1=[r2, b], SmallVFlow(b, c), r3=[r1, c].
> -----------^-------------------------------------
> ---------------
> SourceValue
> a	b
> ===============
> 1	2
> ===============
> ---------------
> SmallVFlow
> a	b
> ===============
> 2	4
> 4	6
> 6	8
> 8	4
> 8	10
> ===============
> ---------------
> B
> x
> ===============
> [[nil, 1], 2]
> [[[nil, 1], 2], 4]
> [[[[nil, 1], 2], 4], 6]
> [[[[[nil, 1], 2], 4], 6], 8]
> [[[[[[nil, 1], 2], 4], 6], 8], 4]
> [[[[[[nil, 1], 2], 4], 6], 8], 10]
> [[[[[[[nil, 1], 2], 4], 6], 8], 4], 6]
> [[[[[[[[nil, 1], 2], 4], 6], 8], 4], 6], 8]
> [[[[[[[[[nil, 1], 2], 4], 6], 8], 4], 6], 8], 4]
> [[[[[[[[[nil, 1], 2], 4], 6], 8], 4], 6], 8], 10]
> ===============
> ```
> 
> Note that the lists/ADT cannot be cyclic - they can be at mosts DAGs and there is no single list in set B, i.e. it contains a set of lists.
> 
> I hope that helps.

HI,I suddenly found that when I use .limitsize B(n=10),it is used to limit the B record numbers,not single B length,
Do we have any method to limit every single B length?

**Comment by lyj18688610256** [comment]
> In your example, you create an endless set of lists. You can double-check this adding a `.limitsize B(n=10)` directive. The output becomes:
> 
> ```
> B(r1), r1=[r2, b], SmallVFlow(b, c), r3=[r1, c].
> -----------^-------------------------------------
> ---------------
> SourceValue
> a	b
> ===============
> 1	2
> ===============
> ---------------
> SmallVFlow
> a	b
> ===============
> 2	4
> 4	6
> 6	8
> 8	4
> 8	10
> ===============
> ---------------
> B
> x
> ===============
> [[nil, 1], 2]
> [[[nil, 1], 2], 4]
> [[[[nil, 1], 2], 4], 6]
> [[[[[nil, 1], 2], 4], 6], 8]
> [[[[[[nil, 1], 2], 4], 6], 8], 4]
> [[[[[[nil, 1], 2], 4], 6], 8], 10]
> [[[[[[[nil, 1], 2], 4], 6], 8], 4], 6]
> [[[[[[[[nil, 1], 2], 4], 6], 8], 4], 6], 8]
> [[[[[[[[[nil, 1], 2], 4], 6], 8], 4], 6], 8], 4]
> [[[[[[[[[nil, 1], 2], 4], 6], 8], 4], 6], 8], 10]
> ===============
> ```
> 
> Note that the lists/ADT cannot be cyclic - they can be at mosts DAGs and there is no single list in set B, i.e. it contains a set of lists.
> 
> I hope that helps.

Hi,I suddenly found sometimes .limitsize(n=10) can't work in my exampl
![5](https://user-images.githubusercontent.com/60656299/142335424-c9f360c3-dc46-400f-b78e-7b7233913be1.png)
e
![6](https://user-images.githubusercontent.com/60656299/142335456-a08cfed1-502e-4a38-afdb-464a82d72ead.png)

I set the limitsize n=10,but in the result I found 47 rows

**Comment by b-scholz** [comment]
This is related to the number of tuples generated in a fixpoint iteration. `.limitsize` is only approximate (and only a lower-bound).
