### ISSUE TITLE
sign-compare error in cmake build on MacOS

### ISSUE THREAD

**Issue by tlogan** [souffle-lang/souffle#2128]
After running `cmake -S . -B build`, I run into an error with `cmake --build build` on MacOS 12.0.1

```
...
[ 65%] Building CXX object src/CMakeFiles/libsouffle.dir/ram/utility/NodeMapper.cpp.o
[ 66%] Building CXX object src/CMakeFiles/libsouffle.dir/reports/DebugReport.cpp.o
[ 66%] Building CXX object src/CMakeFiles/libsouffle.dir/synthesiser/Synthesiser.cpp.o
[ 66%] Building CXX object src/CMakeFiles/libsouffle.dir/synthesiser/Relation.cpp.o
[ 67%] Building CXX object src/CMakeFiles/libsouffle.dir/parser/scanner.cc.o
/Users/thomas/souffle/build/src/parser/scanner.cc:2018:41: error: comparison of integers of different signs: 'unsigned long' and 'int' [-Werror,-Wsign-compare]
        if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/CMakeFiles/libsouffle.dir/parser/scanner.cc.o] Error 1
make[1]: *** [src/CMakeFiles/libsouffle.dir/all] Error 2
make: *** [all] Error 2
```

I've tried setting various flag variables including `export CXXFLAGS = "-Wno-error=sign-compare"`, but none seems to affect the compilation.

**Comment by tlogan** [comment]
The issue is resolved when I build from the release 2.1 instead of the master branch.

**Comment by remysucre** [comment]
Still an issue on master, so this should remain open

**Comment by b-scholz** [comment]
The problem is that source code was produced by the scanner. Can you try setting the flag in the CMakelist.txt. 
```
set(CMAKE_CXX_FLAGS "-Wno-error=sign-compare")
```

**Comment by remysucre** [comment]
It compiles now, but I'm failing a lot of tests (958). Is that expected?

**Comment by b-scholz** [comment]
Which test is this?

**Comment by b-scholz** [comment]
What are you working on? Send me an email Bernhard.Scholz@sydney.edu.au.

**Comment by remysucre** [comment]
Moving the discussion on test failures to #2170 per email discussion with Bernhard.
