### ISSUE TITLE
shadowed homebrew-installed bison on macOS

### ISSUE THREAD

**Issue by yihozhang** [souffle-lang/souffle#2143]
Hello Souffle developers!

Thanks for the detailed instructions for building! I followed the instruction [here](https://souffle-lang.github.io/build#mac-os-x-build) for building Souffle on macOS and it seems that `brew link bison --force` is no longer working now with this warning:
```
Warning: Refusing to link macOS provided/shadowed software: bison
If you need to have bison first in your PATH, run:
  echo 'export PATH="/usr/local/opt/bison/bin:$PATH"' >> ~/.zshrc

For compilers to find bison you may need to set:
  export LDFLAGS="-L/usr/local/opt/bison/lib"
```
I worked around this problem by following this StackOverflow [post](https://stackoverflow.com/questions/53877344/cannot-configure-cmake-to-look-for-homebrew-installed-version-of-bison). With the suggested edit to `CMakeLists.txt`, I am able to build Souffle on macOS Big Sur 11.6.1 and brew 3.3.6. 

I just want to bring up this issue to you and I am happy to create a PR for fixing it. But if you have any potential concerns about the issue or the proposed fix, you could fix it on your own :)

**Comment by b-scholz** [comment]
Please, could you create a pull request with the changes to CMakeList.txt?
