### ISSUE TITLE
Remove SQLite 

### ISSUE THREAD

**Issue by psubotic** [souffle-lang/souffle#216]
Is anyone using this? Its really messing up the interface compilation and it only adds a dependency that is not standard (i.e., java etc.). We have enough problems with boost, I propose (unless someone really needs it) we remove this or make it optional.

**Comment by scyptnex** [comment]
This was added by oracle and recently merged into our main branch.
Perhaps the main use cases are on their end?

I'd favour making it optional, i.e. a --with-sql at configure time.  Is kostantyn handling this in #199

**Comment by b-scholz** [comment]
We have the SQLite3 backend as a way to query results. If we want to remove it, we will need a replacement for querying output relations.

**Comment by seanmcl** [comment]
Couldn't you use Souffle itself to query results?

**Comment by b-scholz** [comment]
Unfortunately we haven't got an interactive query processor for Soufflé yet.

**Comment by psubotic** [comment]
ok this is building now -- i still think it should be optional but thats on another issue. So im closing this
