### ISSUE TITLE
Towards Elastic Incrementalization for Datalog

### ISSUE THREAD

**Issue by simpletonDL** [souffle-lang/souffle#2162]
The paper _"Elastic Incrementalization for Datalog"_ describes two new incremental souffle engines: Soufflé-counting and Soufflé-elastic. Can you please tell me how to run souffle in incremental mode? Or are these engines only for research purposes and there is no proper interface yet?

**Comment by b-scholz** [comment]
Please check the news section on Soufflé’s homepage. There you find the link to David’s research prototype. 

The plan is to merge incremental evaluation around March. Would you like to help us in this endeavour?

**Comment by simpletonDL** [comment]
Sorry for the late response, I probably won't be able to participate in the integration. But it will be very cool if souffle can be used in incremental mode. So I'm sorry, so far I can only wish you good luck!

**Comment by b-scholz** [comment]
No worries! You can still participate with less time involved such as documentation, installation scripts, etc.
