### ISSUE TITLE
Document how to pass ADTs into Souffle binaries through input files.

### ISSUE THREAD

**Issue by markww** [souffle-lang/souffle#2169]
I have a Souffle program where I would like to use an ADT type in an input relation. I'm having trouble getting the binary generated from my Souffle datalog program to accept the syntax for the ADT that I'm attempting to provide via an input file. In searching the documentation, I haven't found any wording indicating that ADTs can't be passed through input relations. However, I suspect that what I'm trying to do might not be possible because the documentation explicitly states that record types *can* be passed through input relations while remaining silent upon ADTs.

It would be great if the documentation would either explicitly indicate that providing ADTs through input relations is not supported or indicate the syntax by which an ADT can be provided in an input file.

**Comment by markww** [comment]
I appear to have gotten it to work by using the default tab delimiters rather than setting my delimiter to `,`. Probably because setting the delimiter to `,` caused the components of the ADTs to be seen as different columns. While this is me just making a boneheaded move in this case, I probably would have realized that much faster had the docs assured me that it should be possible to send ADTs through input files.

**Comment by b-scholz** [comment]
Please send me an email to Bernhard.Scholz@sydney.edu.au if you want help. And this is also a reminder to improve the documentation.
