### ISSUE TITLE
OpenMP hangs on Ubuntu 14.04 (deadlock?)

### ISSUE THREAD

**Issue by psubotic** [souffle-lang/souffle#217]
I just installed a new OS (ubuntu 14.04) and notice I get a deadlock or something when running through the jni interface, even with 1 thread.  Occasionally I get an assertion in openmp. 

../nptl/pthread_mutex_lock.c:80: __pthread_mutex_lock:Assertion `mutex->data.__owener == 0'

I'll add a test case in the tests/interface folder but wont hook it up to the auto testing framework as it fails due to this and the sqlite code. If someone can replicate this please let me know. Everything works fine on osx. Is there a way to disable openmp on linux?

**Comment by b-scholz** [comment]
Perhaps Herbert can look into this.

**Comment by HerbertJordan** [comment]
When I find some time I can have a look at it.

Regarding disabling OpenMP: can anybody who knows the build system configuration answer that? However, it might not be related to OpenMP since pthread_mutex locks may be also utilized by other APIs.

**Comment by b-scholz** [comment]
I feel there might be still a script where you enable -fopenmp. Perhaps you trace the compiler script invocation and checkout how the library is generated with the compile script. The other issue might be that the interpreter is build with -fopenmp. That might cause issues as well.

**Comment by b-scholz** [comment]
I forgot to say that the semantics for the compiler is that setting the number of threads to one in the configuration environment means sequential execution. Note that the interpreter works differently. The compilation process for the interpreter decides whether openmp is present or not.

**Comment by b-scholz** [comment]
Has this issue been resolved?

**Comment by psubotic** [comment]
there is a work around i.e., disable openmp but its not resolved.

**Comment by mmcgr** [comment]
Closing this as JNI has been removed to make way for a new swig interface.
