### ISSUE TITLE
Test: evaluation/indexed_inequalities_compare_csv fails on aarch64

### ISSUE THREAD

**Issue by broffra** [souffle-lang/souffle#2171]
The test `evaluation/indexed_inequalities_compare_csv` may fail on aarch64 architectures with:
```
----------------------------------------------------------
1d0
< 4294967290
5a5
> 4294967295
<end of output>
Test time =   0.07 sec
----------------------------------------------------------
Test Failed.
```

Note that the test passes in 64-bit mode: `cmake -S . -B build -DSOUFFLE_DOMAIN_64BIT=ON`
```
$ ctest -R 'evaluation/indexed_inequalities_compare_csv' --output-on-failure

100% tests passed, 0 tests failed out of 3
```

Also note that the compiler works correctly, only the interpreter outputs the incorrect result below:
```
$ souffle tests/evaluation/indexed_inequalities/indexed_inequalities.dl --output-dir -
---------------
rel_2
x
===============
4294967290
4294967291
4294967292
4294967293
4294967294
===============
---------------
```
Expected output of `rel_2` can be found [here](https://github.com/souffle-lang/souffle/blob/babc4192ecca04080bf5c01433f982b77065ce19/tests/evaluation/indexed_inequalities/rel_2.csv).

The issue appears to be with an undefined behaviour occurring during casting the result of `std::pow` (which has `double` type) back to a `uint32_t` on [this line](https://github.com/souffle-lang/souffle/blob/babc4192ecca04080bf5c01433f982b77065ce19/tests/evaluation/indexed_inequalities/indexed_inequalities.dl#L17) of the test. An overflow occurs in 32-bit mode whereas 64-bit integers are already large enough.

I think I have located the issue and will try to have a PR out shortly.

**Comment by remysucre** [comment]
This is broken again, possibly by a9a6587
