### ISSUE TITLE
Exit code 137

### ISSUE THREAD

**Issue by gabriele-costa** [souffle-lang/souffle#2185]
When running souffle from command line, after a while I get
`[1]    <pid> killed     souffle -F. -D. model.dl` 

Where `<pid>` is souffle's process id. By checking the exit code I find 137, but I could not find its meaning in the documentation.

**Comment by b-scholz** [comment]
Can you send us the program? If not possible, can you run top and check whether your program uses up all the memory of your system.

**Comment by b-scholz** [comment]
Alternatively, compile Souffle in debug mode and run souffle in the debugger (gdb/lldb).

**Comment by gabriele-costa** [comment]
Thank you very much for your answer. I am attaching the last version of my code (which still results in the same error after a while). The computation gets stuck on rule Trans for a few minutes before the error
[wbpls.zip](https://github.com/souffle-lang/souffle/files/8046957/wbpls.zip)

Also, here is a screenshot of top -p [pid] while running souffle on the file given above
![Schermata del 2022-02-11 08-55-33](https://user-images.githubusercontent.com/10499254/153555862-61109789-5f90-4eae-856b-e1006d0ec73b.png)

**Comment by b-scholz** [comment]
Can you do me a favour and replace the `eqrel` relations with default relations? Add the transitive closure rules to those.

**Comment by gabriele-costa** [comment]
Sure, here you are. I noticed that some eqrel are not strictly needed. I removed all of them and I confirm that I am still getting the same error.

[wbpls.zip](https://github.com/souffle-lang/souffle/files/8048757/wbpls.zip)

**Comment by b-scholz** [comment]
How much memory has your machine? I am running it on a bigger server (with -j16). Top reads as follows:
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                          
2053976 scholz    20   0   20.0t   9.8g  23328 R  1600   7.8 174:56.73 souffle    
```

**Comment by b-scholz** [comment]
Are you sure this program is terminating?
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                          
2053976 scholz    20   0   20.0t  36.8g  23328 R  1597  29.3   1370:57 souffle                          
```

**Comment by gabriele-costa** [comment]
> How much memory has your machine? I am running it on a bigger server (with -j16). Top reads as follows:
> 
> ```
>     PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                          
> 2053976 scholz    20   0   20.0t   9.8g  23328 R  1600   7.8 174:56.73 souffle    
> ```

I am running it on a DELL XPS with 16GB RAM

> Are you sure this program is terminating?
> 
> ```
>     PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                          
> 2053976 scholz    20   0   20.0t  36.8g  23328 R  1597  29.3   1370:57 souffle                          
> ```

Well, perhaps not the entire program and I wanted to debug it. In particular, I made a few Debug rules (Debug 1, 2, ...) which are testing the premises of the Trans rule that should be applied to the example Configuration (last part of the program). The premises seem to be satisfied, and the correct rule appears in the verbose output. But then it gets stuck there. I am also recording the entire terminal session with asciinema. As soon as it is ready I am posting it (sorry, it takes a while).

**Comment by b-scholz** [comment]
Please add `.limitsize` directives to your source code so that the program terminates without filling up the relations. Investigate the output of the relations.

**Comment by b-scholz** [comment]
Most likely, you received the exit code 137 because you ran out of memory.

**Comment by gabriele-costa** [comment]
After digging a bit more I confirm that most likely the problem is due to memory exhaustion caused by an exponential explosion of the search space in my program. In particular, I think that the problem I am trying to model does not perfectly apply to the internal logic of souffle. I will reorganize it and try again, but I think that a goal-driven rule evaluation strategy would provide better results in my case. As a general remark, let me share very briefly my expeirience (in case it may be helpful for others).
1. souffle is a great tool, easy to learn, very close do the abstract idea behind Datalog in general. Some directives (e.g., I/O) are extremely convenient.
2. souffle would benefit from a little more support for debugging. The --verbose output is useful, but something like breakpoints or assertions would be of great help for developers
3. a query-driven evaluation strategy for rules would make souffle extremely flexible and adaptable to most problems.
I am really thankful for your kind support and for the nice work done with souffle. I hope my comments can give you hints for further improvements.
