### ISSUE TITLE
Incorrect result with magic transform and `eqrel`

### ISSUE THREAD

**Issue by bertram-gil** [souffle-lang/souffle#2190]
Hi guys, 

Consider the following program:
```
.decl notEqrel(x:number,y:number)
.decl isEqrel(x:number, y:number) eqrel
.decl a__(a:number) 
.decl b__(a:number) 

notEqrel(x, y) :- isEqrel(x, y).
isEqrel(x, y) :- notEqrel(x, y).
isEqrel(0,1).
notEqrel(1,2).

.output a__
.output b__ // Output node

a__(a) :- notEqrel(a, a).
b__(c) :- !a__(b), a__(c), a__(b).
b__(a) :- a__(a).
```

Running the above program gives me the following for the relation `b__`:
```
$ souffle_59260/src/souffle -w --magic-transform=* prog.dl && cat b__.csv 
0
1
2
```

Now, adding `notEqrel(a, b), notEqrel(c, a)` in the rule for `a__`, should have no effect on `a__` and also not on `b__`.
But if I now run the following new program, I get:

```
$ souffle_59260/src/souffle -w --magic-transform=* prog.dl && cat b__.csv 
1
2
```
FYI, running both programs without `--magic-transform=*` returns:
```
0
1
2
```
I am using the latest commit: 592605c21c6b0af9a971499ad9c6a147302184b1

**Comment by bertram-gil** [comment]
Hi guys, is this a confirmed bug or am i doing something wrong?

**Comment by b-scholz** [comment]
When a magic-set transformation is applied to `eqrel` relations, they need to be expanded to their explicit form, i.e., 
```
.decl notEqrel(x:number,y:number)
.decl isEqrel(x:number, y:number) 

isEqrel(x,x) :- isEqrel(x,_).
isEqrel(x,y) :- isEqrel(y,x).
isEqrel(x,z) :- isEqrel(x,y), isEqrel(y,z).

.decl a__(a:number)
.decl b__(a:number)

notEqrel(x, y) :- isEqrel(x, y).
isEqrel(x, y) :- notEqrel(x, y).
isEqrel(0,1).
notEqrel(1,2).

.output a__
.output b__ // Output node

a__(a) :- notEqrel(a, a),notEqrel(a, b), notEqrel(c, a).
b__(c) :- !a__(b), a__(c), a__(b).
b__(a) :- a__(a).

```

Alternatively, the specialization of the magic-set transformation needs to stop for `eqrel` relations.
