### ISSUE TITLE
Warning about missing parentheses in generated code.

### ISSUE THREAD

**Issue by luc-tielen** [souffle-lang/souffle#2194]
Somebody who uses souffle-haskell told me that the generated C++ code generates warnings about missing parentheses (which show up as "errors" in GHC). The code still seems to compile and work though.

I think the fix for the warning could be easy, by adding some extra parentheses in the code that is generated to avoid ambiguity?
Below is a snippet of the C++ warnings the person is seeing:

https://gist.github.com/tchoutri/3a97348479f35e5df0a14e3f8dc3ceb8

**Comment by XiaowenHu96** [comment]
> -Wparentheses
>  ... when operators are nested whose precedence people often get confused about. 

In this case, the compiler generates warnings simply for readability alarm. The code itself is correct.
Not sure how would we improve that. I do not think simply wrapping each sub-expressions into parentheses will improve readability, in the contrast, this probably going to make the code even harder to read. 

The compiled code is not meant to be read anyway... Maybe we should disable the warning instead.

**Comment by luc-tielen** [comment]
I think you can't disable the warning though, since the C++ code in this case was generated but not immediately compiled by souffle itself. (`souffle -g program.cpp program.dl` for example).
In this case, the C++ code is compiled via the GHC Haskell compiler (and that is also how the C++ flags are provided).

If the generated code is not meant to be read, we might as well add the extra parentheses to get rid of the warning (and improve the end user experience)?

**Comment by XiaowenHu96** [comment]
I see.
Would you like to provide the fix?
Also,  another alternative is to use the `cxx-options` with `-Wno-parentheses` in souffle-Haskell, will this suppress the warning?

**Comment by luc-tielen** [comment]
Yes it would suppress it, but it feels like the fix is in the wrong place then (compiling with another setup would still generate the error).

I'll take a look at it when I have some time.
