### ISSUE TITLE
Having trouble installing souflé on the windows linux subsystem.

### ISSUE THREAD

**Issue by warmy54** [souffle-lang/souffle#2203]
As the title says, I'm running the windows linux subsystem. (the 20.04.4 ubuntu version to be exact)
When running the  "curl -s https://packagecloud.io/install/repositories/souffle-lang/souffle/script.deb.sh | sudo bash"  that the instalation guide instruct me to use, I get an the following result:

Detected operating system as Ubuntu/focal.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/souffle-lang_souffle.list...done.
Importing packagecloud gpg key... curl: (22) The requested URL returned error: 429
gpg: no valid OpenPGP data found.
done.
Running apt-get update... done.

The repository is setup! You can now install packages.

But if I then try the following command which is: "sudo apt-get install souffle"

I get the following error

Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package souffle

Afterward I obviously can't use soufflé.

Is it something i'm doing wrong ?

**Comment by XiaowenHu96** [comment]
See #2198.
