### ISSUE TITLE
Is it possible to use subsumption along with choice domain?

### ISSUE THREAD

**Issue by ucasqsl** [souffle-lang/souffle#2207]
Subsumption seems not to work with a choice domain specified.
```
.decl A(k:number, v:number) choice-domain k
.output A
A(1, 1).
A(1, x+1):-
    A(1, x),
    x < 10.
A(1, v1) <= A(_, v2):-
    v1 < v2.
```
expected output:
```
1 10
```
result
```
1 1
```
Is it possible to use subsumption along with a choice domain? Or are there any other ways to achieve the same goal if I have a choice domain `k` but want to keep the largest `v` for it?

**Comment by b-scholz** [comment]
Oh - that is an interesting one - why do you need this? Subsumption is more potent than choice anyway...

**Comment by ucasqsl** [comment]
The initial value of `v` is used to hold the place. Useful facts will be discovered after some analysis, and I want to update the value of `v` with the result.

**Comment by philzook58** [comment]
Does it help that subsumption alone solves your particular example? You can delete with subsumption so long as there is a notion of some values being better than other.
```
.decl A(k:number, v:number)
.output A(IO=stdout)
A(1, 1).
A(1, x+1):-
    A(1, x),
    x < 10.
A(x, v1) <= A(x, v2):-
    v1 < v2.
// output: 1 10
```

**Comment by ucasqsl** [comment]
> Does it help that subsumption alone solves your particular example? You can delete with subsumption so long as there is a notion of some values being better than other.
> 
> ```
> .decl A(k:number, v:number)
> .output A(IO=stdout)
> A(1, 1).
> A(1, x+1):-
>     A(1, x),
>     x < 10.
> A(x, v1) <= A(x, v2):-
>     v1 < v2.
> // output: 1 10
> ```

Thanks for your reply. In my use case, which is much more complicated, there is no such thing as `x < 10`. I use the choice domain to make sure that the program will stop.
```
.type depend = [EA: number, l: number, r: number]
.decl A(EA:number, d:depend, v:number, t:symbol) choice-domain (EA, d)
.output A
.decl Add(EA:number, EA1:number, EA2:number)
Add(1, 1, 2).
A(1, [1, 0, 0], 2, "a").
A(2, [2, 0, 0], 2, "a").
A(x, [x, l, r], vl + vr, t):-
    Add(x, l, r),
    A(l, [l, _, _], vl, t),
    A(r, [r, _, _], vr, _).
```
in this case, I use `(EA, d)` to chose the first occurrence of the value. What I really want to change is the `t`, if latter I find that setting the type `t` to "b" is better, I want to update that somehow.
Maybe this logic is too complicated for a single relation, I'll try to split it into multiple parts.

**Comment by XiaowenHu96** [comment]
choice prevents anything that breaks the dependency from ever being inserted into the relation. So your second rule does not generate anything actually. 

Why is the 'first occurrence' so important? I don't think having two strategies where one always keeps some keys unique and the other always "chooses the 'better' one with the same keys" will ever work within a single relation.

**Comment by ucasqsl** [comment]
> choice prevents anything that breaks the dependency from ever being inserted into the relation. So your second rule does not generate anything actually.
That's actually what I observed.
> Why is the 'first occurrence' so important? 
To prevent infinite relations generated by calculation, if you remove the choice-domain from the above example like this
```
.type depend = [EA: number, l: number, r: number]
.decl A(EA:number, d:depend, v:number, t:symbol) //choice-domain (EA, d)
.output A
.decl Add(EA:number, EA1:number, EA2:number)
Add(1, 1, 2).
A(1, [1, 0, 0], 2, "a").
A(2, [2, 0, 0], 2, "a").
A(x, [x, l, r], vl + vr, t):-
    Add(x, l, r),
    A(l, [l, _, _], vl, t),
    A(r, [r, _, _], vr, _).
```
it will never stop.
> I don't think having two strategies where one always keeps some keys unique and the other always "chooses the 'better' one with the same keys" will ever work within a single relation.
What I'm doing is to keep the value unique while assigning a better type, that's two different fields. I agree that should be split into multiple relations. 
Thanks.
