### ISSUE TITLE
GCC/LTO build issue with "lib'never gonna'.so"

### ISSUE THREAD

**Issue by cmuellner** [souffle-lang/souffle#2214]
Commit 285f45134b3ece0abc8fce31529567496e30e92b from #2019 introduced changes that improve the handling of paths containing spaces.

To do so, the patch creates a library "lib'never gonna'.so" and tests if quoted strings are properly passed.

Building Souffle with `-flto` triggers an issue in GCC (Fedora 35: `gcc (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9)`):
```
[ 10%] Linking CXX shared library "lib'never gonna'.so"
cd /home/cm/src/souffle/2.2-cmake-centos8/builddir/tests/semantic/pragma2 && /usr/bin/cmake -E cmake_link_script CMakeFiles/lib_foo.dir/link.txt --verbose=1
/usr/lib64/ccache/c++ -fPIC -fPIC -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 
-fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fopenmp -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld 
-specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -fopenmp -O3  -shared -Wl,-soname,"lib'never gonna'.so" -o "lib'never gonna'.so" CMakeFiles/lib_foo.dir/lib_foo.cpp.o
lto1: error: open gonna.so. failed: No such file or directory
make[3]: *** [/tmp/ccoCqby4.mk:2: /tmp/ccOKHsb6.ltrans0.ltrans.o] Error 1
lto-wrapper: fatal error: make returned 2 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
```

I don't know how GCC maintainers think about spaces in library names. However, I am not aware of anyone who is brave enough to add spaces in library paths in production. Also, `find / -name 'lib* *' 2>/dev/null | while read LINE; do echo "$LINE" ; done` does not find anything except `lib'never gonna'.so` and `lib'let you'.so` in Souffle build directories.

My proposal would be:
1. isolate the issue and file it against GCC's Bugzilla
1. remove the pragma2 test from Souffle

@OlivierHamel any thoughts on this issue?

**Comment by cmuellner** [comment]
GCC bug report can be found here: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104895

**Comment by OlivierHamel** [comment]
> Any thoughts?

Yes: Good luck.
There are comments in the test case that detail additional variants that have been disabled for similar reasons (broken tooling). 

The lack of system level facilities for parsing/unparsing command line invocations have been a disaster for the human race. I've had trouble with almost every single damn tool involved in producing a binary: build systems, compilers, linkers, etc. Invariably someone, somewhere, in the pipeline screws up encoding/escaping file names or paths somewhere.

If this is a blocker for your platform/compiler combo then it might be worth just disabling that test case.

**Comment by b-scholz** [comment]
Is this issue resolved? I don't think we can resolve this issue within Souffle - right?

**Comment by cmuellner** [comment]
The underlying issue (being able to build libraries with spaces in the file name) can't be fixed in Souffle.
And I don't see this will be fixed in the near future (nobody really cares much about that).

What can be done in Souffle: disable the test case for Linux or remove it.

For the [Fedora package](https://copr.fedorainfracloud.org/coprs/cmuellner/souffle/), I've simply commented out the test (see https://github.com/cmuellner/souffle/commit/f7691feb707bf0a709baf5fba59203ca3f0b32dd).

I can prepare a patch using that disables the test `if(CMAKE_SYSTEM_NAME STREQUAL "Linux")`.

**Comment by b-scholz** [comment]
Yes - that would be great!

**Comment by b-scholz** [comment]
Can we close this issue?

**Comment by cmuellner** [comment]
Yes, can be closed.
Thanks for the reminder!
