### ISSUE TITLE
suspicious unused `value` in `SipsMetric.cpp`

### ISSUE THREAD

**Issue by quentin** [souffle-lang/souffle#2218]
Hi, `clang` found this unused variable `value` although the involved computation seems important:

https://github.com/souffle-lang/souffle/blob/d1522e06c6e99c259951dc348689a77fa5f5c932/src/ast/utility/SipsMetric.cpp#L252-L255

Is a `cost.push_back(value);` missing or something ?

**Comment by b-scholz** [comment]
Yes - that is an issue. Something went wrong here.
