### ISSUE TITLE
Functors require their own namespace

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#2223]
User-defined functors (UDF) are declared as external "C" functions in the namespace of souffle. 

When I was working on a subsumption example (https://github.com/souffle-lang/souffle/pull/2216), I noticed that there was a name clash with functions in the souffle system and UDFs.

My suggestion is to have an own functor namespace for user-defined functors so that there won't be a name clash in future. I.e., finding out that there is a name clash could be time-consuming for developers writing UDFs.

**Comment by quentin** [comment]
Hi @b-scholz, we are experimenting an alternative solution where functors can also be setup programmatically by passing a name and the equivalent of a function pointer.  This allow fine-grained control of functor binding.

**Comment by b-scholz** [comment]
Oh - my solution was very rough. I just stumbled into a name clash with the Souffle system. 
Function pointers are great but you may lose performance by having this indirection. 

We also have this issue that functors are invoked several times with the same arguments inside a rule (esp. for recursive rules because we need to simulate the previous knowledge, i.e., current - delta, with a negation).

To make the execution more efficient, we could store the result of a functor in a tuple so that it can be accessed multiple times rather than recomputing the result for multiple uses (cf. `ResolveAliases.cpp`).

**Comment by b-scholz** [comment]
I close this issue - perhaps we can open a new issue with your proposal so that it is not lost.
