### ISSUE TITLE
souffle does not properly escape shell arguments when calling mcpp

### ISSUE THREAD

**Issue by ddehaasgt** [souffle-lang/souffle#2235]
This causes failure when running souffle against files/directories that contain spaces, parentheses, or other shell-escapable characters.
This primarily seems to be problematic for include directories ("-I") and the datalog program itself.

Example:
```
$ mkdir "/tmp/()"                                                                                                                                          
$ echo "// Empty" > "/tmp/()/test.dl"
$ souffle "/tmp/()/test.dl" 
sh: 1: Syntax error: "(" unexpected
```

Unfortunately, simply escaping the arguments is non-trivial because of the way that `takesMany` concatenates multiple values into a single string (via " ", which is not safe) and then splits it by " " again later.

**Comment by b-scholz** [comment]
Could you fix it? Could you convert the arguments of mcpp with stringify (which does the escaping etc.) in main.cpp ?

**Comment by ddehaasgt** [comment]
My bad. I went to pull `master` to reproduce and fix it, and its already been resolved. This issue can be closed.
