### ISSUE TITLE
Subsumption related segfault

### ISSUE THREAD

**Issue by pnwamk** [souffle-lang/souffle#2239]
The following program triggers a segfault for me on both MacOS and Linux with the current HEAD (8fb6c11):
```
.decl City(n: symbol)

.decl PreferredRoute(?c1 : symbol, ?c2 : symbol)
PreferredRoute(?c1, ?c2) :-
  City(?c1),
  City(?c2),
  ord(?c1) <= ord(?c2).
// this (nonsensical) subsumtion rule is required for the segfault
PreferredRoute(?c1, ?c2) <= PreferredRoute(?c1, ?c2) :-
  ord(?c1) < ord(?c2).

.output PreferredRoute(IO=stdout)
```

The subsumptive rule is erroneous/nonsensical and perhaps should be triggering a user level error of some kind? Anyway, let me know if I can provide any additional context that would be useful.

**Comment by langston-barrett** [comment]
This might be a duplicate of #2228

**Comment by pnwamk** [comment]
Ah, apologies. That appears almost certainly to be the case, since the existence of a reflexive subsumption clause seems key. I'll close this issue.
