### ISSUE TITLE
Function for substrings, and other string manipulation

### ISSUE THREAD

**Issue by DominicRomanowski** [souffle-lang/souffle#224]
Add a function to cut strings into substrings, and other string manipulation.

eg. 
```
.decl inp(a:Text)
inp("abcdefg").

.decl outp(a:Text) output
outp(substr(a,1,3)) :- inp(a).

>>> "bc"

**Comment by Kostast23** [comment]
It would be very handy to have a substring function. Especially, one that does not only work as a constructor, i.e., returning a substring, but enables us to do some sort of pattern matching. For example, we could write `p(?pos) :- substring("a.b.c", ?pos, 1, ".")` to get the position(s) of "." in a string (1 denotes the length of the substring and not its end).

**Comment by lyndonhenry** [comment]
Substring and string length functors have been added as of pull requests  #328 and #330, and together with the existing `cat` functor I believe provide the minimal necessary mechanics to arbitrarily manipulate strings and perform pattern matching on them. The idea of implementing pattern matching as a relation means that Souffle would be required to have built in relations (it doesn't currently, only user defined relations exist), which is significantly different to a functor (which are only built in, and cannot be defined by the user). Certainly this is possible, perhaps even advantageous, but it is an entirely different ball game.

**Comment by b-scholz** [comment]
Unfortunately, functors cannot work as relations at the moment. The iteration space needs to be constructed manually for your example. Have a look here,

https://github.com/souffle-lang/souffle/blob/master/tests/semantic/string_substr1/string_substr1.dl

For the problem above, you could write:

```
.decl paux(x:number, s:string)
paux(0,"a.b.c").
paux(i+1,s) :- paux(i,s), i < strlen(s). 

.decl p(x:number)
p(?pos) :- paux(?pos,"a.b.c"), substr("a.b.c", ?pos, 1) = ".". 
```

**Comment by Kostast23** [comment]
:) I have been checking the test cases! Thank you for the quick responses and the examples!
