### ISSUE TITLE
Only computing the output relation (without I/O)

### ISSUE THREAD

**Issue by tomjerryMa** [souffle-lang/souffle#2253]
Hi,

Is there a way to avoid writing to a file?

I want to do some benchmarking on souffle, but I don't want to include the I/O time. It will be perfect if there is a way to achieve that!

I really appreciate any help you can provide.

**Comment by b-scholz** [comment]
Yes - just use `.printsize` instead of `.output`. 

Is this for a publication? If so, I can give you more precise measurement methods. Mind you - you will still have the runtime of .input included.
