### ISSUE TITLE
eqrels removed by default transformer pipeline

### ISSUE THREAD

**Issue by langston-barrett** [souffle-lang/souffle#2257]
Looks like https://github.com/souffle-lang/souffle/commit/59f2f949156e73798141b61317201d8cfe2ca0fb causes Souffle to remove eqrels by default:
```
.decl e(x: number, y: number) eqrel
e(0, 0).
e(x, x + 1) :-
  x < 100,
  e(x, x).
.printsize e
```
via `--show=transformed-datalog` becomes
```
.decl e(x:number, y:number) btree
e(0,0).

e(x,(x+1)) :- 
   x < 100,
   e(x,x).

e(x,z) :- 
   e(x,y),
   e(y,z).

e(x,y) :- 
   e(y,x).

e(x,x) :- 
   e(x,_).
```
A temporary workaround is to pass `--disable-transformers=ExpandEqrelsTransformer`.

**Comment by langston-barrett** [comment]
This is the sort of non-functional thing that could be caught with #2249.

**Comment by b-scholz** [comment]
Thanks for spotting this. Yes - indeed a performance regression test system would be wonderful. 
Do you have spare capacity to build it? I am happy to give some guidance.
