### ISSUE TITLE
Error: Unable to stratify relation(s)

### ISSUE THREAD

**Issue by sdifv** [souffle-lang/souffle#2266]
I'd like to simulate a process of routing prapogation：a node get the `BestOspfRoute` from (adj) `fromNode`, and then uses the aggregation function `min ` to compute the `BestOspfRoute` , and then propagates it to adjs until it reaches the fixpoint.
The main program is written as follows:
```
OspfRoute(node, prefix, origin, nhip, cost):-
    OspfIntf(node, _, prefix, _),
    origin = node,
    nhip = 0,
    cost = 0.

OspfRoute(node, prefix, origin, nhip, cost1+cost2):-
    BestOspfRoute(nextNode, prefix, origin, preNhip, cost1),
    OspfAdj(node, intf, nextNode, nextIntf),
    Intf(nextNode, nextIntf, nhip, _),
    OspfIntf(node, intf, _, cost2),
    preNhip != nhip,
    node != origin.

BestOspfRoute(node, prefix, origin, nhip, minCost):-
    OspfRoute(node, prefix, origin, nhip, _),
    minCost = min cost: OspfRoute(node, prefix, _, _, cost).
```
When I ran this souffle` program, I got a error:
```
Error: Unable to stratify relation(s) {BestOspfRoute,OspfRoute}
Relation OspfRoute in file ospf.dl at line 7
.decl OspfRoute(node: symbol, prefix: symbol, origin: symbol, nhip: unsigned, cost: unsigned)
------^---------------------------------------------------------------------------------------
has cyclic aggregation in file ospf.dl at line 35
    minCost = min cost: OspfRoute(node, prefix, _, _, cost).
------------------------^------------------------------------
1 errors generated, evaluation aborted
```
It seems like that souffle` can't handle the iterative compute process? Is there any suggestions to solve this problem? 
Thank you!

**Comment by b-scholz** [comment]
You need recursive aggregates which are currently developed. 
https://github.com/souffle-lang/souffle/pull/2263

It may work in 2-3 weeks with the new extension.

**Comment by sdifv** [comment]
OK, thanks for your contribution!

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: Bernhard Scholz ***@***.***>
发送时间: Tuesday, April 26, 2022 9:14:54 AM
收件人: souffle-lang/souffle ***@***.***>
抄送: Yhao ***@***.***>; Author ***@***.***>
主题: Re: [souffle-lang/souffle] Error: Unable to stratify relation(s) (Issue #2266)


You need recursive aggregates which are currently developed.
#2263<https://github.com/souffle-lang/souffle/pull/2263>

It may work in 2-3 weeks with the new extension.

―

**Comment by asejfia** [comment]
Any update as to when will the recursive aggregates be merged into main?

**Comment by b-scholz** [comment]
There are unforeseen delays with the staffing. Would you like to help? The current prototype works for the compiler but not for the interpreter.

**Comment by asejfia** [comment]
I found a workaround for my specific case but I'd be happy to help if the issue persists until after late August. Will write again to check.
