### ISSUE TITLE
Souffle 2.2 profiling on synthesized code doesn't compile

### ISSUE THREAD

**Issue by dbueno** [souffle-lang/souffle#2275]
I am running souffle 2.2 under macos. The attached file cannot be compiled and profiled at the same time. I used the command: `souffle -c -p s.prof ../test.dl` If I manually add the following `#include` line to the synthesized file, then compiling works.

```
#include "souffle/profile/Logger.h"
```

[test.dl.txt](https://github.com/souffle-lang/souffle/files/8710101/test.dl.txt)

**Comment by adamjseitz** [comment]
I believe this was fixed by https://github.com/souffle-lang/souffle/pull/2186, and should no longer occur if you update to 2.3.
