### ISSUE TITLE
Component inheritance breaks inner instantiation

### ISSUE THREAD

**Issue by dbueno** [souffle-lang/souffle#2298]
I'm not sure the right title for this issue. Here's an input file.

```
.comp A {
    .decl E(s: symbol, t: symbol)
    E("a", "b").
    E("b", "c").

    .comp A1 {
        .decl F(s: symbol, q:symbol)
        .decl R(s: symbol)

        F(s, t) :- E(s, t), R(t).
        F(s, t) :- F(q, t), E(s, q).
    }

    .init myA1 = A1
}

.comp B : A {}

.init myA = B  // CHANGE THIS TO .init myA = A
myA.myA1.R("c").
.output myA.myA1.F
```

Souffle 2.2 and 2.1 report:
```
Error: Undefined relation myA.myA1.R in file test.dl at line 22
myA.myA1.R("c").
^----------------
Error: Undefined relation myA.myA1.F in file test.dl at line 23
.output myA.myA1.F
--------^----------
```

But if you make the indicated change, it compiles fine. Am I missing something here? `B` inherits from `A` and adds nothing, so instantiating `B` should be essentially the same as instantiating `A`.

In my actual code, component `B` does contain declarations and rules, so eliminating `B` isn't a viable solution.

**Comment by quentin** [comment]
Hi, with a build on a recent version of the code your example runs correctly:
```
---------------
myA.myA1.F
s       q
===============
a       c
b       c
===============
```

Have you tried with release 2.3 for instance ?
