### ISSUE TITLE
Improve schedule algorithm for executing a rule

### ISSUE THREAD

**Issue by souffle-lang** [souffle-lang/souffle#23]
The query scheduling algorithm does not deliver high quality schedules. A better algorithm has to be deployed - perhaps even auto-tuning to improve the quality of the schedules.

**Comment by b-scholz** [comment]
Assume we have translated a rule to a loop-nest that has following structure:

```
for t1 in R1:
  for t2 in R2:
     ...
     for tk in Rk:
        if C(t1,....,tk) then
           project t1, ... , tk
```
Each loop in the loop nest traverses a relation `Rk`. The current tuple `tk` of relation `Rk` is used in the project condition `C(t1,...,tk)`. If the condition holds, the tuples are used as arguments for the project statement. The project statement produces a result tuple for the result table.

Let's assume that the projection condition `C(t1,...tk)` is a conjunction of terms, and terms operate on subset of tuples, i.e.,

```
C(t1, ..., tk) = C1(T1) /\ ... Cl(Tl)
```
where `Ci` are terms and `Ti` are subset of tuples, e.g., `{t1, t2, t5}`. If for a term, only a subset of tuples is required, we can hoist the term to the outer-most loop for which the term semantically is still correct. As a result, the iteration space of the loop nest becomes smaller. We do this for all terms.

In general, loop nests with traversals that have conditions have following structure:

```
for t1 in R1: C1'(t1)
  for t2 in R2: C2'(t1,t2)
     ...
     for tk in Rk: Ck'(t1,t2,...,tk)
           project t1, ... , tk
```

Note that the projection condition is now pushed up into the outer loops by breaking it up into terms.

The question is to find the loop order among the relations that has the smallest iteration space for all loops.
