### ISSUE TITLE
SWIG interface generation not working (.o file not found)

### ISSUE THREAD

**Issue by fgauthie** [souffle-lang/souffle#2305]
Trying to generate a SWIG interface currently triggers a file not found error.

Steps to reproduce:
1. Build Soufflé with `-DSOUFFLE_SWIG=ON`
2. Run SWIG tests: `ctest -j8 -L swig`

The issue is that `souffle-compile.template.py` builds the `.o` file name by using the absolute path to the output file instead of a relative path to the current working temporary directory: https://github.com/souffle-lang/souffle/blob/429e1681ce97c8a792f1e4577bf2e9001835daa6/src/souffle-compile.template.py#L153

Replacing with `cmd.append(os.path.basename(args.output) + ".o")` fixes the issue.

**Comment by quentin** [comment]
Hi, thanks for the investigation! Would you like to submit a pull request for this fix ?

**Comment by fgauthie** [comment]
Sure, see #2308
