### ISSUE TITLE
incorrect bshru

### ISSUE THREAD

**Issue by junghee** [souffle-lang/souffle#2310]
Souffle's `bshru` operator seems to produce incorrect value.

For example,

0x98000000 `bshru` 10

The result is supposed to be 0x260000.

However, Souffle produces

0x3fffffffe60000

**Comment by b-scholz** [comment]
Can you write a mini example that reveals the issue? 

There could be an overflow converting the hex number, or an incorrectly implemented shift operation is the cause of the problem.

**Comment by quentin** [comment]
Hi @junghee, could you share a datalog example and details about the Souffle version (`souffle -h`). Also do you know if Souffle was built with `SOUFFLE_DOMAIN_64BIT` ?

**Comment by junghee** [comment]
Hi @quentin, thank you for your response. When I was trying to create a toy datalog example for you, I realized that it is not a souffle problem, but a problem in my way of computing the expected result.
```
mov     r0, #0x98000000
mov     r1, #10
lsr     r0, r0, r1
```
When we decode the arm binary assembled from the above instructions, we get -1744830464 as the lhs value, which is 64-bit (sign-extended) 0xFFFFFFFF98000000, and our translated datalog souffle query produces the correct result, which is 0x3FFFFFFFF60000.
Whereas, I had a wrong assumption that the lhs value is 64-bit (zero-extended) 0x98000000, and the result is expected to be 0x260000.

Sorry for the false alarm.

Thank you again for your response.
