### ISSUE TITLE
list of soufflé front-ends?

### ISSUE THREAD

**Issue by monperrus** [souffle-lang/souffle#2314]
Hi all,

Is there a list of soufflé front-ends? (in particular, we're looking for a way to translate Javascript and Java to Soufflé facts).

Thanks!

--Martin

**Comment by b-scholz** [comment]
Please, read up on the DOOP project. It has a Java extractor based on the SOOT project. 
Unfortunately, we only have an incomplete list here:

https://souffle-lang.github.io/applications

We would be grateful to add more extractors/applications to the list if you could find more on the internet (there is an edit button).

**Comment by b-scholz** [comment]
I am not aware of an "open-source" Javascript extractor. Perhaps there is a possibility to reuse open-source Javascript static analyzers to build an extractor.

**Comment by monperrus** [comment]
Thanks!
