### ISSUE TITLE
Assertion failed with Provenance

### ISSUE THREAD

**Issue by DerZc** [souffle-lang/souffle#2316]
Hi,

I run the following code with ```souffle -F. -D. -t none orig_rules.dl```, then I get assertion failed.

```
Requested arity not yet supported. Feel free to add it.
souffle: /souffle/src/include/souffle/utility/MiscUtil.h:217: void souffle::fatal(const char*, const Args& ...) [with Args = {}]: Assertion `false && "fatal error; see std err"' failed.
```

[temp.zip](https://github.com/souffle-lang/souffle/files/9712909/temp.zip)

But the command ```souffle -F. -D. orig_rules.dl``` runs successfully.

The version of souffle is ```2.3```.

**Comment by b-scholz** [comment]
This is not a bug - it is a feature. The interpreter de-specializes relational data structures (see PLDI'21). Therefore, we cannot have an arbitrary number of arities for relations in the interpreter and must establish an upper bound on the arity. If we substantially increase the arity number, the compile time of Souffle becomes unacceptable.

**Comment by DerZc** [comment]
Of course, thank you for your prompt answer!

**Comment by DerZc** [comment]
So does this means we only can use limited number of arities with Provenance. Because it runs successfully with Provenance.

**Comment by b-scholz** [comment]
If you added the flag `-c`, it should work out of the box. 

The number of arities per relation type is defined here: 
https://github.com/souffle-lang/souffle/blob/master/src/interpreter/Util.h

The de-specialization only works by specializing the data structures ahead of time (with its arity). The interpreter cannot re-compile itself quickly for an unobserved arity yet.

**Comment by DerZc** [comment]
I tried just now and I got it. Thank you for your careful answer.

**Comment by quentin** [comment]
Relates to https://github.com/souffle-lang/souffle/issues/2311#issuecomment-1268522495
