### ISSUE TITLE
A question about the semantic of the negative

### ISSUE THREAD

**Issue by DerZc** [souffle-lang/souffle#2317]
Hi,

I have a question about the semantic of negative.

There is an datalog program:
```
.decl a(A:number, B:number)
.decl b(A:number, B:number)
.decl c(A:number)

.input a
.input b

c(A):- a(A, B), !b(_, _).
.output c
```

The input of `a` is `1        2`, the input file of `b` is `3        4`. Then the output of c is empty. But since there are no same variables in `a` and `b`, so the results should be same no matter `!b(_, _)` or `b(_, _)`, right?

I run this program in z3
```
Z 64

a(A:Z, B:Z) input
b(A:Z, B:Z) input
c(A:Z) printtuples

a(1, 2).
b(3, 4).

c(A) :- a(A, B), !b(_, _).
```
The result is `1`, has the different with Souffle.

**Comment by DerZc** [comment]
When I remove the data in b.facts and give an empty input to `b`, the result of `c` is `1`.

**Comment by b-scholz** [comment]
Z3's semantics might not be quite right. In my view, I would read the predicate `!b(_,_)` that there must not exist a tuple in `b`.  Note that there are different interpretations w.r.t. negation in Datalog.

**Comment by DerZc** [comment]
Sure, maybe this is not in the scope of what z3 deal with as [this](https://github.com/Z3Prover/z3/issues/6389).

We can close this issue.
