### ISSUE TITLE
g++-11: The build tool has reset ENV; --env=std required.

### ISSUE THREAD

**Issue by trganda** [souffle-lang/souffle#2325]
I have install the souffle with homebrew on mac monterey version 12.6 (chip:m1 max)

```
brew install --HEAD souffle-lang/souffle/souffle
```

After that, follow the [soufffle example](https://souffle-lang.github.io/simple), everything is ok until run
```
souffle -F. -D. -oexample example.dl
```

I got a error
 
```
g++-11: The build tool has reset ENV; --env=std required.
failed to compile C++ sources
```

And I'm try to compile the generated source code `example.cpp` manually.
```
cc -I/opt/homebrew/opt/souffle/include -std=c++11 example.cpp
```
but it's not work, more error produce.

TL, DR
```
In file included from example.cpp:1:
In file included from /opt/homebrew/opt/souffle/include/souffle/CompiledSouffle.h:20:
/opt/homebrew/opt/souffle/include/souffle/RecordTable.h:55:32: error: no member named 'data' in namespace 'std'
    return recordTab.pack(std::data(initlist), initlist.size());
                          ~~~~~^
In file included from example.cpp:1:
In file included from /opt/homebrew/opt/souffle/include/souffle/CompiledSouffle.h:21:
/opt/homebrew/opt/souffle/include/souffle/SignalHandler.h:146:19: error: no member named 'is_always_lock_free' in 'std::atomic<const char *>'; did you mean '__atomic_always_lock_free'?
    static_assert(decltype(msg)::is_always_lock_free, "cannot safely use in signal handler");
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  __atomic_always_lock_free
/opt/homebrew/opt/souffle/include/souffle/SignalHandler.h:146:34: note: '__atomic_always_lock_free' declared here
    static_assert(decltype(msg)::is_always_lock_free, "cannot safely use in signal handler");
                                 ^
/opt/homebrew/opt/souffle/include/souffle/SignalHandler.h:146:34: error: builtin functions must be directly called
    static_assert(decltype(msg)::is_always_lock_free, "cannot safely use in signal handler");

// more error info ignored.
```

**Comment by quentin** [comment]
Hi trganda,

## Manual compilation

When compiling manually with gcc you should use C++17, try `cc ... -std=c++17`. But you may need even more options before a successful build.

## Possible fix of `souffle-compile.py`
The root cause is likely the setup in `souffle-compile.py` that has been generated by during the build of Souffle by `brew`.

**Could you share the content of the ~30 first lines of `souffle-compile.py`** that should be the `JSON_DATA_TEXT` variable ?

This variable contains all the options that `souffle` eventually pass to the compiler. It should contain a line like `"std_flag": "-std=c++17",`.

## Possible brew formula fix

The error `The build tool has reset ENV; --env=std required.` seems recurrent, could you also try the fix (adding `env :std` to the `souffle` formula) discussed here for another brew formula: https://github.com/ska-sa/homebrew-tap/issues/20

## Status of Apple M1 hardware support

The Souffle project does not have continuous integration for Apple M1 hardware, so supporting this architecture is currently difficult. Your help is welcomed.

**Comment by trganda** [comment]
Thanks for your suggestion @quentin.

When the first time I encounter this problem, I have search and read the [https://github.com/ska-sa/homebrew-tap/issues/20](https://github.com/ska-sa/homebrew-tap/issues/20). And try to manual replace the default compiler of brew to the manually installed gcc (with path `/opt/homebrew/opt/gcc/bin/g++-12`), see [xlla comment](https://github.com/ska-sa/homebrew-tap/issues/20#issuecomment-905707294).

After that the info `g++-11: The build tool has reset ENV; --env=std required.` was disappear, and it's tips the `include file no found`. So I have tried the way in the previous comment `cc -I/opt/homebrew/opt/souffle/include -std=c++11 example.cpp` and take this issue because I don't know how souffle call the outside compiler to compile c/c++ file.

But you comment help me known what's the possible reason.

## souffle-compile.py

The JSON_DATA_TEXT was below

```
#!/usr/bin/env python3
JSON_DATA_TEXT = """{
  "compiler": "/opt/homebrew/Library/Homebrew/shims/mac/super/g++-11",
  "compiler_id": "AppleClang",
  "compiler_version": "14.0.0.14000029",
  "msvc_version": "",
  "includes": "-I/tmp/souffle-20221019-29532-1c32bqh/src/include -I/Library/Frameworks/Mono.framework/Headers",
  "std_flag": "-std=c++17",
  "cxx_flags": "",
  "cxx_link_flags": "-Wl,-search_paths_first -Wl,-headerpad_max_install_names",
  "release_cxx_flags": "-O3 ",
  "debug_cxx_flags": "-g",
  "definitions": "-DUSE_NCURSES -DUSE_LIBZ -DUSE_SQLITE",
  "compile_options": "",
  "link_options": "/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib/libsqlite3.tbd /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib/libz.tbd /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib/libncurses.tbd",
  "rpaths": "/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib:/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib:/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib",
  "outname_fmt": "-o {}",
  "libdir_fmt": "-L{}",
  "libname_fmt": "-l{}",
  "rpath_fmt": "-Wl,-rpath,{}",
  "path_delimiter": ":",
  "exe_extension": "",
  "source_include_dir": "/tmp/souffle-20221019-29532-1c32bqh/src/include",
  "jni_includes": ":"
}"""

# --- JSON_DATA_TEXT variable is inserted before this line ---
```

Run below command
```
/opt/homebrew/bin/souffle-compile.py -oexample -v example.cpp
```

The output show

```
"/opt/homebrew/Library/Homebrew/shims/mac/super/g++-11" -DUSE_NCURSES -DUSE_LIBZ -DUSE_SQLITE  -I/tmp/souffle-20221019-95509-1k7wa6m/src/include -I/Library/Frameworks/Mono.framework/Headers -std=c++17  -O3  -o /Users/trganda/Projects/pratices/datalog/example /Users/trganda/Projects/pratices/datalog/example.cpp /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib/libsqlite3.tbd /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib/libz.tbd /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib/libncurses.tbd -Wl,-rpath,/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib -Wl,-rpath,/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib -Wl,-rpath,/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib
```

On my machine, `/opt/homebrew/Library/Homebrew/shims/mac/super/g++-11` linked to `/opt/homebrew/Library/Homebrew/shims/super/cc`. I'm not familiar with `homebrew`, so I'm not sure what the different of this compiler with the buildin compiler or the manually installed gcc/clang by `brew`.


## Solving

I'm try the different compiler of my machine.

* buildin gcc compiler, Apple clang version 14.0.0 (clang-1400.0.29.102) (`/usr/bin/g++`)
* gcc installed with `brew install gcc`, version 12.2.0 (`/opt/homebrew/opt/gcc/bin/g++-12`)
* clang installed with `brew install llvm`, version 15.0.2 (`/opt/homebrew/opt/llvm/bin/clang++`)

I have replace the `"/opt/homebrew/Library/Homebrew/shims/mac/super/g++-11"` with the path of there compiler, and replace the include path `/tmp/souffle-20221019-95509-1k7wa6m/src/include` to `/opt/homebrew/opt/souffle/include`

Run

```
/opt/homebrew/opt/gcc/bin/g++-12 -DUSE_NCURSES -DUSE_LIBZ -DUSE_SQLITE  -I/opt/homebrew/opt/souffle/include -I/Library/Frameworks/Mono.framework/Headers -std=c++17  -O3  -o /Users/trganda/Projects/pratices/datalog/example /Users/trganda/Projects/pratices/datalog/example.cpp /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib/libsqlite3.tbd /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib/libz.tbd /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib/libncurses.tbd -Wl,-rpath,/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib -Wl,-rpath,/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib -Wl,-rpath,/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib
```

It's work. For future work, I'm modified the `JSON_DATA_TEXT` of `souffle-compile.py` file, as show below
```
JSON_DATA_TEXT = """{
  "compiler": "/usr/bin/g++",
  "compiler_id": "AppleClang",
  "compiler_version": "14.0.0.14000029",
  "msvc_version": "",
  "includes": "-I/opt/homebrew/opt/souffle/include -I/Library/Frameworks/Mono.framework/Headers",
  "std_flag": "-std=c++17",
  "cxx_flags": "",
  "cxx_link_flags": "-Wl,-search_paths_first -Wl,-headerpad_max_install_names",
  "release_cxx_flags": "-O3 ",
  "debug_cxx_flags": "-g",
  "definitions": "-DUSE_NCURSES -DUSE_LIBZ -DUSE_SQLITE",
  "compile_options": "",
  "link_options": "/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib/libsqlite3.tbd /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib/libz.tbd /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib/libncurses.tbd",
  "rpaths": "/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib:/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib:/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib",
  "outname_fmt": "-o {}",
  "libdir_fmt": "-L{}",
  "libname_fmt": "-l{}",
  "rpath_fmt": "-Wl,-rpath,{}",
  "path_delimiter": ":",
  "exe_extension": "",
  "source_include_dir": "/opt/homebrew/opt/souffle/include",
  "jni_includes": ":"
}"""
```

Now, the `souffle -F. -D. -oexample example.dl` was work too.

## Future Test

From the previous test, I think the problem was the `souffle-compile.py` file.

After reading the source code, the `souffle-compile.py` was generated by https://github.com/souffle-lang/souffle/blob/master/src/CMakeLists.txt#L518.

The fixed data of `JSON_DATA_TEXT` are related to

* compiler -> `${SOUFFLE_COMPILED_CXX_COMPILER}` -> specify by `-DCMAKE_CXX_COMPILER` in `souffle.rb`
* includes -> `${SOUFFLE_COMPILED_INCLUDES}`
* source_include_dir -> `${CMAKE_CURRENT_SOURCE_DIR}/include`

The compiler can be specified by replace `-DCMAKE_CXX_COMPILER=g++-11` to `-DCMAKE_CXX_COMPILER=/usr/bin/g++` in `souffle.rb`. But while install `souffle` with `brew install --HEAD souffle-lang/souffle/souffle`, the source code looks like clone into /tmp dir resulting in the the `includes` and `source_include_dir` refer to a no exists path.

If want to fix this issue (I'm not sure where this problem occurs in other computer with m1/m2 serials chip.) , may be the code of [homebrew-souffle](https://github.com/souffle-lang/homebrew-souffle/blob/master/Formula/souffle.rb) should be modified. I'm not familiar with brew and ruby, and hope this can fix in future time. At the same time, I'll try to do that and take a pull request if I solve it gracefully.
