### ISSUE TITLE
Component ADTs cannot round trip through .input and .output even with rfc4180=true

### ISSUE THREAD

**Issue by bmeck** [souffle-lang/souffle#2349]
```prolog
.comp Component {
  .type ADT = A {}
  .decl Relation(value: ADT)
}
.init Instance = Component
Instance.Relation($Instance.A()).
.input Instance.Relation(filename="out.csv", rfc4180=true)
.output Instance.Relation(IO=stdout, headers=true)
```

Produces a `out.csv` with:

```csv
"$Instance.A"
```

When run against the same program with `.input` instead of `.output` for `"out.csv"` an error is produced:

```console
$ souffle test.dl
Error loading Instance.Relation data: Error converting <$Instance.A> in column 1 in line 1; cannot parse fact file out.csv!
```

**Comment by bmeck** [comment]
This appears to be caused by https://github.com/souffle-lang/souffle/blob/a508ae4671338af7a934a659d07d3316329e822b/src/include/souffle/io/ReadStream.h#L152 reading only an identifier not a qualified name.

**Comment by quentin** [comment]
Good catch! Would you like to work on a fix?
Also, did you try with other `IO` methods like `json` and `sqlite` ?

**Comment by bmeck** [comment]
Sure. Can do

**Comment by bmeck** [comment]
JSON doesn't support ADT at all it seems due to lack of `'+'` in writing and reading, SQLite seems to write stuff to the DB, but misses data? SQLite does not support reading ADTs due to lack of `'+'` support.

Example used for this:

```prolog
.comp Component {
  .type ADT = A {} | B { s: symbol }
}

.init Instance = Component
.decl Rel(n: number, key: Instance.ADT)
Rel(-1, $Instance.A()).
Rel(-2, $Instance.B("test")).
Rel(-3, $Instance.B("test")).
.output Rel(IO=sqlite)
```

SQLite appears to record branch data but nothing with the symbols and `__SymbolTable` is empty.
