### ISSUE TITLE
Missing ability to integrate interpreter into C++?

### ISSUE THREAD

**Issue by Xazax-hun** [souffle-lang/souffle#2365]
If one already integrated the C++ compiler into a project, e.g., it can programmatically populate input relations, and process the output relations, it would be great if it was possible to use the interpreter for quick experiments when one does not need to change the input relations. This would save the time of recompiling everything, and the interpreter should be sufficiently fast for smaller inputs.

**Comment by quentin** [comment]
Hi, I am currently integrating changes that goes into this direction: reuse of the souffle library. Stay tuned.

**Comment by quentin** [comment]
The souffle main driver is now usable as a library, see `MainDriver.h` in #2366.

There is a usage example in test https://github.com/souffle-lang/souffle/blob/master/tests/libsouffle_interface/vfs_overlay_test.cpp

Note that the souffle library interface is subject to changes at any time without guarantee of compatibility.
