### ISSUE TITLE
`inline` in recursive query trigger an error number of atoms bug in query plan

### ISSUE THREAD

**Issue by DerZc** [souffle-lang/souffle#2370]
Hi,

Consider the following program:
```
.decl crno(A:symbol) inline
.decl feja(A:symbol) inline
.decl wpnh(A:symbol, B:symbol)
.decl jypl(A:symbol, B:symbol)
.decl uzfj(A:symbol) btree

jypl("a", "b").

feja(A) :- crno(A).
wpnh(B, B) :- feja(B).
uzfj(B) :- jypl(B, B).
crno(B) :- uzfj(A), jypl(B, A).
jypl(B, A) :- wpnh(A, B), feja(A).
.plan 0:(2,1)

.output jypl
```
I run it with "souffle example.dl" and get the error message:
```
Error: Invalid execution order in plan (expected 3 atoms, not 2) in file example.dl at line 14
.plan 0:(2,1)
--------^-----
```
But there are only two subgoals in the rule of `jypl`, so can not be 3 atoms. I can avoid this error by removing any `inline` in this program.

The version of souffle is `b8b1d69`.

**Comment by quentin** [comment]
Hi,
The `jypl(B,A)` clause has 3 atoms after inlining:

```
jypl(B,A) :- wpnh(A, B), feja(A).
=>
jypl(B,A) :- wpnh(A, B), crno(A).
=>
jypl(B,A) :- wpnh(A, B), uzfj(A2), jypl(A, A2).
``` 

The plan applies to the clause after inlining, so it is expecting 3 atoms instead of 2 in the non-inlined clause.

**Comment by DerZc** [comment]
Hi, 
I got it, thank you very much! 

But maybe sometimes it may be difficult to calculate the query plan, especially when the program is large and there are many inline relations.
