### ISSUE TITLE
Race condition suppresses helpful parse error messages

### ISSUE THREAD

**Issue by adamjseitz** [souffle-lang/souffle#2386]
In Souffle 2.2, when processing ddisasm datalog sources, if a syntax error was present, we would get an error like:

```
$ souffle src/datalog/main.dl -g /tmp/souffle_disasm_arm32.cpp -MARCH_ARM32
Error: syntax error, unexpected identifier, expecting . in file code_inference.dl at line 108
    arch.delay_slot(From,To).
----^-------------------------
1 errors generated, evaluation aborted
```

However, in 2.3 and newer, we observe this, instead:

```
$ souffle src/datalog/main.dl -g /tmp/souffle_disasm_arm32.cpp -MARCH_ARM32
Pre-processors command failed with code 36096: '/usr/bin/mcpp -e utf8 -W0 -I "."  -DARCH_ARM32 -DRAM_DOMAIN_SIZE=64 "main.dl"'
terminate called after throwing an instance of 'std::runtime_error'
  what():  Pre-processor command failed
```

This new error message is introduced in fe7f9479da7741d4e134dafc8e131df927b0bfe6, which adds the return code check:

```cpp
    } else if (preprocessor_status != 0) {
        std::cerr << "Pre-processors command failed with code " << preprocessor_status << ": '" << cmd
                  << "'\n";
        throw std::runtime_error("Pre-processor command failed");
```

I tried to find a minimal example to reproduce it, and found when reducing the ddisasm source, as the input got smaller, the error became increasingly intermittent.

I found with `strace` that in the failing case, `mcpp` is terminated by `SIGPIPE`. It seems that the parser closes in the input stream (which is the output of the `mcpp` process) when encountering the parsing error. A race exists between `mcpp` finishing preprocessing and the parser closing the pipe.

One simple fix is to move the `endInput()` call until after parser errors are checked:

```diff
diff --git a/src/main.cpp b/src/main.cpp
index 8f4ba085c..3c4e79925 100644
--- a/src/main.cpp
+++ b/src/main.cpp
@@ -607,7 +607,6 @@ int main(int argc, char** argv) {
     DebugReport debugReport;
     Own<ast::TranslationUnit> astTranslationUnit = ParserDriver::parseTranslationUnit(
             InputPath.string(), Input->getInputStream(), errReport, debugReport);
-    Input->endInput();

     /* Report run-time of the parser if verbose flag is set */
     if (Global::config().has("verbose")) {
@@ -631,6 +630,7 @@ int main(int argc, char** argv) {

     // ------- check for parse errors -------------
     astTranslationUnit->getErrorReport().exitIfErrors();
+    Input->endInput();

     // ------- rewriting / optimizations -------------
```

However, I don't think this is the best solution. It seems like it might be nicer to prevent the parser from closing the pipe, so that a true `mcpp` error takes precedence over parsing errors. I could not figure out how to change the parser's behavior in this respect. Maybe someone with more familiarity with bison/flex could take a look.

**Comment by quentin** [comment]
`endInput()` should probably not raise an exception by itself, since it returns a boolean indicating success/failure.

It would be more robust to read the whole pre-processor's output (`Input->getInputStream()`) to a buffer, then check `endInput()` and only then call Souffle parser with that buffer.
