### ISSUE TITLE
Extensional Higher-Order Datalog

### ISSUE THREAD

**Issue by v217** [souffle-lang/souffle#239]
Can Soufflé be extended to accept Extensional Higher-Order Datalog as described in the very short paper:

[Kountouriotis, Vassilis, Panos Rondogiannis, and William W. Wadge. "Extensional higher-order datalog." Proceedings of the 12th International Conference on Logic for Programming, Artificial Intelligence and Reasoning (Short Paper). 2005.](https://scholar.google.com/scholar?hl=en&q=Extensional+Higher-Order+Datalog)

Thanks!

**Comment by b-scholz** [comment]
This is a very interesting proposal to extend Soufflé. I don't see why not. Of course, it is a question of engineering details. Perhaps we can talk in more detail via Skype.

**Comment by v217** [comment]
Reading the enthusiastic [blog post](https://billwadge.wordpress.com/2016/01/18/extensional-higher-order-prolog/) by Bill Wadge, I first heard about this line of research. (Even though the blog post is about prolog, the ideas and added expressiveness are true for datalog as well.)

https://billwadge.wordpress.com/2016/01/18/extensional-higher-order-prolog/
