### ISSUE TITLE
Maybe there is a clerical error in official doc.

### ISSUE THREAD

**Issue by fynch3r** [souffle-lang/souffle#2391]
Hi, I found a clerical error in official doc , please check it.

https://souffle-lang.github.io/types#algebraic-data-types-adt

> Alebraic Data Types are extended versions of records, which permit several type shapes for an ADT. Each shape in the ADT we call a branch. A branch is defined similar to a record, however, it has a unique branch identifier.

Maybe first word of the above paragraph should be "Algebraic".

**Comment by quentin** [comment]
Hi, thanks for noticing this error, would you like to submit a fix in [https://github.com/souffle-lang/souffle-lang.github.io/blob/master/pages/docs/types.md ?](https://github.com/souffle-lang/souffle-lang.github.io/blob/333dfd90984caa6852fe5931174ca6a7029aee7b/pages/docs/types.md?plain=1#L240) ?
