### ISSUE TITLE
Souffle 2.4 release?

### ISSUE THREAD

**Issue by aeflores** [souffle-lang/souffle#2393]
Hi,
It has been quite long since the last Souffle release (May 2022) and a lot of improvements have taken place since then. Would you consider doing a new release soon?

**Comment by ruricolist** [comment]
@quentin We heard from @b-scholz who suggested we synchronize with you and your team to create a new release.

**Comment by b-scholz** [comment]
Please can you have a look here:
https://github.com/souffle-lang/souffle/wiki/Release-process

It might be outdated but the idea is to summarise the changes in a release note  (acknowledging the contributors and listing the changes). The changelog should be updated in its own new PR:
https://github.com/souffle-lang/souffle/blob/master/debian/changelog

and a post should be created. For example, an old post looks like this:
https://github.com/souffle-lang/souffle-lang.github.io/blob/master/_posts/2020-09-25-release.md

After the PR with the new release note is merged, the create release button is to be pressed. 
I hope this helps.

**Comment by quentin** [comment]
Hi, I'll try to create a new release version.
Are we happy with the current state of the main branch? Any bug/issue we would like to fix before the release?

**Comment by b-scholz** [comment]
Thanks! That would be wonderful!
