### ISSUE TITLE
A problem about souffle-2.3？

### ISSUE THREAD

**Issue by lwy0518** [souffle-lang/souffle#2395]
Hello! After I downloaded the souffle-2.3 installation package, then I entered the "souffle-addon" and executed the command "make -j8", and the following error occurred:
![image](https://user-images.githubusercontent.com/72444130/218382821-3b0c40f0-58f4-4e6f-9f34-53c80d00313d.png)

What is the reason for this problem? Looking forward to your reply.

**Comment by quentin** [comment]
Hi, can you provide some detailed reproduction steps ?

**Comment by lwy0518** [comment]
Hi. I'm so sorry, it may be a problem with my downloaded project--"gigahorse". At present, I have successfully installed souffle-2.3, and I don't know the reason for the above problem.
