### ISSUE TITLE
Parser: address boundary error

### ISSUE THREAD

**Issue by ceclin** [souffle-lang/souffle#2408]
I currently use the latest release (2.4), which is installed on windows wsl2 (ubuntu) following the [installation guide](https://souffle-lang.github.io/install#debianubuntu-systems).

Address boundary error occurs if input is a file with following content:
```
x
```

Example:
```
> souffle x.dl
Error: syntax error, unexpected end of file, expecting ( or . in 
fish: Job 1, 'souffle x.dl' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by ceclin** [comment]
I tried some debugging. Here is something that may be helpful. 
(I am not sure since I am new to souffle's source code)

https://github.com/souffle-lang/souffle/blob/b60c8e9f3b9cc6b3e8b980a44fa53033328accee/src/parser/scanner.ll#L411-L417
`yylloc.file` is empty after `yyinfo.pop();`

A possible patch:
https://github.com/souffle-lang/souffle/blob/b60c8e9f3b9cc6b3e8b980a44fa53033328accee/src/parser/SrcLocation.cpp#L142-L144
```cpp
    if (yylloc.file) Frames.push(yylloc);
    yylloc.file = NewFile;
    yylloc.start = yylloc.end = {1, 1};
```

**Comment by quentin** [comment]
The root cause is that we pop the last valid context frame before creating the last token, hence `yylloc`  is the empty location.
