### ISSUE TITLE
SQLite reader silently replaces empty strings with "n/a"

### ISSUE THREAD

**Issue by dbueno** [souffle-lang/souffle#2411]
https://github.com/souffle-lang/souffle/blob/9aca1614a8865476abd681f17544dc9032dbb186/src/include/souffle/io/ReadStreamSQLite.h#L69

I use empty strings all over the place in my Souffle code. I recently switched from using CSVs to using SQLite and souffle doesn't preserve the content of tuples that had empty strings. Instead, after import, the empty strings are replaced with the string "n/a". I don't think this should be done; import should preserve what was exported.

Is there a workaround for this?

**Comment by quentin** [comment]
I agree that the current logic seems wrong, especially for strings.
I don't see any workaround, it requires a fix.
