### ISSUE TITLE
Ability To Project Records In Rules

### ISSUE THREAD

**Issue by chrisnevers** [souffle-lang/souffle#2436]
Hello, I can't tell from the documentation whether or not I should be able to access record fields or do some form of deconstruction in a rule. I have an example below of what I thought would work. Hopefully it's apparent and you can let me know the preferred way of doing it.

```Datalog
.pragma "fact-dir" "."
.pragma "output-dir" "-"

.type Person =
  [ id : symbol
  , name : symbol
  , mother : symbol
  , father : symbol ]

.decl person(id: symbol, name: symbol, mother: symbol, father: symbol)
.input person(delimiter=",", headers="true")

.decl PersonRec(p: Person)
PersonRec([ id, name, mother, father ]) :- person(id, name, mother, father).

.decl parent(P: Person, C : Person)
parent(P, C) :-
  PersonRec(P), // if parent is a person
  PersonRec(C), // if child is a person
  ( P.id = C.mother ; P.id = C.father ). // if the parent's id is equal to either of the child's parent's id
  // ^ this errors
```

I was also wondering, is it possible to read a csv directly into a corresponding record? For example, I'm manually creating a rule in the example to construct a record

**Comment by quentin** [comment]
Hi, the projection from records is not supported currently.
You really have to perform the destruction yourself:

```
P = [id, _a, _b, _c],
C = [_d, _e, mother, father],
(id = mother ; id = father)
```

Which is not very practical. Also note that Souffle does not let you use `_` in the deconstructions and you have to provide dummy named variables for fields that you don't use (again a limitation that could be removed with a bit of work). The `_` prefix tells Souffle it's ok if these variables are not used.
