### ISSUE TITLE
Copyright/License headers

### ISSUE THREAD

**Issue by scyptnex** [souffle-lang/souffle#244]
This is basically a TODO:

some new files don't have the correct copyright header blocks, probably its time again for us to fix this.

Our copyright practices are:

 * we are "The Souffle Developers" (no accent), all our source files (those not created by Oracle) say that is the owner.
    * if you would like to copyright something as your own it must be under the UPL, and it may not pass code review.
 * Copyright dates should reflect (1) when a file was **first created** and (2) **most recently updated** by a holder. (so no more of that Copyright "2013, 2014, 2016...", it offers no greater legal protection than just "2013, 2016")
 * Original owners only.  If we modify one of Oracle's files (even extensively) we still say it is their copyright (as they must do if they modify one of ours, not that that will ever happen). this whole "Copyright 20XX Foo, Modified 20XY Bar" just means that Bar cant protect the work at all, and Foo cant protect the work in the breif window between 20XX copyright expiring and 20XY expiring.
    * Oracle is a giant heartless multinational corporate entity, if there's one thing we can count on them to do its to defend copyright we claim is theirs to defend :P

Our options ordered by effort are:

1. Find all the files that dont have the copyright header and add them manually

2. Adopt a copyright managament tool to do the above, as well as conform all the current license/copyright notices

3. Do the above, and add a test to the test suite that inspects the source files and fails if you forget to put the notice there.

**Comment by mmcgr** [comment]
I'm closing this as we have the header blocks in place now.

There are still no automated checks so this issue "may" be re-opened in future.
