### ISSUE TITLE
 Performance in interpreter mode

### ISSUE THREAD

**Issue by jsjzgy** [souffle-lang/souffle#2468]
![image](https://github.com/souffle-lang/souffle/assets/57884913/83482703-57ef-4779-bcdd-4e4af0fe69af)
When using souffle to execute large test cases, the performance in interpreter mode is very low. I would like to ask if you have any good suggestions to optimiz
[test.tar.gz](https://github.com/souffle-lang/souffle/files/14110083/test.tar.gz)

**Comment by quentin** [comment]
Hi,
- What version of Souffle are you using?
- How does runtime compares with compiled mode?
- Does multithreading helps (`-j N`) ?
- You may want to select a different SIPS heuristic, for instance `.pragma "RamSIPS" "delta-max-bound"`. See [https://github.com/souffle-lang/souffle/blob/42e432b3c56160431d43072bc98ec60828439b6c/src/ast2ram/utility/SipsMetric.cpp#L322](https://github.com/souffle-lang/souffle/blob/42e432b3c56160431d43072bc98ec60828439b6c/src/ast2ram/utility/SipsMetric.cpp#L322)

Then it really depends on your program.
If some rules are specifically slow, looking at the `RAM` intermediate representation (`--show transformed-ram`) may help spot an issue. Then crafting dedicated `.plan` may help if the scheduling of the rule is not optimal.

**Comment by jsjzgy** [comment]
> Hi,
> 
> * What version of Souffle are you using?
> * How does runtime compares with compiled mode?
> * Does multithreading helps (`-j N`) ?
> * You may want to select a different SIPS heuristic, for instance `.pragma "RamSIPS" "delta-max-bound"`. See https://github.com/souffle-lang/souffle/blob/42e432b3c56160431d43072bc98ec60828439b6c/src/ast2ram/utility/SipsMetric.cpp#L322
> 
> Then it really depends on your program. If some rules are specifically slow, looking at the `RAM` intermediate representation (`--show transformed-ram`) may help spot an issue. Then crafting dedicated `.plan` may help if the scheduling of the rule is not optimal.
. The Souffle version used is 2.4.1
. Using '-PSIPS:delta-max-bound', the results do not result in a significant improvement in performance
. The attachment is with 'time ./src/souffle -F.. /.. /tests/database/java-sec-code -D ./result .. /.. /tests/rules/2.dl -j20 --wno all --no-warn --show transformed-ram' command

[ram.txt](https://github.com/souffle-lang/souffle/files/14119612/ram.txt)
