### ISSUE TITLE
An exception unhandled in MainDriver.cpp

### ISSUE THREAD

**Issue by Mz1z** [souffle-lang/souffle#2470]
I build this on windows, and throw this exception.
Does here need a try catch?
![image](https://github.com/souffle-lang/souffle/assets/91617089/c829fe04-3d57-4df3-bb6c-1979c194f619)

**Comment by Mz1z** [comment]
I found the problem! here need add ".exe" to find the real file:
![image](https://github.com/souffle-lang/souffle/assets/91617089/c342d464-6b7a-4452-8d9f-95181a9c3931)

**Comment by Mz1z** [comment]
I solve the problem like this:
```cpp
#ifdef _WIN32
inline bool isExecutable(const std::string& name) {
    std::string win_name = name + ".exe";
    return existFile(
            name) || existFile(win_name);  // there is no EXECUTABLE bit on Windows, so theoretically any file may be executable
}
#else
```

**Comment by Mz1z** [comment]
> Hi, Your environment probably does not have the command `mcpp` or `gcc`, maybe because you are on Windows.
> 
> If your C pre-processor command is neither `mcpp` nor `gcc` you can either not use a pre-processor at all (`souffle --no-preprocessor`) or use the C pre-processor of your choice with `souffle --preprocessor "command"`.
> 
> For instance if you want to use `mcpp.exe`: `souffle --preprocessor "mcpp.exe -e utf8 -W0"` Or `souffle --preprocessor "cl -nologo -TC -E"`.

,Thank you for your reply. I have gcc in my environment, and I debugged this function, it really need to add ".exe" to the end of the path.

**Comment by Arnavpmr** [comment]
How do you have gcc in your environment for windows?
Did you use Windows Linux Subsystem or MinGW?
