### ISSUE TITLE
no conversion for stoi when parsing --jobs=auto (without OPENMP)

### ISSUE THREAD

**Issue by christopher-tilt-str** [souffle-lang/souffle#2475]
Found in version 2.4.1 (tag)
Build on Mac OS Apple Silicon according to [build for Mac](https://souffle-lang.github.io/build#mac-os-x-build), OPENMP not installed

run souffle with `--jobs=auto`

## Expected result
Runs with default number of cores

## Actual result
Fails with `atoi: no conversion`

## Cause
The code in MainDriver does correctly parse the case of `--jobs=auto`, however later uses call `stoi()` without considering the possibility of the argument not being an integer; and this leads to a crash when it's called as `stoi("auto")`.

PR to follow

**Comment by quentin** [comment]
Thanks for the report.

By the way, since you are on Apple ARM, I must warn you that there might be some concurrency issues leading to crashes when OpenMP is enabled. I will open an issue about it.

**Comment by christopher-tilt-str** [comment]
Hello Quentin,

Thank you for your email. I work with Raimund at STR and have recently begun using Souffle on an Arm Mac. I have seen some failures in local tests and still need to run them down to determine their cause. I’ll be on the lookout for what seems like concurrency issues and try to share results or add comments onto your recent issue report; and if possible, a PR, though I’m sure it will be much more difficult to fix concurrency issues than the simple fix I found for atoi(“auto”).

Thanks for your support!

Cheers, Chris Tilt

From: Quentin Sabah ***@***.***>
Date: Friday, March 15, 2024 at 2:08 AM
To: souffle-lang/souffle ***@***.***>
Cc: Tilt, Christopher ***@***.***>, Author ***@***.***>
Subject: Re: [souffle-lang/souffle] no conversion for stoi when parsing --jobs=auto (without OPENMP) (Issue #2475)
*** WARNING: This message originates from outside the STR organization. ***
*** Please take appropriate care in opening any links or attachments. ***


Thanks for the report.

By the way, since you are on Apple ARM, I must warn you that there might be some concurrency issues leading to crashes when OpenMP is enabled. I will open an issue about it.

**Comment by quentin** [comment]
I created #2476 to track these issues.

**Comment by christopher-tilt-str** [comment]
That’s perfect, Quentin. Thank you. I’ll add any comments or insights to that issue.

Cheers, Chris

From: Quentin Sabah ***@***.***>
Date: Friday, March 15, 2024 at 8:39 AM
To: souffle-lang/souffle ***@***.***>
Cc: Tilt, Christopher ***@***.***>, Author ***@***.***>
Subject: Re: [souffle-lang/souffle] no conversion for stoi when parsing --jobs=auto (without OPENMP) (Issue #2475)
*** WARNING: This message originates from outside the STR organization. ***
*** Please take appropriate care in opening any links or attachments. ***


I created #2476<https://github.com/souffle-lang/souffle/issues/2476> to track these issues.
