### ISSUE TITLE
Build error on Fedora 40 for Souffle 2.2

### ISSUE THREAD

**Issue by tchoutri** [souffle-lang/souffle#2490]
It doesn't seem possible to build Souffle 2.2 on Fedora 40 at the moment:

```
/home/tchoutri/Vrac/souffle-2.2/src/tests/disjoint_set_property_test.cpp:143:12: error: use of deleted function ‘souffle::PiggyList<T>::PiggyList(souffle::PiggyList<T>&&) [with T = long unsigned int]’
  143 |     return nodes;
      |            ^~~~~
```

I already had to pass `-Wno-error=deprecated-declarations` in `src/CMakeLists.txt` but I don't have a good workaround for this.

**Comment by quentin** [comment]
Version 2.2 is quite old, not surprising that recent compilers may complain. I would recommend building 2.4.1 if you can.

**Comment by quentin** [comment]
The latest version of the line is `return souffle::PiggyList<parent_t>{nodes};`. That might be enough to fix?

**Comment by tchoutri** [comment]
Unfortunately this is out of my hands, I use a programming language's bindings to Soufflé, not directly. I have no control over these bindings but I know that each new version takes a toll on the maintainers of these downstream bindings.

**Comment by tchoutri** [comment]
I am also surprised, I thought C++ had some kind of backwards compatibility guarantees. Is there anything I can to on my end?

**Comment by tchoutri** [comment]
> The latest version of the line is `return souffle::PiggyList<parent_t>{nodes};`. That might be enough to fix?

Ok! Thank you!

**Comment by quentin** [comment]
New versions of compilers tend to implement more and more warnings.
You may consider removing at least `-Werror` here to disable "warnings into errors" behavior:

https://github.com/souffle-lang/souffle/blob/ea4ebd45b56619f9362d5db9bb6b7783b4bbb24c/src/CMakeLists.txt#L198-L199

**Comment by tchoutri** [comment]
I have done this, but it doesn't seem to effect the error. 
Is there any command to build the binary and not the tests?

**Comment by quentin** [comment]
You should be able to disable the build of tests with `cmake -DSOUFFLE_ENABLE_TESTING=OFF ...`

**Comment by quentin** [comment]
This branch builds with tests on my fedora 40: https://github.com/quentin/souffle/tree/v2.2

https://github.com/souffle-lang/souffle/compare/2.2...quentin:souffle:v2.2

**Comment by quentin** [comment]
I'm closing this question. Feel free to re-open if needed.
