### ISSUE TITLE
Aggregation

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#25]
Currently, aggregation is sub-optimally translated. 
- multiple occurrences of the same aggregate computation are computed multiple times
- for complex rules the aggregation is computed in a side-table and the side-table is computed exhaustively; compute the side-table on demand rather exhaustively
- for min/max aggregate the whole table is traversed to find the min/max; better to let the index do the job.

**Comment by mmcgr** [comment]
Closed in favour of #662.
#662 is about a workaround for an aggregator bug, but addressing that bug will also involve addressing these performance issues.
