### ISSUE TITLE
`--parse-errors` executes the given Datalog file

### ISSUE THREAD

**Issue by iliastsa** [souffle-lang/souffle#2501]
I'm trying to use the `--parse-errors` option to run some quick sanity checks on some Souffle datalog code. While the flag documentation suggests that it should print parse errors if any and exit, it seems like the provided datalog file is also interpreted, which is not ideal for many reasons (longer runtimes for larger programs, CWD is littered with output files etc).

For example:

```
~/test - [] $ ls
total 12
drwxrwxr-x  2 iliastsa iliastsa 4096 Jul 25 16:33 ./
drwxr-x--- 60 iliastsa iliastsa 4096 Jul 25 16:22 ../
-rw-rw-r--  1 iliastsa iliastsa  175 Jul 25 15:53 test.dl

~/test - [] $ cat test.dl 
.decl Edge(x: symbol, y: symbol)

.decl Reachable(x: symbol, y: symbol)
.output Reachable

Reachable(x, y) :- Edge(x, y).
Reachable(x, y) :- Reachable(x, c), Reachable(c, y).

~/test - [] $ souffle --parse-errors ./test.dl
Warning: No rules/facts defined for relation Edge in file test.dl at line 1
.decl Edge(x: symbol, y: symbol)
------^--------------------------
~/test - [] $ ll
total 12
drwxrwxr-x  2 iliastsa iliastsa 4096 Jul 25 16:32 ./
drwxr-x--- 60 iliastsa iliastsa 4096 Jul 25 16:22 ../
-rw-rw-r--  1 iliastsa iliastsa    0 Jul 25 16:32 Reachable.csv            <------- this is from execution
-rw-rw-r--  1 iliastsa iliastsa  175 Jul 25 15:53 test.dl

```

I'm using Souffle version 2.4.1.

**Comment by quentin** [comment]
Hi, I think `--parse-errors` is unused in the code and should be removed from the allowed set of options and man page.

The current behavior of Soufflé is to exit with an error status on *errors*, but continues on *warnings*. That's why `--parse-errors` is now useless, and that explains why execution continues in you example.

**Comment by iliastsa** [comment]
I see... it would be very handy to have a flag that does some basic souffle checks (everything before execution takes place erhaps?).

**Comment by iliastsa** [comment]
I just realized that there is `--show` that does pretty much what I asked for :smile:
