### ISSUE TITLE
Souffle doesn't build for x86 because of `ParallelUtil.h:649:68: error: requested alignment '96' is not a positive power of 2`

### ISSUE THREAD

**Issue by MIvanchev** [souffle-lang/souffle#2502]
Trying to build Souffle for x86, see [here](https://github.com/MIvanchev/void-packages/commit/79c043b8490320c228b0405c800f26c9ab965c68) and the [respective output](https://github.com/MIvanchev/void-packages/actions/runs/10130159667/job/28011105348#step:7:102). Any way to patch this?

**Comment by quentin** [comment]
Computed value for `hardware_destructive_interference_size` is used in `alignas` and is expected to be a power of `2`.

Comptation can be found here:
https://github.com/souffle-lang/souffle/blob/e6cc66820e0d3c537f57aab2f5c80b0d54cb5208/src/include/souffle/utility/ParallelUtil.h#L26-L35

We never had any report of a non-power-of-2 value. I invite you to check the intermediate values of this computation in you particular environment that might be specific to your hardware arch, libc, compiler. What is the value of `sizeof(max_align_t)` in your setup?

**Comment by MIvanchev** [comment]
If the computation is `2 * sizeof(max_align_t)` and the output is 96 I reckon `sizeof(max_align_t)` is 48.

**Comment by quentin** [comment]
That's my point, if that's the branch your compiler took, then `48` is quite an unusual size. Using an exotic setup? You can probably replace the whole expression with `64` if you don't want to spend more time on your issue.

**Comment by MIvanchev** [comment]
It's our CI build setup for the Void Linux repos and I'd like to build something that our users will appreciate and be stable, I don't mind spending time on it :)

**Comment by quentin** [comment]
The assumption in this code is that it would always return a power-of-2. If that's not the case for some legit reason then there is the opportunity to fix a bug here.

I'm not 100% sure what the C/C++ standards have to say about the expected value of `sizeof(max_align_t)` and `std::hardware_destructive_interference_size`. Maybe `sizeof(max_align_t)` is not guaranteed to be a power of 2.

**Comment by MIvanchev** [comment]
>Maybe sizeof(max_align_t) is not guaranteed to be a power of 2.

Yes, I believe that's the case. Maybe something like `pow(ceil(sqrt(sizeof(max_align_t))), 2)` is better suited for the constexpr's value?

**Comment by quentin** [comment]
It was a mistake to use `sizeof`, `alignof` would make more sense according to the standard.

However, eventually what we really want is at least the cache-line size, and it's probably conservative enough to hard-code `64` when `__cpp_lib_hardware_interference_size` is not available as in this example https://en.cppreference.com/w/cpp/thread/hardware_destructive_interference_size

**Comment by MIvanchev** [comment]
@quentin I changed the value to 64 using [this patch](https://github.com/MIvanchev/void-packages/commit/3c2ae6b30d6bb1e6992f294ba9fc058fef351cea#diff-85f7b96f7b9d3ea50d65f28b8c1c432f4fa96ca609c6b554e6b2789e83fd176eR25) and some tests are failing for i686:

```
The following tests FAILED:
	 15 - ram_arithmetic (Failed)
	 18 - brie (Timeout)
	3496 - profile/lrg_attr_id_run_prof_top (Failed)
	3497 - profile/lrg_attr_id_cmp_prof_top (Not Run)
	3520 - profile/recursive_run_prof_top (Failed)
	3521 - profile/recursive_cmp_prof_top (Not Run)
```

**Comment by quentin** [comment]
Please provide more details about the failures, test logs, maybe with `ctest --output-on-failure`.
Note that we test Soufflé only on 64 bits platforms.

**Comment by MIvanchev** [comment]
The test logs are [here](https://github.com/MIvanchev/void-packages/actions/runs/10159700729/job/28094480624)

>Note that we test Soufflé only on 64 bits platforms.

Is i686 supposed to be supported or am I just wasting time :)

**Comment by quentin** [comment]
i686 is not supposed to be supported.

**Comment by MIvanchev** [comment]
Thanks for clarifying!
