### ISSUE TITLE
Debug Report Option for Testsuite

### ISSUE THREAD

**Issue by lyndonhenry** [souffle-lang/souffle#253]
Soufflé offers the option to generate a debug report to an html file when run with `--debug-report=<my_file>.html`. This is an extremely useful feature to trace execution and diagnose problems. It would be good if the test suite were to have a flag to generate these reports.

**Comment by mmcgr** [comment]
Fixed by #280 

If the testsuite is created by:
```
SOUFFLE_CONFS="[desired_flags] ---debug-report=debug_report.html" make check
```
then the debug report will be present for failed tests. If you need the report for passing tests, once make check has been run you can do
`./testsuite --debug`
