### ISSUE TITLE
Syntax error in configure script

### ISSUE THREAD

**Issue by varming** [souffle-lang/souffle#273]
I tried building the latest Souffle master on both Linux and OSX and failed.

On Linux it fails to run configure as on line 10511 `PKG_CHECK_MODULES(LIBEDIT, libedit)` appears. This looks like an issue with m4 expansion of configure.ac.

On OSX I get a syntax error in configure line 2594: LT_INIT(dlopen). Again it looks like missing m4 macros.

**Comment by pnappa** [comment]
@DominicRomanowski

**Comment by DominicRomanowski** [comment]
Is the libedit issue due to missing the "libedit-dev" package?

**Comment by b-scholz** [comment]
Please can you check that you installed libedit on your system, i.e., 
For Liunx: ```apt-get install libedit-dev``` 
For Mac OS X: ```brew install libedit```

**Comment by varming** [comment]
On OSX: After running aclocal and autoconf I managed to get to the same point as on Linux, i.e., a syntax error as `PKG_CHECK_MODULES(LIBEDIT, libedit)` is in configure (this time on line: 21485). 

Looking at configure.ac line 259 I see `PKG_CHECK_MODULES(LIBEDIT, libedit)`. Who provides the m4 macro `PKG_CHECK_MODULES`? It turns out that `pkg-config` does, and indeed after installing `pkg-config` autoconf expands the macro and the configure script works.

So you added a dependency on `pkg-config`. You need to update README, INSTALL, and/or https://github.com/souffle-lang/souffle/wiki/build.

**Comment by b-scholz** [comment]
Thanks for the info? Does it work for you know and can we close this issue?

**Comment by varming** [comment]
It works for me. "Can we close this ticket?", well, you cannot build Souffle from the repo with the tools mentioned in the documentation, so there is a problem to solve (IMHO).

**Comment by b-scholz** [comment]
Which tools are missing in the documentation? I believe we have added pkg-config on the wiki page.

**Comment by varming** [comment]
It looks like the wiki was recently updated: https://github.com/souffle-lang/souffle/wiki/build/_compare/f86e4d64629d0074b0f46296989af0aa14f5324f. That completes this issue.
