### ISSUE TITLE
Issue with compilation from Datalog to C++?

### ISSUE THREAD

**Issue by anantoni** [souffle-lang/souffle#295]
Hello,

It seems that I have encountered a possible issue when trying to run souffle -c on an analysis file. Souffle hangs before producing a .cpp file.  I have identified that the addition of a particular rule causes the issue, but after several attempts to modify the rule I could not find a solution.

I have attached the file produced after running the preprocessor, since it is not easy for me to reproducde the issue in a smaller example. The commented-out rule at line 1133 is the one causing Souffle to hang, removing it leads to almost instant compilations.

Kind Regards,
Anastasios Antoniadis

[analysis.txt](https://github.com/souffle-lang/souffle/files/751046/analysis.txt)

**Comment by b-scholz** [comment]
Hi Taso,

Recently we added an optimisation to find better topological sorts (local brute force search) to minimise memory consumption. Unfortunately, the lookahead for the brute-force solution is too expensive in terms of runtime. For your specification, the algorithm takes too long. 

A quick work around is to comment out line 314 in PrecedenceGraph.cpp (NB: the function should exit immediately after invocation). This will fix your problem, i.e., the brute-force look-ahead will be disabled. 

Lyndon has already a fix for this issue. It is in the pipeline of pull requests.

Cheers,
Bernhard.

**Comment by lyndonhenry** [comment]
That pull request has been merged (#294). I was able to compile both without the problem rule (in approx. 30s) and with the rule (in approx. 60s). You should be able merge the latest changes from upstream and it hopefully will work.

**Comment by anantoni** [comment]
Everything went well after getting the latest changes. Thank you both!

Cheers,
Anastasios

**Comment by lyndonhenry** [comment]
Glad to hear it. Thank you too for pointing out the issue.
