### ISSUE TITLE
Compiling code containing .plan statements, with -p option

### ISSUE THREAD

**Issue by Kostast23** [souffle-lang/souffle#296]
Hello,

when I try to run soufflé with -c and -p options and I have a .plan statement in my code (as simple as **.plan 1:(2,1)**), soufflé produces a .cpp file that cc1plus tries but fails to compile. Instead, it produces an ever growing .ccerr file that contains error messages and grows by approximately 1 GB per minute.

If I omit the -p option or the .plan statement everything works as expected.

Part of the [.ccerr file](https://github.com/souffle-lang/souffle/files/753024/output.txt)
The error message "_expected primary-expression before end of line_" is printed indefinitely.

Kind regards,
Konstantinos Triantafyllou

**Comment by b-scholz** [comment]
We are aware of the issue. It is related to the function stringify() in Utils.h. The generated strings for the profile-log methods do not have proper escape sequences for double-quotes.  

We are working on a solution. This is part of the new profiler tool that we have rewritten 
(NB: we have rewritten the tool in C++ and we have now a graphical user interface in HTML/Javascript).

**Comment by Kostast23** [comment]
After the #300 changes the issue seems to go away.
