### ISSUE TITLE
Macros for Errors, Warnings, Messages, Breakpoints, and Asserts

### ISSUE THREAD

**Issue by lyndonhenry** [souffle-lang/souffle#304]
Souffle currently handles errors in an ad-hoc manner; there is inconsistent formatting, confusion with assertions, no inclusion of file or line number references, no clear separations of warnings and messages, etc. Note that this isn't addressing the error reporting for datalog programs, which is quite good, but instead errors which occur within the actual compiler. It would be good to define a simple and central means of handling errors and things like them. I propose the following functions:

- **Error**: print to std::cerr, call exit(1), enabled always
- **Warning**: print to std::cerr, enabled always
- **Message**: print to std::cout, enabled always
- **Breakpoint**: print to std::cerr, enabled only in development
- **Assert**: call 'assert' method, enabled only in development

Each of these takes as arguments either nothing, text to be printed, or both text to be printed and a callback function. During development they will print their file of origin and the line number on which they were called, at all other times these will be ommitted.

**Comment by b-scholz** [comment]
Can we have a look how other projects are dealing with these issues?
I find that CLANG/LLVM is always a great example to find good software engineering principles implemented.

**Comment by lyndonhenry** [comment]
Yes, that's certainly a better way to go about it -- I just happened to have several of these implemented as macros around in odd places after my latest bout of refactoring. Anything that avoids macros while achieving the same thing is in my thinking going to be much nicer.

**Comment by icesparrow** [comment]
I had to deal with similar issues in my PhD project so I wrote a Logger (with functionality that you mention) a few years back. This includes logging in different modes (such as warnings, errors debug messages etc), time stamps, stack traces (using GNU `backtrace`), enhanced assertions, custom break points for debugging ans so forth. 

I have attached the code ([here](https://github.com/souffle-lang/souffle/files/761214/logger.zip)), it has been taken from my old project so there  are couple of functions missing, but I think that would be sufficient to see whether this is something you want to consider using in Souffle. I can quickly fix the rest and give an example of use if you are interested.

**Comment by lyndonhenry** [comment]
Thank you very much, this looks quite comprehensive. I think we could use this. Could you explain a little on how it works? I don't mean a full documentation or anything, just a basic outline of the primary functions you call and what they do.

**Comment by icesparrow** [comment]
Yes, sure, I will make a small example with a few applications and send it out soon

**Comment by icesparrow** [comment]
I have added the missing functions and made an example of use with some explanations. Have a look at `main.cpp`. You can build it with `make`. The code is [here](https://github.com/souffle-lang/souffle/files/766237/logger.zip)
