### ISSUE TITLE
Compressed fact files

### ISSUE THREAD

**Issue by HerbertJordan** [souffle-lang/souffle#32]
Fact files can be very large, contain a text-based representation of data. This data can be effectively compressed (by a reasonable factor, example data showed a factor of 6). Storing fact files in a compressed format would not only reduce disc usage, it may also increase the speed of loading facts into relations, since less data needs to be retrieved from secondary storage.

**Suggestion A:** support XY.facts as either being clear-text or gzip-compressed input

**Suggestion B:** pre-processed facts; we provide an extra tool converting facts into a binary format that can be directly loaded as a relation; 

Suggestion A would requires less effort and it reuses common tools while suggestion B may lead to higher performance, in particular when the fact files contain unordered data, causing lots of cache misses during load operations. However, they are not mutual exclusive. Both may be added independently.

**Comment by HerbertJordan** [comment]
One more thing: Suggestion B does not introduce library dependencies to some gzip implementation.

**Comment by b-scholz** [comment]
Isn't it better to have a binary format for relations. Say if we have a conversion tool that converts unstructured text to a structured format, then relations can be loaded very efficiently.

The conversion would happen only once and the binary format can be re-used again and again.

**Comment by HerbertJordan** [comment]
That is Suggestion B.

**Comment by b-scholz** [comment]
This is also related to a SQLITE3 interface. Perhaps we can rely on SQLITE3 to do all the hard work of storing and querying.

**Comment by b-scholz** [comment]
This is resolved with Martin's latest changes for  .input/.output directives.
