### ISSUE TITLE
Plan statement in multi-head rule makes Soufflé crash?

### ISSUE THREAD

**Issue by Kostast23** [souffle-lang/souffle#322]
```
.decl A(a:number) output
.decl B(b:number) output
.decl C(c:number) output
.decl D(d:number) output

A(1).

A(x+1) :- B(x), C(x).
D(x) :- A(x).

B(x), C(x) :- A(x), D(x), x < 10.
.plan 1:(2,1)
```

Soufflé crashes when provided with the above program. The issue goes away if I remove the plan statement or either of `B(x)` and `C(x)` from the head of rule `B(x), C(x) :- A(x), D(x), x < 10.`.

Thank you for your time!

**Comment by b-scholz** [comment]
We haven't tested the plan feature for multiple heads in a rule. 

Please can you expand the multi-head rule as follows,
```
B(x) :- A(x), D(x), x < 10. .plan 1:(2,1)
C(x) :- A(x), D(x), x < 10. .plan 1:(2,1)
```
and see whether it still crashes.

**Comment by Kostast23** [comment]
There is no crash if I expand the rule like you said!
