### ISSUE TITLE
Refactor Functors

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#331]
Currently we have UnaryFunctors, BinaryFunctors, and Ternary Functors. Ideally, we unify the classes in AST and RAM to an n-ary functor. This reduces maintenance costs. 

The helper files Unary/Binary/TernaryFunctorOps.h can be improved / perhaps tables. In addition the naming of the functions is clumsy.

**Comment by mmcgr** [comment]
An n-ary could also allow for functors without a fixed size. e.g. string concatenation, max, min. Writing the datalog would be easier;
```
max(a, b, c, d)
```
instead of 
```
max(max(max(a, b), c), d)
```
In the case of string concatenation implementation it would also be a performance improvement, as mentioned in #761.

**Comment by azreika** [comment]
For the AST, currently in the process of unifying Unary, Binary, and Ternary functors to n-ary functors, and replacing the three header files (Unary/Binary/TernaryFunctorOps.h) with a single, cleaned-up one.

**Comment by azreika** [comment]
RAM operators are tied heavily to the AST functors, so to properly unify the AST functor classes, the RAM operator classes (Unary, Binary, and Ternary as well) will likely also be unified in the same PR. This crosses over with issue #541.

**Comment by azreika** [comment]
> An n-ary could also allow for functors without a fixed size. e.g. string concatenation, max, min. Writing the datalog would be easier;
> 
> ```
> max(a, b, c, d)
> ```
> instead of
> ```
> max(max(max(a, b), c), d)
> ```
> In the case of string concatenation implementation it would also be a performance improvement, as mentioned in #761.

Can this be raised as a separate issue? I will make a PR soon for functor unification.
