### ISSUE TITLE
Can't configure and build Souffle on mac

### ISSUE THREAD

**Issue by psubotic** [souffle-lang/souffle#344]
Two Issues: 
 - configure is trying to find jni.h in the wrong directory
I can get around it by copying jni headers to the location it is looking for but the corresponding m4 file should be modified so that it checks for this case too.

My jni.h is in /System/Library/Frameworks/JavaVM.framework/Headers/
looks for it in /System/Library/Frameworks/JavaVM.framework/Versions/include/

- Build errors e.g., 

./GraphUtils.h:274:30: note: in instantiation of member function 'souffle::index::CollectionIndexTable<const
      souffle::AstRelation *, std::set>::movePrepend' requested here
            this->indexTable.movePrepend(removedVertex, retainedVertex);
                             ^
./PrecedenceGraph.h:118:20: note: in instantiation of member function 'souffle::HyperGraph<index::SetTable, const
      souffle::AstRelation *>::joinVertices' requested here
        sccGraph = GraphConvert::toAcyclicHyperGraph<index::SetTable>(precedenceGraph->getGraph());
                   ^
./IndexUtils.h:241:10: note: candidate function not viable: no known conversion from 'const set<const souffle::AstRelation *>'
      to 'const souffle::AstRelation *const' for 2nd argument
    void prepend(const size_t index, const Object& object) {
         ^
./IndexUtils.h:252:10: note: candidate template ignored: substitution failure [with T = set]: too few template arguments for
      class template 'set'
    void prepend(const size_t index, const T<Object>& objects) {
         ^                                 ~
./IndexUtils.h:236:15: error: no matching member function for call to 'append'
        this->append(toIndex, this->get(fromIndex));
        ~~~~~~^~~~~~
./GraphUtils.h:276:30: note: in instantiation of member function 'souffle::index::CollectionIndexTable<const
      souffle::AstRelation *, std::set>::moveAppend' requested here
            this->indexTable.moveAppend(removedVertex, retainedVertex);
                             ^
./PrecedenceGraph.h:118:20: note: in instantiation of member function 'souffle::HyperGraph<index::SetTable, const
      souffle::AstRelation *>::joinVertices' requested here
        sccGraph = GraphConvert::toAcyclicHyperGraph<index::SetTable>(precedenceGraph->getGraph());
                   ^
./IndexUtils.h:215:10: note: candidate function not viable: no known conversion from 'const set<const souffle::AstRelation *>'
      to 'const souffle::AstRelation *const' for 2nd argument
    void append(const size_t index, const Object& object) {
         ^
./IndexUtils.h:226:10: note: candidate template ignored: substitution failure [with T = set]: too few template arguments for
      class template 'set'
    void append(const size_t index, const T<Object>& objects) {

Any clue as to what is going on?

**Comment by lyndonhenry** [comment]
The build errors were me, sorry. I've got a fix in the works with some proper unit tests already, but tomorrow morning I'll revert the code for those things causing the error back to how they previously worked just so they don't happen for now. I didn't pick this up as the build doesn't give any error on my specific compiler/os combination. As for the first one, I haven't got a clue.

**Comment by mmcgr** [comment]
The first part should be fixed by the updated scripts in #346.

**Comment by psubotic** [comment]
Many thanks guys!

**Comment by lyndonhenry** [comment]
The second should be fixed by #348, though I can't be 100% as the only mac environment I have access to is the one on Travis.

**Comment by b-scholz** [comment]
Paul - please double-check whether there are still problems.

**Comment by psubotic** [comment]
ok ill do this today

**Comment by psubotic** [comment]
works!
