### ISSUE TITLE
Java API

### ISSUE THREAD

**Issue by psubotic** [souffle-lang/souffle#35]
Would be nice to wrap the c++ api with JNI for scala/java users.

**Comment by b-scholz** [comment]
Indeed! Soufflé does have a C++ binding mechanism only, and does not support language bindings to other languages.  It would be great to have multiple languages bindings for (1) Java and (2) Python. The challenges would be to replicate relational data-structures in the host languages and implement high-performance interfaces such that information can be exchanged between the host language and Soufflé efficiently, i.e., we will have large relations.

**Comment by psubotic** [comment]
Oh forgot to say - im onto this - will have an initial version soon-sih.

**Comment by b-scholz** [comment]
Paul - can we close this issue?

**Comment by psubotic** [comment]
yes - ill have a pull request ready for the mainline approx. end of next
week

**Comment by b-scholz** [comment]
This can be closed now ?

**Comment by psubotic** [comment]
yes
