### ISSUE TITLE
souffle -c leaves temp files behind

### ISSUE THREAD

**Issue by mmcgr** [souffle-lang/souffle#350]
At the moment, if you run ```souffle -c ...``` a temporary cpp file and executable are created, used, then left behind with each run. It would be neater if these were automatically removed once finished with.

If you need to keep the cpp file or executable, there are the -o or -g options.

**Comment by b-scholz** [comment]
This can be fixed in the compiler script compile-souffle and in the RamExecutor.cpp.

**Comment by mmcgr** [comment]
The code change is trivial, but is the existing behaviour useful? It's potentially easier to debug if you have the cpp file.

I think they are temp files that should not be left behind, but I wanted a second opinion before changing it.

**Comment by b-scholz** [comment]
I believe removing the temporary files is fine because we have now the options 
-o <exe> 
and 
-g <c++ file> 

Both options would either generate an executable and/or a c++ file.

**Comment by b-scholz** [comment]
Perhaps Paul & Herbert could comment on this as well.

**Comment by psubotic** [comment]
yes, i cant see any reason to keep them as default.
