### ISSUE TITLE
Hex value not in range

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#353]
I believe this is a new behavior from last month.  I got the following error from this line

    atom__ip("ip__205_251_233_179", 0xCDFBE9B3).

    Error: Number constant not in range [-2^31, 2^31-1] 

Did the parser change?

**Comment by lyndonhenry** [comment]
Yes, pull request #294 changed the parser due to issue #276, which would effect this. I don't believe this is a bug, as the wiki defines this as correct behavior at https://github.com/souffle-lang/souffle/wiki/user-manual. 

From the wiki:
> - **Numbers** are signed integer numbers and are fixed to a fixed range. At the moment the range is fixed to the int32_t type covering the range [ -2^31 .. 2^31 -1 ]. However, the type could be altered by a compile time flags to any basic type that the C++ compiler supports.

**Comment by seanmcl** [comment]
I agree it should probably not be considered a bug.  I think it's not the greatest user experience that I need to calculate a negative decimal number from the 32 bits though.  Why support hex at all in that case?

**Comment by b-scholz** [comment]
There  is a quick workaround. We can treat addresses/hex numbers as unsigned integers and introduce an extra unsigned range check.

However, I think there is a fundamental problem: we will need a signed integer type and an untyped integer type with two different sets of operations.

**Comment by seanmcl** [comment]
Sounds good.  FWIW, we don't use any shift operations, just & which is agnostic to the sign.

**Comment by lyndonhenry** [comment]
Yeah, I think having a signed/unsigned integer type would probably be a good idea. Currently Souffle pretends that all numbers are 32 bit signed integers, which has advantageous for things like constructing efficient data structures, but disadvantages for things like division. It might be good to define a proper set of numeric types (nothing as involved as C, just something simple) and so also address issue #215.

**Comment by varming** [comment]
An alternative to defining a signed/unsigned types is defining a few unsigned operations. That is what they did in the JDK and it is not terrible, especially if you find nice syntax for the unsigned operations. You need unsigned/unsigned versions of: compare, division, remainder, and shift right (only four, am I missing some operation?).
