### ISSUE TITLE
Strange compilation behaviour

### ISSUE THREAD

**Issue by Kostast23** [souffle-lang/souffle#361]
Hello!

I experience some strange behaviour. It seems that soufflé changes a portion of our code
```
isContext(?calleeCtx),
ReachableContext(?calleeCtx, ?signature),
VarPointsTo(?hctx, ?value, ?calleeCtx, ?this) :-
    ?signature = "<java.lang.ThreadGroup: void <init>()>",
    ThisVar(?signature, ?this),
    SystemThreadGroup(?hctx, ?value),
    StartupInvocation(invocation), ?calleeCtx = [invocation].
```
to this code (copied from the output of souffle-profile)
```
isContext(?calleeCtx),
ReachableContext(?calleeCtx, ?signature),
VarPointsTo(?hctx, ?value, ?calleeCtx, ?this) :-
    ThisVar("<java.lang.ThreadGroup: void <init>()>", ?this),
    SystemThreadGroup(?hctx, ?value),
    isMethodInvocation(invocation), ?calleeCtx = [invocation].
```
in an attempt to optimize things(?)

However, the only **StartupInvocation** rule is defined like this
```
StartupInvocation(?invo) :-
    ?invo = "<<jvm-startup-context>>",
    isMethodInvocation(?invo).
```
As can be seen the code that souffle produces is missing the `?invo = "<<jvm-startup-context>>"` part, which should not happen.

Changing the **StartupInvocation** rule's code to
```
StartupInvocation("<<jvm-startup-context>>").
```
solves the problem.

I am running [code.txt](https://github.com/souffle-lang/souffle/files/828654/code.txt) with -c and -p options enabled. The affected rules are in lines 1011-1039.

Thank you for your time!

**Comment by b-scholz** [comment]
I believe this is related to multiple headers in rules, which are not tested very well. 

Could you rewrite the rules to the following three rules:
```
isContext(?calleeCtx) :-
    ?signature = "<java.lang.ThreadGroup: void <init>()>",
    ThisVar(?signature, ?this),
    SystemThreadGroup(?hctx, ?value),
    StartupInvocation(invocation), ?calleeCtx = [invocation].

ReachableContext(?calleeCtx, ?signature) :-
    ?signature = "<java.lang.ThreadGroup: void <init>()>",
    ThisVar(?signature, ?this),
    SystemThreadGroup(?hctx, ?value),
    StartupInvocation(invocation), ?calleeCtx = [invocation].

VarPointsTo(?hctx, ?value, ?calleeCtx, ?this) :-
    ?signature = "<java.lang.ThreadGroup: void <init>()>",
    ThisVar(?signature, ?this),
    SystemThreadGroup(?hctx, ?value),
    StartupInvocation(invocation), ?calleeCtx = [invocation].

```

and double-check whether it works.

**Comment by Kostast23** [comment]
I rewrote the rules ([code.txt](https://github.com/souffle-lang/souffle/files/830801/code.txt)) but the problematic behaviour does not go away.

**Comment by b-scholz** [comment]
I try to come up with a simpler examples that exhibits this behaviour. I tried the following example,

```
.decl A(x:symbol)
A("a").
A("b").

.decl B(x:symbol)
B(x) :-
   x = "a",
   A(x).

.output B
```

and it is transformed to the following program (NB: I used --debug-report=x.html to produce the dump). 

```
// -- A --
.decl A(x:symbol) 

A("a").

A("b").



// -- B --
.decl B(x:symbol) output 

B("a") :- 
   A("a").
```

**Comment by b-scholz** [comment]
Can you pinpoint more precisely (with a small example) what the problem is? It could be that the constant propagation does not work in the presence of records?

**Comment by Kostast23** [comment]
Sorry for the late response. My system provides the same final output, which however changes the semantics of the program. The correct output should be
```
isContext([invocation]) :- 
   _ThisVar("<java.lang.ThreadGroup: void <init>()>",?this),
   SystemThreadGroup(?hctx,?value),
   isMethodInvocation(invocation),
   invocation = "<<jvm-startup-context>>".
```

Here is a small example that depicts the problem. The following program
```
.type X = [x:symbol]

// -- A --
.decl A(a:X) output 

A([b]) :- 
   B(b).

// -- B --
.decl B(b:symbol) 

B("a") :- 
   C("a").

// -- C --
.decl C(c:symbol) 

C("b").
```
is transformed to
```
.type X = [x:symbol]

// -- A --
.decl A(a:X) output 

A([b]) :- 
   C(b).

// -- C --
.decl C(c:symbol) 

C("b").
```
after the RemoveRelationCopiesTransformer is run. The RemoveRelationCopiesTransformer identifies that B("a") can be replaced by C("a") but replaces all instances of B(x) with C(x) instead of C("a"). I have a fix (which I can commit should the approach be correct) that covers this case by not replacing B with C.

**Comment by souffle-lang** [comment]
Ok - I see the problem. This is not related to an individual rule/multi-heads etc. This problem seems to be related to the transform RemoveRelationCopiesTransformer. Our checker for copy alias is too simplistic.

Could you comment out the following line in ```main.cpp``` (located ~ line 249)

```
transforms.push_back(std::unique_ptr<AstTransformer>(new RemoveRelationCopiesTransformer()));
```

and check whether the produced code is semantically correct. 

Basically, we don't check whether in a copy-rule all arguments are variables.
