### ISSUE TITLE
Build a brew package for Souffle

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#367]
It would be great if we could add a soufflé package to the brew project.

**Comment by b-scholz** [comment]
There is an initial version here:

https://github.com/souffle-lang/homebrew-souffle

```
brew install souffle-lang/souffle/souffle
```
 or 
```
brew tap souffle-lang/souffle
brew install souffle
```

It would be great if some volunteers could test the brew package and report issues.

**Comment by zyzek** [comment]
Seems to work perfectly for me on Homebrew 1.3.0, macOS 10.12.6; though I'd have liked if it had installed the 1.1.0 release.

**Comment by mmcgr** [comment]
This is not actually working now. I think the script expects a tar of the repo, but is actually getting a pkg.

**Comment by b-scholz** [comment]
Yes. This is correct. We would need a tar generated by ```make dist``` on a mac platform.
