### ISSUE TITLE
Automated Copyright/License Header Management

### ISSUE THREAD

**Issue by lyndonhenry** [souffle-lang/souffle#371]
I'm opening this in response to closed issue #244, so that we don't have to keep re-opening it each time the headers are invalidated and also because the automation of the headers seems sufficiently different to the existence of those headers alone to warrant its own issue (i.e. that was more of a bug, this is more of an enhancement).

We need 
- a way to automatically check that the copyright/license headers exist and are correct
- a way for developers to automatically generate correct headers over their code

Without knowing particular details of the legal issue surrounding this, it might just be enough to have a list of Oracle copyrighted files which have their corresponding header checked, and have everything else to be under the copyright of "The Souffle Developers", the headers for which are checked/generated for every file which is not explicitly under Oracle's copyright.

**Comment by scyptnex** [comment]
For posterity, i was looking into tools for this part:

* https://github.com/osterman/copyright-header
* https://github.com/rubicon-oss/LicenseHeaderManager (visual studio)
* https://github.com/mycila/license-maven-plugin (maven)

**Comment by mmcgr** [comment]
I think we could mostly do this by just having standard header text for *.h/*.cpp files and *.dl files. If a new file is added to `src` or `test` then it must have the expected header (with the current year).

How do we handle including files that aren't written by us? A separate directory for non-souffle developer written files would be simplest.
