### ISSUE TITLE
Debug reporter has valgrind errors

### ISSUE THREAD

**Issue by taipan-snake** [souffle-lang/souffle#376]
Valgrind complains about memory leak issues when running the debug reporter with --debug-report=<file>.html

**Comment by mmcgr** [comment]
Can you give an example that demonstrates the issue?

I can see a few kb being lost during parsing of RuleBody, or related to that, but I don't see any difference when I use the debug reporter.

**Comment by mmcgr** [comment]
The initial problem can't be duplicated. Some minor memory leaks in parsing were fixed in #402, which may be related.

If an example of the memory leaks can be found then reopen this issue and we can investigate.
