### ISSUE TITLE
make install and make uninstall bypassing SignalHandler.h

### ISSUE THREAD

**Issue by anantoni** [souffle-lang/souffle#389]
Hi,
It's been a while I've been encountering this issue. Basically, whenever I run make install, SignalHandler.h is not copied to the include files directory <prefix>/include/souffle and I have to copy it there manually. Similarly, whenever I run make uninstall it is the only file not removed from the aforementioned directory. This has occurred on several different machines, but I can't see anything wrong in configure.ac.

Best regards,
Tasos

**Comment by mmcgr** [comment]
The patch fixes the issue in my testing. If you keep seeing the same behaviour after a bootstrap/configure/makei install, reopen this issue and I'll re-investigate.
