### ISSUE TITLE
Soufflé interpreter/compiler segfaults

### ISSUE THREAD

**Issue by Kostast23** [souffle-lang/souffle#392]
Hi!

It seems that Soufflé segfaults with the following [input](https://github.com/souffle-lang/souffle/files/1044861/analysis.txt), which was not the case some time ago. Here is a [core.zip](https://github.com/souffle-lang/souffle/files/1044937/core.zip) with a core dump and a soufflé binary compiled from the latest source, in case you could take a look.

Thank you!

**Comment by b-scholz** [comment]
We will have a look and check what changes made the crash.

**Comment by mmcgr** [comment]
I can duplicate the problem locally with that input. The first souffle version that can read that input file as is is from 21/2, and it has the same issue. I'll change the iodirectives to the old version so I can look further back for a working commit. Since the input worked before, I suspect the issue was introduced in changes shortly before then.

The segfault happens after `translationUnit.getAnalysis<RelationSchedule>()` is called. At the end of of the vector of `RelationScheduleStep` it contains is one containing a null `AstRelation`. That eventually crashes `RamTranslator`. I have yet to find how the null `AstRelation` gets added.

**Comment by Kostast23** [comment]
Thanks a lot! The original code contained old-version io-directives, so maybe the ones running the analysis used an older version of soufflé that didn't have the issue.

**Comment by Kostast23** [comment]
Maybe the issue has to do with "count" and stratification, as we found that the code compiles in case the following lines
```
Stats_Metrics("2.5", "array index points-to (SENS)", c) :- c = count : ArrayIndexPointsTo(_, _, _, _).
Stats_Metrics("3.5", "instance field points-to (SENS)", c) :- c = count : InstanceFieldPointsTo(_, _, _, _, _).
Stats_Metrics("4.5", "static field points-to (SENS)", c) :- c = count : StaticFieldPointsTo(_, _, _).
```
are removed or the following line
```
.output ArrayIndexPointsTo, InstanceFieldPointsTo, StaticFieldPointsTo
```
is added.

**Comment by mmcgr** [comment]
A minimal example:
```
.decl A()
.decl B()
.decl C(x:number)
.output C
A().
C(y) :- y = count : A().
C(y) :- y = count : B().
```

**Comment by mmcgr** [comment]
Or using sum instead of count:
```
.decl A(x:number)
.decl B(x:number)
.decl C(x:number)
.output C
A(1).
C(y) :- y = sum a : A(a).
C(y) :- y = sum a : B(a).
```

**Comment by b-scholz** [comment]
Great work to find out what's going on. I will have a look how to fix it as well.

**Comment by mmcgr** [comment]
Using the minimal example this issue can be duplicated in the initial import of the souffle repository in 2014.

The problem starts with aggregations of empty relations. When empty relations are removed, aggregations of the empty relations remain, so whenever souffle tries to fetch their removed predecessor from the computed program a null relation is returned. If that null relation is used a segfault is likely.

**Comment by b-scholz** [comment]
I checked today; there is a quick fix for dropping relations, i.e., we add an “if(rel != nullptr)” around line 1063 in RamEexecutor.cpp.

However, it does not solve the problem of not removing the relations properly. It is only a quick work-around.

**Comment by b-scholz** [comment]
I have created a pull-request for a quick fix. We need to do a proper fix later.
