### ISSUE TITLE
Aggregate behaviour with empty relations

### ISSUE THREAD

**Issue by mmcgr** [souffle-lang/souffle#399]
Currently a rule with an aggregate over an empty relation is accepted, but produces no output. The rule is effectively ignored.
Such a rule should either lead to valid output (e.g. sum/count -> 0) or an error message.

**Comment by b-scholz** [comment]
Here is an example: 
```
.decl A(x:number)
.decl B(x:number)
B(x) := x = count : A(_)
```

At the moment, we will not get a result for B.
