### ISSUE TITLE
MAC OS X / CLANG-OpenMP

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#41]
CLANG++/OpenMP on MAC OS X does not work. It seems that the parallelisation macros in ParalleUtils.h do not work properly for Clang++/OpenMP (NB: for G++/OpenMP on MAC OS X seems to work without issues).

**Comment by HerbertJordan** [comment]
What version of clang are you using?

**Comment by b-scholz** [comment]
I get following output:
```
clang version 3.5.0 
Target: x86_64-apple-darwin15.3.0
Thread model: posix
```
typing `clang-omp++ -v`. I installed clang-omp by `brew install clang-omp`. 

You are right - it might be a good point to double-check whether a new version of `clang` has no issues.

**Comment by souffle-lang** [comment]
brew deploys an initial version of the openmp project (around version 3.5) which seems to be buggy and make the Souffle's test-cases fail. 

I rebuilt the latest version of clang++ 3.9 with the openmp project. The test-cases are passing.

I believe we need to wait until brew is upgrading clang-omp to a newer version or adding the omp project to the llvm brew package.
