### ISSUE TITLE
debug-report hangs

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#411]
I can't get the debug-report flag to do anything useful.  Am I doing it wrong?

```
$ time souffle db.dl 2>/dev/null
?24?query__0	11
souffle db.dl 2> /dev/null  0.24s user 0.01s system 95% cpu 0.269 total
```

```
$ time souffle --debug-report=/tmp/souffle-out db.dl
(hangs)
```

```
$ time souffle --debug-report /tmp/souffle-out db.dl
(hangs)
```

**Comment by mmcgr** [comment]
I haven't managed to duplicate a hang. Do you have an example that produces the hang?

I _can_ make a segfault when the debug report tries to show the work done by the new magic set transform, which may be related.

**Comment by b-scholz** [comment]
I believe I know why this is happening: It could be that the rendering of the dot-graphs for the precedence graph and the SCC graph is too slow.

One work-around is to remove the graphviz tools from your system and run the debug-report option again. I am presuming Soufflé will terminate without troubles. We had similar issues with very large specs in the past. However, the SCC graph and precedence graph will be missing in the report.

**Comment by b-scholz** [comment]
Could you double-check whether it is related to graphviz?

**Comment by seanmcl** [comment]
Sorry, I lost that particular example.  I'll reopen if/when I find another example.
