### ISSUE TITLE
Eliminating Identical Rules / Relations

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#42]
Redundant rules are not eliminated at compile time,

```
A(x,y) :- B(x,z), C(z,y).

A(x,y) :- B(x,z), C(z,y).
```

and produces two rules in the RAM program.

**Comment by b-scholz** [comment]
This is also related to have better Alias analysis of relations: semantic equivalence can be detected by syntactic equivalence.

**Comment by azreika** [comment]
Implemented by PR #697.
