### ISSUE TITLE
Ignored string in delimiter for output

### ISSUE THREAD

**Issue by gkastrinis** [souffle-lang/souffle#422]
A string literal syntax is used in output clauses when specifying a delimiter.

    .output Foo(IO="file", filename="Foo.csv", delimiter="@")

But it appears that the semantics are that of a **single** character.
If the provided string is more than one character, all after the first one are ignored.

E.g. "@@" is treated as "@", ", " is treated as ",", "abcd" is treated as "a".

If this is the intended semantics, a warning message would be helpful.
Otherwise, I guess it is a bug.

**Comment by mmcgr** [comment]
The delimiter is indeed a single character, and if you give a longer string only the first character is used.

I don't see any reason not to allow multiple character delimiters now, though. I already have some minor updates to csv IO in progress so I can incorporate this change.

**Comment by gkastrinis** [comment]
Great! That would be awesome.

**Comment by mmcgr** [comment]
Fixed by #441
