### ISSUE TITLE
Developer Certificate of Origin

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#432]
I suggest to introduce the Developer Certificate of Origin (DCO ) for our fork of Souffle. It is simple and broadly accepted in the open source community. The DCO attests the contribution of a developer.  The latest version of a DCO can be found here:
http://elinux.org/Developer_Certificate_Of_Origin

I would prefer using a bot that checks the DCO sign-offs and the sign-offs are reflected in the repo. There are automated DCO solutions for github such as this one:
https://github.com/probot/dco

Please let me know how you feel about this change in our fork, i.e., establishing DCOs for future commits.

**Comment by psubotic** [comment]
ok for me - prefer something automated and easy

**Comment by mmcgr** [comment]
Seems good to me.

**Comment by HerbertJordan** [comment]
I have to wonder whether this consistent with my university employment. I am pretty sure nobody will ever complain, but I am equally certain that if I'd ask I will get - after discussing with many people - a very confident maybe.

However, since from my point of view the DCO does not change anything regarding my contributions, and provides added legal security to the project, I am totally fine with it.

**Comment by b-scholz** [comment]
Indeed, this is a valid point. Current active contributors who are employed by companies/universities, may require the green light from their legal departments whether they can contribute via the DCO. Note that Australian students will not have the problem because their IP belongs to them.

**Comment by b-scholz** [comment]
Herbert - could you ask your legal department whether they would approve DCO.

**Comment by psubotic** [comment]
does DCO allow for anonymous commits? i.e., can someone check-in code from an account that does not reveal their identity and sign their name as "anon" etc.

**Comment by b-scholz** [comment]
No - I don't believe so. My understanding is that contributors sign-off for each commit with their  names and their email addresses. 
https://github.com/wking/signed-off-by/blob/master/Documentation/SubmittingPatches

There are some concerns about the authentication of signed-off commits. A solution for this is to use GPG. I believe GitHub supports this as well. 
https://help.github.com/articles/signing-commits-using-gpg/

**Comment by psubotic** [comment]
Also, another question. What if someone forks and a bunch of people do some cool things without a DCO. Does this prevent their contributions being added? or does forking force them to use a DCO?

**Comment by b-scholz** [comment]
We may want to get some legal advice on this (NB: I am not a law professor specialising in open source). 

The current outbound license of our fork is UPL since Oracle has open-sourced Soufflé under the UPL. However, in our fork we do not have an inbound license established (i.e. governance).  If we establish the DCO for our fork now, we ask the future contributors of our fork to explicitly acknowledge the UPL for each contribution. 

At the moment our fork is permissive; everybody can contribute towards code & documentation with no restrictions. I believe that by contributing, contributors accept the UPL for their contributions implicitly (inbound = outbound). 

Back to your question: if somebody forks our fork, I believe this is up to them how they want to establish their governance (i.e. inbound license). Common choices are (1) no governance, (2) DCO, and  (3) CLA. We won't have any control about this, and it is not our business. It is the natural progression of open-source.

There is now an imminent danger that we disgruntle some contributors by establishing DCO for our fork. As a consequence, they may start a new fork.  Hence, we have this public discussion how contributors feel about DCO. We would like to have an understanding of the damages/advantages caused by introducing DCO for our fork.
