### ISSUE TITLE
Update wiki with new build instructions for OSX

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#435]
I understand there's a bug on the latest OSX with the profiler and gcc-7.  Could you please update the wiki instructions for building on OSX?  

Thanks!

**Comment by b-scholz** [comment]
Indeed - this is a big TODO; we need to get the documentation in order. We haven't done this for ages.

**Comment by mmcgr** [comment]
gcc-7 has a problem on both Linux and OSX. On Linux it seems to have to do with the combination of openmp and gcc-7 so possibly the same applies to OSX.

I changed the OSX build instructions to remove the mention of gcc-7 and added a general note about the gcc-7 issues. I'm not able to test the OSX instructions, though. If brew installs gcc7 by default, then more detailed instructions are needed.

**Comment by b-scholz** [comment]
Great that you found the cause. If we do a complete new build of gcc7, does the problem still exist.

**Comment by mmcgr** [comment]
I built gcc7 from the latest source yesterday, and it had the same issue.

**Comment by b-scholz** [comment]
@HerbertJordan - is there a new openmp standard for gcc7, i.e., has the semantics changed?

**Comment by seanmcl** [comment]
gcc7 is the default when I got my latest laptop and did brew install:

```
 brew info gcc
gcc: stable 7.1.0 (bottled), HEAD
GNU compiler collection
https://gcc.gnu.org/
/usr/local/Cellar/gcc/7.1.0 (1,400 files, 245.7MB) *
  Built from source on 2017-06-21 at 17:14:39 with: --without-multilib
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gcc.rb
==> Dependencies
Required: gmp ✔, libmpc ✔, mpfr ✔, isl ✔
==> Options
--with-jit
	Build just-in-time compiler
--with-nls
	Build with native language support (localization)
--without-multilib
	Build without multilib support
--HEAD
	Install HEAD version
```

**Comment by mmcgr** [comment]
Now that the gcc7 issues have been fixed, I updated the wiki again with current build instructions.
