### ISSUE TITLE
OSX, magic_liberal_identifiers and compilation time

### ISSUE THREAD

**Issue by mmcgr** [souffle-lang/souffle#437]
Sometimes the OSX tests on Travis reach the 10 minute time out while compiling magic_liberal_identifiers (and less often, magic_hmmer). It looks like a busy time for travis slows the test enough to fail. In #419, the generated cpp for that test goes up from 2700 lines to 7000 lines - this test then consistently fails even when the timeout is extended to 40 minutes. 

Can we do anything to speed up the compilation stage or is this an acceptable hazard of compiling complex datalog (or is there an obscure souffle bug somewhere)?

For more detail: running the tests with -g to generate the cpp file finishes fast. The test times out if I add a second stage that runs souffle-compile. That strongly suggests compilation is the slow part. Locally compilation of the #419 version takes ~12s with the gcc family and ~30s with clang's, and travis linux takes about double that which is slow, but workable.

#419 -g output from magic_liberal_identifiers:
[osx_magic.zip](https://github.com/souffle-lang/souffle/files/1186354/osx_magic.zip)
current -g output:
[current_magic.zip](https://github.com/souffle-lang/souffle/files/1186502/current_magic.zip)

**Comment by b-scholz** [comment]
Could it be that the VMs of Travis have different memory configurations (ie. they start swapping)?

**Comment by mmcgr** [comment]
The VMs have 4GB of memory according to the Travis docs, which should be plenty. Compiled locally on linux it uses 500MB for gcc and 300MB for clang.

That said, the timeout is either due to swapping or some deeply nested loops running too long.

**Comment by mmcgr** [comment]
For right now we can disable/simplify the tests that push us over the limit.
