### ISSUE TITLE
Documentation request: Build instructions for RHEL/Centos

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#442]

**Comment by b-scholz** [comment]
There are some docker files there:
https://github.com/souffle-lang/souffle-docker

**Comment by lyndonhenry** [comment]
Can confirm that the following bash script works for the current Docker image for centos 7 ([here](https://hub.docker.com/_/centos/)) as of today (14/12/2017). 

A more stable choice for the bison package is desirable, but this solution is simple and it works.

~~~
#!/bin/bash
yum install -y gcc-c++ java-1.8.0-openjdk sqlite-devel ncurses-devel redhat-lsb-cxx zlib-devel aws-cli zip autoconf automake bison doxygen flex g++ gcc git graphviz libsqlite3-dev libtool libncurses5-dev lsb-release make openjdk-8-jdk zlib1g-dev;
curl https://kojipkgs.fedoraproject.org/packages/bison/3.0.4/6.fc26/x86_64/bison-3.0.4-6.fc26.x86_64.rpm > bison-3.0.4-6.fc26.x86_64.rpm;
yum --nogpgcheck localinstall -y bison-3.0.4-6.fc26.x86_64.rpm;
rm bison-3.0.4-6.fc26.x86_64.rpm;
git clone https://github.com/souffle-lang/souffle;
cd souffle;
chmod 775 bootstrap;
./bootstrap;
chmod 775 ./configure;
./configure;
make;
make install;
~~~

**Comment by seanmcl** [comment]
This no longer works.  I can't find an mcpp package in EPEL.

**Comment by seanmcl** [comment]
I'm doing this for now

```
RUN wget https://www.rpmfind.net/linux/centos/6.9/os/x86_64/Packages/libmcpp-2.7.2-4.1.el6.x86_64.rpm \
  && wget https://www.rpmfind.net/linux/centos/6.9/os/x86_64/Packages/mcpp-2.7.2-4.1.el6.x86_64.rpm \
  && rpm -i libmcpp-2.7.2-4.1.el6.x86_64.rpm \
  && rpm -i mcpp-2.7.2-4.1.el6.x86_64.rpm
```

**Comment by b-scholz** [comment]
MCPP was part of the soufflé repository because the LLVM’s cpp does not work for Souffle. This hasn’t been ideal – and we removed the mcpp source from Souffle since we discovered that mcpp is available as Debian package and brew package for MAC OS X installations. Sorry for the inconvenience.
