### ISSUE TITLE
Documentation request: "static linking"

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#443]
I'd like to build souffle on one platform and copy it to another binary compatible platform.   If someone on the team could document how one could do this in general it would be great.

Currently I'm getting

```
# ./souffle
./souffle: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory
```

I notice this error goes away when I installed the packages in the build instructions.  I'd like a totally minimal docker image for this, so if someone could define precisely what libraries are required that would be great.

**Comment by b-scholz** [comment]
That is the OpenMP library of gcc. Have you had a look at the new Docker files here:
https://github.com/souffle-lang/souffle-docker

**Comment by seanmcl** [comment]
No, I hadn't seen those.  They look good!  

However, our real problem is using Souffle in Lambda, which may not have any of the dependencies.  We're using Docker to build souffle, and then want to copy the binaries into the zip file used by Lambda.  This is where static linking would really save us, since we currently can't figure out how to get Souffle running in Lambda due to missing library dependencies.  Maybe this is the wrong issue title!  Renaming.
