### ISSUE TITLE
Stop on the first failure

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#446]
I'm trying to use souffle in different OS contexts.  I think souffle should fail earlier when something goes wrong

```
/var/task/usr/local/bin/souffle-compile: line 54: dirname: command not found
souffle-compile error: installation error: souffle header files cannot be found
failed to compile C++ source ./soufflep9Bafe
failed to run executable ./soufflep9Bafe
sh: ./soufflep9Bafe: Permission denied
```

I find all the errors after the first to be confusing.

**Comment by lyndonhenry** [comment]
I agree that they are confusing, I propose we do the following to address similar sorts of things:

- Souffle should terminate with a non-zero exit code and an error message immediately upon the first internal error it encounters (but not errors with the input datalog program, as this is handled separately).
- If a file name appears in an error, debug, warning, or other message, then it should always print the absolute path of that file, and not the relative path.
