### ISSUE TITLE
Allow build without ncurses

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#448]
I can't build souffle without ncurses.  I've tried all combinations of `--without-ncurses`, `--without-ncursesw`, `--disable-ncurses`, `--disable-ncursesw`.   For building on sparse architectures it would be nice to have as few dependencies as possible.  If this is a true requirement, please add it to the wiki build instructions.

**Comment by mmcgr** [comment]
Great idea. I'll have a look at making `./configure --disable-ncurses` work. There's already an option to use stdout instead, so provenance would still be somewhat usable.

**Comment by mmcgr** [comment]
I'm adding a --disable-provenance flag that I think suits your needs better, if you are not using the interactive provenance explorer. This will remove the need for ncurses entirely.

Disabling ncurses neatly will take more work and hinder integrating upcoming provenance changes so I'm putting that off for now, but I still think it's worth doing once provenance is more stable.

**Comment by mmcgr** [comment]
Fixed by #453 

`./configure --disable-provenance` will now disable ncurses - and slightly reduce binary size and compilation time.
