### ISSUE TITLE
-I not working as expected

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#449]
```
LD_LIBRARY_PATH=/var/task/lib:/var/task/lib64 /var/task/bin/souffle -I /usr/include -c path.dl
compiler error: cannot compile source file ./souffleVarrRi.cpp
/var/task/bin/g++  -Wall -std=c++11   -O3 -fopenmp  -o/tmp/souffleVarrRi ./souffleVarrRi.cpp -lpthread -lncursesw -I/var/task/bin/../include
In file included from /var/task/include/souffle/AstTypes.h:19:0,
                 from /var/task/include/souffle/CompiledSouffle.h:19,
                 from ./souffleVarrRi.cpp:1:
```

Note that I'm using `-I /usr/include` but that is not showing up on the g++ commandline.  What am I doing wrong?

**Comment by mmcgr** [comment]
It looks like the -I flag only affects the c pre-processor. It is not intended to affect souffle's compilation stage.

**Comment by b-scholz** [comment]
That is correct. The flag -I is only there for guiding the cpp for Datalog programs. You could change this in the scuffle-compile script.

**Comment by mmcgr** [comment]
In which case, you can use `./configure CXXFLAGS="-I ..."` to add it to the g++ command line when souffle-compile runs.
