### ISSUE TITLE
--disable-libz flag doesn't work as expected

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#450]
I tried to use the `--disable-libz` flag.  The compiler fails to compile the generated c++ files because it's missing the libz headers.

**Comment by mmcgr** [comment]
This works as expected on the systems I have to check on. It's a fairly simple check for the disable flag in the configure script, so there's not much scope for a problem there.

What system does the problem occur on? Are there any warnings when you run `./configure --disable-libz`? Can you check that the configure script was run with the disable flag before the compilation was attempted?

**Comment by b-scholz** [comment]
Have you done an "sh bootstrap"?

**Comment by seanmcl** [comment]
Oh, probably not, just configure.  Closing.
