### ISSUE TITLE
--with-ncurses doesn't work as expected

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#451]
When I use the `--with-ncurses` flag, souffle still looks for `-lncursesw`.  I needed to symlink one to the other.

**Comment by mmcgr** [comment]
I haven't managed to duplicate this. If `./configure --with-ncurses` is not specified then ncursesw is the preferred choice, assuming it can be found. If `--with-ncurses` is specified then the configure script skips the ncursesw section entirely. Either way, it shouldn't be possible to end up with -lncursesw.

What system is this occurring on?

**Comment by seanmcl** [comment]
Building everything, gcc etc from source on centos7.  I don't have time to spend now narrowing it down, but closing in favor of #448.
