### ISSUE TITLE
Get rid of souffle-compile.sh

### ISSUE THREAD

**Issue by lyndonhenry** [souffle-lang/souffle#454]
The script that compiles generated C++ programs in Souffle (found at /src/souffle-compile.sh) has caused a few annoyances recently, and potentially should be replaced by something written in C++.

## Why? 

- Bash is often slow, due to its liberal creation of processes.
- Bash is troublesome when it comes to cross-platform consistency, even with the most common of dependencies.
- Bash has a reputation being both bug prone and undebuggable.
- For a large C++ project, calling bash imposes a large context swtiching burden on the developer.

Bash is good, it has its rightful use and place -- for example in coordinating and getting information different parts of the operating system -- and maybe that is the case here. But I think its use and that of external scripts in general should have a clear justificaiton for being.

**Comment by psubotic** [comment]
Are you sure this is a good idea? For example, someone may have various
unforeseen non-standard deployment constraints e..g, they want to compile
to a shared  library on some deployments etc. bash seems like a very
simple, lightweight way of allowing a user to control this. If this is put
in c++ we need to allow users to configure the compilation or would we tell
users to resorted to using the -g  flag and writing their own scripts? Do
the benefits really outweigh the drawbacks + effort?

Im not saying you are wrong. Im pretty agnostic, but I think the burden
goes the other way, i.e., we clearly need to articulate how getting rid of
it provides benefits that significantly outweigh the drawbacks.
- how much compilation time will we save?
- the script is pretty simple as of now (aside from some usage printing and
input checks it calls a compiler) what consistency issues do you foresee?
- what bugs have you seen in this small script and how was it hard to debug?

**Comment by lyndonhenry** [comment]
Not at all am I sure it's a good idea, indeed it might be one of those cases where bash is the best thing to use. 
I doubt we will save much compilation time at all, that point was just against the use external bash scripts in general as poor practice. Really, it doesn't exactly apply here and so that point can be thrown out the window.
Having the script as a lightweight way to configure compilation is, I agree, an excellent advantage. However, the script itself is generated by autoconf/automake, so users have to either know how to configure through these or generate the script and edit it themselves -- unless they specifically don't want OpenMP support, which is the only configuration option the script itself provides (which seems quite arbitrary). Doing it in C++ is, because of this advantage, perhaps a bad idea, maybe a good old fashioned Makefile would be better, or even just sticking with bash. The crux of this point is not the use of bash, but the somewhat sprawling nature of configuration options for compiling Souffle and running it. It would be good to have a singular, consistent interface for this sort of thing. It might just be worth closing this issue and opening another one on that point, as it seems a more fundamental and important concern. 
In terms of cross-platform consistency and bugs, I've had a few troubles with resolving the paths of things. For example, to get the absolute path of a file, I went though `realpath` command, which is supported on most modern Unix-like systems, but not all, and so had to be changed to `readlink -f`, which is also supported on most but not all systems, and had to finally be changed to `cd "$(dirname $1)"; dir="$PWD"; cd "$OLDPWD";` which is supported on all POSIX compliant systems. By no means a difficult fix, but one which was time consuming to debug due to having to make sure it worked across different platforms, and certainly more effort than it should take to resolve an absolute path.

**Comment by b-scholz** [comment]
Thanks for starting this discussion. Is it possible to measure the overheads? 
Is there something more lightweight that could replace our shell-script but still is not C++? E.g., a embedded DSL in C++ doing scripting work in form of a library?

**Comment by scyptnex** [comment]
The bash script is a bit of a hack but i wouldnt replace it with a C++ version. The bash file is actually configured by automake so that the settings you use to configure souffle with are used when you want to compile a souffle executable. **Of course that is a bad architectural decision**. Ideally, there would be a separate configuration which was used for souffle and which souffle uses for its compilations.

To be honest the only silver bullet here is to use a real build system (cmake, automake, gradle) to build souffle executables. This is the only way to allow cross platform building, and the kind of things @seanmcl was requesting

A better mechanism for building souffle executables was discussed in #150

**Comment by mmcgr** [comment]
Closing this as the consensus is to keep it, at least until such time as the build system is changed more substantially.
