### ISSUE TITLE
Parameter Handling of Option -j

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#46]
When compiled with `-o -j<nr>` the number of cores `<nr>` is ignored in the executable and the default number of processors is used instead.

**Comment by HerbertJordan** [comment]
There is one bug left here: when using -j auto, the `omp_num_threads` function in the interpreter and the executable is called with 0 as the number of threads, which is undefined behavior.

In both cases it should be something like
```
if (num_threads > 0 ) omp_num_threads(num_threads);
```

**Comment by b-scholz** [comment]
Ok - I will have a look.

**Comment by b-scholz** [comment]
Please can you have a look. The next change set deals with appropriate parameter handling for "auto". I checked for various execution models to ensure that omg_num_treads() is only invoked if a specific number of jobs is set.
