### ISSUE TITLE
proposal: plugins

### ISSUE THREAD

**Issue by psubotic** [souffle-lang/souffle#461]
Souffle has been recently improved a lot with excellent student projects from Bernhard's ug students. However, as they keep coming, souffle could get pretty bulky and monolithic. While some of these enhancements are core enhancements, i.e., every user will want them, many are specific to niche users. Unfortunately, with every enhancement comes dependencies to external libraries etc. I propose the concept of a souffle plugin, i.e., a group of extensions that live in a separate souffle-lang repo that implement a certain interface and that can be plugged into Souffle on the request of users during build time. This makes it easier for people to contribute without knowing the core internals, keeps the core engine clean, isolates bugs etc.  This isn't an easy task but I think with the Souffle interface we have a bit of a start to this.  I would like to hear peoples opinions and potentially who would be interested into helping out with this.

**Comment by lyndonhenry** [comment]
I like this idea, it would certainly improve code quality immensely. It would be a pretty difficult task, as most of the enhancements are spread across the codebase in different places and are not easy to modularise, but I'd say worth it, and if Souffle keeps growing as it is, a necessity. 

We'd have two huge design challenges ahead of us:

1. What is Souffle core, and what are each of the plugins?
2. What does the interface need to expose to a plugin?

These of course go hand in hand - if the interface does not expose the capability for a new plugin to be implemented but is correct in what it exposes, then you're dealing with a part of Souffle core and not a plugin. Similarly, if you can implement your new feature as a plugin, it is not part of Souffle core. 

Tackling this task all at once or by one person would be practically impossible; you'd have to figure out how each plugin worked, extract it from the code, move it to a plugin, and pray very hard nothing was left that depended on it. Doing it plugin by plugin is a nightmare also as everyone's code would be breaking from week to week and you'd have to figure our what plugins you needed, and things could get quite a bit more disorganised than they are. 

So, as a first start, to allow the design of the interface to grow organically and allow developers to gradually move things to plugins from the areas of code they know and understand best, we could break the src directory up into sub directories, each of which is the code for a plugin within its own namespace. From there we can go through each directory, and turn it from being an include of Souffle to being a plugin. Eventually, we'd have a collection of folders that can easily be moved to separate repos.
