### ISSUE TITLE
Better Namespacing Using Subdirs in src

### ISSUE THREAD

**Issue by lyndonmhenry** [souffle-lang/souffle#462]
Currently, the source code for Souffle is mostly all contained together in a single src directory. 

This can make it a bit confusing to find the area of code you are looking for, or to understand how things fit together as a whole. 

So, the idea is that we have subdirectories in src, with the code in each belonging to its own namespace (where the namespace is the base name of the subdirectory). There should be no subsubdirectories, one level of nesting is, I think, suffient in all cases. This also ties in to #461, and will make it much easier to do. 

Also, it is not at all immediately obvious what file a class resides in. So in each subdirectory, the names of the files should indicate clearly what classe/s live in them. One possible way to do this is to be like Java and have one top level class defined per file. Certainly that solves this problem, but I'm hesitant to recommend it as Souffle has a lot of small top level classes (e.g. each of the AST node types, RAM statements/operations, etc) which work a lot better if they are all together in the same file. It might not be possible to avoid this tradeoff unless we do things as we do, that is putting classes together in the same file as per what seems appropriate on a case by case basis, and so remains to be discussed if having a standardised way of doing this is a good way to go.

**Comment by scyptnex** [comment]
Also related to the build system #150

**Comment by b-scholz** [comment]
We should consider this after RAM Refactoring Issue #541.

**Comment by mmcgr** [comment]
We've now deepened souffle's directory structure to separate components.
```
src
src/ast
src/ast/analysis
src/ast/transform
src/interpreter
src/ram
src/ram/analysis
src/ram/transform
src/synthesiser
src/tests
src/utility
```
src/io would also be nice, but a little more work with the build system is need first

**Comment by mmcgr** [comment]
Many classes are still grouped together in single files. This is simpler in some cases, but are minimally unrelated in others. With the new directory structure it's now easier to separate the classes into separate files and still maintain a clear organisation. This has already been done for the grouped analyses and transformers.

Next up, separate files for the class in `src/ast` and `src/ram`.

**Comment by b-scholz** [comment]
Let's split ast/Abstract.h into separate class files as well, and also all its sub-classes. Similarly, we should split all ram classes and have them reside in their own files.

**Comment by b-scholz** [comment]
By the way - the copyright messages are not correct - a lot of transformations/analysis were implemented by the souffle-dev team. We need to cross-check and change the copyright accordingly.

**Comment by mmcgr** [comment]
Extending this a bit to include public headers:
```
src/

src/ast/
src/ast/analysis/
src/ast/transform/

src/ram/
src/ram/analysis/
src/ram/transform/

src/interpreter/

src/synthesiser/

src/tests/

# public headers used by both interpreted and synthesised souffle
src/include/souffle/
src/include/souffle/io/
src/include/souffle/profile/
src/include/souffle/utility/
```

We could add to that with
```
src/include/souffle/datastructure/
src/include/souffle/provenance/
src/parser/

src/driver/ # less sure about this one, but gives somewhere to put all the option and shared ast/ram files
```

**Comment by b-scholz** [comment]
There are more TODOs:

- There is still a mutual dependency in AstProgram.h and Utils.h that needs to be removed.
- The class descriptions are very terse and need to be extended with syntax examples
- Check for consistent interfaces across AST and the need for Provenance elements in AST (SubroutineArgument.h / ProvenanceNegation.)
- Check for consistent interface naming
- Remove forward class declaration where possible
- Define own ast/TypeDomain.h
- ast test-cases should be pushed into the ast-directory structure

**Comment by b-scholz** [comment]
- ram/analysis still has files ending with analysis
- double-check copyright messages
- src/Utils.cpp needs to be renamed to src/TypeAttribute.cpp

**Comment by mmcgr** [comment]
- [ ] There is still a mutual dependency in AstProgram.h and Utils.h that needs to be removed. (Some functionality would need to be moved into an Analysis.)
- [ ] The class descriptions are very terse and need to be extended with syntax examples
- [ ] Check for consistent interfaces across AST and the need for Provenance elements in AST (SubroutineArgument.h / ProvenanceNegation.)
- [ ] Check for consistent interface naming
- [ ] Remove forward class declaration where possible
- [ ] Define own ast/TypeDomain.h
- [ ] ast test-cases should be pushed into the ast-directory structure
- [ ] ram/analysis still has files ending with analysis
- [ ] double-check copyright messages
- [ ] src/Utils.cpp needs to be renamed to src/TypeAttribute.cpp

**Comment by mmcgr** [comment]
`ast` namespaces added in #1628

**Comment by b-scholz** [comment]
I would suggest breaking up the TODO list and putting each TODO item into an own issue. @mmcgr - are you ok with that?

**Comment by b-scholz** [comment]
The main reason is that @azreika will start with the translator refactoring, and some of the TODO items are connected.

**Comment by b-scholz** [comment]
Talked to @mmcgr - we are closing this issue. I have put left-over TODO items into new issues.
