### ISSUE TITLE
substr() is executed before a strlen() check

### ISSUE THREAD

**Issue by brodyf** [souffle-lang/souffle#464]
Suppose we were to execute the following Datalog program in Souffle:
```
.decl S(s:symbol)

S("hello").

.decl reversed(s:symbol, r:symbol)

reversed(s, substr(s, strlen(s)-1, 1)) :- S(s).
reversed(s, cat(r, substr(s, strlen(s)-(strlen(r)+1), 1))) :-
    reversed(s, r),
    strlen(r) < strlen(s).

.output reversed(IO=stdout)
```
We get the expected results:
```
---------------
reversed
===============
hello	o
hello	ol
hello	oll
hello	olle
hello	olleh
===============
```
However, Souffle also outputs a warning to stderr, depending on whether the program was executed in the interpreter or compiled:
- `souffle buggy.dl`:
```
warning: wrong index position provided by substr("hello",-1,1) functor.
```
- `souffle -c buggy.dl`:
```
warning: wrong index position provided by substr("hello",18446744073709551615,1) functor.
```
There are two related problems here:
- The check `strlen(r) < strlen(s)` is carried out after `substr(s, strlen(s)-(strlen(r)+1), 1)`. The warning arises from -1 being used as an index for `substr()` and causing an out_of_range exception to be thrown.
- The difference in the warning messages caused by the compiled version first casting -1 to `size_t` via `substr_wrapper()`.

I would be interested to hear your thoughts, especially regarding the first one.

**Comment by mmcgr** [comment]
The first part is expected behaviour. All parts of the rule can be executed at once. In practice they are executed in an arbitrary order.

Note that it may be faster to execute the body first, but this would need more thought and testing.
