### ISSUE TITLE
Subprogram Compilation w/ Records

### ISSUE THREAD

**Issue by lyndonhenry** [souffle-lang/souffle#467]
Pull request #465 introduced the `-s` option, however if any argument having a record type occurs in the program, it is automatically disabled in `src/AstSemanticChecker.cpp`. 

There are `TODO`'s in that file, added in #465 that explain how to disable this behaviour, however this causes problems as with the `-s` option, relations involving records in their head start being treated as input relations (which they cannot be). 

Now, one solution to avoid the problems of relations involving records in their head being used as input relations is to create artificial dependencies between such relations and those in their body, making them recursive and so put together in a single subprogram.

Another `TODO` in `src/PrecedenceGraph.cpp` shows how to to this, but unfortunately this creates unused variables in the `CREATE_OP_CONTEXT` macro as noted by the `TODO` in `RamExecutor.cpp`.

**Comment by b-scholz** [comment]
Let's discuss this issue after refactoring.
