### ISSUE TITLE
Subprogram Compilation Timeout

### ISSUE THREAD

**Issue by lyndonhenry** [souffle-lang/souffle#468]
The tests in evaluation timeout with the new `-s` option -- added in #465 -- when running on Travis. It would clearly be better if they didn't. A `TODO` has been added to `.travis.yml` noting this, and showing how to enable evaluation tests with the `-s` option.

The reason for this is almost certainly due to the number of different subprograms that must be compiled when using the `-s` option. As a starting point for a solution, it would be good if one could set a maximum number of subprograms *N*, and if the number of stratum is greater than *N*, have multiple stratum assigned to a single subprogram.

**Comment by mmcgr** [comment]
As far as the testing part of this goes, would it make sense to have a category of tests specifically for testing -s and -f?

I think whether or not this makes sense depends on whether you need to run all the tests to find obscure corner cases, and make sure we don't break them in future, or can you check -s/-f code specifically with the right tests.

**Comment by lyndonhenry** [comment]
I thought about this and unfortunately, it certainly won't work for `-s`. `-s` needs to be tested for corner and edge cases, as we need to be sure that computation can work over the course of executing the produced subprograms. With new features, and even existing ones (see the issue regarding records #467) this can cause problems, as the programs themselves aren't allowed to communicate any information except in the form of intermediate facts files and output csv files. It's easy to conceive of a scenario in which someone introduces a new feature that violates this constraint to achieve its ends.

`-f`, on the other hand, this might work for, as all it does is produce additional output files, and additional read calls which only ever do anything if execution is terminated halfway through, then restarted, which the testsuite doesn't even test for -- like the `-p` tests, it is really only to make sure that nothing funny happens in Souffle if we use `-f`, not that `-f` itself actually works.

**Comment by b-scholz** [comment]
We have retired these options / let's refresh after RAM refactoring.
