### ISSUE TITLE
Output ordering determinism

### ISSUE THREAD

**Issue by mmcgr** [souffle-lang/souffle#475]
Currently output, to stdout, does not have a deterministic ordering. This is almost entirely (entirely?) from printsize, the use of -D-, or IO directives sending relations to stdout.

It would be useful if output was always in the same order, and that order was related to the declaration of the relations in the datalog file. This is not always the case at the moment, and can vary on each run.

**Comment by pnappa** [comment]
Threaded or not?

**Comment by mmcgr** [comment]
Threading does not affect this (for now). Currently the behaviour is the same whether threaded or not as we don't write to stdout while still working with other relations - or even really do much with multiple relations at once. As soon as we do have that sort of threading the order will be non-deterministic for some programs.

The non-determinism here seems to be entirely due to relations that are ordered arbitrarily by memory address. The result is usually the same, but not always.

**Comment by mmcgr** [comment]
I'm closing this issue as it is reasonable for souffle to re-order execution, for example, for better performance, and also reasonable to output logging information as soon as it is generated. This means both that the order will change and that we want it written out immediately.

If we ever return to this issue then we will need a new Logger that has an option to store output until souffle finishes and re-order it before output.

**Comment by mingodad** [comment]
Can this behavior be in the documentation to help other people, like me that was going to open a new issue and search for `output order` found this one.

**Comment by mingodad** [comment]
Added a pull request here https://github.com/souffle-lang/souffle-lang.github.io/pull/125 to document this behavior.
