### ISSUE TITLE
Weird errors on records

### ISSUE THREAD

**Issue by gkastrinis** [souffle-lang/souffle#479]
I have the following simple (?) code and I cannot figure why I get the errors I get.

    .type _R5 = [var0:symbol, var1:number]
    .type _R6 = [var0:number]
    .type _T1_RAW = [var5:_R5, var6:_R6]
    .type T4 = [var0:_T1_RAW]
    .decl foo(var0:symbol, var1:T4)
    .output foo
    foo("Hello", [["Hello", 42], [nil]]).

-------

    $> souffle -w out.dl
    Error: Symbol constant (type mismatch) in file out.dl at line 8
    foo("Hello", [["Hello", 42], [nil]]).
    ---------------^----------------------
    Error: Number constant (type mismatch) in file out.dl at line 8
    foo("Hello", [["Hello", 42], [nil]]).
    ------------------------^-------------
    Error: Null constant used as a non-record in file out.dl at line 8
    foo("Hello", [["Hello", 42], [nil]]).
    ------------------------------^-------
    3 errors generated, evaluation aborted

I'm not sure about the version of souffle. The binary I run might not be entirely up to date. I see "Version: 1.1.0" but I don't know if this updates in each commit.

**Comment by lyndonhenry** [comment]
This looks like correct behaviour to me.

For the rule 
```
.decl foo(var0:symbol, var1:T4)
```
The second argument expands as 
```
var1:T4 = [var0:_T1_RAW] =  [[var5:_R5, var6:_R6]] = [[[var0:symbol, var1:number], [var0:number]]
```

For the fact 
```
foo("Hello", [["Hello", 42], [nil]])
```
The `nil` object, which is of the type of an empty record, is used as a number. 

However, both
```
foo("Hello", [["Hello", 42], nil])
```
and 
```
foo("Hello", [["Hello", 42], [0]])
```
*should* work fine (though I haven't tested it myself).

**Comment by lyndonhenry** [comment]
Yeah, just confirmed it then and the current version of souffle has the correct behavior. 

I've extended and commented your program below to show what I mean.
```
.type _R5 = [var0:symbol, var1:number]
.type _R6 = [var0:number]
.type _T1_RAW = [var5:_R5, var6:_R6]
.type T4 = [var0:_T1_RAW]
.decl foo(var0:symbol, var1:T4)
.output foo
foo("Hello", [["Hello", 42], [nil]]). // original error, meant to do this
foo("Hello", [[["Hello", 42], [nil]]]). // new error, also meant to do this
foo("Hello", [[["Hello", 42], nil]]). // no error here, intended behavior
foo("Hello", [[["Hello", 42], [0]]]). // no error here either, all works as expected
```

Records are one of those things that really ought to be documented better though, a point illustrated most directly by the fact that this issue already far exceeds the length and comprehension of the wiki page.

**Comment by gkastrinis** [comment]
Oh, it was just a typo on how many brackets were needed. I almost took that for granted and I couldn't figure out the error messages. Sorry to bother you!

Just a follow-up question and you can close this.

Is there any reason to prefer flat vs nested records? E.g. is [[1,2],[3],["hello"]] worse in some way compared to [1,2,3,"hello"]?

**Comment by lyndonhenry** [comment]
That is OK, the error messages aren't really very helpful when it comes to records yet -- I do feel like they should be, this is both a trivial bug to detect and common enough to have its own message. 

On nested records, one reason to prefer flat ones is this very issue -- that is, for the user, a minor typo in the correct number of brackets leads to confusing error messages. 
Other than that, I'm not familiar enough with their implementation to confidently say I know what I'm talking about, as I've haven't touched most of that code.

I think @mmcgr was looking in to them recently, and would likely known better than I would.

**Comment by mmcgr** [comment]
The flat approach is faster to run. The extra indirection needed for records slows things down. Whether the difference in speed is important depends on the size of the input. 

If records better represent your problem, though, then your code may be faster to write.
