### ISSUE TITLE
Performance Optimization for Indicator Relations

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#48]
Example:

```
R(x) :- A(_), B(x). 
```

Transfer tuples from relation B to relation R if relation is not empty. Semantically, this can be interpreted as

```
R(x) :- size(A)>0, B(x). 
```

Souffle currently does not provide this optimization.

**Comment by mmcgr** [comment]
Did this get worked on?
Currently the compiled version turns `R(x) :- A(_), B(x).` into
```
if (!rel_1_A->empty()) {
  for (const auto& env1 : *rel_2_B) {
```
Which seems to be what you describe.
I think the relevant parts of the code are
https://github.com/souffle-lang/souffle/blob/1392c6772c11760c9048fb7a5a65ed20c0cf2d3e/src/RamTranslator.cpp#L668-L673
and
https://github.com/souffle-lang/souffle/blob/1392c6772c11760c9048fb7a5a65ed20c0cf2d3e/src/RamExecutor.cpp#L483-L488

**Comment by b-scholz** [comment]
This has been fixed.
