### ISSUE TITLE
Provide a code-generation only flag to integrate souffle in external tool build system.

### ISSUE THREAD

**Issue by HerbertJordan** [souffle-lang/souffle#49]
For embedding souffle analysis into tools, only source code needs to be generated. An external build script then build the analysis as part of the enclosing application.

Suggestion: add an option -g to the compiler, which stops the compiler after generating the output code.

**Comment by b-scholz** [comment]
We have already this flag. This is the -o flag. The source code and an executable is generated. However, the executable is not invoked.

**Comment by HerbertJordan** [comment]
I know, and the request is about a flag to just create the code and skip the compilation to an executable.

**Comment by b-scholz** [comment]
I see. Sure - go for it.

**Comment by HerbertJordan** [comment]
Added by  8a68cd0
