### ISSUE TITLE
Profiling tests

### ISSUE THREAD

**Issue by mmcgr** [souffle-lang/souffle#490]
The current tests of the profiling code need to be improved. They do not test the code in any depth, and the results are non-deterministic (although usually the same).

There are currently two tests of the profiling code that are used.
The first is to run the standard testcases with `-p profile.log` which tests if enabling profiling output causes the normal output to differ. This checks if enabling profiling breaks anything.
The second is to check the souffle-profile executable which runs souffle with `-p profile.log` then runs souffle-profile to generate more specific profiling output, then checks the result by counting the number of lines. This is a very minor check of the souffle-profile code and relies on the output of `-p profile.log` to be the same on every run - which is not a reliable assumption.

How can we test the code in more depth? How can we make the tests repeatable?

**Comment by mmcgr** [comment]
I think the `-p profile.log` tests can be removed. The current tests ensure that enabling profiling doesn't break anything, and tests it with "all" commands, but this seems like a trivial test that is only useful in thorough testing, not a standard level of testing.

The Profile category of tests can be made deterministic by using a saved log, rather than generating one each time the test is run. Alternatively, the input program could be written in a way that forces a particular ordering of events. I think this might also be a bit frail as optimisations are added to souffle. Either way, we are still testing that the text matches what we expect rather than does it work.

I would be okay with disabling both types of test for default testing levels. Testing the syntactic/semantic code with `-p` does check for major breakages, and the Profile category with a saved log checks if souffle-profile still outputs as expected, so I think they are both useful, but not an essential baseline test. Users reporting issues may be a more reliable test.

**Comment by lyndonhenry** [comment]
The CSV output Souffle produced is unordered, and with the close of #475, it seems it will likely always (and I think rightly) be so. The tests for CSV files sort the actual and expected output, then do a diff. The only thing I can think of stopping us from doing the same thing with the profiler is that it produces counts and times, and these won't be the same across each run. So why not just `sed s/[0-9][0-9]*//g'` on the profiler log files to remove the numbers, then sort and diff them as we do with the CSV files? Keeping their ordering non-deterministic also means they (may presumably) give insight into the order of events in the code which are meant to be non-deterministic.

**Comment by mmcgr** [comment]
The profiler tests are a little more special than that. They test the output of the profiler analysis rather than the profile output. Their output can sometimes change drastically. I have not looked into it any further, but I expect that this is down to the order of the relations in the profiling log  - so modifying the profile output as you suggest before running those tests would still make the test deterministic.

I think if the tests of souffle-profile are modified, as they would need to be if the profile output is changed to json, then the tests should be split into tests that profile output can be read by the profiler, and tests that a profile output stored with the test case generate the expected analysis. This lets the test be more deterministic while the input can still be non-deterministic.

Tests that the expected profiling output is generated would also be nice, although care would be needed to avoid rules that might be optimised away in future. I'm not certain, but I think this is almost equivalent to your suggestion.

**Comment by mmcgr** [comment]
I'm closing this as the profiling storage and output is being rewritten, affecting the required tests.
