### ISSUE TITLE
Provenance explain interface fails with certain strings

### ISSUE THREAD

**Issue by taipan-snake** [souffle-lang/souffle#492]
The explain interface for provenance (invoked with `-t1`) will not work with certain strings containing brackets or spaces. For example, given the program

```
.decl a(x:symbol)
.output a

a("b(").
a("b c").
```

attempting to `explain a(b()` or `explain(b c)` will cause a lookup error.

This can be fixed by improving the string matching in the explain interface.

**Comment by b-scholz** [comment]
You could use the C++ regular matching interface, to write a better command line parser, i.e., 
http://en.cppreference.com/w/cpp/regex/regex_match

**Comment by taipan-snake** [comment]
Fixed by #511
