### ISSUE TITLE
Handle \r\n

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#495]
We experienced a problem on OSX and Linux where CSV input files to Souffle with line endings using the Windows convention of \r\n added \r to the last atom of the line.  A zipfile is attached with a short example.  I think Souffle should either raise an exception or handle this correctly; the user never means for \r to be the last character.

**Comment by seanmcl** [comment]
[cex.zip](https://github.com/souffle-lang/souffle/files/1415576/cex.zip)

**Comment by psubotic** [comment]
@mmcgr @b-scholz can you guys look into this soonish? Otherwise ill fix it on the weekend. Thanks!

**Comment by souffle-lang** [comment]
We will double-check today the issue.

**Comment by seanmcl** [comment]
Thank you for the quick fix!
