### ISSUE TITLE
Equivalence relation 

### ISSUE THREAD

**Issue by nikofil** [souffle-lang/souffle#498]
I have been looking at the `eqrel` qualifier, and possible performance gains that it might yield. However, looking at the code at https://github.com/souffle-lang/souffle/blob/master/src/RamRelation.h#L324 it is my understanding that declaring a relation as `eqrel` simply adds all the pairs to the relation that are under the same equivalence class instead of using some specialized data structure. Therefore, declaring a relation `.decl rel(x: symbol, y: symbol) eqrel` is similar to doing:
```
.decl rel(x:symbol, y:symbol)
rel(x, x) :- rel(x,y).
rel(y, x) :- rel(x, y).
rel(x, z) :- rel(x,y), rel(y,z).
```
Is this correct, and if so do you plan to change the implementation to something more efficient?

**Comment by psubotic** [comment]
do you observe any performance gains using eqrel over encoding the explicit
datalog rules ? From our experiments, you should see considerable
performance gains.

**Comment by mmcgr** [comment]
The interpreted version is still a naive implementation. It's faster than the equivalent datalog version, but the complexity is similar. The compiled version is, as Paul said, considerably faster.

We do have plans to improve the interpreted version, but right now there's no definite timeline.

**Comment by nikofil** [comment]
Yes, you are right.
Thanks!
