### ISSUE TITLE
Feature request: write header line with variable names in CSV output

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#499]
Souffle CSV files correspond to relations in the input datalog file.  E.g.

```
decl foo(x: Int, y: Int)
```

I would love an option to tell Souffle to write the CSV file for `foo` with a header line consisting of the variable names, here it would be `x\ty`

We need this because we are solving problems in different parts of a program and don't want to need to parse the datalog file to get the input variable names.

**Comment by b-scholz** [comment]
That can be done in the I/O system. I will ask Martin.

**Comment by mmcgr** [comment]
This used to be challenging, since the compiled version does not have the named attributes, but that's no longer an issue. I should be able to implement this pretty quickly now.
