### ISSUE TITLE
Segmentation fault when using eqrel

### ISSUE THREAD

**Issue by nikofil** [souffle-lang/souffle#501]
I came across a segmentation fault which happens sometimes when using `eqrel`. I'm attaching the most minimal example that would throw the segfault. This was tested using the current Github snapshot, as well as version 1.1.0.

[err.zip](https://github.com/souffle-lang/souffle/files/1449922/err.zip)
To run the example:
```
unzip err.zip
cd final
souffle -c err.dl -o a
./a -Ffacts -Dout
```

The exact error is:
```
Segmentation violation signal in rule:
Merge(from,to) :- 
   Reachable(meth1),
   StoreInstanceField(from,stBase,fld,meth1),
   Merge(stBase,loBase),
   LoadInstanceField(loBase,fld,to,meth2),
   Reachable(meth2).
in file /final/err.dl [66:1-71:22]
```

**Comment by mmcgr** [comment]
I've duplicated the issue, and I think I have a fix.

**Comment by nikofil** [comment]
I tested your PR and it fixes the example I uploaded, but after testing it with a larger input, the segfault is still there. I'll upload another example soon, once I figure out which facts are needed to reproduce it, as my facts dir is 640 MB.
Also, I noticed the following:
```
~/d/o/v/b4e67c5821fe81cf36e661bf860ca82f3c278a378d459fe5a130043e38f04b0b experiment ❯ ./b -j1 -Ffacts -Dout
Segmentation violation signal in rule:
Merge(from,to) :- 
   Reachable(meth1),
   StoreInstanceField(from,stBase,fld,meth1),
   Merge(stBase,loBase),
   LoadInstanceField(loBase,fld,to,meth2),
   Reachable(meth2).
in file /home/nfil/doop-nexgen/out/vpt-eq/b4e67c5821fe81cf36e661bf860ca82f3c278a378d459fe5a130043e38f04b0b/vpt-eq.dl [1366:1-1371:22]
~/d/o/v/b4e67c5821fe81cf36e661bf860ca82f3c278a378d459fe5a130043e38f04b0b experiment ❯ ./b -j2 -Ffacts -Dout
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 3501427744) >= this->size() (which is 253)
[1]    49104 abort (core dumped)  ./b -j2 -Ffacts -Dout
```
(using many threads results in `std::out_of_range`)

**Comment by nikofil** [comment]
I wasn't able to remove any facts, thankfully it was compressed down to 29MB, so here you go.
https://drive.google.com/open?id=1g7nOkKGC9214RpZXIiSkTnUIDeRjNkvZ
To run:
```
unzip last.zip
cd last
souffle -c vpt-eq.dl -o vpt
./vpt -Ffacts -Ddatabase
./vpt -Ffacts -Ddatabase -j2
```

**Comment by mmcgr** [comment]
Thanks for the update. The issue now is similar - stale data is being cached. I'm not seeing the new source as yet.

I expect #503 is related and due to use of the stale data that does not have the newer insertions. That's just a guess at this point, though.

**Comment by mmcgr** [comment]
I believe I've finally found the underlying cause of the new error. It required a large dataset and the right access patterns to trigger.

A fix should be ready soon. (And incidentally, I'm told a much faster implementation of eqrel is coming in the near future.)
