### ISSUE TITLE
eqrel relations sometimes don't have all relevant tuples

### ISSUE THREAD

**Issue by nikofil** [souffle-lang/souffle#503]
As the title says, I've noticed that `eqrel` relations sometimes don't contain all relevant tuples, particularly when an `eqrel` relation appears both in the head and body of a rule some tuples might be missed (though I'm not sure this is the only case that this happens).
An example can be found at https://drive.google.com/open?id=1ILHEJaBwIBPci2S1Yn4ciWzT8XHOYuE5. Once again, it's a bit large, but I couldn't manage to reproduce it with less inputs.
You can see the error by running the following commands:
```
$ souffle -Ffacts -Dout err.dl
$ wc -l out/Reachable.csv
13 out/Reachable.csv
```
Then, if you comment out the first line in `err.dl` and run the same commands, `Reachable.csv` will have 2 additional lines. This shouldn't happen, as commenting out the first line simply changes `Merge` to `Merge2` in line 12, however the two should contain the same info, as `Merge` is defined with `eqrel`.
```
.decl Merge(h1: HeapOrVar, h2: HeapOrVar) eqrel
.decl Merge2(a: HeapOrVar, b: HeapOrVar)
Merge2(b, a) :- Merge(a, b).
```

**Comment by mmcgr** [comment]
After fixing #501, both the initial error and the later one fixing that revealed, I think this is not directly related to #501. Adding a Merge 3, set up similar to Merge2, produces different results even in interpreted mode. In interpreted mode there is also the quirk that a Merge4 eqrel that should be a copy of the Merge eqrel, is not identical.
e.g.
```
.decl Merge3(a: HeapOrVar, b: HeapOrVar)
.decl Merge4(a: HeapOrVar, b: HeapOrVar) eqrel
Merge3(a, b) :- Merge(a, b).
Merge4(a, b) :- Merge(a, b).
.output Merge, Merge2, Merge3, Merge4
```

**Comment by mmcgr** [comment]
This seems to be caused by an assumption in souffle's code that pre-dates eqrel: that if you insert n tuples into a relation (Merge), then inserting those same n tuples into a copy (Merge2) has the same effect. This is not true when one is an eqrel.

In your example, also defining Merge2 as an eqrel should help, but obviously this can't be done in any case where you specifically need a non-eqrel relation.

**Comment by b-scholz** [comment]
May I suggest to simulate the equivalence relation, i.e., if we write for Merge4
```
Merge4(a,a) :- Merge4(a,_). 
Merge4(b,b) :- Merge4(_,b). 
Merge4(b,a) :- Merge4(a,b).
Merge4(a,c) :- Merge4(a,b), Merge4(b,c). 
```

**Comment by nikofil** [comment]
Merge4 works right without the need for additional rules. Adding the rules you suggested to Merge2 or Merge3 fixes the problem for them too, however not for Merge.

**Comment by b-scholz** [comment]
If you remove all "eqrel" qualifiers in the declaration of relations, and add to each equivalence relation the rules as given above for the relation, the problem still persists?

**Comment by nikofil** [comment]
No, everything works then (but is much, much slower).

**Comment by b-scholz** [comment]
This is expected. We just try to narrow down the issue.  The problem is that we most likely have a bug in how we keep track of the deltas and newly found pairs of the equivalence relations. 

When you switch on the eqrel qualifier for a single relation only (from Merge, Merge1 to Merge4), which versions work correctly?

**Comment by mmcgr** [comment]
A simpler test case that shows the problem:
```
.decl notEqrel(x:number,b:number)
.decl isEqrel(x:number, y:number) eqrel

notEqrel(x, y) :- isEqrel(x, y).
isEqrel(x, y) :- notEqrel(x, y).

isEqrel(0,1).

notEqrel(1,2).

.output isEqrel, notEqrel(IO=stdout)
.printsize isEqrel, notEqrel
```

**Comment by b-scholz** [comment]
As discussed today we need to over-approximate the new knowledge of an equivalence relation so that we can still utilise an equivalence relation for the new knowledge. Otherwise the costs of using a b-tree or brie for the new knowledge may become to slow.
