### ISSUE TITLE
Build system should not die if I am too aggressive with parallelism

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#505]
When I dropped from `-j 32` to `-j 2` the build worked.  Would it be possible for the build to still succeed even if I give a `-j` argument with more cores than are available?

**Comment by mmcgr** [comment]
The build system does work with more cores than the system has. The limitation is usually more to do with memory consumption than cpus available. The compiler can get quite memory-hungry when making souffle.

At least, it does for all the machines I've tested it on. If you saw this in relation to the errors in #504 , those error messages mentioned an internal gcc error. Could the problem have been a transient gcc bug or a memory issue? If not, I would guess there is another dependency issue.

Unless IO is your bottleneck, setting -j to the number of cores or a bit less is probably fastest.

**Comment by b-scholz** [comment]
I am just curious whether make has an adaptive option for -j<nr>. Depending on the system capabilities, it will set <nr> fully automatically.

**Comment by mmcgr** [comment]
The closest to an adaptive option is `make -j` with no number which starts a thread for every job. As long as you have the memory for it, this will keep your cores busy. 

Closing this for now as I can't duplicate it. If you see the problem again, please re-open this issue with any new details you can provide.
