### ISSUE TITLE
Create Launchpad PPA for install/update on Ubuntu

### ISSUE THREAD

**Issue by jgsuess** [souffle-lang/souffle#506]
I know you are able to build a *.deb package. Could you set up a [PPA](https://help.launchpad.net/Packaging/PPA)? I think this would be great, especially for teaching environments.
BTW: Thanks for the person who set up the homebrew!

**Comment by b-scholz** [comment]
Yes - we do have one but we haven't uploaded the latest versions for some time. 

https://bintray.com/souffle-lang/deb/souffle

This reminds me that we should be more consistent about this.

**Comment by mmcgr** [comment]
I updated bintray with the latest release, 1.2.0, but we should automate this process so the bintray ppa is updated with each tagged release.

**Comment by b-scholz** [comment]
This is related to issue #53.

There is an article how to do this. We would need automated signing etc. 
https://blog.bintray.com/2014/12/16/hosting-debian-packages-on-bintray-rocks/

**Comment by mmcgr** [comment]
Travis has docs on how to automate the process: https://docs.travis-ci.com/user/deployment/bintray/

Re #125 - that would be great, but even if we do get souffle into the standard packaging system, it would be good to have an unstable ppa for the latest master build.

**Comment by mmcgr** [comment]
I set up a ppa for Souffle's current head.

https://launchpad.net/~souffle-lang/+archive/ubuntu/souffle
