### ISSUE TITLE
Compiling with Souffle in a Sandboxed Environment

### ISSUE THREAD

**Issue by lyndonhenry** [souffle-lang/souffle#507]
I have a very particular use case, explained as follows:

1. I'm on a Linux machine with sudo privileges and all Souffle dependencies installed.
2. I pull Souffle from github, bootstrap it, run configure, and make.
3. I now copy the contents of the Souffle directory to another machine, which is an exact clone except has no Souffle dependencies installed (meaning no C++ compiler).  I do not have sudo privileges on this machine and cannot install new packages.
4. I now compile a datalog program on the new machine with the copied Souffle executable, with the -o/--dl-program option enabled. 

Currently, the last step fails, as Souffle needs a C++ compiler to produce an executable from the generated code. 

I can include anything I want in the copy over to the new machine, so pointing the system call Souffle makes to the C++ compiler to some other executable bundled with it in the copy is likely the most feasible route.

Anyone have any ideas or thoughts on how to proceed with this?

**Comment by mmcgr** [comment]
If the new environment has a c++ compiler, then you could change souffle-compile to point to it. Otherwise you either compile gcc/clang on the new machine, or copy a pre-compiled version over with Souffle.

If you can be sure that the compiler you copy over will work work on the new machine, that seems simplest.

**Comment by b-scholz** [comment]
Perhaps you can try to install the GCC/G++ compiler in the local directory and ship with souffle the locally installed GCC compiler. GCC/G++ does not need to be installed globally. Note that the local installation is a little bit tedious but you may need to install it only on the primary computer and the local installation can be replicated like souffle. The issue might be that you need to alter the souffle-compile.in script pointing to the local directory. But that doesn't sound too difficult.
