### ISSUE TITLE
Test environment

### ISSUE THREAD

**Issue by mmcgr** [souffle-lang/souffle#515]
The current testing framework is proving cumbersome. It needs to run faster. Ideally, we also test on more platforms.

Currently on travis, with the tests run in parallel, and no delays setting up images for each job, testing takes 60 - 120 minutes. Faster testing would be better, but that's an acceptable speed for our usage. However, OSX images are usually in demand so testing is more likely to take a day or more. If the tests run slowly, either due to the testing setup or the code being tested, this can be even longer.

Short term I propose that we limit use of OSX in particular, and only test with gcc on that platform. A faster alternative is to use the Syntactic/Semantic tests as basic functionality tests for all platforms and limit evaluation tests to a single platform. The downsides to less cross-platform testing is small(ish) for code that doesn't use advanced compiler/cpu features.

Longer term we need to automate local testing with jenkins, with automated feedback to developers. The full set of tests can then be run on a wider selection of platforms, with travis being used as a fast test of basic functionality.

**Comment by b-scholz** [comment]
I suggest to beef up the local test environment at USYD, and install on it docker such that various linux environments can be simulated (ubuntu, redhat, centos, archlinux, suse, etc.). The machine should perform tests in a responsive fashion <=30min.  For Mac OS X we would require an alternate setup.

I suggest to keep package building on travis and have there only light-weight testing. 

I suggest that both infrastructures require to pass all tests before we can accept the pull request.

In addition, it would be great to consider code coverage tools, i.e., newly checked-in code requires to have sufficient coverage by testing.

**Comment by mmcgr** [comment]
I think we need a new category of test - quickEvaluation. Currently, and as I suggest above, we use Syntactic & Semantic tests as a quick test to see if souffle works in a particular environment. Instead, we could use quickEvaluation with a limited set of evaluation tests that run fast and test as wide a range of souffle's functions as we can, within that speed limitation. Syntactic/Semantic tests can then be run faster with the only variations of parameters being those relevant to syntax/semantics/non-evaluation. The full Evaluation tests can be more comprehensive, slower, and only run as needed.

This will allow us to have faster testing of a wide range of functionality (useful for limited setups like Travis), with slower, more comprehensive tests, as needed (such as in the proposed local testing

**Comment by mmcgr** [comment]
To update this issue:
Travis has greatly improved OSX testing speed, and the occasional minor delays with linux builds are also improved.
A reduced evaluation suite for quicker testing exists and is used - `SOUFFLE_CATEGORY=FastEvaluation make check`
Testing of master on our own servers is done with a variety of platforms using docker for linux builds and a VM for FreeBSD.

More comprehensive testing of pull requests on our own servers is almost ready, but with the improvements Travis have made this is also less immediately important. At this point I think it makes more sense to slightly redesign the test infrastructure to use souffle's own docker repository and enable more test environments with docker on Travis.

**Comment by mmcgr** [comment]
The current testing framework is stable. We may in future add more tests, especially of different platforms, but the problems addressed by this post have either been dealt with by travis, or by our own changes.
