### ISSUE TITLE
Fix warnings compiling souffle

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#519]
There are several comparison unsigned/signed issues when compiling soufflé. 
This needs to be fixed. 

I would suggest to enable warnings and stop compilation for the soufflé system in the presence of warnings. Unfortunately, our generated C++ is harder to control and we cannot enforce this easily.

**Comment by mmcgr** [comment]
Currently the generated scanner.cc causes an unsigned comparison warning. I don't see any modifications we can make to scanner.ll that would avoid that. If we want to stop compilation for unsigned comparison warnings, then we may need to turn them off for that one file.
