### ISSUE TITLE
Give better error message from CLI

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#535]
I just ran 

```
$ souffle -co path.out path.dl
```

instead of the correct

```
$ souffle -copath.out path.dl
```

I got an executable named `path` with no error message, and was surprised it was not called `path.out`.  I would have preferred an error message from the first command rather than having it silently ignore the argument.

Thank you.

**Comment by mmcgr** [comment]
The two forms seem to have identical results on my system (Ubuntu, latest master build). They also both produce an executable named 'path' when asked to produce one named 'path.out'.  I don't see any need for the name change. I think that the output path should be the one that was asked for, or an error given.

If you are seeing different behaviour between the two versions then it would help if you could give the OS, compiler, and souffle version.

**Comment by seanmcl** [comment]
Sorry.  

* OSX 10.12.6
* Souffle 1.2.0
* Apple LLVM version 9.0.0 (clang-900.0.39.2)
