### ISSUE TITLE
Feature request: Travis build for RHEL/Centos

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#537]
https://stackoverflow.com/questions/32535195/how-to-run-tests-on-centos-7-with-travis-ci

We use a Centos stack, and it would be nice to be able to build Souffle as it evolves.  Currently I'm spending time trying to figure out how to get mcpp working.

**Comment by mmcgr** [comment]
We've been pretty hesitant to set up docker on travis for testing given how slowly our tests run already, and how flaky that gets on travis, but we do test further locally. We've been using Fedora 27, but I've set up a CentOS7 image as well in our local testing farm. To make mcpp work, without compiling from source, I added the nux desktop repository.

The basic dockerfile is:
```
FROM centos:7

RUN yum install -y autoconf automake bison clang doxygen flex gcc gcc-c++ git kernel-devel ncurses-devel sqlite-devel libtool make java-1.8.0-openjdk pkg-config python sqlite sudo zlib-devel

# add repo for mcpp
RUN yum -y install epel-release
RUN rpm -Uvh http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm

RUN yum install -y mcpp
```

**Comment by mmcgr** [comment]
gcc on centos7 is 4.8.3, which does not fully support c++11. You'll also need to install a c++11 compliant compiler.

Souffle will build with 4.8, but anything that uses regex will have problems. I believe that's only provenance.

**Comment by b-scholz** [comment]
This feature request is also related to issue #547.
