### ISSUE TITLE
SSL certificate for souffle-lang.org needs update

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#538]
Getting insecure warning.  Image attached.

**Comment by seanmcl** [comment]
![screen shot 2018-01-08 at 8 57 53 am](https://user-images.githubusercontent.com/110393/34681880-10cf0856-f452-11e7-812a-b0a89fd7323b.png)

**Comment by b-scholz** [comment]
I feel this is resolved. I close the issue.
