### ISSUE TITLE
Printing records for debugging

### ISSUE THREAD

**Issue by pratikfegade** [souffle-lang/souffle#540]
Hi,

Souffle currently does not support the dumping of records, instead printing a unique index for the record. It would be nice if it actually did print the records. I was wondering if that can be done easily. If yes where could I start from to do that?

Thanks,
Pratik Fegade.

**Comment by mmcgr** [comment]
See #142

It can't be done easily so has not been a priority yet. That may change with our current refactoring efforts.

The main obstacle to trivially supporting record output is just that a relation does not know about records, it only has the unique index without knowing it's a record. If that link has been provided then there are just the issues mentioned in #142.

**Comment by pratikfegade** [comment]
Thanks! I missed that issue.

Pratik Fegade.

**Comment by mmcgr** [comment]
Closing this in favour of #142. It's definitely a feature we would like to add, in some form.
