### ISSUE TITLE
Debian installer broken

### ISSUE THREAD

**Issue by jgsuess** [souffle-lang/souffle#549]
After installing in a mint ubuntu:16.04 docker container, souffle is not in the path and 
`find / -name "souffle"` only gives: `/usr/share/doc/souffle`
Do you need a test case or can you do a casual check?

**Comment by mmcgr** [comment]
Launchpad is successfully building empty debs. I've disabled the ppa until that's fixed.
The release page has a working deb file: https://github.com/souffle-lang/souffle/releases/download/1.2.0/souffle_1.2.0-1_amd64.deb , and of course building from source works.

**Comment by mmcgr** [comment]
We have a new repository you can use at
https://bintray.com/souffle-lang/deb-unstable
The debs are uploaded with every change on master.
Tagged releases are at
https://bintray.com/souffle-lang/deb

You may need to install the public keys for the repository before use:
`apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61`
