### ISSUE TITLE
Assertion error when using components

### ISSUE THREAD

**Issue by anantoni** [souffle-lang/souffle#554]
Hello,

In the latest versions of Souffle I keep getting an assertion error when trying to compile my a program with two components.

`souffle: AstProgram.cpp:95: void souffle::AstProgram::appendClause(std::unique_ptr<souffle::AstClause>): Assertion `r && "Trying to append to unknown relation!"' failed.`

My understanding is that this is related to the rules performing copies of relations between my two components (c1 and c2), but I haven't been able to narrow down the issue in a smaller example. However, going several commits back the same program compiles successfully and I think the results are correct. I have attached my code (the part related to the initialization of c2 starts at line 2850). Hopefully the assertion will give you an indication of the possible problem.

[context-insensitive.txt](https://github.com/souffle-lang/souffle/files/1667558/context-insensitive.txt)

Thanks in advance.

Best regards,
Tony

**Comment by b-scholz** [comment]
Tony - can you give us the commit for which your program still works. I have been debugging the issue the last two hours. I understand that the clauses of an instantiated relation (e.g. c1.Value_isMock) are not translated correctly, i.e., the prefix c1 for example is missing.

**Comment by b-scholz** [comment]
I can confirm that the version d92a74ccb1264709890fb36c2b401b655ebefc9f has not the bug.

**Comment by b-scholz** [comment]
I can confirm that the version f323e124c415b358c92d45feb92eae4559937699 has the bug.

**Comment by b-scholz** [comment]
I can confirm that the version 38fb8fe4b0b9d7cbd38e0a89c00c82fd2fe82ac6 has the bug.

**Comment by b-scholz** [comment]
I can confirm that the version c7da0f407ce6626f908c61ae7c6dccf1b85a9863 has the bug.

**Comment by b-scholz** [comment]
I can confirm that the version 7a2736e2dfde55614b76cf0a0dea634c272c193f has the bug.

**Comment by b-scholz** [comment]
I can confirm that the version f44336230868f9f575bcab4c6e379f865be91d80 has not the bug.

**Comment by b-scholz** [comment]
I can confirm that the version 3539ef7237534c489c9ae54f98f5a919353a91fc has the bug.

**Comment by b-scholz** [comment]
I can conform that the version 0cd3fc35618b9a928c8c8f196888176056248ac5 has not the bug.

**Comment by b-scholz** [comment]
Ok - I found the culprit - better to write a binary search script one day to do the job fully-automatic. It is the change from 024e0df0b91c5039c2e52ae973dd3667248e8870 to d92a74ccb1264709890fb36c2b401b655ebefc9f.

**Comment by b-scholz** [comment]
A quick fix is to disable the transformer ExtractDisconnectedLiteralsTransformer from the transformer pipeline in main.cc. I.e., remove/comment out the line ```transforms.push_back(std::unique_ptr<AstTransformer>(new ExtractDisconnectedLiteralsTransformer()));```

**Comment by b-scholz** [comment]
This is a small example that
```
.comp C {
 .decl A(x:number) output
  A(1).
  A(x):-A(x), A(y).
}
.init c = C
```
causes the crash.

**Comment by b-scholz** [comment]
I feel we need to remove .init and .comp entries in an AstProgram as soon as they are expanded.

**Comment by anantoni** [comment]
Thanks for the fix guys.

Best regards,
Tony
