### ISSUE TITLE
Re-design loading and storing of relations

### ISSUE THREAD

**Issue by souffle-lang** [souffle-lang/souffle#56]
Synopsis: extend mechanism to load and store relations

Relations have qualifiers such as `input` and `output` to load relations from tab-separated files and store relations to tab-separated files.  Example,

```
.decl A(x:number, y:number) input
.decl B(x:number) output
```

Provide an input/output statement that specifies a set of relations to be loaded from files and stored to files, respectively.

**Comment by b-scholz** [comment]
This has been completed with Martin's new I/O system.
