### ISSUE TITLE
Program Interface with SWIG

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#573]
It would be great to have a program interface via SWIG such that other languages can interface Soufflé.

More information about SWIG can be found here:
http://www.swig.org

**Comment by b-scholz** [comment]
Andres worked on this issue and gave us permission to upload his work here under UPL. Please find attached his report and code to make it work.  We would need some volunteer to integrate Andres work 

[Interfaces with examples.zip](https://github.com/souffle-lang/souffle/files/1804954/Interfaces.with.examples.zip)

**Comment by psubotic** [comment]
I can volunteer if it’s not urgent   
  

  
  

  
  
>

**Comment by lyndonhenry** [comment]
Gameplan:

- Each interface is generated to `//src/swig/[name-of-language]`.
- Each interface has a corresponding set of tests at `//tests/swig/[name-of-language]`.
- All tests for each interface will run on the Jenkins server.
- Instructions for building the interfaces with be _VERY VERY VERY WELL_ documented in either the wiki or the Souffle website.
- Instructions for using the interfaces will also be _VERY VERY VERY WELL_ documented in either the wiki or the Souffle website.
- A section on the use of SWIG in Souffle will be added to the `README.md`.
- SWIG will generate interfaces for Souffle for the following languages.
    - High priority:
        - Java
        - Javascript
        - Python
    - Medium priority:
        - C#
        - Go
        - MzScheme/Racket
        - OCaml
    - Low priority:
        - D
        - Guile
        - Lua
        - Octave
        - Perl
        - PHP
        - R
        - Ruby
        - Scilab
        - Tcl
