### ISSUE TITLE
Docker Code in souffle-utilities vs in a Separate souffle-docker Repository

### ISSUE THREAD

**Issue by lyndonhenry** [souffle-lang/souffle#589]
Currently, souffle-docker and souffle-utilities are separate repositories. As per PR #578, there is discussion on whether to merge souffle-docker into the souffle-utilities repository. Please see the comments there for the full stream of thoughts, and the pros and cons of each approach. The question is, what should be done?

**Comment by b-scholz** [comment]
I am not so sure about standard practice. What is LLVM doing?

**Comment by lyndonhenry** [comment]
LLVM's official GitHub mirror (over at https://github.com/llvm-mirror/llvm) stores them in `//utils/docker`. So they don't have a separate repo for utilities or for docker files, but instead keep everything together in one big repository. If we follow them, we get rid of both souffle-utilities and souffle-docker repos, and merge everything into souffle in a `//utils` directory (probably do the same for `souffle-vim` while we are at it for the sake of being consistent). 

Standard practice seems to be to just keep `Dockerfile`s in a top level `//docker` directory, however this is a claim based on my own experiences from the code bases that I have seen and is 100% completely and totally anecdotal -- I'm not sure if there is an actual standard practice for this.

**Comment by lyndonhenry** [comment]
The `souffle-docker` repository has been improved dramatically. There is now an official Souffle account on Dockerhub, found [here]( https://hub.docker.com/r/souffle/). Users can now pull images from there. The Github repository may henceforth only be used for developing these images.

**Comment by b-scholz** [comment]
I feel we should start following LLVM. LLVM is a classical example how proper software engineering is applied to compilers.

**Comment by lyndonhenry** [comment]
Sounds like a good plan. LLVM has more people, working over a longer period of time, with most certainly having more development expertise than us, solving the same (or similar enough) design and organization problems as us -- we get better solutions than likely we could come up with, but with practically zero time or effort on our part. Anything that gives us better code but for less work seems a pretty sensible move.

**Comment by lyndonhenry** [comment]
I forgot about this, I'll solve and close it in the next day or two. I just have to move the souffle-docker code into Soufflé, it's a trivial change. It does still matter though, as souffle-docker is a test dependency for Soufflé as things are.

**Comment by lyndonhenry** [comment]
Closing as per #764
