### ISSUE TITLE
Profiler Changes

### ISSUE THREAD

**Issue by lyndonhenry** [souffle-lang/souffle#590]
Previously, souffle output logging in a custom format, which may be seen [here](https://github.com/souffle-lang/souffle/wiki/Internals#log-file-format.) As of PR #578, the souffle profiler outputs logging in both JSON and the custom log format. The custom log format is non-standard, and so is being retired. Souffle should have one logging format as per the comments in #578.

- For the sake of support, there should be a souffle log file conversion tool to in the souffle-utilities repository to go from the new format to the old and vise-versa.
- The souffle-profiler itself will also need to be re-written, in order to use the new format, hence why it has not been deprecated yet.
- If there is a logging format that is better than JSON to the extent where it makes sense to re-write existing code to use it, then we should of course do that instead. Suggestions are welcome.

**Comment by lyndonhenry** [comment]
This is also related to #591.

**Comment by mmcgr** [comment]
I think this also relates to #490. If the output order is less dependent on race conditions, which this might provide, then tests of the output are simplified.

**Comment by lyndonhenry** [comment]
That is cool, I didn't consider that. I had some thoughts on #490, now that I'm reminded of it again, I will post those there.

**Comment by lyndonhenry** [comment]
JSON should be dropped as 

1) it requires reproducing the names of each field per line, which is too costly
2) it requires a curly brace to end a line, which presents formatting difficulties 
3) it is too complicated for this task, with nesting and types presenting unnecessary challenges to parsing for souffle-profile
4) it is too unstructured, and cannot be simply imported readily into existing tools (as, for example an SQL table)

CSV would address each of these points. It would also permit easy conversion back to the old format by replacing instances of one or more commas with a semicolon, and would be consistent with the format typical for other output files in Souffle. However CSV is not very compressed, and so something else may be the ideal.

**Comment by b-scholz** [comment]
There is some progress with the underlying architecture. We have started building a dynamic data-structure and have it fully integrated in Soufflé. 

Perhaps we create a pull-request later this week. We also have more profiling events, i.e., periodically we query cpu/memory utilisation and the profiler needs to be extended for this purpose and literal counts will come in near future. 

Hence, we will have a huge number of events and I feel the only way forward is a binary format as an output of a Souffle program. 

As suggested before (by Lyndon), we would need a tool to convert the format to JSON and other text formats. 

The profiler needs to be adapted for the new binary format.

**Comment by lyndonhenry** [comment]
As it is related, #615 gives the ability to convert Souffle logfiles to CSV format, to permit users to analyse logfile data using tools other than souffle-profile.

**Comment by lyndonhenry** [comment]
Additional, as it was brought up at #615, the organisation of the souffle-profile code is not so nice.

Having it as an entirely separate repository seems like overkill/spaghetti code and would create more overheads for both users and developers than joy. Merging it together with the rest of the souffle code in `src/` is not so good for separation of concerns and complicates dependencies. Instead I suggest a happy medium:

- `/src/profilerlib` becomes just `/src/profiler`
- `/src/souffle_prof.cpp` becomes `/src/profiler/main.cpp`, and produces `souffle-profile` binary in `/src`
- all code in `/src/profiler` lives in namespace `souffle::profiler`
- all files in `/src/profiler` can depend on any file in `/src`, but not vise versa 

This convention can then be followed for other such cases, and so more generally:

- directories in `src` are nested namespaces of souffle, all code within these directories lives in that namespace
- if such a directory `/src/foo` contains a `main.cpp`, then a binary will be produced at `/src/souffle-foo` 
- files in such directories containing a `main.cpp` can depend on files in `/src`, but not vise versa

**Comment by mmcgr** [comment]
This is now either encompassed by #661 or deprecated by #661 .
