### ISSUE TITLE
Json output for provenance 

### ISSUE THREAD

**Issue by lememta** [souffle-lang/souffle#608]
It would be nice if given a set of predicates to explain, souffle can output a JSON file with the output of the provenance.

**Comment by lememta** [comment]
Moreover, it would be nice to have an alternative to the interactive input for the provenance (i.e. `explain predicate("...")`). There should be an option to give in input a file of predicates 'to be explained' and get a set of JSON file showing the provenance. Perhaps, even the input should be some sort of Json file.

**Comment by b-scholz** [comment]
David is returning from his internship in the next two/three weeks. We will look into this issue.

The current activity on this front is to make the provenance implementation faster. At the moment, the provenance system in Souffle would not permit parallel execution (i.e. -j <nr>). To overcome this issue, we are specialising the underlying data-structure to make the execution fast.  The current results are very promising. We will create a pull-request soon for this improved provenance soon.

**Comment by b-scholz** [comment]
Note that the commands for explain can be stored in a text file. 
When calling the executable you can pipe the commands in. 

```
./souffle -o myprog -t1 myprog.dl
./myprog <command
```

where the command could look like
```
format json
output provenance.txt
explain predicate1(...)
explain predicate1(...)
explain predicate1(...)
explain predicate1(...)
...
output 
```

**Comment by b-scholz** [comment]
In this case the explanations are stored in file provenance.txt in JSON format.

**Comment by lememta** [comment]
This is great. It works and exactly what I needed. Thank you for the quickly providing this feature.

**Comment by HalleyYoung** [comment]
@b-scholz I'm trying this right now with foo.dl exactly as in the provenance example (attached with a .txt rename to satisfy github) and the commands as simple as I could make them (attached).  It's not producing any output.  Any idea why?
[command.txt](https://github.com/souffle-lang/souffle/files/5839170/command.txt)
[foo.txt](https://github.com/souffle-lang/souffle/files/5839178/foo.txt)

Command I ran:

```
souffle -o foo -t1 foo.dl
./foo <command.txt
```

Thank you so much for your amazing work!

**Comment by b-scholz** [comment]
Hi Halley - I just see your message now. 
With the latest version it still works. I feel the problem is that you have used the wrong command options to execute it. 
Please try the following:
```
souffle -t explain foo.dl <command.txt
```
and it should work.

**Comment by b-scholz** [comment]
The issue is that you generate an executable with `-o foo` rather than executing the program.

**Comment by b-scholz** [comment]
Let me know whether it works now.

**Comment by HalleyYoung** [comment]
@b-scholz Thank you so much, sorry for being confused, now it works perfectly!
