### ISSUE TITLE
Hashcode 2018 in souffle ?

### ISSUE THREAD

**Issue by mingodad** [souffle-lang/souffle#621]
Hello !
I've been looking at the Hashcode 2018 competition and after some thought could came with a solution (not the best one) using basically sqlite3 (https://github.com/mingodad/sqlite3-hashcode-2018) and also found another solution with better score in java (https://github.com/GameXtra/Google-Hash-Code-2018) but they do so by brute force or simple assignment.

Then I started looking for other possible solutions and then prolog came in and also picat, I've been reading and looking for examples the last 3 weeks but could not figure out how to (if possible) describe the problem in souffle/prolog/solvers terms to find a (good/best) solution.

Someone here have done it in souffle/prolog/solvers and can share/help ?

Cheers !

**Comment by b-scholz** [comment]
That would be wonderful to rewrite it in Souffle. I am not acquainted with the Hashcode 2018 competition. The question is how to model the challenge in a relational model and how to phrase the queries for it. 

I would suggest that you attempt the first prototype in Souffle. We can help optimising / improving the prototype.

**Comment by mmcgr** [comment]
Closing, since the competition is finished.
