### ISSUE TITLE
Max results

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#637]
One feature that would be great would be to be able to stop souffle once a certain number of results were obtained for each output relation.  For example, in our use case we typically have a single output relation, and only care about, say, the first 10 results, when hundreds of thousands are ultimately generated.  I'd love a way to tell Souffle to stop so I could respond to our user requests faster.

**Comment by gkastrinis** [comment]
For my perspective, this sounds like an interesting feature to have :D 
Another, similar feature to ask is a "max time" instead of max results.

**Comment by b-scholz** [comment]
This would be a very nice feature. However, there is a problem with relation-dependencies. The only way to make it work is that relations that are not used in other relations, could have this feature. I could  envisage a qualifier in the language declaration such as, 
```
.decl A(x:number) sizelimit 10
```

For dependent relations, this is a very difficult feature to implement. Say, if we have two relations A and B, and B depends on the totality of A - especially in case of negation. The only way to implement this effectively is to switch the underlying evaluation from semi-naive evaluation to a stream-oriented evaluation. Lyndon is going to work on this as soon as he will commence his studies at USYD. Note that a stream-oriented approach for evaluation reduces the latency of results for relations; however, the throughput of evaluation might not be so perfect.

How do you feel about this?

**Comment by seanmcl** [comment]
Yes, I certainly see the problem, especially with respect to negation. All the relations that we want this for are not used in other relations, so that restriction is fine by me!  The stream-based evaluator sounds neat, but if we could get some hack together to just stop at a certain number in the meantime that would be ideal.

**Comment by b-scholz** [comment]
I will discuss with Martin.

**Comment by seanmcl** [comment]
Thinking about this more, what if I have 

```
.decl a(x: number)
.decl b(x: number) sizeLimit 10 
.output b

a(0).
a(X+1) :- X < 10000000, a(X).
b(X) :- a(X).
```

This is the kind of situation we'd use the feature for.  Is there an easy, hacky way to get what I'm hoping for here without full streaming support?

**Comment by azreika** [comment]
For an example like that, you could probably create an intermediate relation that uses the `$` functor to index each tuple, then only grab the first 10 indexed.

```
.decl a(x: number)
a(1).
a(X*2) :- X < 1000, a(X).

// .decl b(x:number)
// .capacity b(10)

.decl b_indexed(x:number, y: number)
b_indexed(x,$) :- a(x).

.decl b(x:number)
b(x) :- b_indexed(x,y), y < min y : { b(_,y) } + 10.
.output b
```
