### ISSUE TITLE
Boolean type and operators

### ISSUE THREAD

**Issue by HerbertJordan** [souffle-lang/souffle#64]
It would be great to add boolean values in addition to numbers, symbols and strings to the set of basic types. 

Currently, when modeling booleans, the corresponding operators have to be modeled via extra relations. This extra overhead and memory access is slow.

What would be needed:
 - new bool primitive type
 - true and false constants
 - and, or, xor, negation, equality, and inequality operations

*Options A:* full integration

*Options B:* map it to numbers and encode it as follows:
 - true = 1
 - false = 0
 - neg = 1-x
 - and = x * y
 - or = neg(and(neg(x),neg(y)))
 - equality and inequality remains the same

Option B does not actually require any change since it can be realized by macros in a DL file. For our current work we will need this feature -- the question is whether we should go for the macros or think about a full integration.

**Comment by psubotic** [comment]
Full integration would of course be nicer but if we are having time issues perhaps go with option B with a note to eventually to option A. What is your view Herbert on A vs B?

**Comment by HerbertJordan** [comment]
Actually I wanted A, and just while writing i realized that B is possible. 

Maybe we can even make it a precedence case by providing B as a standard library dl file which we ship with souffle and which may be included into an analysis. Having a sort of standard library would be a cool, cheap new feature. And altering the encoding of those whenever we get a better idea is easy and quick.

**Comment by b-scholz** [comment]
We could also introduce logical operations - not just bitwise. To be orthogonal we could introduce 
operations `land`, `lor`, `lnot`, `lxor`, `limply`.  Perhaps we introduce also a bxor for a bitwise xor. Can you think of more operations?

I would prefer if we forgo a concrete data type for boolean types. It would be stored as a number anyway. What do you reckon?

**Comment by psubotic** [comment]
that would be nice. It would also be nice to be able to specify hex
literals.

**Comment by HerbertJordan** [comment]
For our setup we utilized a header file defining the following:
```
#pragma once

// define a basic boolean type
.number_type bool

// define true/false constants
#define true 1
#define false 0

// define boolean operators
#define not( X ) (1-X)
#define and(X,Y) (X*Y)
#define or(X,Y) not(and(not(X),not(Y)))
```
This way, no compiler modifications are necessary. Maybe we can think about supporting other types and operators in a similar way. One might, for instance, model IP addresses correspondingly now that we have the binary operators.

**Comment by b-scholz** [comment]
I believe that the arithmetic representation of logical values, i.e., 0 / 1 values is dangerous because we cannot guarantee that is only the value zero or one. I have added the logical operations:
 * a land b 
 * a lor b 
where the logical value 0 represents false and any other value represents true following the C-semantics.

**Comment by b-scholz** [comment]
I close this issue. We still could add constants such as TRUE and FALSE to the Souffle language; However, I feel we can do the same with an include file as Herbert indicated. 

We don't have logical xor or logical implications; however, this can be easily constructed with the existing operators. 

I am closing this issue. Please re-open it, if you have further feature requests related to this issue.
