### ISSUE TITLE
ReplaceSingletonVariables transformer causes segmentation fault

### ISSUE THREAD

**Issue by anantoni** [souffle-lang/souffle#656]
Hello,

I've been encountering a segmentation fault in the latest commits and I've managed to track down the commit that introduced the issue. Its hash is 1a2b08b8fb2f978969556c5868b2b5ed8c4dce16 and it adds the replace singleton variables transformer to pipeline so I expect the issue to be related to the replacement of singleton variables.

Best regards,
Tony

This is the datalog file that causes the segmentation fault and the command is souffle -c: [context-insensitive.txt](https://github.com/souffle-lang/souffle/files/1986492/context-insensitive.txt)

**Comment by mmcgr** [comment]
Also happens with just `souffle context-sensitive.txt`. In debug mode it segfaults in addCondition at RamOperation.cpp:277
```
assert(c->getLevel() <= level);
```
as c, the condition being added, is a nullptr.

**Comment by azreika** [comment]
Segfault seems to happen when trying to resolve an equality constraint in the RAM with an undefined left-hand side. I assume this has something to do with either alias resolution or a missing check for variable use in the transformer. Moving the transformer to occur after alias resolution (the `ResolveAliasesTransformer` transformation)  seems to solve the problem for this case, but I'm going to try for a minimal example to confirm before pulling changes up.

**Comment by azreika** [comment]
Minimal example:
```
.decl a(x:number)
a(x) :- x = 0, y = 0.
.output a()
```

This is (more or less) converted to:

```
disconnected() :- _ = 0.
a(0) :- disconnected().
```

Segfaults when translating `_ = 0` from AST->RAM, since the LHS is undefined.

This issue appears implicitly in the code provided, due to code of the form:
```
a(x), b(x,y) :- x = 0, y = 0.
```
which is equivalent to:
```
a(x) :- x = 0, y = 0.
b(x,y) :- x = 0, y = 0.
```
but won't throw any warnings about unused variables in `a`'s body.

Will pull up the fix for the segfault soon.
