### ISSUE TITLE
Type Cast using the AS keyword

### ISSUE THREAD

**Issue by vogelfr** [souffle-lang/souffle#657]
I am currently trying to cast strings representing numbers to number to be able to compare the natural (instead of lexicographical) ordering. While looking through the [parser file](https://github.com/souffle-lang/souffle/blob/master/src/parser.yy) I found the AS keyword described as type cast.

However as gets flagged as unexpected identifier where ever it is used. How can we cast strings comprised of digits to numbers?
```
.decl debug(n:number)
debug(n) :- string = "1", n = string as number.
```

**Comment by b-scholz** [comment]
This is not working. We would need a new functor to convert strings to integers. 
Are you interested in implementing the new functor? We could support you.

**Comment by b-scholz** [comment]
I have added two new functors to convert between strings and numbers.

**Comment by vogelfr** [comment]
Thank you for implementing it!
I have no idea how to implement functors so I wouldn't have been able to do it myself.

**Comment by b-scholz** [comment]
No worries. May I ask what you are using Soufflé for? We are always after new benchmarks.

**Comment by vogelfr** [comment]
We used it in Program Analysis course at ETH in a project for doing Taint Analysis. You can find the [description here](https://www.sri.inf.ethz.ch/passproject.php)
