### ISSUE TITLE
Aggregates

### ISSUE THREAD

**Issue by mmcgr** [souffle-lang/souffle#662]
Currently aggregates may have problems when contained within another rule, particularly if aggregates are nested inside aggregates (#651, #556, #564, #550).

The workaround for any issues is to avoid inlining aggregates. e.g.
```
.decl t(x:number, y:number)

t(1,2).
t(2,3).

.decl good, bad, m(x:number)
.output good,bad(IO=stdout)

m(n) :- n = max(y) : {t(_,y)}.


good(x) :- t(x,y), m(y).
bad(x)  :- n = max(y) : {t(_,y)}, t(x,n).
```

Until inlined aggregates are handled properly the workaround is required.

**Comment by b-scholz** [comment]
Can somebody check whether all the failing ones are fixed?

**Comment by mmcgr** [comment]
All issues linked here now work, but we still need to add tests to make sure they keep working. Nested aggregates are still problematic.

**Comment by b-scholz** [comment]
I would suggest disabling nested aggregates. Make sure that non-nested aggregates work correctly.
