### ISSUE TITLE
Facts-File with \r\n Line-End Lead to Strange Behaviour

### ISSUE THREAD

**Issue by ntruessel** [souffle-lang/souffle#663]
When a `.facts` file contains CRLF line endings, Soufflé reads the files without warinings or errors, but fails to produce correct output. Some minimal example:

`demo.dl`
```
.decl edge(s:symbol,d:symbol)
.input edge

.decl via(s:symbol,d:symbol,v:symbol)
.output via
via(s,d,v) :- edge(s,v), edge(v,d).
```

`edge.facts` (\r\n line-end)
```
n1	n2
n2	n3
```

**Comment by mmcgr** [comment]
I haven't been able to reproduce this.

Are you using a version of Souffle from before 2017-10-26 (such as version 1.2 from the release page)? That's when a change was made to handle Windows line endings. If you are, then try a more recent version, either by using an unstable package from https://bintray.com/souffle-lang/ or by compiling from source.

If you have a recent version, could you tell me what OS you using and which compiler, if you built from source.

**Comment by ntruessel** [comment]
I'm using version 1.2 (as it is the latest release). Using a more recent version, everything works fine.
