### ISSUE TITLE
configure: error: C++ preprocessor "/lib/cpp" fails sanity check

### ISSUE THREAD

**Issue by mheiber** [souffle-lang/souffle#667]
On OS X 10.12.2, ./configure is failing with 

```
configure: error: C++ preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details
```

I'm attaching the config.log. Thanks for pointing me in the right direction to get Soufflé to build, I'm excited to try it out.

[config.log](https://github.com/souffle-lang/souffle/files/2043196/config.log)

**Comment by mheiber** [comment]
I tried skipping

```
export CXX=/usr/local/bin/g++-5
export CXXFLAGS=-fopenmp
export SOUFFLECPP=/usr/local/bin/cpp-5
```

and now Make completes with exit code 0, but there's no `bin` directory or `souffle` executable.

**Comment by mmcgr** [comment]
It looks like part of the documentation has somehow regressed to an out of date version.

If you use brew to install g++ then you will get a particular version - currently g++-8. You may still be using the default g++/clang, which works (now?), but does not support openmp.

Unless you run make install the executables will be in the src directory by default.

**Comment by mheiber** [comment]
thanks!
