### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by mheiber** [souffle-lang/souffle#670]
Is there Windows support?

**Comment by b-scholz** [comment]
Actually, yes - it should work out of the box. Windows 10 has a sub-system for Linux. I tried it some time ago and it works. Have a look:

https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by mheiber** [comment]
Thanks!
I'm stuck on Windows 7 here, but one day will have nice things.

**Comment by gfour** [comment]
An update on Windows support: the .cpp file that Souffle can generate on a POSIX system, can be compiled on non-WSL Windows via Cygwin and `g++ -Wa,-mbig-obj ...`. Tested with Souffle 1.5.1.

**Comment by b-scholz** [comment]
The latest PR adds a testing system for Windows; the code is now compatible with MSVC.
