### ISSUE TITLE
'.input' not working consistently with relations that have additional rules

### ISSUE THREAD

**Issue by gkastrinis** [souffle-lang/souffle#675]
We have the following simple example

```
$ cat foo.dl
.decl Foo(x:number)
.decl Bar(x:number)
.decl Foobar(x:number)
.input Foo
.input Bar
.output Foobar
Foobar(x) :- Bar(x).
Bar(x) :- Foo(x).

$ cat Foo.facts
1
2
3

$ cat Bar.facts
4
5
6

$ souffle foo.dl

$ cat Foobar.csv
1
2
3
```

If instead we add '.output Bar' then we get

```
$ cat Foobar.csv
4
5
6
1
2
3
```

**Comment by mmcgr** [comment]
A slightly simpler from is to remove `.input Foo` from your example - then Foobar is empty. It seems that the pruning of the Ast ignores input directives for intermediate relations.

**Comment by mmcgr** [comment]
If you're building from source, it looks like a quick workaround is to disable the RemoveRelationCopiesTransformer by commenting out line 359 in main.cpp
