### ISSUE TITLE
Souffle doesn't accept "-jX" argument in Mac

### ISSUE THREAD

**Issue by gkastrinis** [souffle-lang/souffle#680]
Souffle doesn't recognize the -jX (e.g. -j4) argument for parallel execution.
It's fine if parallel execution is not supported in Mac, but it would be nice if it was possible to ignore the argument instead of terminating with an error.

In Doop we are auto-generating the souffle command invocation and for this we have to detect if we are running on Mac and if so don't use the "-j" argument

**Comment by mmcgr** [comment]
I haven't been able to duplicate this. Could you give me a bit more information:
- The full command passed to souffle that leads to the error
- How souffle was built or installed on your Mac
- What compiler you used
- What version of xcode is installed
- Any more specific details about the error message

**Comment by gkastrinis** [comment]
I will try to provide extra information but I currently don't have any Mac to replicate in detail. It is just that we have seen this issue from a couple of users of Doop.

My understanding is that souffle was build from the latest version of the repo at the time (a couple of weeks ago maybe, not that far in the past). 

What happens is that Doop will generate a run command for the executable produced by souffle like the following

`binaryExecutableName -j4 -Fpath/to/facts -Dpath/to/output`

This produces the following error/usage message
```
Usage: binaryExecutableName [OPTION]

Options:
-D <DIR>, --output=<DIR>     -- Specify directory for output relations
(default: .)
(suppress output with "")
-F <DIR>, --facts=<DIR>      -- Specify directory for fact files
(default: .)
-i <N>, --index=<N>          -- Specify index of stratum to be executed
(or each in order if omitted)
-h                           -- prints this help page.
--------------------------------------------------------------------
Copyright (c) 2016 Oracle and/or its affiliates.
All rights reserved.
```

If instead they try the following, it works ok

`binaryExecutableName -Fpath/to/facts -Dpath/to/output`

**Comment by mmcgr** [comment]
Thanks, I can reproduce it now.

It's intended behaviour, but I don't think it's a good idea. If I changed it to print out a warning message when -j4 is used but not supported, then continue execution, would that work for your usage?

**Comment by yiwasaki** [comment]
My friend happened this prob., and environment is those.

- OS: MacOS X 10.13.5
- xcode version : 9.4.1
- cpp version    : Homebrew cpp 8.1.0
- how to install souffle:
    used pre-build package ver. 1.3.1(souffle-1.3.1.pkg) downloaded from souffle github.
    and, open pkg file.
    [https://github.com/souffle-lang/souffle/releases/download/1.3.1/souffle-1.3.1.pkg](souffle-1.3.1.pkg)
- Using Mac H/W is Mac book 12-inch early 2015

**Comment by gkastrinis** [comment]
@mmcgr Yeah, I think a warning message and then continuation will help. Thanks!
