### ISSUE TITLE
Should mcpp be a dependency in the .deb package?

### ISSUE THREAD

**Issue by hiqua** [souffle-lang/souffle#708]
I have installed Soufflé using the latest .deb provided. I tried to run:

```
souffle tests/syntactic/binary/binary.dl
```
but this returns
```
Error: failed to locate mcpp pre-processor
```

while it runs correctly with the `mcpp` package installed.

Given #518, I would think that `mcpp` should be a dependency of `souffle`.

**Comment by mmcgr** [comment]
Yes, it should be. Thanks for pointing this out.
