### ISSUE TITLE
ssl certificate seems broken

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#715]
![screen shot 2018-09-07 at 12 00 31 pm](https://user-images.githubusercontent.com/110393/45238142-b157e980-b295-11e8-9f21-3da14dce7e4e.png)

**Comment by souffle-lang** [comment]
I double-checked. The "enable HTTPS" button is not pressed. However, before we can press the button we need to resolve some google issues from where we received the google DNS domain.

**Comment by b-scholz** [comment]
We solved the issue. The problem was that the apex domain was muddled with the www subdomain.
