### ISSUE TITLE
Website unavailable

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#729]
![screen shot 2018-09-19 at 6 51 23 am](https://user-images.githubusercontent.com/110393/45757547-7bd9c700-bbd8-11e8-8ea8-828aac515af6.png)

**Comment by psubotic** [comment]
Man google are giving us troubles with hosting, I’ll fix it as soon as I’m at a computer. Sorry.   
  

  
  

  
  
>

**Comment by lyndonhenry** [comment]
This is what I see on my end:

![2018-09-20-000045_1920x1080_scrot](https://user-images.githubusercontent.com/20922332/45758168-54cad600-bc68-11e8-8764-a389cc2e3398.png)

Obviously it's different, but with #715 closed, it should not occur.

Can also confirm that other Github pages sites are working, so it might not be a good old "not our problem".

**Comment by psubotic** [comment]
Ok guys I’ll look at it ASAP— in a tram atm.   
  

  
  

  
  
>

**Comment by lyndonhenry** [comment]
Cool. For the sake of completeness/reproducibility, here's chrome/chromium with the same complaint.

![2018-09-20-000929_1920x1080_scrot](https://user-images.githubusercontent.com/20922332/45758784-c3f4fa00-bc69-11e8-83a9-736191faaa6b.png)

**Comment by b-scholz** [comment]
It seems to be alright now - can somebody try again?

**Comment by lyndonhenry** [comment]
Yep, works for me. Screenshot showing on Firefox and Chrome:
![2018-09-21-091452_1920x1080_scrot](https://user-images.githubusercontent.com/20922332/45851577-fa706900-bd7e-11e8-8a85-1b600fed8452.png)

**Comment by lyndonhenry** [comment]
Yep, works for me. Screenshot showing on Firfefox and Chrome:
![2018-09-21-091452_1920x1080_scrot](https://user-images.githubusercontent.com/20922332/45851577-fa706900-bd7e-11e8-8a85-1b600fed8452.png)

**Comment by b-scholz** [comment]
Great - let's close the issue.
