### ISSUE TITLE
Negations with relatively grounded variables

### ISSUE THREAD

**Issue by mmcgr** [souffle-lang/souffle#730]
At the moment we allow this
```
E(x, y) :- B(x, z), C(z, y).
A(x, y) :- D(x, y), !E(x, y).
```
but not
```
A(x, y) :- D(x, y), !(B(x, z), C(z, y)).
Error: Ungrounded variable z
```

It could be useful to handle the second form.

We can do this easily in the AST, by transforming it to the first case, but that may lead to surprising amounts of memory being used by the new relation, and would stop inlining of some relations from working, since it effectively outlines the newly inlined relation. Alternatively, the RAM handles it, but a more work is needed to implement it.

Apart from the arguable direct benefits of allowing these rules, it would mean that inlining could be used in more cases.

**Comment by b-scholz** [comment]
Well the second form is strictly not in Horn-Clause from. 

```
A(x, y) :- D(x, y), !(B(x, z), C(z, y)).
```

can be rewritten to 

```
Q(x,y):- B(x, z), C(z, y).
A(x, y) :- D(x, y), !Q(x,y).
```

**Comment by gkastrinis** [comment]
If this is indeed the rewrite that takes places, it is also erroneous right?
e.g.
B(1, 2)
C(5, 3)
D(1, 3)

D(1, 3), !( B(1, z), C(z, 3) ) gives D(1, 3)

whereas
D(1, 3), !B(1, _) gives nothing
D(1, 3), !C(_, 3) gives nothing

**Comment by azreika** [comment]
As pointed out above, if handled on the AST level, the written rule becomes a disjunction where the connection between the two appearances of the named variable is broken. This should not be allowed.

The alternative is to compute such appearances on the fly, which means introducing a new construct on both the AST and RAM level which handles things like `!(B(x,z), C(z,y))`. On the RAM level, this would behave more like a complex existence check that grounds new variables, which falls outside the natural scope of Souffle - and would likely require the join `B(x,z), C(z,y)` anyway.
