### ISSUE TITLE
Range queries

### ISSUE THREAD

**Issue by mmcgr** [souffle-lang/souffle#735]
It would be nice to turn constraints that can be addressed by an index into an index query. e.g.
```
A(x) :- B(x), x > 1000.
```
This is currently implemented as a full scan of B, and every value is compared to 1000. Our datastructures already implement range queries so this could be turned into a simple copy of all matching values.

While our datastructures support this, the RAM does not. We would need something like a RamScanConstraint to complement the existing RamScan.

**Comment by SamArch27** [comment]
@mmcgr Can we close this?

**Comment by mmcgr** [comment]
If this has been done, then sure. If so, which PR?

**Comment by SamArch27** [comment]
#1563
