### ISSUE TITLE
Getting "Segmentation violation signal in rule" when running an analysis.

### ISSUE THREAD

**Issue by sifislag** [souffle-lang/souffle#756]
Hello,
Running [this](https://pastebin.com/raw/0euEXS20) script with -j4 using souffle version 1.4.0-249-g82a34b28 I get this error message after the compilation is completed:

```
Segmentation violation signal in rule:
mainAnalysis.PoolOperation(?ctx,?insn,cat("<tensor ",cat(?inFunction,cat("/",cat(?funName,cat(?inputsTensorArgVal,cat("+",cat(?kernelSizeArgVal,cat("+",cat(?stridesArgVal,cat("+",cat(?paddingArgVal,cat("+",cat(?dataFormatArgVal,">")))))))))))))) :-
mainAnalysis.FunctionInvResolvesTo(?ctx,?insn,_,_,?function),
mainAnalysis.Function_Module(?function,"<tensorflow.layers>"),
mainAnalysis.PoolOperationFunctionInfo(?function,?funName,_),
mainAnalysis.ResolvedActualParamValue(?ctx,?insn,?function,"inputs",_,?inputsTensorArgVal),
mainAnalysis.ResolvedActualParamValue(?ctx,?insn,?function,"pool_size",_,?kernelSizeArgVal),
mainAnalysis.ResolvedActualParamValue(?ctx,?insn,?function,"strides",_,?stridesArgVal),
mainAnalysis.ResolvedActualParamValue(?ctx,?insn,?function,"padding",_,?paddingArgVal),
mainAnalysis.ResolvedActualParamValue(?ctx,?insn,?function,"data_format",_,?dataFormatArgVal),
Instruction_Function(?insn,?inFunction).
```

It does not always happen but it happens on most executions.
Is this a known bug or an indication of something being wrong in my code?

Thanks,
Sifis.

**Comment by b-scholz** [comment]
It could be that the symbol-table overflows. 

Can you send us the complete code?  However, we don't know without running it on our own.
You can send the code either to Martin or me (Bernhard.Scholz@sydney.edu.au).

**Comment by b-scholz** [comment]
Sorry - I see the code is attached. Please can you also give us the input data. Otherwise it is hard to reproduce the problem.

**Comment by mmcgr** [comment]
With those facts, 814 symbols are generated. Souffle segfaults when trying to look up the symbol for the index 2037411683 (or other large number). This seems to be while trying to output mainAnalysis.ConvOrPoolOperation_GetNumbersForDim. Somehow that is getting an invalid symbol index.

**Comment by b-scholz** [comment]
It seems that you run out of symbols/strings. The system permits 2^32 symbols only.

Is there a way to reduce the number of cat functors?

**Comment by mmcgr** [comment]
814 is actually substantially less than 2^32, so I don't think that's the problem here.

**Comment by b-scholz** [comment]
I am concerned about the index number 2037411683.
This may be an indication that the pool is flooded. 
The index is close to the number of possible symbols.

**Comment by sifislag** [comment]
I'm using a very small input program to ensure that only a few new strings are created. Inspecting the output data in one successful run of the above script (with the same input), I can see that only 5 new strings are created using these macros that concatenate a lot of strings together.
Also this above rule that causes the segmentation fault does not produce any output, as it should with this input.

**Comment by mmcgr** [comment]
We've found the issue causing the segfault, and should have a fix soon.

**Comment by sifislag** [comment]
Perfect, thanks for the update!
