### ISSUE TITLE
Concatenated concatenation operators should be concatenated

### ISSUE THREAD

**Issue by mmcgr** [souffle-lang/souffle#761]
```
cat(cat(x, y), z)
```
Is executed recursively, generating many symbol mappings that are immediately discarded. It would be better to merge nested cats into one operation.

**Comment by b-scholz** [comment]
Let's have a single functor class in AST and RAM first before we apply this optimization in the translation. It would be a simple RAM transformer.

**Comment by azreika** [comment]
More generally, as pointed out in issue #331, we would like some functors to take in a non-fixed number of arguments e.g. being able to write `max(1,2,3)` instead of `max(1,max(2,3))`, or `cat(x,y,z)` instead of `cat(cat(x,y),z)`.
