### ISSUE TITLE
Updating Souffle (built from source)

### ISSUE THREAD

**Issue by anantoni** [souffle-lang/souffle#763]
Hello, 

I have a question regarding updating Souffle when built from source, for instance after I pull the latest changes. I use these commands:
`cd souffle
 sh ./bootstrap
 ./configure
 make clean
 make`
However, it seems that for some reason I don't get the updated version of Souffle to install. The PACKAGE_STRING variable remains at the previously installed version. I have also tried 
`make distclean` and `make am--refresh` but it still seems that something related to the previous version remains cached and the binaries are not built and updated correctly. The only way I can resolve this, is by performing a clean clone of the repository. Can you please provide me with the correct commands to delete all the cached configuration and update Souffle correctly?

Thanks,
Tony

**Comment by mmcgr** [comment]
The autom4te cache is storing the output of configure commands. It does seem like something `make distclean` could be clearing up more thoroughly, and removing that too.

For a more immediate fix, `git clean -fxd` will remove everything not from the repo.
Alternatively, `make distclean && rm -rf autom4te.cache/` will also work and not remove any other files you've created.

**Comment by anantoni** [comment]
That's exactly what I needed, thanks!
