### ISSUE TITLE
Managing licenses

### ISSUE THREAD

**Issue by icesparrow** [souffle-lang/souffle#77]
I have noticed that the Oracle license uses UTF-8 quotes around “Larger Work”, which caused an issue with some Java files in OSX (can be fixed with `-encoding` option to `javac`). I am wondering is these quotes are intentional? Also, I think that for managing licences it would be good to use something like a `headache` (available via apt in Debian/Ubuntu). Any thoughts?

**Comment by b-scholz** [comment]
Nathan added the license information to the header. I believe the quotes are irrelevant for the license and we can change this. Nathan  - any opinion? 

What is the headache file in Debian/Ubuntu?

**Comment by b-scholz** [comment]
We have now the issue that we added wave that has a different license. 
The wave license needs to be reflected in the licensing of Souffle.
 
If someone knows how to do that, that would be great.

**Comment by icesparrow** [comment]
In Frama-C, where we need to deal with different licences and third-party software we simply have a directory `licences`, rather than a single file. Note that each separate source file that is under license already includes the same license.

**Comment by icesparrow** [comment]
In Debian/Ubuntu `headache` is the name of the package and the executable, so

```
sudo apt-get install headache
headache ...
```

should do the trick

**Comment by b-scholz** [comment]
Sure - let's go for the license directory. Note that sooner or later Herbert will add GTEST and this has another BSD style license. For the profiler, other dependencies might arise in near future.

**Comment by icesparrow** [comment]
Ok, I will add the directory then

**Comment by icesparrow** [comment]
Another issue that I noticed is as follows: some licences are pretty long, so it has become a good practice to equip individual source files with small notices called headers rather than licences themselves.  The purpose of a header is not to give a license but rather indicate that this file is licensed and point to a location of the license file. For instance, if Soufflé were under  GPL version 2, an example header could look as below:

```
This file is part of Soufflé.

Copyright (c) 2016 Oracle and/or its affiliates. All Rights reserved

you can redistribute it and/or modify it under the terms of the GNU Lesser General 
Public License as published by the Free Software Foundation, version 2.1.

It is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.

See the GNU Lesser General Public License version 2.1 for more details (enclosed in 
the file  licenses/LGPLv2.1).
```

The benefit of using headers is that they are smaller, rarely change and easier to deal with than licences themselves. 

The other question is whether we can reformat the license we have, as I mentioned before it has UTF characters and a bit too wide to my taste, mostly such information is formatted at 80 characters, otherwise it is a bit difficult to read. So I would like it to be 80 characters long, with UTF characters and trailing white spaces removed.

Where do we stand on all this?

**Comment by b-scholz** [comment]
I am easy. I believe I read that UPL does require only a single License file only. We don't need the license replicated all over the place. 
https://opensource.org/licenses/UPL
https://oss.oracle.com/licenses/upl/

```Reduced overhead in source files.  The UPL expressly permits use of the license without including a full copy of the text, which is useful for JavaScript or other cases where minimizing space consumed by licenses is desired – see below for our recommendation of how to apply the license or include proper attribution without the full text.
```

A header of this notion 
```
/*
** MyWidget version 1.0.
**
** Copyright © 2015 WidgetCo, Inc.  All rights reserved.
** Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/
```

Is sufficient. I would prefer it. Copying headers is a mess...

**Comment by scyptnex** [comment]
Ill wait for Konstantyn's go-ahead before merging PR #99 , since he took on this issue, and my PR only shrinks the license headers, it doesnt universally manage all the licenses in a `license/` directory

**Comment by nkeynes-oracle** [comment]
> On 17 Apr 2016, at 8:15 pm, Bernhard Scholz <notifications@github.com> wrote:
> 
> Nathan added the license information to the header. I believe the quotes are irrelevant for the license and we can change this. Nathan - any opinion?
> 

The source I copied the license text from has the unicode quotes by the looks of it. I can’t see how changing the quote character would have any legal significance though, so that shouldn’t be an issue.

Regards,
Nathan

**Comment by scyptnex** [comment]
Consolidating all license issues in the new issue #100
