### ISSUE TITLE
Different behavior running souffle from command line and as an external process of our project.

### ISSUE THREAD

**Issue by sifislag** [souffle-lang/souffle#781]
Hi,
This problem initially occurred in Doop. Doop spawns an external process using java's ProcessBuilder to execute a souffle compilation command (e.g., souffle -c -o exename analysis.dl). 
After a change in my analysis.dl while attempting to compile a .dl file to exe (or just to cpp using -g) the process becomes idle after some seconds without producing a .cpp file. However, running the same command by hand it runs successfully.
The dl file is [HERE](https://pastebin.com/raw/jTHafyYU).
We have a minimal example of this behavior using this groovy script:
As you can see I'm passing the whole environment of System, with an empty environment it would not execute. I tried 3 different systems and the outcome is the same.
```
import java.util.concurrent.Executors

if (args) {
    new Executor().execute(args.toList())
}
else {
    println "Nothing to do"
}


class Executor {
    static final Closure STDOUT_PRINTER = { String line -> println line }

    File currWorkingDir = new File(".")
    Map<String, String> environment = [:]

    void execute(List<String> command) {
        environment.putAll(System.getenv())
        def process = startProcess(command)
        
        // Add a shutdown hook in case the JVM terminates during the execution of the process
        def shutdownActions = {
            println "Destroying process: $command"
            process.destroyForcibly()
            println "Process destroyed: $command"
        }
        def shutdownThread = new Thread(shutdownActions)
        Runtime.getRuntime().addShutdownHook(shutdownThread)

        try {

            // Wait for process to terminate
            def returnCode = process.waitFor()
            process.inputStream.readLines().each { STDOUT_PRINTER.call(it.trim()) }

            // Check return code and raise exception at failure indication
            if (returnCode != 0)
                throw new RuntimeException("Command exited with non-zero status:\n $command")

        } catch (e) {
            Runtime.runtime.removeShutdownHook(shutdownThread)
            shutdownActions.call()
            throw e
        } 
    }

    Process startProcess(List<String> command) {
        def pb = new ProcessBuilder(command)
        pb.directory(currWorkingDir)
        pb.redirectErrorStream(true)
        pb.environment().clear()
        pb.environment().putAll(this.environment)
        pb.start()
    }
}

``` 

Do you have an idea what could be the cause of this? 
Thanks, 
Sifis.

**Comment by mmcgr** [comment]
In the past there was an issue with mcpp and environment variables for location. If the test succeeds with these set in the environment
```
LANG=en_AU.UTF-8
LANGUAGE=en_AU.UTF-8
LC_ALL=en_AU.UTF-8
```
then it's likely to be mcpp again.

What OS are you running this on? Are you compiling souffle yourself, or using one of the packages?

**Comment by anantoni** [comment]
The issue was this line `def returnCode = process.waitFor()` which was before the inputStream.readLines(). So the problem was on our end because in this case Souffle produced too many warnings. However, with regard to that, is it possible to have different warning levels in Souffle? For instance a way to disable warnings such as the one about not printing records verbatim and leave only the no rules/facts defined and unused variables ones.

**Comment by mmcgr** [comment]
There isn't support for partial disabling of warnings, but you can disable **all** warnings with `-w`.
