### ISSUE TITLE
Unable to import multiple analysis in same TU

### ISSUE THREAD

**Issue by HerbertJordan** [souffle-lang/souffle#80]
Due to the utilization of global management structures, including the 
```
ProgramFactory *ProgramFactory::base __attribute__ ((weak)) = nullptr;
```
and
```
static factory_Sf_varpointsto_example factory;
```
it is not possible to import more than one analysis into a single C++ translation unit. We should try to get rid of those.

**Comment by b-scholz** [comment]
We needed these factories for finding any arbitrary analysis at runtime. 
Could you preserve the functionality?

**Comment by HerbertJordan** [comment]
The call
```
ProgramFactory::find("my_analysis");
```
should still work -- and is also tested by the interface integration tests, as far as I know. 

The Mechanism works as follows: The constructor of a factory is registering it within the list of factories maintained by the common base class `ProgramFactory`. This registering is triggered by the creation of a global `factory` variable of the proper type. I altered the code so that the global variable name contains now the name of the analysis, e.g. `factory_points_to_analysis`.

**Comment by b-scholz** [comment]
Great! We just need to be conscientious so that the Oracle Labs folk still can use a newer version of Souffle.
