### ISSUE TITLE
Provenance and components

### ISSUE THREAD

**Issue by gfour** [souffle-lang/souffle#804]
Hello,

The "explain" mode of provenance seems to have trouble with components (Souffle version: 1.4.0-444-g72573fb).

Assume the following example (component-provenance.dl):
```
// Example from https://github.com/oracle/souffle/wiki/components
.comp MyComponent {
  .decl TheAnswer(x:number)
  TheAnswer(42).
  .output TheAnswer
}

.init myCompInstance1 = MyComponent
.decl Test(x:number)
.output Test
Test(x) :- myCompInstance1.TheAnswer(x).
```

I compile and run it with provenance enabled:

```
$ souffle -c -o exe component-provenance.dl --provenance=1
$ mkdir test-dir
$ ./exe -F. -D$(realpath test-dir)
```

First, "explain" on component-relation tuples seems to not work:

```
Enter command > printrel myCompInstance1-TheAnswer
---------------
myCompInstance1-TheAnswer
===============
42
===============
Enter command > explain myCompInstance1-TheAnswer(42)
Relation not found
```

Also, "explain" crashes when it tries to mention myCompInstance1.TheAnswer in another derivation:
```
Enter command > explain Test(42)
segmentation fault (core dumped)
```

**Comment by mmcgr** [comment]
Fixed by #809

**Comment by gfour** [comment]
Thank you for the quick fix, the two problems (relation naming + segfault) in my issue description above were fixed. However, I cannot fully use "explain" with components since I cannot find how to print a rule reported by "explain".

For example, "explain" reports this:
```
Enter command > explain Test(42)
myCompInstance1.TheAnswer() 
------------------------(R1)
          Test(42)          
```
and it seems rule R1 can be printed with "rule":
```
Enter command > help
...
rule <relation name> <rule number>: Prints a rule
...
```
But I cannot find how to call "rule" and the error message conflicts with the "help" instructions:
```
Enter command > rule myCompInstance1-TheAnswer R1
Usage: rule <rule number>
Enter command > rule myCompInstance1.TheAnswer R1
Usage: rule <rule number>
Enter command > rule R1
Usage: rule <rule number>
Enter command > rule 1
[1]    9704 segmentation fault (core dumped)  rlwrap ./exe -F. -D$(realpath test-dir)
```

**Comment by mmcgr** [comment]
The accepted form is
```
rule Test 1
```
since the relation in the head of the rule is `Test`.

The usage message should be fixed, and the segfault shouldn't happen, but I think the commands could be be more helpful, too.

**Comment by gfour** [comment]
Running "explain" on component relations still has some bugs, take this code (based on the original minimal example above):
```
.comp MyComponent {
   .decl TheAnswer(x:number)
   TheAnswer(42).
   .output TheAnswer

   .decl TheAnswer2(x:number)
   TheAnswer2(x) :- TheAnswer(y), x = y + 1.
   .output TheAnswer2
}

.init myCompInstance1 = MyComponent

.decl Test(x:number)
.output Test
Test(x) :- myCompInstance1.TheAnswer(x).

.decl Test2(x:number)
.output Test2
Test2(x) :- myCompInstance1.TheAnswer2(x).
```
Compile and run:
```
$ souffle -c -o exe component-provenance.dl --provenance=1
$ ./exe     
Explain is invoked.
Enter command > explain myCompInstance1-TheAnswer2(43)
exe: /usr/local/include/souffle/ExplainProvenanceSLD.h:135: std::unique_ptr<souffle::TreeNode> souffle::ExplainProvenanceSLD::explain(std::__cxx11::string, std::vector<int, std::allocator<int> >, int, int, size_t): Assertion `info.find(std::make_pair(relName, ruleNum)) != info.end() && "invalid rule for tuple"' failed.
[1]    17773 abort (core dumped)  ./exe```

**Comment by mmcgr** [comment]
#818 changes how component relations are named internally, which should standardise the names that are exposed in provenance (and profiling).

As a side effect you would now use `explain myCompInstance1.TheAnswer2(43)` instead of `explain myCompInstance1-TheAnswer2(43)`, and default output filenames for these relations changes similarly. I think this naming is better as the component relation naming is more consistent, but this may cause problems for any scripts that expect the hyphens.

**Comment by gfour** [comment]
Provenance seems to work now with components.
