### ISSUE TITLE
Subtyping not checked

### ISSUE THREAD

**Issue by olligobber** [souffle-lang/souffle#832]
The following code causes a crash instead of an error, since `number | symbol` is not a subtype of `number`:

```
.type X = number | symbol 
.type Y = number

.decl A(x : X)
A(1).

.decl B(x : Y)
B(x) :- A(x).

.output B(IO = stdout)
```

**Comment by mmcgr** [comment]
That's an odd flow. First visitUnionType is called (TypeSystem.cpp:255), which then gets a string name by calling visitType, which then fails because it doesn't recognise union types.

**Comment by azreika** [comment]
This will be fixed with the release of the new typesystem (currently producing the correct error messages in the `new-typesystem` branch).
