### ISSUE TITLE
Parser problem when relation contains .type

### ISSUE THREAD

**Issue by 6d77** [souffle-lang/souffle#850]
The following snippet does not compile:

```prolog
.comp Test {
    .decl type(t: symbol)
    type("test").
}

.init test = Test
// facts do not work
test.type("outer").
// but also directives as this
.output test.type
```

The resaon seems to be that the `.type` part of the relation name is considered to start a new `.type` declaration statement. If you choose any other non-reserved name for the relation the code works well.

**Comment by lyndonhenry** [comment]
Have you tried similar things with other keywords? E.g. `.comp comp { .decl decl(symbol:symbol) }` or some such. 

If the behaviour across keywords is consistent, it might be best to document this behaviour somewhere, and in future regard it as intended. 

Changing the grammar to support use of keywords as names would be difficult to implement as Souffle treats all whitespace the same. This also means any tools (e.g. syntax highlighters) would have to deal with a more complex grammar, and arguably introduces more cognitive load for readers/writers of code with keywords as names. 

Also, it would then even more difficult to test, as each keyword would have to be used as each possible "kind" (variable, relation, component, etc) of name (so |keywords| × |name-kinds| tests in total).  

Is there any particular use case for this that justifies the developer effort required?

**Comment by b-scholz** [comment]
We could fix this issue in the scanner - however there are issues because it becomes highly ambiguous. 

.type is clearly a keyword and the user should have added a blank in between. E.g., 

```
.comp Test {
    .decl type(t: symbol)
    type("test").
}

.init test = Test
// facts do not work
test . type("outer").
// but also directives as this
.output test.type
```
should work.

We could extend the scanner by checking whether the character before the ".type" is a portion of an identifier.

**Comment by lyndonhenry** [comment]
Huh, sorry, I think I might have been completely wrong on this one. I like the simplicity of this space-after-dot trick, it's an easy yet elegant solution. I agree, a sentence or two mentioning it in the docs would be totally sufficient.
