### ISSUE TITLE
Inverted sequence of parameter types for .functor

### ISSUE THREAD

**Issue by 6d77** [souffle-lang/souffle#856]
When defining a custom functor with multiple parameters of different types, the actual sequence of types seems to be exactly inverted.

When I define
```
.functor f(symbol, number): symbol
```
invocations of `@f` behave as if the first parameter would be a number and the second a symbol. Indeed, when inverting the sequence of types in the functor definition, everything works well, including the actual invocation of the functor. This is also the case with more than 2 parameters.

**Comment by 6d77** [comment]
I'm not an expert in yacc, but I assume that the reason is in `parser.yy`:
https://github.com/souffle-lang/souffle/blob/cdbda16ac8e1bcf528304064110d818190782af3/src/parser.yy#L418
Here the next typearg seems to be prepended to the collection of typeargs instead of appended.

**Comment by b-scholz** [comment]
We will double-check; thanks for this. We also need test-cases for user-defined functors.

**Comment by yanniss** [comment]
@b-scholz Since you wanted test cases, I just published a repo with 256-bit arithmetic functors:
  https://github.com/yanniss/souffle-num-addon/

Haven't used this in action yet, but soon will, so ironing out functor bugs would be very welcome.

**Comment by b-scholz** [comment]
I hope we get our test scripts for our tests/interface/functor library under control soon. 

@6d77 - yes indeed. This is the issue.  

If you need functors now, please apply this change in your local versions until the test scripts for functors are fixed.
