### ISSUE TITLE
Only one -M option allowed

### ISSUE THREAD

**Issue by 6d77** [souffle-lang/souffle#859]
There is only one `-M` option allowed on the command line - despite the fact that the implementation would also work with multiple. I think it is just the entry in the option table, that should allow multiple -M options:
https://github.com/souffle-lang/souffle/blob/cdbda16ac8e1bcf528304064110d818190782af3/src/main.cpp#L186
Here a `true` would be fine.

**Comment by 6d77** [comment]
Addition: just setting this to `true` does not help. Is there any chance to set more than one macro from the command line?

**Comment by mmcgr** [comment]
The text given to the `-M` option is split on spaces, and each part prepended with `-D`.
```
souffle -M "foo=bar bob=alice" test.dl
```
will run the pre-processor with
```
-Dfoo=bar -Dbob=alice
```

As long as you don't need spaces in your macros, the result is similar.

**Comment by 6d77** [comment]
Thanks, that solved my problem. I'll close this issue.
