### ISSUE TITLE
Implicit declarations of relations

### ISSUE THREAD

**Issue by psubotic** [souffle-lang/souffle#89]
would be nice to be able to infer types for IDBs, i.e., so one does not have to declare an IDB table if it isn't an output table.

**Comment by icesparrow** [comment]
Paul, could you please add a milestone? I suppose that is not too urgent of an issue?

**Comment by psubotic** [comment]
added the one furthest away - as its not urgent

**Comment by icesparrow** [comment]
Thanks Paul, I think that would be good if we add milestones to all of the issues, otherwise it is a bit difficult to sort them out

**Comment by psubotic** [comment]
Agreed! Sorry about that!

**Comment by b-scholz** [comment]
Paul - if you can remember we had several typos in our relation names/variables while programming some big specifications at Oracle Labs. It caused serious havoc and it was hard to debug. 

For example, if you have following code:

```
.decl Hello(x:number, y:number)
Hello(1,1).
Hello(1,2).
Yello(x,y):-Hello(x,y),Hello(y,z). 
.decl Mello(x:number, y:number) output
Mello(x,y) :- Yello(x,y).
```

would you say that relation `Yello` should be implicitly declared.

Perhaps we could provide some annotation that this is really a new table and not just by usage, e.g., 

```
.decl Hello(x:number, y:number)
Hello(1,1).
Hello(1,2).
Yello(x,y) <= Hello(x,y),Hello(y,z). 
.decl Mello(x:number, y:number) output
Mello(x,y) :- Yello(x,y).
```

giving the symbol `<=` the meaning that this is not just an entailment but also a definition of relation `Yello` whose type is deduced from variables `x` and `y`.

Perhaps you have a better idea.

**Comment by HerbertJordan** [comment]
We could use something like
```
.decl Yello ( auto )
```

**Comment by psubotic** [comment]
yes -- Both those annotations are ok. The problem isn't so much declaring
the table but searching for its variable types. My preference is the
minimal annotation possible is the best

**Comment by psubotic** [comment]
Sorry Bernhard, just realised the second suggestion is exactly what you describe. Yes I like this but would be nice to so say - inherit everything like Herbert's and my suggestion. Im not personally fussed with syntax.

**Comment by b-scholz** [comment]
I like Herbert's proposal 
```
.decl Yello(auto)
```
best because it still forces the user to declare a relation. This notation provides the convenience, that the attribute types are automatically deduced.
