### ISSUE TITLE
Exponentiation Operator is Left Instead of Right Associative

### ISSUE THREAD

**Issue by stephenbrady** [souffle-lang/souffle#904]
Usually, the exponentiation operator is right associative - e.g., `(10 ^ (1 ^ 2))` - but Souffle is treating it as left associative -`(10 ^ 1) ^ 2)`.

This program yields `p(100)`. I would expect `p(10)`.
```
.decl p(X: number)
.output p

p(X) :- X = 10 ^ 1 ^ 2.
```

**Comment by stephenbrady** [comment]
I may try to debug this and submit a patch, starting with this line: https://github.com/souffle-lang/souffle/blob/master/src/parser.yy#L208.

**Comment by b-scholz** [comment]
Thanks for spotting this; please submit a pull-request with the fix and a simple test-case if you want to fix it. We are happy to fix this as well.
