### ISSUE TITLE
Segmentation fault calling functor

### ISSUE THREAD

**Issue by 6d77** [souffle-lang/souffle#918]
I observed a segfault using functors in some specific circumstances. I tried to make a minimum, but still reasonable example and came up with the following:

```prolog
.decl in(s: symbol)
.decl shift1 (r: symbol)
.decl shift2 (s: symbol, r: symbol)
.decl cnt(n: number)
.functor shift(symbol, number): symbol

cnt(0).
cnt(n+1) :- cnt(n), n < 6.
in("abcdef").
in("123456").
shift1(r) :- in(s), r = @shift(s, n), cnt(n).
shift2(s, r) :- in(s), r = @shift(s, n), cnt(n).

.output shift1(IO=stdout)
.output shift2(IO=stdout)
```

and the functor implementation

```c
#include <string>

extern "C" {
const char* shift(const char* str, int cnt) {
    thread_local std::string value;

    value = std::string(str);

    if (value.size() > 0) {
        for (int i = 0; i < cnt; ++i) {
            value = value.substr(1) + value.at(0);
        }
    }

    return value.c_str();
}
}
```

The error message states a problem in the line `shift1(r) :- in(s), r = @shift(s, n), cnt(n).`:

```
Segmentation violation signal in rule:
shift1(@shift(s,n)) :-
   in(s),
   cnt(n).
```

Interestingly, everything works if I

* comment out this line (shift2 works as expected!)
* use a constant string instead of in(s), e.g. `shift1(r) :- r = @shift("qwertz", n), cnt(n).` works
* use a constant number instead of cnt, e.g. `shift1(r) :- in(s), r = @shift(s, 4).` works

Do you have any idea?

**Comment by 6d77** [comment]
I did now run Souffle in the debugger to track the problem down. The exception occurs in Interpreter.cpp:76 visitElementAccess. The `ctxt` is a vector of three elements. First and third element are null pointers, only second element contains a valid pointer to an integer. `access.getIdentifier()` and `access.getElement()` both return zero, so the second array access operator fails.

I wasn't able to track down how `ctxt` is actully filled, but `visitElementAccess` assumes it contains a non-null pointer at the index `access.getIdentifier()`, while it actually contains a null pointer.

**Comment by mmcgr** [comment]
It looks like the ConvertExistenceChecksTransformer has decided that we don't need to iterate over `in`, so converts the iteration to an existence check. We then try to use the value from the iteration, which doesn't exist.

**Comment by 6d77** [comment]
Thanks! You are a great and supporting team!
