### ISSUE TITLE
Request for `cat` functor with more than two arguments

### ISSUE THREAD

**Issue by lyndonhenry** [souffle-lang/souffle#919]
Currently, the `cat` functor only takes two arguments.

For example:

~~~
cat("this", cat("is", cat("really", cat("annoying"))))).
~~~

This can cause a lot of trivial bugs when writing code, and causes unnecessary pain when reading code. To illustrate, did you notice that the above example has unbalanced brackets?

A better way to do things would be like so.

~~~
cat("this", "is", "so", "much", "nicer").
~~~

One may oppose this as Souffle doesn't have a means of implementing functors with an unbounded number of arguments at RAM level (or it didn't last time I checked, I may be wrong as per changes between then and now). Permitting this may be difficult, I don't know. In the interests of keeping the IR minimal, an AST transformation might be the right approach. In this way, a multi-argument `cat` becomes simple syntactic sugar for a bunch of two-argument `cat`s.

**Comment by azreika** [comment]
The functors in the AST and RAM have recently been refactored to allow implementing functors with arbitrary arity (PR #853).

This is related to issue #761 and issue #331.

**Comment by cvrac** [comment]
Hello,

Is there any progress regarding this request?

**Comment by b-scholz** [comment]
At the moment nobody is actively working on it. We try to finish the new type system first.
