### ISSUE TITLE
code generated doesnt compile when using eqrel

### ISSUE THREAD

**Issue by psubotic** [souffle-lang/souffle#926]
The code generated when using eqrel and multiple indexes doesn't compile.  See output: 

/Users/psubotic/ws/src/PvarEnforcer/src/llvm.cpp:841:1: error: use of undeclared identifier 'ind_1'; did you mean 'ind_0'?
ind_1.clear();
^~~~~
ind_0
/Users/psubotic/ws/src/PvarEnforcer/src/llvm.cpp:704:9: note: 'ind_0' declared here
t_ind_0 ind_0;
        ^
Seems like there is some issue with indexing and eqrel. If I remove eqrel it is fine (but i need eqrel). I will look more into it and try provide a minimal test case.

**Comment by b-scholz** [comment]
Can you send us the datalog file?

**Comment by psubotic** [comment]
I can send you a simplified version that crashes it. Ill try do this today.

**Comment by b-scholz** [comment]
Thx.
