### ISSUE TITLE
MPI Extension

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#937]
Because of the RAM refactoring, we need to take the MPI extension out and re-merge it after it is working again.

**Comment by b-scholz** [comment]
Let's wait for this when Lyndon is back.

**Comment by lyndonhenry** [comment]
Thanks for waiting on this, I'll be happy to lend a hand once I'm back after Easter. 

In the meantime, if anyone can be bothered, it would be good to have some sort of doc for the new RAM design (maybe on the wiki?). This was I can have a look and start drafting a solution in line with requirements. This would also be a really useful thing to have for ensuring a consistent approach in future, fleshing out the ideas, teaching new developers, reviewing code in pull requests, and having a unified understanding of how things ought to be. Might be a bit painful, but will likely save others hours of blindly hacking about and invalidating others assumptions.

**Comment by b-scholz** [comment]
Xiaowen started to document RAM on our wiki page.
It would be great to put more effort into describing the boilerplate of RAM.

**Comment by lyndonhenry** [comment]
Thanks so much to Xiaowen on the wiki page! Efforts such as this are greatly appreciated, modt especially when they are so neatly structured. I'll try my best to keep the page updated as MPI is refactored, and add to it if I learn anything about the IR/RAM that isn't documented there already. I feel there's still a lot to put in there before it can be understood easily by those outside the Souffle developers echo chamber. 

Dumping the link to that wiki page for reference:
https://github.com/souffle-lang/souffle/wiki/RAM-Intermediate-Representation
