### ISSUE TITLE
User-defined functors features

### ISSUE THREAD

**Issue by yanniss** [souffle-lang/souffle#947]
Based on a chat with Bernhard, I would like to ask for a couple of enhancements to the user-defined functors feature.

A) Right now there can be a single dynamic library of functors, libfunctors.so. While this is a reasonable default, it's much less dynamic than dynamic libraries allow. For instance, it does not permit using two different .so files, with distinct sets of user-defined functors each. We are getting to the point of having multiple independent extensions of Souffle (e.g., one for 256-bit arithmetic, the other for dynamically snapshotting an execution) and it makes no sense to compile such disparate code together into a single .so, just to satisfy the requirement. I expect that extra ".so"s could be looked up either via a naming convention or via a command-line argument that names them.

B) When Souffle is compiling a .dl file that uses user-def functors, it requires that the libfunctors.so (or a symlink to it) be present in the current directory. This seems too strict, since the functor is not involved in (DL-to-C++-to-native) compilation. Also, it's awkward because the compilation directory may not be the one the user expects in a large project, or there might be multiple directories under which Souffle compiles .dl files. Basically, this requirement makes it harder to have mature Souffle clients that employ user-defined functors. Removing it would be very welcome.

Thanks!

**Comment by mmcgr** [comment]
We could use an environment variable `SOUFFLE_LIBRARY_PATH=pathA:pathB` to add paths to search for libraries, and a souffle flag `souffle -LpathA:pathB ...`. The libraries themselves could be a default `libfunctors` plus a user defined list of libraries with an environment variable `SOUFFLE_LIBRARY=a,b` and a matching souffle flag `souffle -la,b ...` (Note that `-l` is currently for the live profiler. That will now only be accessed through the long form `--live-profile` so we can match standard compiler behaviour.)

So we end up with:
```
export SOUFFLE_LIBRARY_PATH=/home/bob/lib
export SOUFFLE_LIBRARY=maths,kittens
souffle kittenAdding.dl -Ffacts -Dout -c
```
or
```
souffle kittenAdding.dl -Ffacts -Dout -c -L/home/bob/lib -lmaths,kittens
```

I'm not sure of the advantages of environment variable vs command line vs both.

**Comment by mmcgr** [comment]
souffle respects LD_LIBRARY_PATH so you can currently use that to specify a path to the library.

**Comment by yanniss** [comment]
LD_LIBRARY_PATH doesn't solve the above problems. I certainly have it set for the .so to be loaded at run-time of the final executable, but it doesn't remove the need to have the file in the current directory when souffle is in compiler mode (which alone prevents the use of multiple libraries). Maybe if this issue is resolved then LD_LIBRARY_PATH *will* be enough to allow using two different "libfunctors.so"s, but I don't know off-hand how dynamic loaders resolve multiple libraries with the same name. (I *think* they don't take the union of all exported functions, just stop once they find one library in the path.)

**Comment by mmcgr** [comment]
I was only suggesting `LD_LIBRARY_PATH` as a workaround for current souffle, not to address using multiple libraries.

For the compilation step to work `LIBRARY_PATH` is needed, e.g.
```
LIBRARY_PATH=<path to library> LD_LIBRARY_PATH=$LIBRARY_PATH ./souffle -c ...
```

I think that helps with the second problem. It would probably be a lot more helpful if the compiled version remembered where its libraries are, though.

**Comment by b-scholz** [comment]
This is in the master - please can you double-check whether it is working for you?

**Comment by b-scholz** [comment]
Martin - please can you amend the documentation?
