### ISSUE TITLE
escaping the escape '\' character

### ISSUE THREAD

**Issue by tomasklapka** [souffle-lang/souffle#950]
I'm trying to use the escape `\` character in a string. It correctly escapes `"` character but not the escape character itself.

This `escape.souffle` program:
```
.decl t(c: symbol) t("\""). t("\\"). t("\"").
```
results into:
```
souffle escape.souffle 
Error: unexpected \ in file escape.souffle at line 1
.decl t(c: symbol) t("\""). t("\\"). t("\"").
----------------------------------------^-----
Error: string literal is empty in file escape.souffle at line 1
.decl t(c: symbol) t("\""). t("\\"). t("\"").
-----------------------------------------^----
Error: syntax error, unexpected symbol, expecting ) or "," in file escape.souffle at line 1
.decl t(c: symbol) t("\""). t("\\"). t("\"").
-----------------------------------------^----
3 errors generated, evaluation aborted
```
Is there any other way to escape it?

**Comment by b-scholz** [comment]
This is a bug in the scanner of Soufflé. Thanks for finding it. 

We need to change the definition of a string in ```scanner.ll```, i.e., 
```
\"([^\"]*|\\\")*\"
```

**Comment by b-scholz** [comment]
I just checked - Zoolang uses following pattern:
```\"(([^\"]|\\\")*[^\\])?\"```
which would capture the behaviour of escape characters.

**Comment by b-scholz** [comment]
Tomas - you can use the above pattern in ```scanner.ll``` until the string pattern is fixed and pushed into the main branch.

**Comment by tomasklapka** [comment]
The provided pattern from Zoolang does not work.
`\"(\\.|[^"\\])*\"` seems to work fine
(source: https://stackoverflow.com/a/2039820).
