### ISSUE TITLE
SIMD, SPMD on SIMD or GPU acceleration

### ISSUE THREAD

**Issue by csabahruska** [souffle-lang/souffle#952]
Would it be possible to utilize SIMD vector instructions either on CPU or GPU?

GPU was succesfully used to run Andersen style points-to analysis:
[A GPU Implementation of Inclusion-based Points-to Analysis](https://userweb.cs.txstate.edu/~mb92/papers/ppopp12.pdf) '12

SSE/AVX instructions were used to accelerate sparse data structures:
http://bitmagic.io/

Maybe Intel SPMD Program Compiler could be useful also:
https://ispc.github.io/perf.html

**Comment by csabahruska** [comment]
https://medium.com/@vaclav.loffelmann/vectorizing-database-operations-with-avx-512-e759ce59abd3

**Comment by b-scholz** [comment]
This is a very exciting question. In principle it is possible and you would gain substantial performance gains running soufflé on gpgpus due to their bandwidth. However you would need to port the whole RAM engine to GPUs including BTrees. The last PPoPP’19 conference had some papers how to port BTrees to gpus.

**Comment by csabahruska** [comment]
[The Futhark Programming Language](https://futhark-lang.org/)
High-performance purely functional data-parallel array programming on the GPU.

This language could be useful for GPU programming/experiments.

**Comment by b-scholz** [comment]
There are some repositories on GitHub implementing relational algebra operations in CUDA. I would start there. A functional language would not help you so much for this purpose. To obtain peak performance, I would choose either CUDA or OpenCL.
