### ISSUE TITLE
Licensing restrictions

### ISSUE THREAD

**Issue by mbudiu-vmw** [souffle-lang/souffle#953]
We are thinking to steal your test programs and use them to test our Souffle to DDLog converter from the DDlog project https://github.com/ryzhyk/differential-datalog. Our project is licensed with an MIT license. I don't know if your license is compatible and would allow us to copy the Souffle code for the tests. If it is not compatible we can probably work out a solution where we only download a piece of your tree to run our tests, and we never incorporate the code into our source tree.

**Comment by b-scholz** [comment]
I am not an open source lawyer. Please be careful mixing different licenses since UPL has some patent clauses. Our source code including tests must be distributed under UPL and we cannot dual license etc. Happy to discuss this offline.
