### ISSUE TITLE
Component member access fails when member names contain direcitve keywords

### ISSUE THREAD

**Issue by LFrobeen** [souffle-lang/souffle#954]
Accessing component members via the dot notation seems to fail when the member's names are identical to directive keywords (i.e. input, output, comp, etc.). This also seems to apply when member names merely start with one of these directive keyword.

See the following example for clarification:

```
.comp MyComponent {
    .decl input(t: number)

    .decl compliant(t: number)
    compliant(t) :- input(t), t < 10.
}

.init myComponentInstance = MyComponent

myComponentInstance.input(1).
myComponentInstance.input(2).
myComponentInstance.input(20).
myComponentInstance.input(40).

.output myComponentInstance.compliance
```

**Comment by b-scholz** [comment]
Please add a blank between dots. We need to disable identifiers that overlap with keywords such as input.

**Comment by azreika** [comment]
We are planning on changing the component member access operator from `.` to `::` in the next major version of Souffle, which will fix this (and other) parser-related issues.
