### ISSUE TITLE
Is there a way to get the intermediate results for the output found by souffle

### ISSUE THREAD

**Issue by lottepuski** [souffle-lang/souffle#956]
From the paths example is it possible to get the facts that souffle used to ascertain that 3 is reachable from 1?

**Comment by lottepuski** [comment]
I found that provenance explain, can be used to launch an interactive session (Snippet: `.pragma "provenance" "explain"`). Which gave rise to two more questions: 

1. Is there a way to automatically get proof for the computed solution?
1. I found that it is possible to generate meaningful output for Record Types built with "native" types. For a user-defined record type, can the user also specify how to output the record type?

**Comment by taipan-snake** [comment]
Hi, yes provenance seems like the best bet for your question. As for your follow-up question about automatically getting proofs, if you're asking about interacting with the provenance interface directly from the command line, it's possible to pipe in commands, e.g. if `in` is a file containing commands:
```
explain bar(x, y)
exit
```
then the following should work
```
souffle --provenance=explain foo.dl < in
```

**Comment by b-scholz** [comment]
Note that if you want to post-process proof-trees there is a JSON option for the output.

Unfortunately, we don't have the record outputs yet but it is on our TODO list.
