### ISSUE TITLE
RAM Refactoring

### ISSUE THREAD

**Issue by mmcgr** [souffle-lang/souffle#961]
* [x] Rewrite ConvertExistenceCheckTransformer with visitors/lambdas to improve clarity
* [x] Rewrite Synthesiser visitQuery to be less confused (We should use the getConditions() function to convert the conjuncted terms to a list of conditions. We can check each condition whether we can place it before or after the context generation. At the moment we don’t do this and either we reject all (slow) or the list has no operations (ExistenceChecks) that rely on a context. )
* [x] Use RamTransformers on the translation unit, not just the program, so that subroutines are also transformed (NB: this holds / we perform transformations on subroutines as well).
* [x] Look at RamAggregates indexed vs non-indexed - keep combined or separate? RamScan should mirror the result
* [x] AstTranslator handling of aggregates is restrictive. E.g. t does not permit functors etc. We should be more generous. The only restrictions should be a single relation but everything else should be ok. With single relations, we also need to exclude unpack operations for records. 
* [x] Remove RamNodeType and use dynamic typing instead, as for AST
* [x] Remove obsolete code from Node/Visitor
* [x] Semantics of RamAggregrate in Synthesiser and LVMGenerator is wrong.  
* [x] Rename getIdentifier() to getTupleId() or something more expressive.

**Comment by b-scholz** [comment]
Another issue is that clone() in RamNode creates a clone of a node that is not wrapped in a smart-pointer. This leads potentially to memory leaks. I suggest changing the clone method so that a smart pointer is returned.

**Comment by b-scholz** [comment]
RamNode.h and RamVisitor.h are separate. I would suggest merging both files because they are highly related.

**Comment by b-scholz** [comment]
RamVisitor.h has functions/templates, e.g., visitPostOrder that (1) are not working and (2) are not used. 
I suggest removing all functions/template that are not appearing in the code.

**Comment by b-scholz** [comment]
Let's separate concerns related to RamAggregate, i.e., let's introduce two new classes: RamAggregrate and RamIndexAggregate where RamAggregate is derived from RamRelationSearch and RamIndexAggregate is derived from RamIndexRelationSearch.
