### ISSUE TITLE
Change Oracle's old Datalog group email 

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#97]
`configure.ac` has an old oracle group email that is unreachable from outside the Oracle network. 

I would suggest to replace it by a google mailing list email address.

**Comment by icesparrow** [comment]
Do we have one or this is something that needs to be set up?

**Comment by b-scholz** [comment]
We have a souffle google groups for questions and answers. 

http://souffle-lang.github.io/community/

I tried to send an email to souffle@googlegroups.com but I couldn't get it to work.

We might need to reconfigure it so that it works for questions and answers and emails.

**Comment by b-scholz** [comment]
Ok - I have it working

souffle-talk@googlegroups.com

**Comment by icesparrow** [comment]
Ok, I will fix it in the `configure.ac`, probably now worth to create a merge request for such a small issue

**Comment by icesparrow** [comment]
Right, it did not let me, just created a pull request
