### ISSUE TITLE
RAM Refactoring - Clone Issue

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#972]
Currently,  we use clone() to create new objects for AST and RAM. However, they don't return smart-pointers. Using covariant returns with smart-pointers is not so easy in C++. 
Here is an article describing techniques to overcome this issue:
https://www.fluentcpp.com/2017/09/12/how-to-return-a-smart-pointer-and-use-covariance/

**Comment by mmcgr** [comment]
So instead of a `virtual AstNode* clone()`, where concrete implementations return `AstActualType*`, we use concrete methods, `std::unique<AstNode> clone()` and a `std::unique<AstActualType> clone()` for each type in the hierarchy (with templates declaring and defining the methods).

**Comment by b-scholz** [comment]
That is correct but we will CRTP to implement it effectively .

**Comment by mmcgr** [comment]
We could also do something like
```c++
template<typename T>
std::unique_ptr<T> unique_clone(const T* other) {
    return std::unique_ptr<T>(other->clone());
}

template<typename T>
std::unique_ptr<T> unique_clone(const std::unique_ptr<T>& other) {
    return std::unique_ptr<T>(other->clone());
}
```
Then we can do
```c++
RamNegation* res = new RamNegation(unique_clone(operand));
```

**Comment by b-scholz** [comment]
In my "clone" branch, I have started to rewrite RAM without CRTP.

**Comment by mmcgr** [comment]
In my "cloning" branch, I tested my approach above (with some regex to update the uses of clone):
https://github.com/souffle-lang/souffle/compare/master...mmcgr:cloning

It works fine, but does leave public the existing raw pointer clone methods.

**Comment by b-scholz** [comment]
Well - I don't like it too much because leaks can potentially still happening - is this correct?

**Comment by mmcgr** [comment]
The only place for a leak is if the Ast/Ram clone() method is used directly. We don't do that, with the change to unique_clone(...), but it doesn't stop anyone doing so in future.

The approach you linked is not elegant, but it does mean that there is no way to get a raw pointer from the interface, which would help protect us from ourselves.

**Comment by HerbertJordan** [comment]
you can hide the clone(..) function by making it private, and name the free unique_clone(..) function a friend of the class.

I would recommend to just name the free function clone, since the unique-part is already covered by its type signature. Also, by setting up nicely, most of the boiler-plate code can be omitted. See this a bit longer example:

```C++

#include <string>
#include <memory>
#include <iostream>
#include <type_traits>

using std::string;
using std::unique_ptr;
using std::make_unique;
using std::cout;

// --- cloning utility ---

template<typename T>
unique_ptr<T> clone(const T& val) {
    return unique_ptr<T>(static_cast<T*>(val.clone()));
}

template<typename T>
unique_ptr<T> clone(const unique_ptr<T>& ptr) {
    return clone(*ptr);
}

template<typename D>
struct base_cloneable {
    template<typename T>
    friend unique_ptr<T> clone(const T&);
private:
    virtual D* clone() const =0;
};

template<typename D, typename Base>
struct default_cloneable : public Base {
    template<typename T>
    friend unique_ptr<T> clone(const T&);
private:
    virtual Base* clone() const override {
        return new D(static_cast<const D&>(*this));
    }    
};


// --- type hierarchy ---

struct Base : public base_cloneable<Base> {
    virtual ~Base() {}
    virtual void print() const =0;
};

struct Group : public Base {
    // adds nothing, just type information
};

struct A : public default_cloneable<A,Group> { // < inherited through decorator
    string name;
    A(const string& name) : name(name) {}
    virtual void print() const {
        cout << "A-" << name << "\n";
    }
};

struct B : public default_cloneable<B,Group> {
    int value;
    B(int x) : value(x) {}
    virtual void print() const override {
        cout << "B-" << value << "\n";
    }
};

// --- use case ---

int main() {

    auto a = make_unique<A>("test");
    auto b = make_unique<B>(12);
    a->print();
    b->print();
        
    // specific types can be cloned, not losing type information
    unique_ptr<A> ac = clone(a);
    ac->print();
    
    // base types can be cloned as well
    unique_ptr<Base> base = std::move(b);
    unique_ptr<Base> base_clone = clone(base);
    base_clone->print();
    
    // so can groups
    unique_ptr<Group> group = std::move(a);
    unique_ptr<Group> group_clone = clone(group);
    group_clone->print();
    
    // also cloning a reference is supported
    const Group& g = *group;
    auto gc = clone(g); // < the result is a unique_ptr
    gc->print();
}
```
You should put the cloning utilities in some header to reuse it also for the AST nodes.

**Comment by HerbertJordan** [comment]
However, I would like to add the following: the whole issue with the cloning and smarter pointers is a symptom of kind of bad design choices for the AST and RAM data structures. You could get rid of all of this and use plain pointer / references by using alternative memory management strategies. 

A related issue is the mutability, which can be realized in the OO kind of way like it is now, or the functional way. The functional way is to use algebraic data types for modeling the AST and RAM nodes. In many of those languages, those are implemented using immutable data structures, allowing sharing. Thus, you do not have to keep track of ownership, and you would not need a clone function. Changes are no longer destructive, but create a modified copy of the original node. The modification, in turns, are realized through visitors. No explicit cloning needed.

The Insieme project is using this approach in C++ very effectively for years. Accessing nodes is easy, and memory management is (almost) transparent to the user.

**Comment by b-scholz** [comment]
So how would you improve the node data-structure. You would overwrite new( ) and have your own garbage collection?

**Comment by b-scholz** [comment]
Can you give us a code snippet to demonstrate this?

**Comment by HerbertJordan** [comment]
That would be a sustential change not only in the data structure but also in all transformers. It also changes the way you have to think about transformations. It will take weeks. At this state, it is probably not worth the effort.

**Comment by b-scholz** [comment]
I believe you are right here. We would like to have minimal changes to the current way of doing business.

**Comment by b-scholz** [comment]
This is another observation because construction and cloning go hand in hand in RAM/AST.
The current argument order in the construction does not follow a strict order. 
I suggest that we have the arguments of the super-class using the order of the super-class. Then we have the new arguments of the current class. We need more discipline here.

**Comment by b-scholz** [comment]
We have now a clone utility to ease the writing of cloning in Util.h
```
template <typename A>
std::unique_ptr<A> clone(const A* node) {
    return node ? std::unique_ptr<A>(node->clone()) : nullptr;
}
```
