### ISSUE TITLE
Grammar for type_param_list is odd

### ISSUE THREAD

**Issue by mbudiu-vmw** [souffle-lang/souffle#975]
This is from the yy grammar:
```
type_param_list
  : IDENT 
  | type_param_list COMMA type_id 
```
I would expect both to be type_id.

**Comment by b-scholz** [comment]
We have refactored the grammar - it will be pushed soon. If you need it for conversion, please have also a look how to you can translate from ast to logicblox or bdd with the files souffle2lb and souffle2bdd.

**Comment by b-scholz** [comment]
The new grammar is checked-in. Please double-check.
