### ISSUE TITLE
RAM Refactoring - Unnecessary Analyses

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#981]
Some of the RAM analyses are quite light weight and can be replaced. 

* Double-check where the constant analysis is currently used and whether it can be replaced by a level analysis (check for -1) 

* RamOperationDepth analysis may not be needed.

**Comment by XiaowenHu96** [comment]
I believed RamOperationDepth was only used in the old RAMI to determine the initial size of InterpreterCtxt. I changed it so InterpreterCtxt now dynamically allocate size on demand.

**Comment by XiaowenHu96** [comment]
This reminds me: do we have variable scope issue in RAM? 

Before LVM, RAMI used to create a new InterpreterCtxt every time it evaluates a RamOperation in `Interpreter::evalOp`. I didn't see why scoping was necessary therefore I decided to use a single global environment instead.
