### ISSUE TITLE
SearchColumns Datatype limiting the number of attributes in a relation to 64

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#995]
Currently, the searchcolumn data-type is a fixed-size 64bit datatype to capture which columns are indexable and which are not. 

The current SearchColumn data-type is limiting Souffle to have relations only up to 64 columns. 

We should replace this data-type type to ``` std::vector<bool>/std::array<bool>``` so that an arbitrary number of columns can be used.

**Comment by lyndonhenry** [comment]
If we can use an std::array, and hence need to know the size at compile time, we should use an std::bitset instead. Consider http://www.drdobbs.com/the-standard-librarian-bitsets-and-bit-v/184401382.

**Comment by b-scholz** [comment]
Yes - I agree. ```std::array<bool>``` cannot be used. bitset would be a very good choice.
