### ISSUE TITLE
RAM Refactoring - Parallel Operations

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#998]
The parallelization is currently handled by the synthesiser and the tuple-id. This is the wrong place to set the parallelization strategy. This needs to be moved to the AstTranslator. 

For this purpose, we need to introduce the following four classes:
- ParallelScan
- ParallelIndexScan
- ParallelChoice
- ParallelIndexChoice
- ParallelAggregate
- ParallelIndexAggregate

The parallel classes can be direct sub-classes of the the non-parallel classes. The only differentiate by their type from their super-classes.

Although not very elegant this would fit best to our visitor pattern. 

This refactoring is necessary to move the parallel strategy from the synthesiser to RAM. An essential strategy so that LVM & RAMI can benefit from the parallelization strategy as well.

**Comment by mmcgr** [comment]
We could make the AstTranslator do a simpler sequential version then a transformer applies the parallelisation strategy.
